### ISSUE TITLE
Built golang stack

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#1003]
We would like to improve pipeline code quality and structure so that we can easily maintain and develop. Our goal is to:
- replace bash scripts with go
- Use Kyma CLI and ALIGN WITH HUSKIES - see https://github.com/kyma-project/kyma/issues/5182
- define best practices for writing prow pipelines
- leverage [hydroform](https://github.com/kyma-incubator/hydroform) for cluster creation process
- reflect all the changes in documentation
- restructure the project (get rid of "development" folder)

**Comment by dekiel** [comment]
We will not migrate code base to golang.
