### ISSUE TITLE
Lint Markdown Links Daily is failing.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#10473]
**Description**

Github workflow `Lint Markdown Links Daily` is failing from 10.04.2024 except two executions.

https://github.com/kyma-project/test-infra/actions/workflows/lint-markdown-links-daily.yml

**Expected result**

Should not fail.

**Comment by Sawthis** [comment]
https://github.com/kyma-project/test-infra/pull/10475

**Comment by dekiel** [comment]
Fixed in #10475
