### ISSUE TITLE
Remove custom override `knative-serving.domainName`

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/test-infra#1064]
**Description**

Remove definition of custom override `knative-serving.domainName` from Prow Job scripts.

**Reasons**
Once https://github.com/kyma-project/kyma/pull/4213 is done, this custom override is no longer valid.

Blocked by: https://github.com/kyma-project/kyma/pull/4213

**Comment by piotrmsc** [comment]
pr : https://github.com/kyma-project/test-infra/pull/1085
