### ISSUE TITLE
Prow Job failure due to out of resource

### ISSUE THREAD

**Issue by KacperMalachowski** [kyma-project/test-infra#10768]
**Description**

The prow jobs for kyma-dashboard are failing due to out of resource even outside business hours.
Example PR: https://github.com/kyma-project/kyma-dashboard/pull/297

**Expected result**

Prow job should finish successfully in time, not causing out of resource.

**Actual result**

Prow job fail due to out of resource. Causing high % of used CPU according to requested CPU.

**Comment by mrCherry97** [comment]
thanks for taking care, here is an example of PR which I was retesting outside business hours, and nothing changed, it was still failing: https://github.com/kyma-project/kyma-dashboard/pull/296

**Comment by KacperMalachowski** [comment]
Reported as busola bug.
