### ISSUE TITLE
Create a proposal for reviewers & approvers concept

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/test-infra#1080]
**Description**

Create a proposal for how we can embrace the reviewers & approvers concept in Kyma to have more control on the code being checked in and also to enable automated PR merge through Tide.

You can check [this doc](https://github.com/kubernetes/test-infra/blob/master/prow/plugins/approve/approvers/README.md) for more information about reviewers & approvers.

**Reasons**

To enable automated PR merge using Tide.

**Comment by kasiakepka** [comment]
This task is handled here https://github.com/kyma-project/test-infra/issues/1079
