### ISSUE TITLE
Enable Artifacts tab in Spyglass

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#1087]
**Description**

Currently, the Artifacts tab is disabled in our Spyglass configuration. To enable it we need to configure some Google Cloud Storage browser and point to it in Spyglass configuration. According to the message that I got from @Katharine it doesn't have to be `gcsweb`, it may be standard GCS browser, but it may require Google login.

Message from @Katharine:
> Strictly speaking, no, but you do need some GCS browser. If you're willing to require a Google login, you can just point at the GCP UI instead.

In case of `gcsweb`, I know that @suleymanakbas91 has some experience with it 😄 

**Reasons**

Some of our jobs may want to generate some artifacts. For instance, I'm working on a job that will dynamically generate manifests with GCP Marketplace configuration. Of course, it will be available to download on releases, but before releases, we want to make it available for testing purposes. In such case, the best place to store it is a job artifact.

**Attachments**

![image](https://user-images.githubusercontent.com/26445970/58572124-5d35d080-823b-11e9-876f-1a7f2e164a75.png)

**Comment by suleymanakbas91** [comment]
Yes, @michal-hudy 😄  `gcsweb` can easily be used for this: https://github.com/kubernetes/k8s.io/tree/master/gcsweb.k8s.io
Then, we can configure spyglass like this: https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml#L29

**Comment by tehcyx** [comment]
Changes are merged.
