### ISSUE TITLE
Migrate pre-test-infra-validate-kaniko-build-config to GitHub Actions

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#10903]
**Description**

The prowjob `pre-test-infra-validate-kaniko-build-config` tests changes in kaniko config. This should be migrated to the GitHub Actions. The image-builder reusable workflow does not accept an input parameter `test-kaniko-build-config`.

Path to the prowjob file: prow/jobs/kyma-project/test-infra/ado-validation.yaml

**Reasons**

Prow shutdown

**Acceptance Criteria**

Changes in `kaniko-build-config` are tested.

**Comment by Sawthis** [comment]
It was already migrated to Github action: https://github.com/kyma-project/test-infra/blob/main/.github/workflows/pull-validate-kaniko-build-config.yml
