### ISSUE TITLE
Autobumper update image versions in all .tf files

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#10937]
**Description**

Autobumper tool must update image versions in all .tf files existing in our repositories. Updating an image versions to the latests available is needed for security fixes and features deliveries.

**Reasons**

The list of .tf files maintained by autobumper is build manually. Because yaml files are detected automatically, new .tf files are not added by developers. This is causing old images used in our production systems.

https://github.com/kyma-project/test-infra/blob/79d1c90bd68539ab9ec97e4c6d2772afbc672c8e/configs/autobump-config/test-infra-autobump-config.yaml#L16

**Acceptance Criteria**

- [ ] The list of .tf files to update images is build or updated automatically.

**Comment by Sawthis** [comment]
Will be implemented in: https://github.com/kyma-project/test-infra/issues/12153
