### ISSUE TITLE
autobumper doesn't update github actions

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#10936]
**Description**

Autobumper tool does not updated image versions in github actions yml files.

image-builder github action uses an one month old image version.
https://github.com/kyma-project/test-infra/blob/79d1c90bd68539ab9ec97e4c6d2772afbc672c8e/.github/actions/image-builder/action.yml#L79

If the tools is excluding a .github path, all workflow files are impacted as well.

**Expected result**

Autobumper is updating image versions in github actions and github workflow files.

**Comment by Sawthis** [comment]
Will be implemented in: https://github.com/kyma-project/test-infra/issues/12153
