### ISSUE TITLE
Image builder works with workflow_dispatch

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/test-infra#10987]
**Description**

Image builder reusable workflow can work with Github Action triggered by `workflow_dispatch`.

**Reasons**

The KEB release is triggered manually, on demand (`workflow_dispatch`), for example: https://github.com/kyma-project/kyma-environment-broker/blob/main/.github/workflows/create-release.yaml
The KEB release is not build every merge to the main branch. It is executed only "on demand".

**Acceptance Criteria**

The workflow_dispatch trigger is an allowed trigger to run image builder reusable workflow.

**Attachments**

**Comment by Sawthis** [comment]
Support for workflow_dispatch event is implemented.
