### ISSUE TITLE
Create a buildpack Dockerfile

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/test-infra#11]
**Description**

Create a buildpack Dockerfile with all the tooling needed for building and testing Kyma components. This buildpack will be used by all the ProwJobs later on.  

**Acceptance Criteria**

- Create a buildpack as a Dockerfile with all the tooling needed for building and testing Kyma components.
- It must include Golang and Node.js tooling as well as other basics needed such as git and gcloud.
- It must be able to build and push Docker images.

**Comment by michal-hudy** [comment]
Closed, because it will be handled by #18
