### ISSUE TITLE
Kyma-integration job fails because zone has not enough resources

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#112]
See output from the kyma-integration job:
http://status.build.kyma-project.io/log?job=prow/kyma/kyma-integration&id=1062285015884238850

```
Authenticating
Activated service account credentials for: [sa-vm-kyma-integration@kyma-project.iam.gserviceaccount.com]

################################################################################
# Creating a new instance named kyma-integration-test-q64ht4t6
################################################################################

WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#performance.
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - The zone 'projects/kyma-project/zones/europe-west3-a' does not have enough resources available to fulfill the request.  Try a different zone, or try again later.

{"component":"entrypoint","error":"wrapped process failed: exit status 1","level":"error","msg":"Error executing test process","time":"2018-11-13T10:04:43Z"}
```

**Comment by Demonsthere** [comment]
As a "bandaid" solution I would suggest increasing the number of nodes in the cluster or increasing the disk space of the existing nodes. However, a long term solution would be to either setup [autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) or use a manager that autoscaling clusters and manages them automatically.

**Comment by Demonsthere** [comment]
Hi,
It seems we are not the only ones that had this [problem in the last few days](https://groups.google.com/forum/#!topic/gce-discussion/Lfyk38giqK8). Moreover, guys from google recommend splitting the load in several zones to workaround this, as this is a common issue. 
As a solution I would propose to iterate over a few zones (all of west-eu?) with some waiting time between the request. 
This won't solve the problem, but may reduce its impact

**Comment by Demonsthere** [comment]
Can we close this now?
