### ISSUE TITLE
add status checks for health endpoints

### ISSUE THREAD

**Issue by tehcyx** [kyma-project/test-infra#1123]
**Description**
Add another grafana dashboard to display health endpoint data for us to better monitor component health. 

**Reasons**
Current Grafana dashboards are not covering health endpoints of components and we're not notified if a component is not working (was not working).

**Comment by lszymik** [comment]
Hello @tehcyx ,

Can you please start using our template We have no idea what it is.
Please also apply some labels. 

Thanks a lot.

Cheers
Lukasz

**Comment by tehcyx** [comment]
@lszymik done.

Whoever picks this up, please see #813 for latest info.
