### ISSUE TITLE
Replace BOT_GITHUB_TOKEN with GITHUB_TOKEN

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/test-infra#1126]
**Description**

This is a follow-up issue after https://github.com/kyma-project/test-infra/pull/1124. The existing `BOT_GITHUB_TOKEN` in `config.yaml` can be replaced safely with `GITHUB_TOKEN` as it is more generally used. This will also simplify the scripts where we define `GITHUB_TOKEN` (see: https://github.com/kyma-project/test-infra/blob/7518b0492e1132830c8a1ffc248ea9334a2e40d1/development/tools/cmd/jobguard/run.sh#L15).

**Comment by mszostok** [comment]
One note:
the test-infra/development/tools/cmd/jobguard/run.sh job uses dedicated GitHub bot, see: https://github.com/kyma-project/test-infra/blob/dfa1b4c42c8c0dcf936ed2b82e25d40be6feae3b/prow/config.yaml#L231-L239

The new bot was created because we wanted to have a separate API Quota.

**Comment by kasiakepka** [comment]
Argument mentioned by Mateusz is a "no go" for this issue.
