### ISSUE TITLE
Write blog post with summary of prow migration

### ISSUE THREAD

**Issue by derberg** [kyma-project/test-infra#114]
**Description**

- have blog post here https://kyma-project.io/blog
- address 
  - context/reason of the move
  - setup we chose
  - interesting details we want to share
  - docs contrib if this will be clarified already

**Reasons**

- show to community that we also use prow
- if details will be known, show we also contribute back

**Comment by kasiakepka** [comment]
Hi @derberg,
Do you think that this task is still valid?

**Comment by derberg** [comment]
I think it it too late, we lost a right moment to do that. closing :(
