### ISSUE TITLE
Github rate limit monitoring

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#1162]
**Description**
Add Github rate limit monitoring
https://developer.github.com/v3/rate_limit/

**Reasons**

**Attachments**

**Comment by tehcyx** [comment]
If we decide to modify the GitHub proxy, we could think about writing out the rate-limites, as they're sent with every response anyways (taken from the link posted):
```
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4999
X-RateLimit-Reset: 1372700873
```

**Comment by dekiel** [comment]
Ghproxy metrics are present in pushgateway and are collected by our Prometheus.
Descriptions of exposed metrics : https://github.com/kubernetes/test-infra/blob/master/ghproxy/ghmetrics/ghmetrics.go

**Comment by dekiel** [comment]
github_token_usage metric present values for three tokens, where value change only for one. Tokens are represented by hashed_token label. We need a way to alert and daw charts for desired token without exposing this token hash.
Whereas token usage reset in github response is a epoch time, value presented by prometheus was converted to prometheus gauge value representation.

**Comment by dekiel** [comment]
Enabled github token usage monitoring and alerting. Prow Grafana dashboard contains gauge for token usage.
![image](https://user-images.githubusercontent.com/12400578/81556406-8ab35580-938a-11ea-9a09-36709ffa3c2c.png)

Alerts are trigerred on threshold 500 to c4core-prow-alerts and when quota is exhausted to c4core-ci-force channels.

**Comment by dekiel** [comment]
Added stat with time to next github token quota reset.
![image](https://user-images.githubusercontent.com/12400578/81566008-85f69d80-939a-11ea-940d-fedcc9637241.png)
