### ISSUE TITLE
Review whitesource scans & reports

### ISSUE THREAD

**Issue by strekm** [kyma-project/test-infra#1163]
**Description**

Scope of this issue:
- [x] review how we use whitesource 
- [x] review reports produced by whitesource
- [x] review prow job for whitesource scans
- [x] Find out if can be run with snyk job
- [x] Investigate what options of notifications whitesource offers (emails, slack, other). 

**Reasons**

Snyk should be replaced by whitesource, so we don't have 2 sources of security scans.

**Comment by strekm** [comment]
https://github.com/kyma-project/test-infra/pull/1054
https://github.com/kyma-project/test-infra/pull/1172

**Comment by tehcyx** [comment]
> #1054
> #1172

#1172 got replaced by #1178

**Comment by tuxgoose** [comment]
#1054 might be getting removed as well, sorry for all of the confusion

**Comment by strekm** [comment]
latest PR: https://github.com/kyma-project/test-infra/pull/1251. Whitesource scan is run as a periodic job on 15th each month. 

In the whitesource report we can see 2 high vulnerabilities in kubernetes libs:
- https://github.com/kubernetes/kubernetes/issues/71411
- https://github.com/kubernetes/kubernetes/issues/76797

A recommended solution would be bumping our deps to use libs in version 1.12.6. Also our infra should be bumped to use kubernetes 1.12.6.

Following projects are affected by mentioned issues:
- api-controller
- asset-store-controller-manager
- idppreset

Whitesource offers email alerting functionality which can be configured per project. In our case, every component (e.g. api-controller) is a project. Seems that's the only way of notifications (needs more investigation?).  Exposing vulnerability report either as a badge on kyma repo or as a link still needs investigation.

**Comment by jakkab** [comment]
OOTB, WhiteSource supports email notifications only. It is possible, however, to save the output of the scan into a file using the ['offline'](https://whitesource.atlassian.net/wiki/spaces/WD/pages/33718339/Unified+Agent#UnifiedAgent-OfflineMode-Optional) option. The output is stored in a JSON object (prettify supported) that could be parsed and forwarded as a Slack notification. This way, we could reuse the [existing code](https://github.com/kyma-project/test-infra/blob/master/development/vulnerabilities-scanner.sh).

**Comment by jakkab** [comment]
[WhiteSource Bolt](https://whitesource.atlassian.net/wiki/spaces/WD/pages/556007950/WhiteSource+Bolt+for+GitHub) might be worth considering as well.

**Comment by piotrmsc** [comment]
Please create separate issues for the given components that require upgrading dependencies.
Please also try enabling bolt on kyma copy repo (on your priv profile) - note that fork will not work. Configure bolt to create issues only for vulnerabilities with lvl >= HIGH

**Comment by jakkab** [comment]
#5079 #5080 #5081 #5082

**Comment by jakkab** [comment]
Since it doesn't support monorepos, Whitesource Bolt is not tailored to fit our needs. See kyma-project/test-infra#607.
