### ISSUE TITLE
Move the "development" folder into the "prow" subfolder 

### ISSUE THREAD

**Issue by kazydek** [kyma-project/test-infra#117]
**Description**

A follow-up task that resulted from the discussion on [this](https://github.com/kyma-project/test-infra/pull/110) PR. 
Move the `development` folder into the `prow` subfolder as it contains only Prow-related scripts.

When moving it, please update the two `README.md` documents accordingly:
- Remove the `development` folder from the project structure from the main `README.md` in the `test-infra` repository.
- Add the `development` folder to the project structure in the main `README.md` for Prow.

**NOTE:** Both `README.md` docs will show the structure mentioned above after the  [PR 110](https://github.com/kyma-project/test-infra/pull/110) is merged so pls wait until that time before you start this task.

**Comment by kasiakepka** [comment]
This task needs to be implemented.

**Comment by adamwalach** [comment]
Follow up in #2281
