### ISSUE TITLE
Reduce the number of jobs in Kyma repository

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#1171]
**Description**

Currently, we have ~230 jobs defined for Kyma repository. Such amount of jobs may scary potential contributor, but this is not the biggest issue. Some time ago GitHub introduced the suggestions feature. It is possible to apply suggestion from PR UI then every applies is represented by commit or it is possible to apply them in batch mode. The batch mode is not a problem in general - it is only one commit. The problem is with applying them separately. Prow reacts on every commit, it is sending statuses for every job many times (start, skip, cancel, finish, fail...). With such amount of jobs, we run really fast into a problem with GitHub requests quota. Such a problem may also occur when developers are pushing changes really often to PR.

I know that we have a GitHub proxy deployed in Prow, but it reduces quota usage only when data is gathered from GitHub, not pushed.

As far as I know, it is not possible to disable suggestion feature and I really don't want to do that as it is a super cool feature :)

I see 2 things that should be done:
 - Reduce the number of jobs for repositories - we should limit them to 20 per repository?
 - Stop using `kyma-bot` in jobs, it should be reserved only for Prow. Jobs should use a separate bot

Also, as @kasiakepka suggested in #1162, we should monitor quota usage.

**Reasons**

Solve a problem with GitHub quota and not scaring potential contributors with a huge number of checks.

**Attachments**

https://developer.github.com/v3/rate_limit/

**Comment by sjanota** [comment]
[This PR](https://github.com/kyma-project/test-infra/pull/1436) makes a component have only two jobs, regardless of the number of supported releases. Is it enough to satisfy the requirements mentioned here or we need further work?

**Comment by kasiakepka** [comment]
I can see that number of defined ProwJobs has decreased since implementing [this PR](https://github.com/kyma-project/test-infra/pull/1436).
Currently we have 242 defined presubmit ProwJobs, on September 19th we had 371 of them.

**Comment by kasiakepka** [comment]
I
