### ISSUE TITLE
Prow pipeline for kyma components

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/test-infra#118]
The goal is to have a pipeline to build all kyma components migrated from internal jenkins to test-infra (prow). To track the progress please add issues for all components.

MIgration guide: https://github.com/kyma-project/test-infra/blob/master/docs/prow/migration-guide.md

**Comment by aszecowka** [comment]
Projects to migrate: (taken from https://github.com/kyma-project/kyma/blob/master/release.Jenkinsfile)

| name | assignee | status |
|-------|-----|--------|
docs| | 
components/api-controller| | 
components/apiserver-proxy| | 
components/binding-usage-controller| | 
components/configurations-generator| | 
components/environments| | 
components/istio-kyma-patch| | 
components/helm-broker| | 
components/remote-environment-broker| | 
components/remote-environment-controller| | 
components/metadata-service| | 
components/installer| | 
components/connector-service| | 
components/ui-api-layer| | 
components/event-bus| | 
components/event-service| | 
components/proxy-service| | 
tools/alpine-net| | 
tools/watch-pods| | 
tools/stability-checker| | 
tools/etcd-backup| | 
tools/etcd-tls-setup| | 
tools/static-users-generator| | 
tests/test-logging-monitoring| | 
tests/logging| | 
tests/acceptance| | 
tests/ui-api-layer-acceptance-tests| | 
tests/gateway-tests| | 
tests/test-environments| | 
tests/kubeless-test-client| | 
tests/api-controller-acceptance-tests| | 
tests/connector-service-tests| | 
tests/metadata-service-tests| | 
tests/remote-environment-controller-tests| | 
tests/event-bus| |

**Comment by mareknawa** [comment]
All migration will be finished by 14.12.2018 - agreement from SoS 2018.12.06
