### ISSUE TITLE
Could not resolve host: github.com

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#1198]
**Description**

Really often jobs fail with status `Could not resolve host: github.com`. It looks like cluster internal DNS doesn't work well.

**Expected result**

github.com is resolved.

**Actual result**

```
# FAILED!
# Cloning kyma-project/kyma at master(f495f5a21a40eb7f0aedc32197415c929785aee2)
$ mkdir -p /home/prow/go/src/github.com/kyma-project/kyma
$ git init
Initialized empty Git repository in /home/prow/go/src/github.com/kyma-project/kyma/.git/
$ git config user.name ci-robot
$ git config user.email ci-robot@k8s.io
$ git fetch https://github.com/kyma-project/kyma.git --tags --prune
fatal: unable to access 'https://github.com/kyma-project/kyma.git/': Could not resolve host: github.com
# Error: exit status 128
# FAILED!
# Cloning kyma-project/test-infra at master
$ mkdir -p /home/prow/go/src/github.com/kyma-project/test-infra
$ git init
Initialized empty Git repository in /home/prow/go/src/github.com/kyma-project/test-infra/.git/
$ git config user.name ci-robot
$ git config user.email ci-robot@k8s.io
$ git fetch https://github.com/kyma-project/test-infra.git --tags --prune
fatal: unable to access 'https://github.com/kyma-project/test-infra.git/': Could not resolve host: github.com
# Error: exit status 128
```

**Steps to reproduce**

https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-components-cms-controller-manager/1145655156545687552/build-log.txt

**Troubleshooting**

**Comment by kasiakepka** [comment]
We found out many ERRORs on  kube-dns pod (workload-kyma-prow cluster), these were issues connecting to kubernetes API. For now we managed to restart the pods that were running with errors.
```
E0622 18:12:07.712203       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:192: Failed to list *v1.Service: Get https://10.31.240.1:443/api/v1/services?resourceVersion=0: dial tcp 10.31.240.1:443: connect: connection refused
E0622 18:12:07.712962       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:189: Failed to list *v1.Endpoints: Get https://10.31.240.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.31.240.1:443: connect: connection refused
```

**Comment by kasiakepka** [comment]
kubedns logs
```
E0701 15:21:52.500715       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:192: Failed to list *v1.Service: Get https:/**/10.31.240.1**:443/api/v1/services?resourceVersion=0: dial tcp 10.31.240.1:443: connect: connection refused

E0701 15:25:25.803957       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:189: Failed to list *v1.Endpoints: Get https:**//10.31.240.1**:443/api/v1/endpoints?resourceVersion=0: net/http: TLS handshake timeout
```
kubectl describe services
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP:                **10.31.240.1**
Port:              https  443/TCP
TargetPort:        443/TCP
Endpoints:         35.246.214.50:443
Session Affinity:  None
Events:            <none>

**Comment by adamwalach** [comment]
I had the same issue when I was creating Kyma 1.13 RC0 release - it triggers multiple jobs at the same.
It looks like some kind of performance problem with DNS - I noticed that usually it happens for a group of jobs triggered simultaneously.

**Comment by kasiakepka** [comment]
It looks like this issue is related to increased traffic on kube-dns pod (to be specific dns cache -dnsmasq). Looks like changing scaling kube-dns settings helped to solve this issue.
See https://github.com/kyma-project/test-infra/pull/1242

**Comment by nachtmaar** [comment]
This happened a lot to us during the release process.

**Comment by adamwalach** [comment]
The most probable cause is issue with scaling of k8s cluster. When we schedule a job, gke is scaling up to handle the load. Sometimes kube-dns or whatever component that is responsible for handling dns-queries is too slow to start up.
Discussion: https://github.com/knative/test-infra/issues/1082
Solution from this thread is to disable auto-scaler and use constant number of nodes.

At this point I wonder what is the benefit of using a scalable-by-design solution if we cannot enable the scaling feature /s

**Comment by adamwalach** [comment]
We should implement something similar to [this](https://github.com/pusher/testing/pull/54/files)
```
until nslookup google.com > /dev/null 2>&1
do
  echo "Waiting for network..."
  sleep 1
done
```
