### ISSUE TITLE
BDBA scans are using outdated image for scanning

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#12122]
**Description**

We created the image tow days ago: https://console.cloud.google.com/artifacts/docker/kyma-project/europe/prod/subscription-cleanup-job (tag: `v20241008-16e57ea5`)
![Screenshot 2024-10-10 at 12 53 46](https://github.com/user-attachments/assets/de606d38-eba8-46fa-b8ca-cdddb48728b1)

In this image we upgraded the Dockerfile to use the latest Golang + Alpine version (happened on 4th Oct): https://github.com/tobiscr/subscription-cleanup-job/blame/main/Dockerfile.job#L2

But based from the findings in BDBA on KCP, it's still finding the previously configured Golang version (1.21.5) which seems to be caused by a non-uploaded new version of our image: https://bdba.tools.sap/#/product/1953737/analysis

Form the details in BDBA, it tells us that the scanned image was uploaded 8 months ago:

![Screenshot 2024-10-10 at 12 59 36](https://github.com/user-attachments/assets/b92409ff-3d48-4dd4-8e40-dd869c66472f)

Could you please verify why it's still not using the latest image version?

THX a lot.

**Expected result**

Scan is using latest release image of subscription-cleanup-job.

**Actual result**
Not latest image is used.

**Steps to reproduce**

**Troubleshooting**

**Comment by Sawthis** [comment]
The protelist had a wrong sha256 for subscription-cleanup-job. It was fixed and now report for BDBA KCP is clear for subscription-cleanup-job.
