### ISSUE TITLE
Upgrade deprecated image in provision-vm script

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/test-infra#123]
**Description**
In the `provision-vm.sh` script we are using a hardcoded debian image `debian-9-stretch-v20181011`, which as for now is deprecated:

```
WARNING: Some requests generated warnings:
 - The resource 'projects/debian-cloud/global/images/debian-9-stretch-v20181011' is deprecated. A suggested replacement is 'projects/debian-cloud/global/images/debian-9-stretch-v20181113'.
```

We should use a custom made image, or use a floating tag (like `latest` in docker) to guard from a problem like this.

**Comment by suleymanakbas91** [comment]
This issue will be solved once we have a custom image.

**Comment by LudovicTOURMAN** [comment]
You could also use the family tag `debian-9` which point to the latest non-obsolete image.
