### ISSUE TITLE
Prepare a performance cluster for resources and KPIs monitoring

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#1244]
**Description**

As far as I know, we have a performance cluster but I heard that it is not ready and alerting for such cluster is not enabled. As we are starting working o Kyma resources consumption we need a cluster that will meet our requirements:
 - alerting for KPIs and resources enabled
 - easy ability to define alert rules
 - the cluster should be deployed periodically (once a week?)

**Reasons**

Monitor Kyma resources usage and verify if KPIs are met.

**Attachments**

**Comment by derberg** [comment]
I will do a separate proposal for it. For now agreed with @michal-hudy to close this one
