### ISSUE TITLE
Define branch protections for test-infra repository

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#131]
**Description**

Define branch protections for `test-infra` repository. It should block PR if Prow jobs fail.

**Comment by aszecowka** [comment]
Please update documentation, that whenever you add new check, you need to define that it is required in branch protections

**Comment by suleymanakbas91** [comment]
Manually done for validation and buildpack jobs.

**Comment by pkosiec** [comment]
It'd be good to have approvers (POs) & reviewers (devs) separately
