### ISSUE TITLE
Orphaned compass integration VM instances are not cleaned up

### ISSUE THREAD

**Issue by tgorgol** [kyma-project/test-infra#1317]
**Description**

Orphaned instances of `compass-integration-test-*` VM aren't cleaned up by `orphaned-vms-cleaner`, probably because of the way it's matching VM names that should be cleaned.

**Expected result**

Orphaned compass-integration VMs should be cleaned along with kyma-integration VMs.

**Actual result**

Orphaned compass-integration VMs are not cleaned.

**Steps to reproduce**

![image](https://user-images.githubusercontent.com/45565988/62276247-eb008880-b443-11e9-846d-4052584883af.png)

**Comment by kasiakepka** [comment]
Implemented in https://github.com/kyma-project/test-infra/pull/1488
