### ISSUE TITLE
Investigate Tide changes affecting Zenhub usage

### ISSUE THREAD

**Issue by tehcyx** [kyma-project/test-infra#1372]
**Description**
For some things, we'll have to figure out if by using Tide features will not be available anymore, when we start using Tide. Questions that came up were for example:

> - Changing ZenHub pipelines (e.g. moving from TODO column to In Progress.
> - Updating Assignees
> - Setting Milestones
> - Changing Estimates
> - Adding issues to Epics & Releases
> - Changing descriptions
> Do you know if all of this will be still possible when migration to Tide will be finished?

**Comment by Disper** [comment]
One more use case to consider is that ZenHub allows performing bulk actions on issues ( https://www.zenhub.com/blog/task-board-bulk-actions/ ). 

Also, please see ZenHub document on permissions access that can be useful - https://help.zenhub.com/support/solutions/articles/43000037261-github-permissions-and-access-in-zenhub

**Comment by kasiakepka** [comment]
As per Michał's comment [here](https://wiki.hybris.com/display/ysf/Release+1.5+-+Lima) "Tide integration is no longer blocked - write access will not be removed until ZenHub provides Triage access rights."
