### ISSUE TITLE
Forward Compass-related job failures to separate Slack channel

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/test-infra#1382]
**Description**

- Extend https://github.com/kyma-project/test-infra/tree/master/development/prow-addons-ctrl-manager and add ability to specify Slack channel in ProwJob label
- Forward Compass-related job notifications to separate slack Channel

Hint: Modify Reporter: https://github.com/kyma-project/test-infra/blob/master/development/prow-addons-ctrl-manager/pkg/slack/reporter.go

**Reasons**

Compass along with compass-agent are experimental components, which shouldn't be reported along other stable components.

**Comment by PK85** [comment]
@pkosiec to which channel do you want to send that?

**Comment by PK85** [comment]
wont fix
