### ISSUE TITLE
AKS performance test setup

### ISSUE THREAD

**Issue by tehcyx** [kyma-project/test-infra#1385]
**Description**
In an effort to find out about the performance of Kyma on AKS, as well as being able to compare these results to how Kyma runs on GCP we'll need to setup a pipeline to create a cluster on AKS and run the performance tests on it.

**Reasons**
Get some insight into performance.

**Comment by mareknawa** [comment]
Neighbors team delivered set up for the performance tests. Hishar and architects team should take it over and make this plan running.

**Comment by kasiakepka** [comment]
This issue is also blocked by https://github.com/kyma-project/kyma/issues/4719
