### ISSUE TITLE
Add testing.sh to the GKE integration pipeline

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/test-infra#139]
**Description**

As requested [here](https://github.com/kyma-project/test-infra/issues/20) by @jakkab helm is required in some testing scripts.
My question would be, should we add helm to the base bootstrap image, or create a buildpack image for helm?

**Comment by jakkab** [comment]
- [ ] add testing.sh to the GKE integration pipeline
- [ ] create bootstrap-based GKE integration image with helm command installed

**Comment by aszecowka** [comment]
- why kyma-gke-integration job is still failling all the time
- can printing out "tlsCrt" be a security issue?
