### ISSUE TITLE
Integrate Tide

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/test-infra#14]
**Description**

To make use of Prow's batch job and automatic merge features, we must integrate Tide. An analysis should be done on how to use and integrate it with Prow. Configurations should be decided as well. Especially, [these configurations](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/tide/config.md) about when to merge a PR automatically.  

**Acceptance Criteria**
- Document how to use/configure Tide and how to integrate it with Prow.
- Provide the configurations for the custom needs of Kyma repos.

**Comment by crabtree** [comment]
Splice was removed from prow (https://github.com/kubernetes/test-infra/pull/9520)

**Comment by suleymanakbas91** [comment]
Thanks for the update! I changed the issue description accordingly.
