### ISSUE TITLE
Explore Provision Gardener on Azure topic

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#1405]
Explore provisioning Gardener on Azure.

**What should be done:**
- [x] Setup call/meeting with Borja
- [x] Align with Huskies team as they are working on Provisioning Kyma on Gardener from Kyma CLI and they also might want to create new pipeline for that. (Make sure that work is not duplicated).
- [ ] setup new pipeline leveraging Provisioning API

**Comment by mareknawa** [comment]
We need to wait with this task for finishing Terraform implementation in Huskies team.

**Comment by kasiakepka** [comment]
Additionally Provisioning API won't be implemented in this release most likely.
https://github.com/kyma-project/kyma/issues/5492

**Comment by kasiakepka** [comment]
Provisioning API repo: https://github.com/kyma-incubator/hydroform and example usage [here](https://github.com/kyma-incubator/hydroform/blob/master/examples/gcp/main.go)
