### ISSUE TITLE
Prow pipelines refinement

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#1408]
In order to prepare for migration from Bash to Go and easier Prow maintenance it is required to:
- [x] remove code duplications
- [ ] unify cleanup method for all the pipelines
- [x] remove unnecessary variables and migrate them to prowjob templates (if possible)

**Comment by mareknawa** [comment]
Take into account Terraform impact on our scripts. Use CLI as much as possible in pipeline definition.

**Comment by kasiakepka** [comment]
We managed to work on nightly pipelines, resource creation and cleanup was improved. 
As refining bash scripts is time consuming we decided to rewrite the pipelines from scratch (in Go). Additionally [Provisioning API](https://github.com/kyma-project/kyma/issues/5492) won't be implemented in this sprint most likely.
