### ISSUE TITLE
Kyma WhiteSouce scan failing

### ISSUE THREAD

**Issue by jose-cortina** [kyma-project/test-infra#1409]
**Description**

In the last 14 days we have no successful execution of the WhiteSource scan running as a job in PROW. The errors seem to be different, the latest one being:

`ERROR: (gcloud.kms.decrypt) PERMISSION_DENIED: Request had insufficient authentication scopes.`

**Expected result**

The WhiteSource scan completes successfully.

**Actual result**

Scan fails.

**Steps to reproduce**

Executed as a job in PROW:
https://status.build.kyma-project.io/job-history/kyma-prow-logs/logs/kyma-whitesource-scan

**Comment by kasiakepka** [comment]
@tehcyx Can you please look at it?
For now I disabled notification for this job so that it is not spamming CI force.

**Comment by kasiakepka** [comment]
This issue was fixed with https://github.com/kyma-project/test-infra/pull/1485 and https://github.com/kyma-project/test-infra/pull/1486
