### ISSUE TITLE
Prow pipeline for releasing kyma

### ISSUE THREAD

**Issue by strekm** [kyma-project/test-infra#144]
Goal is to automate release process of kyma. In this epic we are going to implement jobs for components, as well as specific jobs for releasing.
Documentation: 
Define release jobs for component: https://github.com/kyma-project/test-infra/blob/master/docs/prow/migration-guide-release.md
Kyma release process in Prow: https://github.com/kyma-project/test-infra/blob/master/docs/prow/kyma-release-process.md

**Comment by strekm** [comment]
Projects to migrate: (taken from https://github.com/kyma-project/kyma/blob/master/release.Jenkinsfile)

| name | assignee | status |
|-------|-----|--------|
docs |  | |
components/api-controller| goats | | 
components/apiserver-proxy| goats ||
components/binding-usage-controller|  ||
components/configurations-generator| goats | | 
components/environments| goats ||
components/istio-kyma-patch| goats | | 
components/helm-broker|   | |
components/remote-environment-broker|  | |
components/remote-environment-controller|  | |
components/metadata-service|  | |
components/installer| goats | |
components/connector-service|  || 
components/connection-token-handler |  | |
components/ui-api-layer|   | |
components/event-bus|   | |
components/event-service|   || 
components/k8s-dashboard-proxy|   || 
components/proxy-service|  |  |
tools/alpine-net|  | |
tools/watch-pods|  || 
tools/stability-checker|  | | 
tools/etcd-backup|  |  |
tools/etcd-tls-setup|  ||  
tools/static-users-generator| goats | |
tools/ark-plugins |  | |
tests/test-logging-monitoring|  | |
tests/logging|  | |
tests/acceptance|   | |
tests/ui-api-layer-acceptance-tests|  | |
tests/gateway-tests|  | |
tests/test-environments | goats | |
tests/kubeless-test-client|  | |
tests/kubeless-integration|  | |
tests/api-controller-acceptance-tests | goats | |
tests/connector-service-tests|  |  |
tests/metadata-service-tests|  |  |
tests/remote-environment-controller-tests |  |  |
tests/event-bus|   | |
console/brokers|   | |
console/catalog|   | |
console/components/react|  | |
console/content|   |  |
console/lambda|  | |
console/core|  | |
console/instances|   | |
console/tests|   | |
examples/call-ec|| | 
examples/event-email-service| | |
examples/http-db-service| | |
examples/tracing| | |
examples/monitoring-custom-metris|  | |
examples/tests/http-db-service|  | |
governance|  | |
website|   |  |
incubator/service-catalog-tester |  | |
incubator/kymactl |  | |
incubator/varkes |  | |
incubator/vstudio-extension |  | |
bundles |   | |

**Comment by mjasinski5** [comment]
Guys one question. Should we define release pipelines for non-kyma-repositories? like console? I think this epic should consists of only kyma-related pipelines. Please confirm that.

**Comment by suleymanakbas91** [comment]
> Guys one question. Should we define release pipelines for non-kyma-repositories? like console? I think this epic should consists of only kyma-related pipelines. Please confirm that.

Yes, it should only consists of kyma pipelines. We updated the list accordingly.
