### ISSUE TITLE
Display Prow metrics on dashboard

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#147]
As a Prow administrator, I would like to be able to see the current status of Prow cluster provided by metrics.
See available metrics: https://github.com/kubernetes/test-infra/blob/master/prow/metrics/README.md

Consider adding custom metrics.

**Comment by a-thaler** [comment]
Having the number of executed tests with success ratio will be a nice metric. If you see an easy way to integrate it as custom metric that will be great.

**Comment by aszecowka** [comment]
MVP: 
- are components down?
- memory usage from Prow components
- number of running jobs
- github token usage
- jobs pass rate

**Comment by michal-hudy** [comment]
Github token usage will require more work...
