### ISSUE TITLE
Create pipeline for Kyma verification on latest k8s versions

### ISSUE THREAD

**Issue by derberg** [kyma-project/test-infra#1470]
**Description**

* Implement CI jobs described in the proposal. "kind" is must-have, and "minikube" not. Try to use Kyma CLI if it is possible, if not, report issues.
  * throw alerts to slack channel, in case job fails
* Create a clear process/procedure/guideline how to perform manual work so the whole upgrade flow is simple to go through by any maintainer.

**Reasons**

Implement proposal https://github.com/kyma-project/community/blob/master/collaboration/sig-core/proposals/regular-k8s-upgrades.md to have more regular updates in Kyma related to new k8s versions.

**Comment by michal-hudy** [comment]
Generally, it will like any other integration pipeline, the only difference is the creation of cluster. Currently, we are testing Kyma on Minikube, GKE and AKS. So the flow will be like that:
 1. Provision Tide cluster - probably on VM - use script from Minikube pipeline.
    https://github.com/kyma-project/test-infra/blob/master/prow/scripts/minikube-test.sh
 2. Install Kyma - use CLI installation, or modify installation scripts if needed
 3. Start tests

By default post/periodic pipelines automatically send notifications to slack.

**Comment by derberg** [comment]
all ready and works like a charm but we decided to keep this pipeline running on k8s1.14 as we are now migrating all pipelines to `kind` and want to make sure daily Kyma works on 1.14
once we are done with the migration, we will switch this kind pipeline to k8s16
