### ISSUE TITLE
Provide strategy for updating Prow cluster

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#148]
As a Prow administrator, I am able to update my cluster with the newest version of Prow. 

AC: 
- procedure is documented
- an update is seamless and it does not affect developers experience (ideally zero downtime)

**Comment by Demonsthere** [comment]
Linking the official [documentation](https://github.com/kubernetes/test-infra/blob/master/prow/build_test_update.md).
I would say, what we may want to do is to create a prow job that would patch our cluster deployments with the new version of the image. However, we would still need to update our `starter.yaml`.

An alternative would be to rewrite the `starter.yaml` to a helm chart or even just split into several files that can be modified with the new version tag.

**Comment by Demonsthere** [comment]
As much as I agree with you, the problem with a helm chart will be that it will *our* chart, not *theirs*. We will still need to check their progress every once in a while and update our templates in case they modified something. 
The job I was thinking about would only update the images that are used in the running deployment without modifying the deployments.

**Comment by Demonsthere** [comment]
Small update:
I have checked the way others deal with the problem (knative and istio), and I have to say they do exactly the same: update the image in the deployments, however in a manual way: 
- https://github.com/knative/test-infra/blob/master/ci/prow/cluster.yaml
- https://github.com/istio/test-infra/tree/master/prow/cluster
What is important: we can see that the deployment manifests did not change in quite some time, and only the tags on deployment images change.

**Comment by crabtree** [comment]
In terms of security issues, we need to have a clear plan for cluster updates

**Comment by crabtree** [comment]
Maybe this can be a good starting point https://github.com/kubernetes/test-infra/blob/master/prow/build_test_update.md#how-to-update-the-cluster

**Comment by tehcyx** [comment]
We've just merged a PR with the strategy. You can find it here: https://github.com/kyma-project/test-infra/blob/master/docs/prow/prow-cluster-update.md
