### ISSUE TITLE
Add generic runner script

### ISSUE THREAD

**Issue by mszostok** [kyma-project/test-infra#1499]
**Description**

We should have an option to execute our own script with docker in docker support sth similar that K8s has:

https://github.com/kubernetes/test-infra/blob/8746727bb0959a0b52319cdacb44229702ee0597/config/jobs/kubernetes-sigs/service-catalog/service-catalog-presubmits.yaml#L32-L33

**Reasons**

Right now I can use DIND on other features only when I'm executing 
[build.sh](https://github.com/kyma-project/test-infra/blob/master/prow/scripts/build.sh)
script.

When it comes to executing my own script with the DIND support then I need to copy dedicated code directly into my component because I'm not able to override default execution of build.sh script, so I've copied this part and executing it on our CI:

https://github.com/kyma-project/helm-broker/pull/32/files#diff-32214727abd88219923db6fd4b77327dR93-R95

It's not a good approach. First I should not be an owner of that part, I should only inform you using `preset-dind-enabled: "true"` that my script requires such setup. Second thing is that such customization in future can grow, e.g. maybe we will also add some support for caching etc. and such logic should be definitely sitting under test-infra repo and not in various scripts under different components.

**Comment by dekiel** [comment]
https://github.com/kubernetes/test-infra/blob/cdaab988e09d8a4d5d9336310deb42bfa745c60a/images/bootstrap/runner.sh
