### ISSUE TITLE
Set failure notifications for Prow

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/test-infra#15]
**Description**

Currently, there is no way to receive notifications from Prow in case of job failures. We'll investigate if we can use prometheus & alertmanager to achieve this.

**Comment by kazydek** [comment]
Remember to update the `prow-architecture.md` document and the `prow-architecture.svg` diagram with ifnormation on the Slack plugin.

**Comment by michal-hudy** [comment]
Just an idea: As prow probably doesn't have support for `Slack`, we can try with `Alertmanager`. It is already deployed on the cluster. It only needs to be configured. As an alternative, we can create prow component for Slack.
