### ISSUE TITLE
create postsubmit job for gke kyma integration tests

### ISSUE THREAD

**Issue by strekm** [kyma-project/test-infra#150]
At the moment there's prow/kyma/kyma-gke-integration job which is defined for pre-submits. The goal of this issue to have a similar job post-submits. For time being we can assume the job is triggered on every commit to master branch (later on it should be only triggered if charts are changed). Refactor existing scripts to be reusable.

AC: kyma-gke-integration job is triggered on every commit to master

**Comment by piotrmsc** [comment]
Review : @strekm @Tomasz-Smelcerz-SAP

**Comment by Demonsthere** [comment]
I think the followup is strongly connected to #264. @aszecowka do you have input on this?

**Comment by sjanota** [comment]
@piotrmsc @pbochynski There's already issue created to handle `latest` tag #256. Moving to "To Accept".
