### ISSUE TITLE
Test job for template generator 

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#1505]
Add Prowjob that will verify if someone has edited one of the Prowjob configuration files [listed in templated/config.yaml](https://github.com/kyma-project/test-infra/blob/master/templates/config.yaml) that supposed to be autogenerated.
See also: https://github.com/kyma-project/test-infra/blob/master/docs/prow/templates.md

- [x] Add information about that validation job in documentation.
- [x] Run validation test for all PRs.

**Comment by kasiakepka** [comment]
See also https://github.com/kyma-project/test-infra/pull/1501

**Comment by mszostok** [comment]
I will work on it:)

**Comment by mszostok** [comment]
I've closed my pr: https://github.com/kyma-project/test-infra/pull/1516

and my team-mate implemented this feature here: https://github.com/kyma-project/test-infra/pull/1650

**Comment by kasiakepka** [comment]
Job works as expected.
