### ISSUE TITLE
Grafana Dashboards displaying test coverage

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#1510]
**Description**

Create Grafana Dashboard displaying test coverage

**Reasons**
Measure effectiveness of testing

**Related issues**
https://github.com/kyma-project/test-infra/issues/1798

**Comment by adamwalach** [comment]
We created a StackDriver log-based-metric for a following query:
```
resource.type="k8s_container"
resource.labels.cluster_name="workload-kyma-prow"
resource.labels.namespace_name="default"
resource.labels.container_name="test"
"Total test coverage:" 
```
Chart created in MetricExplorer was unreadable:
<img width="735" alt="Screen Shot 2019-12-03 at 14 34 27" src="https://user-images.githubusercontent.com/8530211/70055605-2bcb0280-15da-11ea-804e-fe521366632e.png">
and it looks like its not possible to make it better cause data points are randomly scattered in time.

Grafana can use StackDriver as a data source:
<img width="1334" alt="Screen Shot 2019-12-03 at 10 08 34" src="https://user-images.githubusercontent.com/8530211/70055729-72b8f800-15da-11ea-8959-279f7ea2ef6b.png">

Charts look better but are still very hard to read:
<img width="1353" alt="Screen Shot 2019-12-03 at 10 08 18" src="https://user-images.githubusercontent.com/8530211/70055901-c592af80-15da-11ea-83cc-b72f357ecc5e.png">
<img width="1359" alt="Screen Shot 2019-12-03 at 10 08 04" src="https://user-images.githubusercontent.com/8530211/70055914-cc212700-15da-11ea-9e71-0a8dc91d2e66.png">

## Summary
Grafana with StackDriver backend has very limited configuration options and we cannot use it to provide information about test coverage metrics.
We have a different solution for that: https://github.com/kyma-project/test-infra/issues/1798

**Comment by kasiakepka** [comment]
I'm closing this issue, it is resolved in https://github.com/kyma-project/test-infra/issues/1798
