### ISSUE TITLE
Google case #20795345 - suspicious activity observed on VM.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#1531]
We need to investigate spike of the traffic outgoing from VM gke-nightly-default-pool-6cd2688d-z1dh:europe-west4-b VM gke-nightly-default-pool-6cd2688d-z1dh:europe-west4-b.

From google mail:
> We have recently detected your Google Cloud Project sap-kyma-prow-workloads (id: sap-kyma-prow-workloads) VM gke-nightly-default-pool-6cd2688d-z1dh:europe-west4-b has been displaying suspicious behavior consistent with denial of service attacks. Based on our records, the most recent outbound traffic spike originated from IP via 34.90.213.205 between 2019-09-29 17:31 and 2019-09-29 17:37.
You can fix the the problem by ensuring that your project traffic directed at third-parties is expected, and that your project has not been compromised. If you do believe that your Google Cloud Project may have been compromised by a third party, we recommend adopting additional security measures and then completely re-installing your project. You can find more tips on securing your instance here (https://support.google.com/cloud/answer/6262505).

**Comment by dekiel** [comment]
I was not able to find logs for VM instance mentioned in mail. Even, I was not able to find case in google support. I've created another one #20812333.

**Comment by dekiel** [comment]
Original case #20795345 is visible. I've asked for more details as couldn't find anything in logs in GCP.

**Comment by dekiel** [comment]
Got update from google, that they sitll didn't manage to get any tracing/debug data to analyse.

**Comment by tehcyx** [comment]
Resolved with Google, teams will have to monitor API Server request. Other tickets are already being worked on.
