### ISSUE TITLE
Migrate links validation from Jenkins to Prow

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#154]
**Description**

Currently, in Jenkins pipeline, we have a links validation on PR if documentation has been changed. Also, we have a nightly validation on every master branch. Such validation should be migrated to Prow.
It should work like right now in Jenkins, so:
 - PR:
   - absolute paths are checked only on changed files
   - relative paths are checked against the whole repository
 - Nightly:
   - absolute and relative paths are checked against the whole repository

AC:
 - PR and nightly validations for all repositories in `kyma-project` organization:
   - [x] community
   - [x] console
   - [x] kyma
   - [x] website
   - [x] test-infra
   - [x] examples
   - [ ] bundles - optional as we don't have links validation in Jenkins for that repository, so it may needs links fixes
   - [ ] luigi - optional as we don't have links validation in Jenkins for that repository, so it may needs links fixes

Notifications to Slack are out of scope. Integration with Slack is not ready.

**Reasons**

Resign from internal CI - Jenkins.

**Comment by pkosiec** [comment]
Review: @michal-hudy @pkosiec

**Comment by mjasinski5** [comment]
Review: @michal-hudy @pkosiec
