### ISSUE TITLE
Update production Prow to current version from upstream

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#1556]
During work on #1162 I've found that feature of github token usage monitoring was implemented in upstream by @tehcyx . As we should upgrade our prow instance I'm going to work on this first.
Acceptance criteria:
- Production Prow instance upgraded to current upstream version.
- Installation instructions are aligned to reflect current status.
- Created issue for continuous and automated upgrade process to follow upstream version.

**Comment by tehcyx** [comment]
Please check for k8s version requirements as well.

**Comment by tehcyx** [comment]
Please make sure that the prow jobs that are definitely in a different format are also reflected in the rendertemplates tool.

**Comment by dekiel** [comment]
We have learned that new version of Prow doesn't allow us to have required status checks which are triggered by `run_if_changed` rule. It's Tide feature, to ensure all non optional status checks finished with success before allowing PR merge. In our setup, it's not possible to use Tide in this role, as it require revoking write permissions on github repositories for organisation users. As a result of it, we would not be able to use zenhub as it require github write permissions for multiple basic operations on pipelines. As for now, prow upgrade is blocked by this limitation and we need to come up with proposal of workaround.
