### ISSUE TITLE
Migrate website pipeline to Prow

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#156]
**Description**

As we are moving to Prow, we need to migrate `website` pipeline. Such pipeline right now pushes some changes to master branch during the build. That behavior should be abandoned as it makes pipeline complicated and in fact, we don't need to push to master.

HINTS:
 - Push new documentation only to `gh-pages` branch, not to master. On the master branch, we should have only mocked documentation for testing purposes, or none.

**Reasons**

Resign from internal CI - Jenkins.

**Comment by pkosiec** [comment]
Another hint:
Use private SSH key for pushing on `gh-pages` branch. Generate new SSH key and add it to `kyma-bot` user.

**Comment by pkosiec** [comment]
Review: @michal-hudy @pkosiec
