### ISSUE TITLE
Enable SSH access to VMs on which integration tests are executed

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#1560]
**Description**

In `kyma-integration.yaml` and `kyma-compass-integration.yaml` we have defined jobs that run kyma on minikube. Sometimes developers want to ssh into the machine for debugging purposes. In the current setup of GKE project where Prow workload is executed, it seems to be not possible to do that.
Ability to SSH to VMs should be enabled for every Kyma code codeowner.

**Comment by kasiakepka** [comment]
I've cleaned up IAM on our _sap-kyma-prow-workloads_ project.
Thanks to custom _kyma_developer_ role developers now have access to K8 clusters as well as VM instances. _Kyma_developer_ role does not expose write access to network and other compute resources.
