### ISSUE TITLE
Upgrade Prometheus to current version.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#1562]
**Description**
We need to research what Prometheus version and prometheus operator version we are running, if there are newer versions available and how to upgrade our systems.
**Reasons**

We should regularly upgrade our monitoring system to follow upstream versions to get latests features and fixes.
We should have robust upgrade process because of critical bugs and security reasons.

**Comment by michal-hudy** [comment]
We don't need to research, everything is described here:

Requirement:
https://github.com/kyma-project/test-infra/blob/master/prow/cluster/resources/monitoring/requirements.yaml#L3
Lock:
https://github.com/kyma-project/test-infra/blob/master/prow/cluster/resources/monitoring/requirements.lock#L4

You can also use the `helm list` command.

**Comment by dekiel** [comment]
Versions in use:
prometheus-operator chart 0.1.30
prometheus-operator app 0.25.0
prometheus 2.5.0
grafana 5.3

**Comment by dekiel** [comment]
Prometheus was upgraded along with recent prow upgrade.
