### ISSUE TITLE
Add a pr-image-guard job for all PRs to master

### ISSUE THREAD

**Issue by sayanh** [kyma-project/test-infra#1604]
**Description**
With the new release process, the PR-XXXX image are of no good hence they should not be in master at all. Add a pr-image-guard job to all PRs to master.

**Reasons**
Having `pr-image-guard`( something like `pre-release-pr-image-guard`) as a required job in all PRs to master will block PRs if the images are not in develop version. This is to force the developers to use a develop version image while merging to master which will avoid having surprises during release.

This is one of the learnings from 1.6 release.

**Comment by aszecowka** [comment]
@sayanh
This proposition tries to invalidate proposal about updating code and chart in the same PR:
https://github.com/kyma-project/community/blob/a86cfa47302d0263f62ee48347cb400bc39e00e3/collaboration/sig-core/proposals/update-code-and-chart-in-one-pr.md

Still, you are not forced to use PR images, you can break them into 2 separate PRs. IMO it should be a team decision which option to use.

**Comment by sayanh** [comment]
@aszecowka What I understand from the proposal is, it does not automate anything but we legalize PR-XX images. I find it strange as although PR-XX images are legal, they are not good to release. If I commit something to master, it should be as good as releasable or we rebuild all the images in the release process(which is not the case anymore).

This job blocks the PR for sure but if a developer wants to test his/her components then the tests do work. So it makes sense to commit only the develop images cause they are releasable as per the new process.

**Comment by sjanota** [comment]
@sayanh While I agree with you it was decided when we were working on changes in the release process that the proposal mentioned by @aszecowka is still valid. Most of our respondees either didn't care are found it valuable. That's why there is an image guard job run on the release branch which verifies if there is any PR image. Every team must make sure that official images are used on the release branch. In exceptional cases release RC with PR images (for example to allow manual testing while a time-consuming fix is being prepared). That's why the guard job is optional.

**Comment by sjanota** [comment]
Using PR images is an additional effort for the team during/before the release. On the other hand, they benefit from having only one PR. It's up to them to decide which way to go as long as they don't slow down the release.

**Comment by sayanh** [comment]
@sjanota When the decision of legalizing the PR image was done the release process was different. I don't see the point of changing the image at the very last moment during the release process. IMO release gets in jeopardy if things are messed at very the last moment(at least that's what happened in the past). I don't see how this is slowing things down as without this image bump(to develop version) you can't even release. In my team, pushing a develop image is in the DOD and I believe that is how things should be done unless there is complete automation in place.

**Comment by adamwalach** [comment]
Since there is no agreement that we should enable this job for all PRs and current setup seems to be working I will close this ticket. If you think it is still needed please reopen or create a new issue
