### ISSUE TITLE
Store metrics from long-running clusters in Stackdriver

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#1623]
**Description**

Enable integration with Stackdriver so it will be able to scrap Prometheus metrics from our long-running clusters (like nightly and weekly).

AC:
 - Integration enabled
 - In Stackdriver:
   - Chart with communication with API server grouped by component
   - Chart with requests grouped by type (same as in Kubernetes Control Plane Status dashboard) with the ability to filter per component.
   - Table with TOP 10 components
 - Kyma developers have access to Stackdriver with the ability to create dashboards

**Reasons**

Currently, we are not able to track regressions in our clusters and we have access to metrics only when clusters are living. Stackdriver is a managed system (so we don't have to DevOps it) that has an ability to scrap and store metrics from multiple clusters. It stores them for longer period of time so we will be able to compare it even between clusters.

**Attachments**

https://cloud.google.com/monitoring/kubernetes-engine/prometheus

**Comment by dekiel** [comment]
Prometheus version 2.7.1 used by Kyma was not tested against compatibility with any stackdriver-sidecar version.

**Comment by michal-hudy** [comment]
Ok, but please check, maybe it will work, if not, please create an issue on Kyma repository that this is something that blocks integration with Stackdriver.

**Comment by dekiel** [comment]
We have deployed stackdriver collector on nightly and weekly clusters. Charts defined in Grafana for number of up api servers is currently not defined in stackdriver becasue of missing metric. Prometheus "up" metric was used in Grafana. Metric is present in stackdriver but is missing apiserver job related data.

I've inspected metrics description retrieved from Stackdriver API. Following is definition of Prometheus up metric. Metric is missing job and instance labels. These labels are used in Grafana dashboard as well and identify time series.

```
ame: "projects/sap-kyma-prow-workloads/metricDescriptors/external.googleapis.com/prometheus/up"
metric_kind: GAUGE
value_type: DOUBLE
type: "external.googleapis.com/prometheus/up"
```

Running collector is writing following errors.
1.
```
level=warn ts=2019-11-04T17:11:35.951Z caller=queue_manager.go:534 component=queue_manager msg="Unrecoverable error sending samples to remote storage" err="rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: external.googleapis.com/prometheus/up, Timestamps: {Youngest Existing: '2019/11/04-09:11:30.022', New: '2019/11/04-09:11:34.195'}}: timeSeries[95-180]"
```
2.
```
level=warn ts=2019-11-04T17:11:46.716Z caller=queue_manager.go:534 component=queue_manager msg="Unrecoverable error sending samples to remote storage" err="rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: The new labels would cause the metric external.googleapis.com/prometheus/kube_deployment_labels to have over 10 labels.: timeSeries[50-54,56-61]"
```
3.
```
level=warn ts=2019-11-04T17:11:48.717Z caller=queue_manager.go:534 component=queue_manager msg="Unrecoverable error sending samples to remote storage" err="rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Field timeSeries[53].metric.type had an invalid value of \"external.googleapis.com/prometheus/instance:node_cpu:ratio\": The metric type must be a URL-formatted string with a domain and non-empty path.: timeSeries[53]; Field timeSeries[54].metric.type had an invalid value of \"external.googleapis.com/prometheus/instance:node_cpu:ratio\": The metric type must be a URL-formatted string with a domain and non-empty path.: timeSeries[54]; Field timeSeries[55].metric.type had an invalid value of \"external.googleapis.com/prometheus/instance:node_cpu:ratio\": The metric type must be a URL-formatted string with a domain and non-empty path.: timeSeries[55]"
```

Running collector required 1Gi memory limit and prometheus server container with sidecar container require 2Gi memory limit, otherwise containers are terminated by OOMKiller.

Another limitation found by @adamwalach is retention of stored metrics. Stackdriver will delete metrics data after 6 weeks. In order to store metrics for longer period, data has to be exported to another long storage tool.

**Comment by michal-hudy** [comment]
I think 6 weeks is OK for now. @pbochynski ?

Do I understand correctly? If we will extend memory, then we will be OK?

**Comment by pbochynski** [comment]
It is ok for us to have just 6 week history. Later on we can dump data to some storage like BigQuery, but we can postpone it.

**Comment by adamwalach** [comment]
Documentation: https://cloud.google.com/solutions/stackdriver-monitoring-metric-export

**Comment by adamwalach** [comment]
Compatibility matrix between SD sidecar and Prometheus: https://github.com/Stackdriver/stackdriver-prometheus-sidecar#compatibility
Version used in Kyma (2.7.1) is listed as not tested. We should upgrade to [v2.11.2]( https://github.com/prometheus/prometheus/releases/tag/v2.11.2)

**Comment by kasiakepka** [comment]
Huskies are planning Prometheus update already: https://github.com/kyma-project/kyma/issues/4520

**Comment by dekiel** [comment]
Prometheus and collector containers are stable after setting limits to 4Gi and 2Gi respectively. Looks that solving OOMKiler issues, solved issue with to many timeseries points. The error is not present in logs anymore.

At present memory settings are manualy adjusted i clusters. Need to place persistent changes in code.

**Comment by dekiel** [comment]
Another OOM on prometheus container happened. Increasing limit to 6Gi. sidecar is stable below 2Gi.

**Comment by dekiel** [comment]
Weekly and nightly clusters are running with stackdriver collector.
Metrics are delivered to stackdriver workspace connected to workloads project.
Issues:
None metrics related to apiservers are delivered to stackdriver. We are getting log messages about unknown resource for apiserver job.

Few other errors are logged for differnet metrics. Recent examples.
- To frequent points written for metric "up"
- To many labels for metric.
- Invalid metric type which must be URL formatted string.

Node memory utilisation metrics can't be displayed with node names. Only pod names are available as metric names.

**Comment by dekiel** [comment]
Further work on defining metrics will be done under #1719
