### ISSUE TITLE
Migrate all pre-submit jobs that requires cluster to kind

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#1624]
**Description**

Migrate pre-submit (on PR) jobs to kind and generate proper reports from it. Execute jobs on a real cluster (GKE, AKS, even Minikube and others if needed) on post-submit jobs.

AC:
 - All pre-submit jobs that require cluster are working on kind
 - Execute GKE clusters as post-submit jobs with notifications on fail
 - JUnit report is generated from job (contains infrastructure, installation, tests and other steps) and stored as an artifact
 - Logs are stored as build artifacts
 - Added more nodes to workload cluster in multiple zones - if needed expand the limit for CPU, Memory, disks and others in project
- adjust documentation to reflect the new approach
- announce on slack channel

**Reasons**

Jobs that are working on GKE clusters are producing lots of resources and it has an impact on job time. Currently, you need to wait long time for a job to finish (when tests are enabled). Also, we have to clean up resources after such clusters.

**Attachments**

**Comment by adamwalach** [comment]
- check if we could use load balancer on kind
- kyma cli supports junit raports for infrastructure, installation and tests
    - note: for a time being infrastructure raports will be implemented in bash 
- improvements to post-master jobs will be done in a separate follow-up issue
- create cleanup job for kind

**Comment by mmitoraj** [comment]
Confirmed with @michal-hudy that it is not critical anymore.

**Comment by michal-hudy** [comment]
I think we should drop that topic for now. The `kind` pipeline is no longer stable on the pipeline...
