### ISSUE TITLE
Add test-infra check if jobs are up-2-date wth config.yaml

### ISSUE THREAD

**Issue by dbadura** [kyma-project/test-infra#1626]
**Description**

When user run ` go run development/tools/cmd/rendertemplates/main.go --config templates/config.yaml` on master, the renderer modify the jobs. 
It's proves that `config.yaml` is out of sync with jobs.

This happens on Master branch.
**Expected result**
When user render jobs from `config.yaml` on master branch, the renderer shouldn't change any of job.
When I changed something in `config.yaml` and doesn't render the jobs, the CI should block this kind of change on PR.
**Actual result**
Rendering the jobs, change about 10 other jobs and add new one.

**Steps to reproduce**
run:
` go run development/tools/cmd/rendertemplates/main.go --config templates/config.yaml` in root directory.

**Troubleshooting**

**Comment by kasiakepka** [comment]
It is related to https://github.com/kyma-project/test-infra/issues/1505

**Comment by adamwalach** [comment]
This issue was solved here: https://github.com/kyma-project/test-infra/pull/1650
