### ISSUE TITLE
Add feature encrypting secrets with GCP KMS service and strogin on GCS.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#1642]
**Description**

All secrets and crypto keys used by Prow must be encrypted and stored in GCS. Installer must support adding prefix for stored secrets to support multiple prow instances in one GCP project.

**Reasons**

Some existing installation apps are expecting secrets available in GCS. Encrypted secrets stored in GCS are chosen way of storing sensitive data.

**Comment by kasiakepka** [comment]
Daniel's contribution: https://github.com/dekiel/test-infra/pull/2

**Comment by dekiel** [comment]
see PR #1774

**Comment by dekiel** [comment]
Merged in #1774
