### ISSUE TITLE
Some tests are turned off when running on local environment

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#1649]
**Description**
Following tests are disabled when running on local env (minikube, kind)
- [application-registry](https://github.com/kyma-project/kyma/blob/release-1.7/resources/application-connector/charts/application-registry/templates/tests/test.yaml#L1-L4)
- [connector-service](https://github.com/kyma-project/kyma/blob/release-1.7/resources/application-connector/charts/connector-service/templates/tests/test.yaml#L1-L4)
- [application-operator](https://github.com/kyma-project/kyma/blob/release-1.7/resources/application-connector/charts/application-operator/templates/tests/test.yaml#L1-L4)

AC: 
- evaluate if they can be enabled on local, so we have the same set of tests running on every environment (or at least the same on kind and gke)

**Comment by adamwalach** [comment]
These tests were disabled because on minikube environment resources like memory and cpu were limited (compared to full gke cluster). We could enable them once again in the kind cluster and see if the situation improves.

**Comment by michal-hudy** [comment]
I have enabled them and they are working:
https://github.com/kyma-project/kyma/pull/6295
https://github.com/kyma-project/test-infra/pull/1732
