### ISSUE TITLE
Implement cleaner for orphaned containers started by DIND

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#1651]
**Description**

As we are using DIND environment with an attached node system, we need to be sure that we don't have any orphaned Docker containers. For sure jobs needs to clean up everything, but we need double protection for that, because jobs may crash.

**Reasons**

Protection against Docker Container leaks

**Attachments**

Take a look at https://github.com/kubernetes/test-infra/blob/master/images/bootstrap/barnacle/main.go

**Comment by kasiakepka** [comment]
All details should be consulted with Michał.
The original idea was to run the cleaner at the beginning of the Prowjob execution.

**Comment by Ressetkk** [comment]
Upon further investigation I don't think there is a need for such cleaner. The ProwJob has it's own command wrapper that monitors and handles signals sent to the container. When rerunning/skipping the job the container gets SIGTERM signal and terminates the processes associated with specified job. Even sending SIGKILL/SIGHUP directly to the container entrypoint process (which is behaviour not likely to occur) does not leave any orphaned processes inherited by PID 1 of host when the container dies.

Docker daemon working in a container has it's own context and has no access to the context/containers/images of the host or previous job and gets deleted after pod removal thus the suggested cleaner has no use in that case.
