### ISSUE TITLE
Add more nodes to workload-kyma-prow

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#1653]
**Description**

Add more `n1-standard-16` node pools to `workload-kyma-prow` cluster in multiple zones. Nodes should scale do 0 if not needed.

AC:
 - Machine: `n1-standard-16` with SSD disks
 - Splited by multiple node pools in multiple zones
 - Number of nodes must fit max concurrent integration jobs (2 Kymas per node 😄)
 - Taints is defined:
    ![image](https://user-images.githubusercontent.com/26445970/67283433-f065f000-f4d3-11e9-8089-49f941dd048b.png)

**Reasons**

As we are migrating PR jobs to Kind, we need to have enough resources on the workload cluster to handle it.

**Comment by kasiakepka** [comment]
New node pool has to be created in the same region as workload cluster (europe-west3). Unfortunately in this region there is only 500GB of SSDs storage available. Migrating workloads cluster to different region with much higher quota (like europe-west4) is not a safe option so I decided to raise a request to change the quota in west3 region. 
https://jira.multicloud.int.sap/plugins/servlet/desk/portal/2/MCO-26479

**Comment by kasiakepka** [comment]
I've also changed workloads cluster settings so that its nodes are created across all zones (europe-west3-a, europe-west3-b, europe-west3-c).
