### ISSUE TITLE
Use dedicated google project for prow setup

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/test-infra#166]
Problem:
Currently the "kyma-project" google project is used to manage all infrastructure related to prow, including
- the prow cluster itself
- the gcs bucket for the secrets
- the gcs bucket for build logs
- the dynamicly created k8s cluster
The project is used as well by kyma developers to have k8s cluster. That people will have access to all that resources as well, where only people acting as prow admins should have access to that resources.

Proposed solution:
Register a dedicated google project "kyma-prow" to manage all prow related resources. Only prow admins should be a member for now.

**Comment by Demonsthere** [comment]
I would suggest to use the situation and improve out current setup:
- Split the deployment into two clusters: 
  - One for the prow deployment
  - Second for the workload - jobs generated by prow
- Implement a manager application to create and maintain the clusters (gardener?)

**Comment by michal-hudy** [comment]
For point 1 we have an issue already: https://github.com/kyma-project/test-infra/issues/27
For point 2 please create an issue.

**Comment by Demonsthere** [comment]
I have created a issue for point 2: #187
