### ISSUE TITLE
Add reference to mkpj images and update documentation on how to use it

### ISSUE THREAD

**Issue by tehcyx** [kyma-project/test-infra#1690]
**Description**
`mkpj` from k8s has docker images ready to use. We should have maybe something like RedHat ([RedHat images.sh][1]) does it and reference these images for usage in scripts that can be easily sourced ([RedHat jobs.sh][2]) for anyone trying to create a job on kyma-prow.

[1]: https://github.com/openshift/release/blob/master/hack/images.sh
[2]: https://github.com/openshift/release/blob/master/hack/job.sh

**Reasons**
Manual editing of job definition has time and time again led to the pipeline being blocked. With prow updates we're rolling forward all components to a certain tag anyways, so with the next update we should be able to reference to a `mkpj` image for use.

**Comment by dekiel** [comment]
I like this idea very much, but this should not be in scope of Update production Prow to current versions from upstream Epic. As soon we will have upgraded prow, we should implement this.
Referencing to new image tag should be part of upgrade process.
