### ISSUE TITLE
Enable Compass GKE Integration job on Kyma release

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/test-infra#1694]
**Description**

Currently, `kyma-gke-compass-integration` job is run on demand, on compass chart change and after merge to Kyma `master`. To make sure there are no breaking changes in dependant components (like Istio or Ory), enable Compass GKE integration job on Kyma release.

**Reasons**

We should validate, if compass and compass-runtime-agent integration tests pass before doing a release, as other component changes (like istio or ory) could impact Compass stability.

**Comment by PK85** [comment]
done
