### ISSUE TITLE
Cluster for Release Candidate is created in wrong project: sap-hybris-sf-playground

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#1697]
AFAIK this project soon will be deletated. In addition to that, not everyone has access to it.

**Comment by derberg** [comment]
sorry if this is a dumb question, but can you specify what would be the right project here? can you specify is we simply need to use different project that already exists or should we create a new one?

**Comment by adamwalach** [comment]
I created follow up ticket: https://github.com/kyma-project/test-infra/issues/1750

**Comment by kasiakepka** [comment]
This issue was resolved [here](https://github.com/kyma-project/test-infra/pull/1888)
