### ISSUE TITLE
kyma-vulnerabilites-scan job failing

### ISSUE THREAD

**Issue by jose-cortina** [kyma-project/test-infra#1705]
**Description**

The [kyma-vulnerabilities-scan](https://status.build.kyma-project.io/?job=kyma-vulnerabilites-scan) job is failing with an error:

```
fatal: No url found for submodule path 'vendor/k8s.io/code-generator' in .gitmodules
: command failed: [git clone --recursive -v --progress https://github.com/google/go-containerregistry /home/prow/go/pkg/dep/sources/https---github.com-google-go--containerregistry]: exit status 128
```

**Expected result**

Job runs successfuly.

**Actual result**

Job fails.

**Steps to reproduce**

Jobs since October 26 have failed (Job history: https://status.build.kyma-project.io/job-history/kyma-prow-logs/logs/kyma-vulnerabilites-scan)

**Comment by kasiakepka** [comment]
Scan is failing on resolving event-sources dependencies.
This pipeline is using DEP v0.5.0
https://github.com/kyma-project/kyma/commits/master/components/event-sources

**Comment by adamwalach** [comment]
To manually test this issue we can use following procedure
```
~/go/src/github.com/kyma-project  docker run -it --rm \
-v $PWD:/workspace/go/src/github.com/kyma-project eu.gcr.io/kyma-project/test-infra/vulnerability-scanner:v20190226-14fa550

cd /workspace/go/src/github.com/kyma-project/kyma/components/event-sources
rm -rf /workspace/go/pkg/dep; make vendor -B
```
and it fails with
```
(62/77) Failed to write github.com/google/go-containerregistry@b02d448a3705facf11018efff34f1d2830be5724
(63/77) Failed to write github.com/golang/groupcache@master
(64/77) Failed to write github.com/golang/protobuf@v1.3.2
(65/77) Failed to write github.com/google/go-cmp@v0.3.0
(66/77) Failed to write github.com/google/gofuzz@v1.0.0
(67/77) Failed to write github.com/googleapis/gax-go@v2.0.5
(68/77) Failed to write github.com/google/uuid@v1.1.1
(69/77) Failed to write github.com/googleapis/gnostic@v0.3.1
(70/77) Failed to write github.com/hashicorp/golang-lru@v0.5.3
(71/77) Failed to write k8s.io/apiextensions-apiserver@kubernetes-1.15.3
(72/77) Failed to write k8s.io/api@kubernetes-1.15.3
(73/77) Failed to write knative.dev/eventing@v0.10.0
(74/77) Failed to write github.com/gogo/protobuf@v1.3.1
(75/77) Failed to write knative.dev/pkg@release-0.10
(76/77) Failed to write knative.dev/serving@v0.10.0
(77/77) Failed to write github.com/aws/aws-sdk-go@v1.25.22
grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export github.com/google/go-containerregistry: failed to fetch source for https://github.com/google/go-containerregistry: unable to get repository: Cloning into '/workspace/go/pkg/dep/sources/https---github.com-google-go--containerregistry'...
POST git-upload-pack (165 bytes)
```

I tried with dep 0.5.0 and 0.5.4.
Please note that it happens only when dep cache is empty (`rm -rf /workspace/go/pkg/dep`)

**Comment by antoineco** [comment]
I looked into it yesterday together with @adamwalach and found out the issue was related to Docker (the overlayfs2 file system specifically). Running `dep ensure` a second time succeeds, but something, somewhere, breaks while caching the package the first time.

The workaround I'd recommend for now:
```bash
for i in {1..5}; do
    make resolve && break
done
```
until we figure out why this particular package is problematic inside a Docker container.

**Comment by kasiakepka** [comment]
There is no need to apply https://github.com/kyma-project/test-infra/pull/1726 as scan is working as axpected. We were not able able to identify what exactly fixed the issue however it happened after kyma-project/kyma#6272. There were no changes made on test-infra scripts or images that could influence vulnerability scanner.
