### ISSUE TITLE
Kyma installation fails on aks nightly

### ISSUE THREAD

**Issue by strekm** [kyma-project/test-infra#1733]
**Description**

Kyma installation is failing on installing tiller:
```
The install-tiller.sh script is deprecated and will be removed. Use Kyma CLI instead.
- Installing Tiller...
error: SchemaError(io.k8s.apimachinery.pkg.apis.meta.v1.APIGroup_v2): invalid object doesn't have additional properties
tiller is not deployed - waiting 5s...
tiller is not deployed - waiting 5s...
tiller is not deployed - waiting 5s...
tiller is not deployed - waiting 5s...
```

https://storage.googleapis.com/kyma-prow-logs/logs/kyma-aks-nightly/1196691891169529856/build-log.txt

https://status.build.kyma-project.io/?job=kyma-aks-nightly

**Expected result**

Kyma installed

**Actual result**

Kyma installation gets stuck on installing tiller

**Comment by Tomasz-Smelcerz-SAP** [comment]
After investigation, this is what is found:
We don't know why it stopped working 6 days ago. But it looks it can be fixed by bumping kubectl version.

To run kyma-aks-nightly job, we're using image: `eu.gcr.io/kyma-project/test-infra/kyma-cluster-infra:v20190528-8897828`. This image is 5 months old and it only contains kubectl in version `1.10.7`
Take a look at this: ```
.../github.com/kyma-project/test-infra $ docker run -it eu.gcr.io/kyma-project/test-infra/kyma-cluster-infra:v20190528-8897828 which kubectl
/google-cloud-sdk/bin/kubectl
```

We have a more recent image: `eu.gcr.io/kyma-project/test-infra/kyma-cluster-infra:v20190927-2687a99` with kubectl 1.14.6, but it's not used!
Take a look at this: 
```
.../github.com/kyma-project/test-infra $ docker run -it eu.gcr.io/kyma-project/test-infra/kyma-cluster-infra:v20190927-2687a99 kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
.../github.com/kyma-project/test-infra $
.../github.com/kyma-project/test-infra $ docker run -it eu.gcr.io/kyma-project/test-infra/kyma-cluster-infra:v20190927-2687a99 /usr/local/bin/kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
.../github.com/kyma-project/test-infra $
.../github.com/kyma-project/test-infra $
.../github.com/kyma-project/test-infra $ docker run -it eu.gcr.io/kyma-project/test-infra/kyma-cluster-infra:v20190927-2687a99 printenv
PATH=/workspace/go/bin:/usr/local/go/bin:/google-cloud-sdk/bin:/workspace:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=9d203eb99464
```

The reason is that PATH is set so that `/google-cloud-sdk/bin/` is before `/usr/local/bin` and our updated kubectl binary is not taken.

**Comment by adamwalach** [comment]
We updated base image to include newest version of kubectl from cloud sdk. I guess having two versions of kubectl in the same image may be very confusing when something changes PATH variable

**Comment by adamwalach** [comment]
AKS nightly is up and running again
<img width="755" alt="Screen Shot 2019-11-21 at 09 12 14" src="https://user-images.githubusercontent.com/8530211/69319349-4b0f7a80-0c3f-11ea-9f87-592e022db139.png">
