### ISSUE TITLE
Change project for Release Candidate clusters

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#1750]
**Description**

Release Candidate clusters are provisioned in ('sap-hybris-sf-playground') that is scheduled to be deleted.

AC:
- reconfigure release jobs to provision RC clusters in the 'sap-kyma-prow-workloads' project
- set TTL (5 days?) and configure cleaners so clusters are automatically removed after TTL expires
- update release documentation

Stretch goal: 
Based on [role-based-access-control](https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control) set different (admin) permissions for RC clusters for "kyma_developer" group. 
The idea is to keep lower permissions for all the other clusters (weekly, nightly, PRs).

**Comment by kazydek** [comment]
@pPrecel  Pls remember to update the docs if required :)
