### ISSUE TITLE
Nightly job for testing gardener on azure

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/test-infra#1757]
**Description**
Besides the regular integration jobs executed on every PR we need to start testing Kyma regulary on all supported cloud providers.
Please add a nightly job for a kubernetes cluster provisioned with Gardener on azure.

The job should
- run every night
- notify to slack about failure
- provision, install, test on base of Kyma CLI
- avoid code duplication but see that the existing nightly for AKS has same base script

**Reasons**
Assure functionality on all providers

**Comment by clebs** [comment]
This issue is blocked by https://github.com/kyma-project/cli/issues/326.
The Hydroform in the current "CLI for prow" binary contains some issues that make provisioning a gardener cluster on azure not possible.

**Comment by clebs** [comment]
Blocked by https://github.com/kyma-incubator/hydroform/issues/49
The gardener custom discovery mechanism has a bug and therefore we can not provision a gardener cluster right now.

**Comment by a-thaler** [comment]
When seeing https://storage.googleapis.com/kyma-prow-logs/logs/kyma-gardener-integration/1207088150984265729/build-log.txt it might be beneficial to print the cli command which was executed for easier reproducability.
Do you have used the --non-interactive mode? as there is the problem with local certificate storage reported..

Can you maybe add the "azure" aspect to the job name as I can imagine that we will add a gcp flavor soon.
