### ISSUE TITLE
Migrate 2 kyma components to prow

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#18]
**Description**

- migrate ui-api-layer
- migrate catalog-ui (maybe instance too if that makes sense)
- document the whole functionality and what needs to be done and how make sure it works
  - what has to be changed in current config
  - parts you know are different in prow and you had to address them differently than in jenkins file
  - how to test locally
- check if we can address current issue we have, that all components (event though they are 100% similar) are not duplicating jenkinsfile

**Reasons**

Have most common use case migrated to prow as a showcase for others

**Comment by michal-hudy** [comment]
Documentation is not prepared, because it is a first attempt to build our components with prow and it will be probably changed.
