### ISSUE TITLE
Assure cleanup of PVs 

### ISSUE THREAD

**Issue by mwieczorek** [kyma-project/test-infra#181]
Assure cleanup of PVs after deleting of kyma cluster.

Right now when the kyma cluster is deleted all the PVs are left. (9 disks, about 250GB for each cluster so about 10$ per month). 
It should be also assured in periodic cleanup of leftovers described here https://github.com/kyma-project/test-infra/issues/177

**Comment by Tomasz-Smelcerz-SAP** [comment]
As mentioned here: https://cloud.google.com/sdk/gcloud/reference/container/clusters/delete,
```
 The following resources are not deleted:

    External load balancers created by the cluster
    Persistent disk volumes
```

**Comment by Tomasz-Smelcerz-SAP** [comment]
How to verify:
- Run the job
- List the PVC from the Kyma cluster once it's installed
- In gcloud console, you can find the disks allocated for the PVC (around nine objects)
- Wait until cleanup is finished
- Ensure disks allocated for PVCs are gone from gcloud

**Comment by sjanota** [comment]
## Review notes
* Tomek was abandoned by demo gods :)
