### ISSUE TITLE
kyma release process document doesn't describe how to handle components changes

### ISSUE THREAD

**Issue by strekm** [kyma-project/test-infra#182]
Describe how components changes (add/edit/delete) will be handled in the context of release. E.g. component "A" was part of release "0.1.0" but shouldn't be part of release "0.2.0", still release "0.1.1" should be possible and should build component "A".

**Comment by piotrmsc** [comment]
@aszecowka can you provide more input?

**Comment by aszecowka** [comment]
I would like to have documentation, that clearly describe what I need to do, as a developer, when:
- I am adding a new component to build - in this case you should create presubmit and postsubmit job for master branch, but also release jobs configured for next releases
- I am removing a component  - then I should remove job definitions for master branch (presubmit and postsubit), but release jobs should work correctly.
