### ISSUE TITLE
Rename all the jobs

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/test-infra#186]
Apparently, using `/` in job names causes problems. We need to rename all the jobs. 

AC: 
- [x] Rename all the jobs as `repo-component` (e.g. kyma-components-binding-usage-controller or console-brokers)

**Comment by suleymanakbas91** [comment]
The reason why we want to keep the repo name is that some monitoring platforms list the jobs only by the name. This could lead to confusion if we have two components with the same name in different repos.

**Comment by Demonsthere** [comment]
I would suggest a slight modification to the naming scheme: `repo_component` so that if each element has '-' itself, the divide will be visible (eg. kyma_components_binding-usage-controller, test-infra_validate-scripts)

**Comment by suleymanakbas91** [comment]
Mixing up the signs does not look good. Also, this way we would be following the same convention as Kubernetes test jobs and would be on the safe side.
