### ISSUE TITLE
Renewal of Prow Grafana certifacte failed.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#1869]
**Description**

Prow Grafana is running with expired certificate. When accessing Grafana console under monitoring.build.kyma-project.io getting invalid cert warning. This causes governance tests failing as well, as test doesn't accept invalid certificates.

monitoring-grafana ingress is set to serve host monitoring.build.kyma-project.io
monitoring-tls secret holds expired cert, key pair.

**Troubleshooting**

Certificates are managed by cert-manager. Cert-manager pod logs contains following messages.

```
E1220 15:09:09.042678       1 controller.go:180] certificates controller: Re-queuing item "monitoring/monitoring-tls" due to error processing: Issuer letsencrypt-prod not ready
I1220 15:09:42.940734       1 controller.go:140] clusterissuers controller: syncing item 'letsencrypt-prod'
I1220 15:09:42.941119       1 logger.go:88] Calling GetAccount
I1220 15:09:43.513020       1 sync.go:71] Error initializing issuer: acme: urn:ietf:params:acme:error:rateLimited: Your ACME client is too old. Please upgrade to a newer version.
E1220 15:09:43.513097       1 controller.go:149] clusterissuers controller: Re-queuing item "letsencrypt-prod" due to error processing: acme: urn:ietf:params:acme:error:rateLimited: Your ACME client is too old. Please upgrade to a newer version.
I1220 15:10:09.042771       1 controller.go:171] certificates controller: syncing item 'default/prow-tls'
I1220 15:10:09.042853       1 sync.go:120] Issuer letsencrypt-prod not ready
```

**Comment by kasiakepka** [comment]
I understand that we have to upgrade cert-manager.
Currently we are using quay.io/jetstack/cert-manager-controller:v0.5.0

**Comment by kasiakepka** [comment]
https://cert-manager.io/docs/installation/upgrading/upgrading-0.5-0.6/

**Comment by dekiel** [comment]
We have to upgrade at least to version 0.8.0. All versions below are blocked by Lets Encrypt due to malfunction of cert-manager ACME client. There are breaking changes between versions 0.5 and 0.8. As our instance isn't complex we might consider upgrade by installation from clean state. We are not using cert-manager helm chart, but rather static manifest.
