### ISSUE TITLE
Prow Threat Modelling

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#19]
To do:
- [x] meet with the security team about threat modelling

**Comment by suleymanakbas91** [comment]
We had two meetings with the security team this week. The first one was mostly an introduction to Prow. Apart from that, we determined all the players (e.g. cluster admins, GCR, GCS, GitHub) that we expect in the final Prow environment and sketched a diagram to see how they would be connected. In the second meeting, we investigated and discussed how all these players can communicate securely with the Prow cluster. Also, we specified what kinds of secrets we'd need and how we would store them. We'll have some more meetings next week to discuss more points in the context of thread modelling.
