### ISSUE TITLE
DNS records cleanup

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#1916]
**Description**
DNS records are not cleaned up properly.

**Expected result**

**Actual result**

~700 DNS records in build-kyma-workloads DNS zone.

**Comment by kasiakepka** [comment]
`apiserver.gke` regexp was not added to the `defaultAddressRegexpList`.
 Updating the regexp didn't help as orphaned records do not match any static IP addresses . hence they are not removed.
I think we should update the cleaner logic and delete the record even if there is no matching IP however first we would have to make sure that we are not deleting newly created addresses/DNS records.

**Comment by magicmatatjahu** [comment]
Also last periodic jobs throw panic with:

```
panic: regexp: Compile(`^((?!nightly|weekly).)*`): error parsing regexp: invalid or unsupported Perl syntax: `(?!`
```
