### ISSUE TITLE
Old Minikube version

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#1918]
**Description**

```
! You are using an unsupported Minikube version '1.0.1'. This may not work. The recommended Minikube version is '1.3.1'
```

**Reasons**

1.0.1 is unsupported

**Attachments**

Build: https://storage.googleapis.com/kyma-prow-logs/logs/post-master-compass-integration/1215191663194935296/build-log.txt

**Comment by kasiakepka** [comment]
We need:
-  more guidelines from Kyma teams about the Minikube version we should use
- ask team if removing updating Minikube 1.0.1 will not impact anyone

**Comment by PK85** [comment]
@kasiakepka please describe in the ticket descrioption what is yourt expectation.

**Comment by kasiakepka** [comment]
We would like to know to which Minikube version we can update.
@clebs @suleymanakbas91 as it is impacting Kym also [Kyma CLI](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_cli/351/pre-kyma-cli-integration/1217447284866813952) can you please provide that info?

**Comment by magicmatatjahu** [comment]
I tested installation of Kyma on this versions:
- minikube 1.6.2
- kubectl 1.12.0 <- this version is used [here](https://github.com/kyma-project/test-infra/blob/master/development/custom-image/install-deps-debian.sh#L17) as I know this image is used in whole minikube integration jobs
- kubernetes 1.14.6
- kyma-cli from my [this](https://github.com/kyma-project/cli/pull/351) PR, where I bumped minikube to 1.6.2 (This is only information to user which version we support)
- Kyma sources from [this](https://github.com/kyma-project/kyma/pull/6848) PR, where all resources is compatible with k8s 1.16 (e.g. api group `extension/v1beta1` -> `apps/v1` etc)

and locally everything was good.

Also mentioned PR https://github.com/kyma-project/kyma/pull/6848 pass installation (some tests sometimes fail) on all integration jobs, so we could conclude that 1.6.2 minikube won’t be a problem on our CI.

**Comment by kasiakepka** [comment]
I managed to test  below pipelines with minikube 1.6.2 and kubectl 1.14.6.

[pre-kyma-cli-integration](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_cli/351/pre-kyma-cli-integration/1219967640945037312)
[pre-master-kyma-integration](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/6935/pre-master-kyma-integration/1219967767747235840)

**Comment by kasiakepka** [comment]
New updated iVM mage is available [here](https://console.cloud.google.com/compute/imagesDetail/projects/sap-kyma-prow-workloads/global/images/kyma-deps-image-v20200122?project=sap-kyma-prow-workloads&authuser=1&organizationId=363385237196)

**Comment by kasiakepka** [comment]
https://github.com/kyma-project/test-infra/pull/1942
