### ISSUE TITLE
Insufficient permissions to list custom resources on a weekly cluster (GKE)

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/test-infra#1947]
**Description**

I can list `httpsources` custom resource from `sources.kyma-project.io` api group.
```
kubectl get httpsources -n kubeless-test
Error from server (Forbidden): Forbidden (user=tomasz.smelcerz@sap.com, verb=list, resource=httpsources, subresource=) (get httpsources.sources.kyma-project.io)
```
It's also forbidden for `admin@kyma.cx`

**Expected result**

It should work :)

**Comment by kasiakepka** [comment]
I updated `kyma_developer` role with `container.customResourceDefinitions.list` permission.
Tomasz confirmed that it is working now.
