### ISSUE TITLE
Migrate Kyma integration pipelines to Kubernetes 1.16

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#1963]
**Description**

As Kyma is compatible with Kubernetes 1.16 we should switch our pipelines to that version.

**Reasons**

Continuous verification of Kyma compatibility

**Acceptance Criteria**

 - GKE/AKS pipelines migrated (1.15 if 1.16 not available)
 - Minikube pipelines migrated
 - Gardener pipelines migrated
 - Update referenced version of Kubernetes in documentation

**Attachments**

**Comment by m00g3n** [comment]
https://github.com/kyma-project/test-infra/issues/1982

**Comment by m00g3n** [comment]
Kyma CLI should also be migrated.

**Comment by michal-hudy** [comment]
@m00g3n please update documentation :smile:
