### ISSUE TITLE
Prow pipeline on K8s 1.16

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#1968]
**Description**
When GKE 1.16 is available setup Prow presets with necessary image and corresponding kubectl version.

**Reasons**
Prow pipelines are compatible with recent Kyma updates (K8s 1.16 update) so that we are able to test the solution.

**Acceptance Criteria**
- GKE K8s 1.16 is tested
- It is easy to wite pipelines for 1.14 and 1.16
- Pipeline running on minikube supports 1.16

**Attachments**
https://github.com/kyma-project/test-infra/issues/1859

It depends on [GKE 1.16 release](https://cloud.google.com/kubernetes-engine/docs/release-notes#january_8_2020)

**Comment by kasiakepka** [comment]
We managed to test Minikube pipelines with helm v2.16.1.
https://github.com/kyma-project/test-infra/pull/1984#pullrequestreview-353602824

**Comment by kasiakepka** [comment]
If K8s 1.16 won't be released by Google this release the plan is to setup pipelines running on latest k8s 1.15.

**Comment by adamwalach** [comment]
Minikube is on 1.16
Kind was temporary disabled (unstable)

**Comment by kasiakepka** [comment]
https://github.com/kyma-project/test-infra/pull/2197/files
