### ISSUE TITLE
Nightly backup job for gardener azure

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/test-infra#1976]
**Description**
Provide a nightly job for testing the backup on gardener with azure, see the kyma-gke-backup-nightly as reference
That ticket will cover the backup part mainly, the restore will be handled by a follow-up ticket

**Reasons**
The scenario is not tested continuously

**Acceptance Criteria**

**Attachments**

**Comment by suleymanakbas91** [comment]
Also, see [kyma-gardener-azure-integration](https://github.com/kyma-project/test-infra/blob/master/prow/scripts/cluster-integration/kyma-gardener-integration.sh) for code reuse.

**Comment by suleymanakbas91** [comment]
Installation always fails, that's why I cannot continue with the task.

**Comment by suleymanakbas91** [comment]
Not valid anymore.
