### ISSUE TITLE
Nightly upgrade job for gardener azure

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/test-infra#1977]
**Description**
Provide a job for testing the upgrade on gardener with azure continuously.
it should be based on same cluster setup as https://status.build.kyma-project.io/?job=kyma-integration-gardener-azure.

Probably it is enough for now to execute it once a day

**Reasons**
The scenario is not tested continuously

**Acceptance Criteria**

**Attachments**

**Comment by a-thaler** [comment]
Blocked for now as related integration job is flaky, see https://status.build.kyma-project.io/?job=kyma-integration-gardener-azure

**Comment by hisarbalik** [comment]
This prow job blocked by https://github.com/kyma-project/kyma/issues/8435
