### ISSUE TITLE
Protecode scan automation

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#1978]
**Description**

Currently Protecode scan is triggered manually and it requires couple manual steps.

**Reasons**

Reduce the amount of work, ease the maintenance.

**Acceptance Criteria**

- Scans runs automatically without any human intervention.
- Scans run on release branch.
- Scans collect input data automatically without human intervention.
- Scans are triggered once a week.
- Scans reports are uploaded to github or wiki.

**Comment by jose-cortina** [comment]
@adamwalach  Please note that this is a requirement for release, so we need to ensure this is prioritized.

**Comment by sergio-oss** [comment]
@adamwalach 

- please ensure we do not scan only repo HEAD as we are currently doing, but we do it for all supported versions. For Managed Offering, we need to support only one version
- please ensure we also scan images used by Compass (in case the proposed approach of getting list of containers from deployed runtime were missing specific images used only in Compass)

**Comment by kasiakepka** [comment]
> @adamwalach Please note that full Protecode scans are a requirement for release, so we need to ensure this is prioritised. At the moment I understand the scan does not cover all images.

@jose-cortina this issue is focusing on Protecode automation, we believe that it is not that critical at the moment.
Let's track security topics and here: https://github.tools.sap/kyma/backlog/issues/36

**Comment by adamwalach** [comment]
solved in https://github.com/kyma-project/test-infra/blob/44055057e170b38363563b9a40a739d46f8e57f5/prow/jobs/scans/protecode-guard.yaml
