### ISSUE TITLE
Backup-restore test doesn't handle PartiallyFailed status correctly

### ISSUE THREAD

**Issue by m00g3n** [kyma-project/test-infra#1982]
**Description**

Backup test does not handle `PartiallyFailed` status correctly.

**Expected result**
- Test should stop if backup completed with status: `PartiallyFailed`.
- A meaningful information about the reason of failure should be visible in test logs.

**Actual result**
- Test doesn't stop if backup completed with status: `PartiallyFailed`.
- No info about the reason of the failure.

Example test log output: https://status.build.kyma-project.io/?job=kyma-gke-backup-nightly

**Steps to reproduce**
- Reproducible in each test run on pipeline. 

**Troubleshooting**

**Comment by suleymanakbas91** [comment]
Since the CRDs are not restored in the first try, we need to try restoring a few times until the CRDs are restored. This leads to the scenario where, after the first try, all the others finish with `PartiallyFailed`. That's why the best we can achieve is `PartiallyFailed`. That's something we need to live with until Velero is able to restore all the CRDs in the first try.

**Comment by m00g3n** [comment]
The retry may not always be good idea eg.

```
time="2020-01-31T14:29:17Z" level=error msg="Error backing up item" backup=velero/mw-31 error="error getting volume info: rpc error: code = Unknown desc = googleapi: Error 403: Required 'compute.disks.get' permission for 'projects/<project>/zones/<zone>/disks/<pvc>', forbidden" group=v1 logSource="pkg/backup/resource_backupper.go:288" name=helm-broker-etcd-stateful-0 namespace= resource=pods
```
Since the log error is just `PartiallyFailed` it would be good to at least know the reason of the.

**Comment by aerfio** [comment]
In order to close https://github.com/kyma-project/kyma/issues/6539 I had to play with velero and I've managed to restore Kyma without `PartiallyFailed` status almost every time, the difference is that I made backup using `velero backup create` command
