### ISSUE TITLE
gcp-container-analysis job not running

### ISSUE THREAD

**Issue by tehcyx** [kyma-project/test-infra#2016]
**Description**
The container analysis job is not running and needs fixing.
[https://status.build.kyma-project.io/?job=\*gcp-container\*](https://status.build.kyma-project.io/?job=*gcp-container*)

**Expected result**
Job should be properly scheduled and return results.

**Actual result**
Job has an error

**Comment by kasiakepka** [comment]
`Failed to open /logs/process-log.txt: open /logs/process-log.txt: no such file or directory`

**Comment by tehcyx** [comment]
Last PR to close the topic: https://github.com/kyma-project/test-infra/pull/2044

**Comment by adamwalach** [comment]
It works now: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-gcp-container-vulnerability-collector/1230103669882490880
