### ISSUE TITLE
Error adding Service Account to role. Role slice is empty

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#2092]
**Description**
When executing installer test run I got a following error:
```
ERRO[0030] Failed assign sa kamil-sa-kyma-release-candidat to roles, got: %!w(*errors.errorString=&{One of mandatory method arguments saname, projectname ,role can not be empty. Got values. saname: kamil-sa-kyma-release-candidat projectname: ### roles: [].}) 
```
It happens when the Service Account roles list is not present.

**Expected result**
There is no error.

**Actual result**
An error occurred when applying roles to Service Account

**Comment by colunira** [comment]
Hello,
Could you elaborate more? What's the issue here?
