### ISSUE TITLE
Do not run e2e-provisioning tests on kyma-gke-compass-provisioner-tests jobs

### ISSUE THREAD

**Issue by franpog859** [kyma-project/test-infra#2147]
**Description**

Do not run `e2e-provisioning` tests on `...-kyma-gke-compass-provisioner-tests` jobs

**Reasons**

`e2e-provisioning` tests on for example `pre-master-kyma-gke-compass-provisioner-tests` job always fail with errors `provisioning failed` and `got empty data from director response` because they do not have the required credentials on these jobs

Currently (18.03.2020) the job is optional so this change is not critical but it generates cost and is misleading for the developers

**Acceptance Criteria**

- [ ] `e2e-provisioning` tests don't run on `...-kyma-gke-compass-provisioner-tests` jobs

**Comment by janmedrek** [comment]
No discussion since March, closing this ticket.
