### ISSUE TITLE
periodic Kyma on Gardener AWS job

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/test-infra#2183]
**Description**
As we want to support gardener on AWS as well, let's have a periodic job for testing kyma on gardener-aws in default setup, so having no production profile applied.

**Reasons**
Test the supported environments in an automated way

**Acceptance Criteria**
There is a job running every day testing a kyma installation with tests every day

**Attachments**

**Comment by clebs** [comment]
Blocked by https://github.com/kyma-incubator/hydroform/issues/104

**Comment by clebs** [comment]
AWS gardener periodic job has been merged to master and runs daily at 14h.
