### ISSUE TITLE
Monitoring reports different number of pending jobs

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#2265]
**Description**

Number of "in progress" jobs is different between http://status.build.kyma-project.io/ and Grafana:
![Screenshot 2020-04-20 at 14 15 02](https://user-images.githubusercontent.com/8530211/79758086-35e96580-831d-11ea-9b78-d6c69ce9440f.png)
vs
<img width="1369" alt="Screenshot 2020-04-20 at 14 14 33" src="https://user-images.githubusercontent.com/8530211/79758089-384bbf80-831d-11ea-84c4-b0a09297c904.png">

 

**Expected result**

The results should be the same

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by tehcyx** [comment]
This is fixed, pushgateway had old jobs, restarting it fixed the reporting.
