### ISSUE TITLE
generate branchprotector-config.yaml

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#2278]
**Description**

branchprotector-config.yaml file should be generated by rendertemplates tool in this same run as generation of config.yaml file.

**Reasons**

branchprotector-config.yaml holds configuration of branchprotector. This config consist of parameters which are subset of config.yaml parameters, but written in old prow config syntax. This is needed because we use old version of branchprotector which doesn't understand new syntax used in config.yaml file. To avoid need of manual sync between files it's required that rendertemplate will generate branchprotector-config.yaml

**Acceptance Criteria**

1. rendertemplates tools is generating branchprotector-config.yaml file in this same run as generating config.yaml
2. PR merging is blocked if template and target file are not synced, same as for config.yaml

**Comment by Ressetkk** [comment]
Resolved in #2371 and #2373
