### ISSUE TITLE
Create documentation for crier

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#2279]
Our prow instance is using crier slackreporter as a replacement for prow-addons-ctrl-manager. This was needed as prow-addons-ctrl-manager was not working with new version of prow and upgrading dependency reequires rewriting tool source code. As we are using crier now, we need to create documentation about this component.

**Comment by kasiakepka** [comment]
https://github.com/kyma-project/test-infra/issues/2311

**Comment by kasiakepka** [comment]
PR https://github.com/kyma-project/test-infra/pull/2431
