### ISSUE TITLE
Certbot failure in post-rel111-kyma-release-candidate

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#2283]
**Description**

Job is failing because certbot tries to set a TXT record in a wrong zone. 
We migrated SA to the `prow` project and it tries to use the zone defined in this project.
For now there is no way to override project that certbot should use, but there is a future request: https://github.com/certbot/certbot/issues/6225

Logs: https://storage.googleapis.com/kyma-prow-logs/logs/post-rel111-kyma-release-candidate/1250728528240971777/build-log.txt

**Expected result**

Certificate is generated correctly and the job is green

**Actual result**

**Steps to reproduce**

**Troubleshooting**
To mitigate this problem we manually copied the TXT record the correct zone (during job execution)

**Related issue:**
https://github.com/kyma-project/test-infra/issues/2283

**Comment by dekiel** [comment]
Fixed in #2365 . We are running on service account form kyma-prow project now.
