### ISSUE TITLE
Enable rerun button on prow status.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#2285]
**Description**

New version of Prow has feature of rerun button on Prow status page. This button allows authenticated users rerun any job. Whereas presubmit jobs could be triggered with comments on issue other job types could not use this mechanism.

**Reasons**

With rerun button developers will be able to rerun postsubmit or periodic jobs without ask and intervention prow admins.

**Acceptance Criteria**

Only authenticated users can rerun job.
Only users from defined grups can rerun particular jobs.
Rerun button trigger valid job.

https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/github_oauth_setup.md
https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/csrf.md
https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/main.go

**Comment by kasiakepka** [comment]
We are getting 404 when opening https://status.build.kyma-project.io/pr and query is not executed properly.

https://github.com/kubernetes/test-infra/issues/17576

**Comment by kasiakepka** [comment]
Below directives are not respected and all users with Github accounts can rerun presubmit jobs:

OLD CONFIG:
```
  rerun_auth_config:
    github_team_ids:
      - 2944419 # prow
```
NEW VERSION:
```
  rerun_auth_configs:
    'kyma-project/test-infra':
      github_team_ids:
      - 2944419 # prow team
    allow_anyone: false
```
`allow_anyone: false` is not helping either.

**Comment by kasiakepka** [comment]
https://github.com/kubernetes/test-infra/issues/17606

**Comment by kasiakepka** [comment]
{"allowed":false,"component":"deck","file":"prow/cmd/deck/main.go:1434","func":"main.handleRerun.func1","handler":"/rerun","job":"post-master-console-compass","level":"info","msg":"Attempted rerun","prowjob":"8ac292dd-98dc-11ea-950e-feca7ea93e21","time":"2020-05-18T10:02:54Z","user":"kasiakepka"}

**Comment by kasiakepka** [comment]
https://github.com/kyma-project/test-infra/pull/2393

**Comment by kasiakepka** [comment]
Enable Prowjobs rerun feature for `cluster-access` team.
