### ISSUE TITLE
Prow pipeline for tests/test-environments

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/test-infra#229]
**Description**
As we are moving to Prow, we need to migrate test-environments tests pipeline.

**Reasons**

Migration guide: https://github.com/kyma-project/test-infra/blob/master/docs/prow/migration-guide.md

Assignee person should update the table at https://github.com/kyma-project/test-infra/issues/118

**Comment by sjanota** [comment]
## Review notes
 * Sometimes jobs are failing because of not enough resources
