### ISSUE TITLE
Add metrics and chart with github token quota usage. Ensure constant token usage refresh interval.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#2350]
Token remaining quota and time to reset is refreshed only when github reply to API request. In API response we have only remaining token quota, to have a usage history computed and monitored we can use token-counter tool.
https://github.com/kubernetes/test-infra/tree/adb8ecf1cb55aa8a806fdfc2981e533e6410d42f/velodrome/token-counter
As a side effect we should have constant token quota  refresh interval as this tool is querying GithubAPI more and more often as we are close to the reset time.
Grafana stat with time to next token reset will benefit from this behaviour as well as it's refreshed in same way as token quota.

**Comment by Ressetkk** [comment]
The metrics are pushed by ghproxy which updates the new data in one minute intervals. It checks response headers for each GitHub API response and updates the data with updated information. During working hours we can rely on prow traffic but the metrics will be updated less frequently when the traffic will be low.

The only thing we can change is the time interval of pushing new metrics data. That can be done by using `--push-gateway-interval` argument in ghproxy deployment. For ex. `--push-gateway-interval=30s` will force to push new metric data every 30 seconds. Prometheus is collecting data in 30 seconds intervals regardless of this change.

If we wanted independent github token monitoring we would be forced to use another data source and scraper, apart from prometheus just for GitHub token monitoring.

If we decide that we need better solution for handling token limit monitoring then feel free to reopen the issue. Closing.
