### ISSUE TITLE
Setup notifications for new CI-Force channel

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#2390]
**Description**

Please setup new notification settings for ci-force channel as it will be moved to T&I workspace (May 20 after 6pm).

**Expected result**

Slack reporter and stability checker are working as usual.
Documentation is updated.
Secrets are updated on the server as well as in the bucket.

**Comment by dekiel** [comment]
I've uploaded slack token for jenkins-ci app in to bucket.
@kasiakepka please upload incoming wenhooks and bot token.

**Comment by kasiakepka** [comment]
Webhooks and `slack-token` secrets are uploaded to the bucket.
I also updated documentation with information about the webhooks see  https://github.com/kyma-project/test-infra/pull/2425.
