### ISSUE TITLE
Update jobs after migration to helm 3

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#2398]
**Description**

Required by https://github.com/kyma-project/kyma/issues/8517
Update our prow jobs (remove tiller part) after kyma-operator is done.

**Reasons**

**Acceptance Criteria**

**Attachments**

**Comment by kasiakepka** [comment]
https://github.com/kyma-project/test-infra/pull/2537

**Comment by kasiakepka** [comment]
I'm waiting for 1.14 release so that it is safer to migrate upgrade pipelines.

**Comment by adamwalach** [comment]
https://github.com/kyma-project/test-infra/pull/2525
