### ISSUE TITLE
Improvements to Kyma release process (from 1.13 retro) 

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#2400]
**Description**

Introduce BOT that will:
- run test on pr in sequence automatically - after all of them are finished bot should announce on a channel that tests failed or succeeded
- after RC cluster is ready bot should publish credentials to the channel and ask for manual test

Add to the docs that before the PR for release is created we should check for PR images

**Comment by kasiakepka** [comment]
Currently there is no such possibility to send Slack notifications for specific jobs only (like pre-relXXX-*). Crier does not support such option however we can consider using [PubSub reporter](https://www.coursera.org/professional-certificates/gcp-cloud-architect?action=enroll#courses) in the future.
