### ISSUE TITLE
Governance job should can filter status code from responses

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/test-infra#2436]
**Description**

We use very opinionated project for links validation in our docs called MILV https://github.com/magicmatatjahu/milv and it currently doesn't support filter response's status code. It's very important, because we have a lot of false failed CI governance jobs because GitHub prevents a lot of requests from our domain with 429 status.

AC:
- upgrade milv with new functionality or make filter in governance-job.sh

**Expected result**

Governance job should always return broken links, and avoid false positives.

**Comment by pbochynski** [comment]
Should we move the repository to  test-infra project first? @magicmatatjahu @adamwalach Please take care :)

**Comment by kwiatekus** [comment]
429 is happening as we request github resources from the same IP to frequently.
Throttling is needed

**Comment by dbadura** [comment]
I created issue here https://github.com/kyma-incubator/milv/issues/8 for this problem.
