### ISSUE TITLE
Remove storage admin role for sa-kyma-artifacts from gcr bucket in kyma-prow project.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#2481]
As a next step of permissions cleanup and securing access to GCR we should remove storage admin role assigned to sa-kyma-artifacts service account and granted on gcr bucket.

**Comment by kasiakepka** [comment]
`sa-kyma-artifacts` account has [Storage Object Admin permissions](https://cloud.google.com/storage/docs/access-control/iam-roles#standard-roles) of following buckets:
- kyma-cli-stable
- kyma-development-artifacts
- kyma-prow-artifacts
