### ISSUE TITLE
Build trusted-workload-kyma-prow and nontrusted-workload-kyma-prow clusters

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#2482]
**Description**

Clusters will be used by kyma prow to execute trusted and non trusted prowjobs. Clusters will provide prowjobs with secrets sets relevant for the trust level of code executed on cluster.

**Reasons**
As a security related improvement we need to categorise prowjobs as trusted and not trusted. This two categories must be separated and provided with different set of secrets.Because we are going to let developers test untrusted code on production prow instance, we need this separation in place.

**Acceptance Criteria**

Clusters will be build with current highest available k8s version.
Clusters will have enabled auto upgrade.
Clusters will start with one node pool in size equal to main pool from workloads-kyma-prow cluster.
Clusters will be build in kyma-prow project.
Clusters will be accessible for production prow instance.

**Attachments**

See #2289

**Comment by adamwalach** [comment]
Things to consider:
- do we need two pools in every cluster 
- use private cluster
