### ISSUE TITLE
Remove storage-admin roles from sa-gke-kyma-integration and sa-kyma-artifacts service account in kyma-project project.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#2491]
**Description**

Following cleanup of storage permissions in kyma-prow project we need to limit access to gcr for sa-gcr-push service account in kyma-project project.

**Reasons**

Access to GCR in kyma-project should be strictly controlled. Having only one service account with access to GCR is simpler for management.

**Acceptance Criteria**

Access to GCR bucket should be granted on bucket level not as IAM role on project level.
Only one service account should have write access to gcr.

**Comment by Ressetkk** [comment]
Closing as in favor of migrating to Artifact Registry. This issue will be invalidated, as service accounts will only have access on specific registry level, not the project or bucket one.

/close
