### ISSUE TITLE
Implement a cleaner for test docker images

### ISSUE THREAD

**Issue by hudymi** [kyma-project/test-infra#2530]
**Description**

Integration pipelines are creating Docker images with Kyma installer that are pushed to `eu.gcr.io/sap-kyma-prow`. Also, pipeline that is testing Serverless with external docker registry is pushing images to that repository too. Unfortunately, those images are not always removed. To solve that we should implement a cleaner that will be removing images older than some period of time (like a week, month, etc.)

**Reasons**

Remove not used test images to keep the docker registry clean.

**Acceptance Criteria**

**Attachments**

**Comment by pbochynski** [comment]
@dekiel Can you verify if it is still valid?

**Comment by Halamix2** [comment]
`eu.gcr.io/sap-kyma-prow-workloads` is cleaned periodically, `eu.gcr.io/sap-kyma-prow` is not used for integration and serverless testing images
