### ISSUE TITLE
Create pipeline that will generate VM image for minikube

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#2547]
**Description**

Currently when you change `install-deps-debian.sh` and introduce errors it won't be tested as this script was always triggered manually. 

**Reasons**

Add `install-deps-debian.sh` to the CI pipeline and perform proper tests.

**Acceptance Criteria**

**Attachments**

**Comment by adamwalach** [comment]
Implemented by https://github.com/kyma-project/test-infra/issues/3804
