### ISSUE TITLE
Varkes job failes because of missing jobguard

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#2575]
**Description**
`post-release-varkes` failes with:
```
#################################################################################
# Execute Job Guard for Release jobs
#################################################################################
KYMA PROJECT DIR /home/prow/go/src/github.com/kyma-project
COMMIT SHA: 
env: 'go': No such file or directory
```

 https://storage.googleapis.com/kyma-prow-logs/logs/post-release-varkes/1281653490766057472/build-log.txt
 https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-release-varkes/1281653490766057472

Base image of this job (`image: eu.gcr.io/kyma-project/prow/test-infra/buildpack-node:v20181130-b28250b`) needs to inlcude jobguard binary.

**Comment by a-thaler** [comment]
fixed 👍
