### ISSUE TITLE
Keep list of all docker images used in long-running clusters

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#2599]
**Description**

We need to make sure that we have a list of all docker images that were used during a lifetime of Kyma cluster.
Directly after cluster is created we should install admission controller that will track every pod creation and save image url (i.e in a config map). 
Before we start working on this task we should check if maybe solution like that already exists.

**Reasons**

This is needed to double check that our protecode scan contains all used images.

**Acceptance Criteria**

- every image URL that was used in any point of time of cluster existence should be preserved
- provisioning scripts for gke-nightly and gke-weekly clusters are updated

**Attachments**

**Comment by sergio-oss** [comment]
Scanners use two approaches, monitor deployed containers and admission controllers. Not sure the open source ones include that part

**Comment by pbochynski** [comment]
Just the idea that you can consider. In k3s installation I ssh to the cluster node and list all the containers that are present in containerd. See the script: https://github.com/kyma-incubator/local-kyma-k3d/blob/master/cache-images.sh
The list covers not only imaged currently running in the cluster (also jobs, init containers, etc)

**Comment by sergio-oss** [comment]
Ideally we should not have exposed SSH ports, and we can not limit source IP. Indeed Prisma Cloud will complain

**Comment by dekiel** [comment]
Thanks for comments. With new workload clusters we are able to limit source IP because they use CloudNAT. We could ssh from workload cluster then. Also we were thinking about using admission controller for that and combining this feature with limiting access to our registry only.

We could use following framework for building webhook server: https://github.com/elithrar/admission-control

**Comment by Ressetkk** [comment]
The new admission controller called `image-guard` was created. It logs all used images in created pods and outputs them to the log. It is currently installing on nightly and weekly cluster. More information about the controller https://github.com/kyma-project/test-infra/tree/master/development/image-guard
