### ISSUE TITLE
Deprecation of GitHub API

### ISSUE THREAD

**Issue by tehcyx** [kyma-project/test-infra#2603]
**Description**
Various scripts use access_token as query parameter with curl to the GitHub API and it's getting deprecated:
```
Hi @kyma-bot,

On July 16th, 2020 at 17:14 (UTC) your personal access token (Prow - Job) using curl/7.52.1 was used as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/repositories/151691065/releases

Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.

Depending on your API usage, we'll be sending you this email reminder on a monthly basis for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.

Thanks,
The GitHub Team
```

I found uses here with a quick search, there might be more:
https://github.com/kyma-project/test-infra/blob/f71c9bf13e36f9c56c83de1f1213e9f7dc0097b8/prow/scripts/lib/kyma.sh#L83
https://github.com/kyma-project/test-infra/blob/7ba2ed315aa9998d4e537f5208e4a4a951637ac4/prow/scripts/cluster-integration/kyma-upgrade-gardener-azure.sh#L148
https://github.com/kyma-project/test-infra/blob/a9b2f0f2631c05243e2dfb1cce85892833bd2259/prow/scripts/cluster-integration/kyma-gke-rel2rel-upgrade.sh#L136
https://github.com/kyma-project/test-infra/blob/9c4fc595b9283c5355fcddbec443eeb9c68163b4/prow/scripts/cluster-integration/kyma-gke-upgrade-xip.sh#L179
https://github.com/kyma-project/test-infra/blob/7ba2ed315aa9998d4e537f5208e4a4a951637ac4/prow/scripts/cluster-integration/kyma-gke-upgrade.sh#L236

We should change this behavior to a solution that works even after deprecation date. Also it seems curl in this container is kind of dated?

**Comment by Halamix2** [comment]
Authorisation was changed to HTTP header based one

log: https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/10511/halamix2_test_of_prowjob_pre-master-kyma-gke-upgrade/1358731612405108736/build-log.txt
