### ISSUE TITLE
TestGrid improvements - missing days_of_results

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#2605]
**Description**

After recent updates to the testgrid configuration process we lost ability to specify "days_of_results"  value.
It means that currently we use default value set in the testgrid repo - 15days. 
Probably we have to implement this feature on our own on provide a PR to the k8s/test-infra repo.
Annotations are missing here: https://github.com/kubernetes/test-infra/blob/master/testgrid/cmd/configurator/prow.go

**Acceptance Criteria**

- change "days_of_results" to 60 in integration reports

**Comment by Ressetkk** [comment]
A PR with this the feature of overriding the `days_of_result` through annotation is raised in https://github.com/kubernetes/test-infra/pull/18408

**Comment by Ressetkk** [comment]
The functionality has been merged to the kubernetes/test-infra repo. The documentation is updated to include the new annotation.
