### ISSUE TITLE
Image syncing

### ISSUE THREAD

**Issue by jpreese** [kyma-project/test-infra#2620]
Greetings Kyma team! As I was browsing the `test-infra` repository I noticed a relatively new addition, your [image-syncer](https://github.com/kyma-project/test-infra/tree/master/development/image-syncer). This is eerily similar to our project, [Sinker](https://github.com/plexsystems/sinker).

It looks like we may be attempting to solve a similar problem, and just wanted to let you know about our solution in the event you wanted to collaborate.

**Comment by jpreese** [comment]
Activity!

**Comment by adamwalach** [comment]
Hi,
Sorry for very late answer ;)
I've seen you message earlier but somehow forgot to reply. 
Our main goal is to have immutable images on our repo. 
So the main feature of our`image-syncer` is that synchronization fails when given image already exist in the target repo and has a different sha.
As far as I understand you can't do that with `sinker`. But maybe I am wrong :)
Anyway, thanks for reaching out!
