### ISSUE TITLE
Prow didn't start tests after comment /ok-to-test

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#2623]
**Description**

We've got PR from external contributor https://github.com/kyma-project/kyma/pull/9082. After adding comment /ok-to-test by trusted user, prow didn't start tests. I had to kick them manualy by commenting /test all.

From the below sequence from file https://github.com/kubernetes/test-infra/blob/5c311347a855ad0d0e782653c773873694dfd059/prow/docs/pr-interactions-sequence.mmd I understand tests, should be started without human intervention.

Reviewer->>GitHub: Creates an "/ok-to-test" Comment
  hook->>GitHub: Adds "ok-to-test" label to PR
  trigger->>k8s: Create presubmit prowJob
  k8s->>prowJob: Run presubmit prowJob
  prowJob->>GitHub: Update PR "statuses" based on job exit code

**Expected result**

Test are started automatically after commenting with /ok-to-test

**Actual result**

Tests must be started manually.

**Comment by suleymanakbas91** [comment]
It's been disabled with https://github.com/kyma-project/test-infra/pull/338 for security reasons. It is a security problem to let external contributors commit anything that will trigger the jobs without someone from the organization checking the code.

**Comment by dekiel** [comment]
There is already a message from Kyma bot with all needed details.
