### ISSUE TITLE
Fix spelling of ProwJob (resource)/Prow job (process) in documentation to conform to guidelines

### ISSUE THREAD

**Issue by majakurcius** [kyma-project/test-infra#2692]
**Description**

Fix the spelling of `ProwJob` (the resource) and `Prow job` (the process) in the documentation to conform to the [guidelines](https://github.com/kyma-project/community/blob/master/guidelines/content-guidelines/08-style-and-terminology.md#terminology).

**Reason**

We mention ProwJobs (the resources) and Prow jobs (the processes) a lot through our documentation and it's easy to confuse them. Moreover, the spelling varies throughout our documentation and is not unified (ProwJobs, Prowjobs, Prow jobs, prowjobs). 
This is why we've had [guidelines](https://github.com/kyma-project/community/blob/master/guidelines/content-guidelines/08-style-and-terminology.md#terminology) put in place to formalize how the two terms are to be spelled in the Kyma documentation. 
The documentation now needs to be update to conform to these guidelines. 

**Related issue**
kyma-project/community#497

**Comment by pbochynski** [comment]
@majakurcius Please answer our friend stale bot :)

**Comment by Ressetkk** [comment]
This issue is still valid.

/reopen
