### ISSUE TITLE
Whitesource scan jobs fail at resolving go deps

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#2728]
**Description**

The whitesource scan jobs fail at resolving dependencies because the `Go` binary is not present in the container. https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-mod-whitesource-scan/1298888940870176769
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-whitesource-scan/1298899133561573376
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/compass-whitesource-scan/1298832821560807424

The job doesn't seem to be failing, but the job output seems really unusual. I think it's worth investigating if this is some kind of blocker and if should be resolved.

**Comment by aberezovski** [comment]
HI Kamil,

I think the errors you see in the whitesource scan output for Kyma repo are known and work by design.
The explanation is the following:
In Kyma repo there are multiple components (GO Projects) which are using different dependencies managers e.g. dep and modules.
There are 2 whitesource scan jobs which are used for the same Kyma repo to scan it using 2 different approach. One scan for dep manager and another scan for modules manager.
Each time the scan is performed for one type of GO projects the other type of projects could not be properly scan due missing depencies details and vice-versa.
For that reason in Whitesource we have 2 different target projects kyma and kyma-mod which stores the scan results for different jobs basing on proper dependencies managers.

**Comment by Ressetkk** [comment]
I think the thing here is a little bit different. It looks like the whitesource scan wants to create the complete dependency tree for top-level dependencies and sub-dependencies but without either `go` or `dep` binaries available it can't fetch the indirect dependencies thus it creates only a tree with top-level dependencies that are defined in the source files for Kyma and components. It looks like it by the similar error output for both *kyma* and *kyma-mod* scans.

Kyma-mod-whitesource-scan:
```
[WARN] [2020-08-27 07:44:12,149 +0000] - The 'vendor' folder is missing and 'modules' package manager pre-step failed. The UA will extract dependencies as a flat tree.
```

kyma-whitesource-scan
```
[WARN] [2020-08-27 08:24:41,483 +0000] - The 'vendor' folder is missing and 'dep' package manager pre-step failed. The UA will extract dependencies as a flat tree.
```

If it's something that we don't need to cover then the issue can simply be closed.

**Comment by aberezovski** [comment]
Today we had a call with Whitesource experts from SAP and showed them scan logs generated by Whitesource Unified Agent  for both Modules and Dep go package managers.

### Whitesource scan for Go project using dep package manager
```
[INFO] [2020-09-16 04:02:01,279 +0000] - topFolder = /home/prow/go/src/github.com/kyma-project/kyma/components/apiserver-proxy
[INFO] [2020-09-16 04:02:01,281 +0000] - Resolve dependencies - START - dep
[WARN] [2020-09-16 04:02:01,284 +0000] - Vendor folder doesn't exist
[WARN] [2020-09-16 04:02:01,285 +0000] - file: /home/prow/go/src/github.com/kyma-project/kyma/components/apiserver-proxy/Gopkg.lock was renamed to Gopkg-2020.09.16T040201+0000.lock
[WARN] [2020-09-16 04:02:01,286 +0000] - file: /home/prow/go/src/github.com/kyma-project/kyma/components/apiserver-proxy/Gopkg.toml was renamed to Gopkg-2020.09.16T040201+0000.toml
[WARN] [2020-09-16 04:02:01,294 +0000] - CommandLineProcess - executeProcessCommand - Command 'dep init' run Failed, Exception: Cannot run program "dep" (in directory "/home/prow/go/src/github.com/kyma-project/kyma/components/apiserver-proxy"): error=2, No such file or directory
[WARN] [2020-09-16 04:02:01,295 +0000] - Can't run init command, output might be outdated, run the init command manually.
[WARN] [2020-09-16 04:02:01,296 +0000] - go.collectDependenciesAtRuntime = true but pre-step failed
[WARN] [2020-09-16 04:02:01,299 +0000] - The file: /home/prow/go/src/github.com/kyma-project/kyma/components/apiserver-proxy/Gopkg-2020.09.16T040201+0000.lock was renamed back to Gopkg.lock
[WARN] [2020-09-16 04:02:01,299 +0000] - The file: /home/prow/go/src/github.com/kyma-project/kyma/components/apiserver-proxy/Gopkg-2020.09.16T040201+0000.toml was renamed back to Gopkg.toml
[WARN] [2020-09-16 04:02:01,327 +0000] - The 'vendor' folder is missing and 'dep' package manager pre-step failed. The UA will extract dependencies as a flat tree.
[INFO] [2020-09-16 04:02:01,331 +0000] - Resolve dependencies - END - dep
```
### Whitesource scan for Go project using modules package manager
```
[INFO] [2020-09-16 04:01:52,406 +0000] - topFolder = /home/prow/go/src/github.com/kyma-project/kyma/components/application-gateway
[INFO] [2020-09-16 04:01:52,408 +0000] - Resolve dependencies - START - modules
[WARN] [2020-09-16 04:01:52,414 +0000] - There was an error in running 'go build' command, please fix your code/imports for maximum results.
[WARN] [2020-09-16 04:01:52,414 +0000] - go.collectDependenciesAtRuntime = true but pre-step failed
[WARN] [2020-09-16 04:01:52,420 +0000] - The 'vendor' folder is missing and 'modules' package manager pre-step failed. The UA will extract dependencies as a flat tree.
[INFO] [2020-09-16 04:01:52,422 +0000] - Resolve dependencies - END - modules
```
The expert guys pointed out that in both cases the Unified Agent was not able to collect the dependencies graph metadata.
- Whitesource scan for Go project using dep package manager:
  - The 'vendor' folder is missing and 'dep' package manager pre-step failed. The UA will extract dependencies as a flat tree.
- Whitesource scan for Go project using modules package manager
  - The 'vendor' folder is missing and 'modules' package manager pre-step failed. The UA will extract dependencies as a flat tree.

### Proposed mitigation

- Whitesource scan for Go project using dep package manager:
  - Ensure that `go` and `dep` executable files are available in the Prow environment where WS Unified Agent is running
  - Ensure the commands `go env GOPATH`, `go env GO111MODULE` and `dep init` run successfully
- Whitesource scan for Go project using modules package manager:
  - Ensure that `go` executable is available in the Prow environment where WS Unified Agent is running
  - Ensure the commands `go build` run successfully
- Ensure that once no warning and errors are logged by the WS Unified Agent, for each project in Whitesource the libraries/dependencies could be also shown as Hierarchy, that is not working right now. 
- Upgrade the WS Unified Agent to the latest version. At the moment the latest one is https://unified-agent.s3.amazonaws.com/wss-unified-agent-20.8.2.jar

**Comment by Ressetkk** [comment]
@aberezovski thanks for this explanation. I will link further updates under this issue

**Comment by Ressetkk** [comment]
I've added the binaries to the image. The scanner job is using them.
dep
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-whitesource-scan/1308254925284708356

modules
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/compass-whitesource-scan/1308329542938529792

I think it's safe to close the issue and reopen it once we experience the problems.
