### ISSUE TITLE
GKE integration periodic cleanup:  Clusters

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/test-infra#274]
Ensure clusters allocated by GKE integration jobs for testing Kyma are removed.
Configure a periodic job for the task.

AC:
- gather a list of clusters to remove
- remove clusters one by one

Note: An idea of how to find clusters to remove: combine pieces of information from name pattern and creation time.

**Comment by aszecowka** [comment]
Duplicates https://app.zenhub.com/workspaces/kyma---all-repositories-5b6d5985084045741e744dea/issues/kyma-project/test-infra/177
