### ISSUE TITLE
set correct REPO_NAME in jobs triggered by pjtester

### ISSUE THREAD

**Issue by k15r** [kyma-project/test-infra#2743]
**Description**

Prow sets some environment variables for the jobs it executes based on the target repo of the pr that triggered the job.

eg. PR to "kyma" sets REPO_NAME to "kyma"
PR to test-infra sets it "test-infra"

with pjtester executing jobs based on PRs to test-infra the variable gets set to a "wrong" value.

Most of our jobs get executed by PRs to kyma, but if you want to test a script for one of those prs using pjtester your REPO_NAME variable does not get set to kyma (the value you expect) but to "test-infra".

A possibility to configure this value using pjtesters config file would make debugging such scripts easier.

**Reasons**

**Acceptance Criteria**

**Attachments**

**Comment by dekiel** [comment]
Fixed in #2904
