### ISSUE TITLE
Organise helper scripts directories

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#2754]
**Description**
At this point we have three different places where the helper scripts reside:
* `prow/scripts/cluster-integration/helpers/` - which generally stores all the helper scripts that are used by the scripts inside `prow/scripts/cluster-integration/` path.
* `prow/scripts/lib/` - a location for helper libraries that have more-general purpose (configuring docker, install Kyma CLI, etc.)
* `prow/scripts/library.sh` - old helper file which imports all of the helper functions and is used by vast majority of the scripts used in Prow.

There is no guidelines for how to maintain and develop additional helper scripts in the repository. The current state is not organised and might lead to some confusions for developers regarding where to place the new helper scripts.

**Acceptance Criteria**

It's needed to do the following:
* Properly deprecate and then remove `library.sh` in favour of using the `lib/` path.
* Move most of the scripts from `prow/scripts/cluster-integration/helpers/` to the `lib/` directory if they are meant to be used more generally.
* Create guidelines on how to add helper functions. Possibly create `README.md` file in the `lib/` directory.

**Comment by k15r** [comment]
maybe we should also add guidelines for:
- function names (currently the pattern seems <name-of-file>::<function>, which makes it really easy to find the sourcecode)
- calling convention (avoid setting global variables that are magically used by functions)
- when something shall be implemented as a function that can be sourced from lib vs full blown script

and  ... whats the threshold of implementing something as e.g. go-binary vs keeping it in bash
