### ISSUE TITLE
automated secret sync between storage and prow clusters.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#2757]
**Description**

All secrets on prow and workload clusters should be managed by automated tool. A tool should run constantly on prow cluster or as periodic job. All changes in storage holding secrets should be reflected in clusters by the tool automaticaly. On the other way secrets state on cluster should be aligned to the content os secrets storage. This way all operations like creating, deleting or updating secrets are done by respective operation on secrets storage. Having such tool in place we could define secret storage dedicated for developers and give them rights to maintain it's content.

**Reasons**
Tool will increase automation level of our CI system.
Will decrease load on Neighbours coming from secrets management, like creation on demand, secrets rotation.
Will increase stability of CI system by preventing differences between running configuration and saved configuration.

**Comment by adamwalach** [comment]
solved by https://github.com/kyma-project/test-infra/pull/3930/files
