### ISSUE TITLE
Check prow and workload clusters configuration against config stored in github.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#2759]
**Description**

In the past we faced issues caused by changes done directly on a cluster without reflecting them in config files stored in github.
https://github.com/weaveworks/kubediff can help us check most of our configuration. For prow config and jobs we could reuse scripts for uploading config and jobs on a cluster.
For GCP configuration https://forsetisecurity.org/ might be helpful.

**Comment by tobiscr** [comment]
@dekiel : I assume we can close this as it's getting obsolete when we move to IaC, right?

**Comment by dekiel** [comment]
Yes, covering our infra with terraform config and implementing drift detection system based on .tf files is our way to solve that problem.
