### ISSUE TITLE
Integration pipelines on GKE 1.17 or 1.18

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#2761]
**Description**

We need to bring Kyma GKE integration pipelines to the newest available version of k8s.
The newest version on the [rapid channel](https://cloud.google.com/kubernetes-engine/docs/release-notes-rapid) is 
 1.18.6-gke.3503, the default one on rapid is 1.17.9-gke.1503.  

**Reasons**

Kyma is compatible with K8s 1.18, gardener already supports 1.18 as well. In order to have a common version across all testing platform we need to update GKE

**Acceptance Criteria**

 - pre-master-gke* jobs are duplicated, they use gke 1.16 and 1.17/18)
 
**Attachments**

**Comment by Ressetkk** [comment]
`pre/post-master-kyma-gke-integration` jobs are set to run on multiple GKE versions now. #2870 added the functionality of generating multiple GKE jobs for specific gke cluster versions provided in template config file.
