### ISSUE TITLE
Avoid running the CI job when there are no code changes

### ISSUE THREAD

**Issue by clebs** [kyma-project/test-infra#2776]
**Description**

Analyze PR changeset to determine if the CI integration job needs to run. Changes to documentation (MD files), github templates (files under https://github.com/kyma-project/kyma/tree/master/.github) and similar should not trigger a the kyma-integration job.

**Reasons**
- Avoid unnecessary waiting time for merging.
- Spare resources.

**Comment by adamwalach** [comment]
I think we have this kind of functionality in place (the `run_if_changed` field)
