### ISSUE TITLE
Postsubmit jobs are not executed

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#278]
**Description**

After updating prow to a newer version `postsubmit` jobs are not executed.

**Expected result**

`postsubmits` jobs should be executed after the merge to `master` branch.

**Actual result**

`postsubmits` jobs are not executed after the merge to `master` branch.

**Steps to reproduce**

Monitor merges to master on `test-infra` repository and watch https://status.build.kyma-project.io/ page.

**Troubleshooting**

**Comment by aszecowka** [comment]
This problem happens only for test-infra repository.

**Comment by aszecowka** [comment]
- as you know our Prow collegues implemented run_if_changed for postsubmits
- in test-infra repo we have postsubmit jobs only for building images
- that jobs have specified run_if_changed param :slightly_smiling_face:
- and we do not modified that images recently :wink:
