### ISSUE TITLE
Event Hubs Namespaces are not cleaned

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#2797]
**Description**

With every execution of integration (upgrade?) test new `Event Hubs Namespace` is created:
![Screenshot 2020-09-30 at 09 29 29](https://user-images.githubusercontent.com/8530211/94655809-6f2bf580-02ff-11eb-890f-5d5d57204d69.png)

**Expected result**

This entries need to be cleaned up after the job is done or periodically by a cleaner job

**Actual result**

We reached maximum number of namespaces and jobs were failing.
For now, we manually remove these entries whenever we see this problem

**Steps to reproduce**

**Troubleshooting**

**Comment by marcobebway** [comment]
A new [job]( https://status.build.kyma-project.io/?job=kyma-azure-event-hubs-namespaces-cleanup.) was introduced to cleanup old Azure Eventhubs Namespaces.
