### ISSUE TITLE
Create pipeline testing kyma uninstallation

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/test-infra#2842]
**Description**

Some time ago we had uninstallation as a release theme but we never properly test it in automated way.
The goal is to create an optional periodic pipeline that will install kyma from master, uninstall it and trigger installation again.

This pipeline should give us the feedback what is still not working or requires changes.

**Reasons**

Uninstallation is not tested properly in kyma

**Acceptance Criteria**

**Attachments**

**Comment by strekm** [comment]
It would be super awesome to use `kyma alpha` commands for this one and if already possible `fast-integration-tests`
