### ISSUE TITLE
Have same script for upgrade tests and release-2-release upgrade tests

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/test-infra#2946]
**Description**

Currently there are 2 scripts to execute the upgrade `kyma-gke-rel2rel-upgrade.sh` and `kyma-gke-upgrade.sh` for different use cases. We should have a single common script as this it involves huge maintenance efforts in both the scripts.

**Comment by lilitgh** [comment]
Duplicate script has been removed
