### ISSUE TITLE
Missing template using node buildpack

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/test-infra#2996]
**Description**

We  should have a template for jobs using [node buildpack](eu.gcr.io/kyma-project/test-infra/buildpack-node)

**Reasons**

It is not easy to define new jobs for projects that should use node buildpack.

**Related issues**
https://github.com/kyma-project/test-infra/pull/2993

**Comment by Ressetkk** [comment]
I think the better approach would be to allow more generic convention. Instead of creating a new solution and introduce a new templates for specific build job we should really allow people to define the image which prow should use and if it's not present, then fallback to a bootstrap image.

**Comment by dekiel** [comment]
Added buildpack-node-data.yaml for templating prowjobs using buildpack-node image.
See #3103
