### ISSUE TITLE
Update kyma alpha upgrade pipeline to latest kyma cli changes

### ISSUE THREAD

**Issue by strekm** [kyma-project/test-infra#3124]
**Description**

`kyma cli alpha deploy` command changed so the pipeline should be updated. 

**Reasons**

Have a green pipeline testing new way of deploying kyma

**Acceptance Criteria**

- k3s cluster provisioned
- kyma deployed using evaluation profile
- fast integration tests triggered 
- optional pipeline is triggered on PR

**Attachments**

**Comment by a-thaler** [comment]
done already
