### ISSUE TITLE
Update kyma alpha uninstallation pipeline to latest kyma cli changes

### ISSUE THREAD

**Issue by strekm** [kyma-project/test-infra#3125]
**Description**

`kyma cli alpha deploy / undeploy` command changed so the pipeline should be updated.

**Reasons**

Have a green pipeline testing new way of removing kyma

**Acceptance Criteria**

- gardener cluster provisioned
- kyma deployed using profile
- fast integration tests triggered
- kyma deployed after it was previously deployed
- pre, post and periodic pipelines implemented as we have for deploy pipelines
- both evaluation and production profiles are tested

**Reference**

https://status.build.kyma-project.io/?job=*alpha*

**Comment by Tomasz-Smelcerz-SAP** [comment]
PR that extends two existing periodic pipelines with "kyma alpha delete" steps: https://github.com/kyma-project/test-infra/pull/3829

**Comment by Tomasz-Smelcerz-SAP** [comment]
Apart from pre/post submit jobs, everything else is done.
I consider this pipeline to be quite a long running one, we probably don't want to test uninstallation along with every single PR. Periodic ones should be fine at the moment.
