### ISSUE TITLE
Improve upload process in k3s jobs

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#3171]
**Description**

Some of our jobs (k3s, minikube based) copy kyma sources to a VM:
https://github.com/kyma-project/test-infra/blob/master/prow/scripts/provision-vm-and-start-kyma-k3s.sh#L104
This takes around 2 minutes: https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-k3s/1351893666624442369/build-log.txt
The time of execution of this step can be improved by adding a tar (or similar) command. This way we don't have to copy thousands of small files.

**Reasons**

K3S job takes 10 minutes, two of them are taken by this step. That's pretty bad.

**Acceptance Criteria**

- improve time of execution of "Copying Kyma to the instance" step
- add comparison data to this issue

**Attachments**

**Comment by Halamix2** [comment]
#3172 reduces this time from 2 minutes to around 14 seconds
