### ISSUE TITLE
Freeze state of prowjobs definition for old releases

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#3176]
**Description**

Every time we do a cleanup in our prow-jobs definitions and later have to create a patch for a previous release we fall into some issues because job definitions do not match scripts (that are stored in the respective release branch)
The idea is that maybe we can disable templates regeneration for old releases. Let's have discussion about that

**Acceptance Criteria**

**Attachments**

**Comment by dekiel** [comment]
Assuming that all prowjobs for older releases have versioned names, we can place in templates conditional statements which will render templates for old releases when condition is meet. Control of which releases should have prowjobs rendered will be done through rendertemplates cli arguments. By default template conditional statements will cause only current release prowjobs will rendered again.
