### ISSUE TITLE
Static cluster version in provisioning scripts

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/test-infra#324]
**Description**

Our provisioning scripts can fail if the currently used cluster version is no longer supported. This happened today.
I have created #323 which is a quick fix, setting the version to a newer but still static one. We should improve the script to get the required version from google each time we run the script. 

**Expected result**

The cluster is created using the latest 1.x.y version we want

**Actual result**

We are linked to a static version 1.10.6-gke.something which changes on a regular basis

**Steps to reproduce**

http://status.build.kyma-project.io/log?job=kyma-gke-integration&id=1073171091721031681

**Comment by lszymik** [comment]
Hello @Demonsthere,

Are you working as a stale bot? :)
