### ISSUE TITLE
Speed up build process for Kyma components

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#3273]
**Description**

This issue is about golang based components.
Main assumption here is improvements can be achieved by caching docker images and golang dependencies

***Docker images***
All Kyma components (written in golang) use the common makefile that encapsulates build process steps in a docker container:
https://github.com/kyma-project/kyma/blob/master/common/makefiles/generic-make-go.mk#L204. Since this is executed in a docker container anyway we can't benefit from image cache on k8s node level.

Example:
https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/10546/pre-kyma-components-eventing-controller/1359111186569760768/build-log.txt
This job uses bootstrap as a base image: eu.gcr.io/kyma-project/test-infra/bootstrap:PR-2951
Next in the makefile it calls eu.gcr.io/kyma-project/test-infra/buildpack-golang-kubebuilder2:v20201009-5d8104e0 (this image inherits from bootstrap).

The second image is downloaded on every execution. That can be avoided if we use the `buildpack-golang-kubebuilder2` directly in the prowjob definition.

***Golang dependencies***
We do not use any kind of local golang cache or proxy. We should evaluate if a solution like [athens](https://github.com/gomods/athens) can bring any benefits. Alternatively we should check if there is a possibility to use golang cache directory (mounted from node)

**Reasons**

It takes more time to fetch dependencies than build and (unit) test the component. That should not be the case.

**Acceptance Criteria**

* provide simple benchmark results   
* use docker cache from k8s node
* improve time of fetching golang dependencies (by using proxy or cache dir or both)

**Links**
* https://github.com/kubernetes/test-infra/issues/5436

**Comment by Halamix2** [comment]
Interesting article on GOPROXY: https://arslan.io/2019/08/02/why-you-should-use-a-go-module-proxy/

**Comment by Halamix2** [comment]
After some tests the difference of download speed between golang.org and local athens GOPROXY was negligible

**Comment by Halamix2** [comment]
Docker caches each layer, taking some time to pack it into .tar archive. In `pre-kyma-components-application-gateway` job, `go mod download` step takes 18s and additional 45s for Docker to pack this layer. After joining `go mod download` nad `go build` steps into one layer, with additional `go clean --modcache --cache`, time for the whole job was decreased by ~30-40 seconds/

Log: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/10600/pre-kyma-components-application-gateway/1361630375704530944
Joined layers: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/10600/pre-kyma-components-application-gateway/1361636415875584000

**Comment by adamwalach** [comment]
Using the base docker image directly on a job level gives us at least 3 minutes (and lowers network cpu usage)
Example:
before:
![Screenshot 2021-03-02 at 09 08 47](https://user-images.githubusercontent.com/8530211/109618475-ddd3e000-7b37-11eb-9c84-e49d96d14b7d.png)

after:
![Screenshot 2021-03-02 at 09 08 12](https://user-images.githubusercontent.com/8530211/109618450-d8769580-7b37-11eb-9a93-4c4225b97e9d.png)

**Comment by Halamix2** [comment]
Two components weren't updated (`console-backend-service`, and `iam-kubeconfig-service`), since they are very rarely used
