### ISSUE TITLE
OOM issues in evaluation profile pipeline

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#3300]
**Description**

After fixing [this issue](https://github.com/kyma-project/test-infra/issues/3290) we checked logs in stackdriver and found that several other components are failing as well:
![Screenshot 2021-02-15 at 16 41 40](https://user-images.githubusercontent.com/8530211/107966878-bcf28300-6fac-11eb-9dbb-69d29c7911bc.png)

List of failing components:
- pilot-discovery
- minio
- manager
- fluent-bit in "kyma-integration-hibernation-gardener-azure" 

**Links**
- https://github.com/kubernetes/kubernetes/issues/69676

**Comment by adamwalach** [comment]
Looks better now:
![Screenshot 2021-02-24 at 12 35 34](https://user-images.githubusercontent.com/8530211/108995010-cc548900-769c-11eb-92d5-c241835edf0f.png)

**Comment by Halamix2** [comment]
#3372 added `oom_debug.txt` artifact for Gardener jobs with debug information about memory limits and usage.

Pods closest to their memory limit:
`k8s_minio_rafter-minio` uses ~90% of memory max, starts at 70-90%, later on drops to ~15% ([example](https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1371432542174973953/artifacts/oom_debug.txt))
`k8s_backend_console-backend` on average uses uses 72-84% of memory

**Comment by dekiel** [comment]
Tracking oom events on all cluster nodes. Increased tracking and detection accuracy. #3394

**Comment by dekiel** [comment]
I've build notification system, which search for oom events in describe nodes command output and notify Kyma team on slack. At present we run production setup with target slack channel set to neighbors. As we confirm nothing is lost or broken, we will switch channel to ci-force probably.

**Comment by dekiel** [comment]
Channel set to ci-force. Teams are notified about OOM events.
