### ISSUE TITLE
Monitor PSPs assignment on test clusters 

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#3308]
**Description**

All Kyma components should have Pod Security Policies assigned. In order to verify that we need to gather information from
our test clusters.

To get a grasp of what is going on in a cluster we can use: 
```
kubectl get pods -A -o yaml | grep "kubernetes.io/psp: 001-kyma-unprivileged" -A 20 | grep name 
```
But this line is pretty useless if we want to gather more detailed data. 
We should create something similar to https://github.com/kyma-project/test-infra/blob/master/prow/scripts/cluster-integration/kyma-gke-long-lasting.sh#L245
Proposal:
```json
{
"name": "pod-name",
"owner": "metrics-server-v0.3.6-7c5cb99b6f",
}
```

**Acceptance Criteria**

- get a list of pods that use kyma-privileged psp and kyma-unprivileged psp (or alternatively we could grab this info for all pods to see what we miss)
- add this feature to `pre-master-kyma-gke-integration`, `pre-master-kyma-gke-integration`, and `kyma-gke-nightly`
- save output to the [artifacts](https://gcsweb.build.kyma-project.io/gcs/kyma-prow-logs/logs/kyma-gke-nightly/1362250777631920131/artifacts/) directory in json format

**Related issue(s)**
https://github.com/kyma-project/kyma/issues/9531

**Comment by Halamix2** [comment]
GKE integration jobs, and gke nightly/weekly should now collect following data into artifacts, sorted by psp and pod name:
```
{ "pods": [
  {
      "name": "alertmanager-monitoring-alertmanager-0",
      "namespace": "kyma-system",
      "owner": "alertmanager-monitoring-alertmanager",
      "psp": "001-kyma-unprivileged"
  },
  (...)
]}
```

**Comment by Halamix2** [comment]
As explained we gather pod security profiles assignments from our gke clusters in following jobs:
* https://status.build.kyma-project.io/?job=post-master-kyma-gke-integration
* https://status.build.kyma-project.io/?job=pre-master-kyma-gke-integration
* https://status.build.kyma-project.io/?job=kyma-gke-nightly

The kyma-psp.json file can be found in the artifacts subdirecotory. Example:
https://storage.googleapis.com/kyma-prow-logs/logs/kyma-gke-nightly/1362613189426024451/artifacts/kyma-psp.json

**Comment by Halamix2** [comment]
json for kyma-integration-evaluation-gardener-azure job: https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1362757931052830721/artifacts/kyma-psp.json
