### ISSUE TITLE
Remove Kind related files

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#3335]
**Description**

Since we no longer use or have any future plans to use [kind](https://github.com/kubernetes-sigs/kind) we should remove all references to it from our scripts/configs.

**Reasons**

We are migrating from minikube to k3s. Kind was only used for a very short period of time because we could not make it stable enough.
According to [this comparison](https://github.com/kyma-incubator/local-kyma#i-see-k3s-k3d-kind-and-minikube---what-should-i-use) there is no advantage of using it

**Acceptance Criteria**

- remove all references to kind pipelines in test-infra from presets, scripts and documentation 
- config files from Kyma repo

**Comment by Halamix2** [comment]
`rafter` and `helm-integration` are still using kind, so `preset-kind-volume-mounts` is still needed

`prow/scripts/kind` directory was used by `kyma-incubator/marketplaces`, but the repo is archived, and `pre-marketplaces` job was already broken by  #3059

**Comment by ammarlakis** [comment]
Kind files were removed in #4466, but the preset is still in use by rafter and helm broker.

**Comment by ammarlakis** [comment]
> @ammarlakis these preset used by some tests, you mentioned on slack, what they provide, what is a name of these presets? Do they refer somehow to the kind? I understand this is the preset `preset-kind-volume-mounts` mentioned by Piotrek. Can we change the name of the preset to not confuse anyone that we use a kind?

Actually the preset is still related to kind. Helm broker provision a kind cluster to do integration tests, while rafter tests are broken so couldn't test whether it uses kind or not and couldn't find it in the repo.
