### ISSUE TITLE
Upgrade Prow to newest version

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#3370]
**Description**

What needs to be done:
- install new version of Prow in neighbours project
- connect it to Kyma test repo
- create list of changes (from a developer point of view)
- check tide integration

**Reasons**

Testgrid integration is broken (version of prow is old)

**Comment by Ressetkk** [comment]
After making several tests with the new Prow instance I can say we are more-or-less ready to update Prow to new components and introduce tide for automatically merging the PRs.

As the approve plugin is still being rewritten to allow approvers work with filters we can utilise GitHub CODEOWNERS file and set-up tide to block merges if the PR is not approved by the reviewers. Additionally to block the manual merges it's needed to set-up tide context as Required in GitHub branch protection. While it is still not ideal solution, as once the PR lands in the tide merge pool the context is green and unblocks the manual merge, but it still gives less time to react and merge it manually. More information about tide can be found in [Tide docs](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/tide).

If the PR branch is not on the latest revision of the main branch then Tide will do a rebase against a latest branch and re-trigger all the tests. Then if the checks pass again it will merge the PR. This approach ensures that the change introduced to the project will work against most up-to-date revision.
Introducing Tide will increase the quality of a testing infrastructure and greatly reduce the number of checks to be shown in the Github status check, which will increase the readability. 

Once the Approve plugin is done then the next major step would be to introduce it organisation-wide and revoke all the write access from the repositories, deprecating GitHub CODEOWNERS.

#1079 #1556
