### ISSUE TITLE
Broken integration with testgrid 

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#3380]
**Description**

<img width="907" alt="Screenshot 2021-03-08 at 16 19 23" src="https://user-images.githubusercontent.com/8530211/110341190-5fd97280-802a-11eb-986c-ec9bed970249.png">

**Comment by adamwalach** [comment]
It looks like a common issue: 
https://github.com/kubernetes/test-infra/issues/21126

**Comment by dekiel** [comment]
Failing Pod test fixed, see #3379
