### ISSUE TITLE
Changing default branch names to `main`

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#3381]
**Description**

This is  an issue for renaming the default branch on repositories from `master` to `main`.
We need to change it on all active(not archived) repositories in `kyma-project` and `kyma-incubator`.
Prowjobs definition need to be updated as well.

**Acceptance Criteria**
- all repositories use `main` branch as a default one
- prow jobs are reconfigured to use the `main` branch

**Links**
- https://github.com/github/renaming

**Related issue**
https://github.com/kyma-project/community/issues/515

**Comment by Halamix2** [comment]
For simplicity treat templates as templates and definitions for jobs without templates
- [ ] Preparation
    - [ ] `jobguard` - add names `pre-main-kyma-components-.*`  etc. to `JOB_NAME_PATTERN`
    - [ ] `changelog-generator` - add main to if
    - [ ] templates - add main in branches for `pre-master` jobs
- [ ] For each repo (in order)
    - [ ] templates - add `main` in templates/jobs if necessary
    - [ ] templates -replace job names with `pre-main-*`, `post-main-*`
    - [ ] tests - changes
    - [ ] at the same time:
        - [ ] GitHub - change branch name from `master` to `main`
        - [ ] templates - change `base_ref` (if exists)
- [ ] Changes inn `test-infra`
    - [ ] same as above, additionaly:
    - [ ] pjtester - Change default branch name
- [ ] Closing changes
    - [ ] `jobguard` - remove names `pre-master-kyma-components-.*`  etc. to `JOB_NAME_PATTERN`
    - [ ] `changelog-generator` - remove master
    - [ ] makefile - some have `ci-master` target
    - [ ] update documentation

**Comment by adamwalach** [comment]
Next items:
- website
- community
- examples

**Comment by adamwalach** [comment]
Something to check, what is the difference between
```
git branch -m master main 
git fetch upstream
git branch -u upstream/main main
```

and the commands that github suggests it the pop-up (last line):

![Screenshot 2021-03-30 at 10 16 33](https://user-images.githubusercontent.com/8530211/112956710-05bb6100-9141-11eb-8a4f-537392402b94.png)

**Comment by Halamix2** [comment]
It seems the last command sets `upstream/HEAD` label to `main` in case anyone is using labels

**Comment by Halamix2** [comment]
presets with `master` in name were renamed to use `main`
