### ISSUE TITLE
Move the `third-party-images` repo to `kyma-project`

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#3385]
**Description**

Since this repo contains essential images used by Kyma we should no longer treat this solution as an experiment and move it to the `kyma-project` organisation.

AC:
- [third-party-images](https://github.com/kyma-incubator/third-party-images) is in `kyma-project` organisation
- prow jobs definitions are updated

**Comment by Halamix2** [comment]
The repo was moved, prow jobs updated, main branch renamed.
