### ISSUE TITLE
pjtester fails after `master`-> `main` migration

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#3473]
**Description**

After replacing all references of `master` with `main` pjtester fails on PRs that reference `kyma` repo:
https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_test-infra/3354/pre-master-test-infra-pjtester/1376442847552606208/build-log.txt
```
failed generate presubmit refs or extrarefs" error="could not get pr number for branch head, 
got error: failed get branch main, got error: GET https://api.github.com/repos/kyma-project/kyma/branches/main: 404 Branch not found []"
``` 

**Related issue**
https://github.com/kyma-project/test-infra/issues/3381

**Comment by dekiel** [comment]
Fixed in #3476
