### ISSUE TITLE
Enable protecode-guard on `third-party-images`

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#3475]
**Description**

[Protecode guard](https://github.com/kyma-project/test-infra/blob/main/templates/data/protecode-guard-data.yaml) should be enabled on: https://github.com/kyma-incubator/third-party-images

AC:
- protecode-guard works on pre-submit jobs in third-party-images repo

**Comment by Halamix2** [comment]
Protecode is enabled, but tag names of some images are different to what protecode expects, leaving some images scanned but not taken into consideration by the job

**Comment by Halamix2** [comment]
Images have now tag names recognised by the Protecode
