### ISSUE TITLE
ProwJob tests should test generated ProwJob CR, rather than the definition.

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#3497]
**Description**

ProwJob tests should generate the prowjob based on the definition that's in the test-infra, then perform the tests. 
**Reasons**

Current tests just check if the definition matches the tests that are written. Sometimes the prowjob definition may differ, but the resulting ProwJob is still the same. The test should not always fail if the ProwJob config has changed, but if the changes in the ProwJob CR are different. This approach should simplify writing the tests on the Prow side.

**Acceptance Criteria**

- Tests are rewritten to generate ProwJob out of the definition, then perform the tests on the generated CR.
- Tests don't always fail if the ProwJob definition has changed.

**Attachments**
https://github.com/kubernetes/test-infra/blob/master/prow/cmd/mkpj/main.go

**Comment by Halamix2** [comment]
Aside from one function defined in https://github.com/kubernetes/test-infra/blob/master/prow/cmd/mkpj/main.go (`func (o *options) genJobSpec(conf *config.Config) (config.JobBase, prowapi.ProwJobSpec)`), everything else can be easily imported as Go modules, allowing us to generate prowjob definitions in-memory during testing

**Comment by Ressetkk** [comment]
wtieend ProwJob spec has only marginal changes for git configuration. There is no real need to check generated jobs at all. Running tests against YAML definition should be enough.

/close
