### ISSUE TITLE
Add Prow build status badges

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/test-infra#355]
We can consider adding Prow build status badges to all the repos, most importantly to Kyma. 

Here is an example: https://status.build.kyma-project.io/badge.svg?jobs=kyma-integration
This is the format: `<deckendpoint>/badge.svg?jobs=comma,separated,job,list`

**Comment by michal-hudy** [comment]
There is one problem, it didn't filter by postsubmit jobs ;)

**Comment by michal-hudy** [comment]
Ok, we changed `postsubmit` jobs names, so now it will work.

Image for `kyma` repository: [https://status.build.kyma-project.io/badge.svg?jobs=post-master-kyma-*](https://status.build.kyma-project.io/badge.svg?jobs=post-master-kyma-*)

![Status](https://status.build.kyma-project.io/badge.svg?jobs=post-master-kyma-*)

**Comment by pkosiec** [comment]
@michal-hudy I think the badge is too long. It would be great to display status like `passing`/`failing`, for one specific job. Like `post-master-kyma-integration` or `post-master-kyma-gke-integration`?

**Comment by michal-hudy** [comment]
@pkosiec It will be not that long if all jobs will pass ;)

**Comment by pkosiec** [comment]
> It will be not that long if all jobs will pass.

Right, but... how often does it happen? 😉We don't want to scare people, right? :smile:
