### ISSUE TITLE
Update GitHub Webhook Gateway to work with Event Publisher Proxy

### ISSUE THREAD

**Issue by kazydek** [kyma-project/test-infra#3584]
**Description**
Event Service used in [GitHub Webhook Gateway](https://github.com/kyma-project/test-infra/blob/main/development/github-slack-connector/githubWebhookGateway/README.md) was removed in [PR 10925](https://github.com/kyma-project/kyma/pull/10925/). That's why the functionality of the GitHub Webhook Gateway needs to be revisited whether it can be replaced with the new [Event Publisher Proxy](https://github.com/kyma-project/kyma/tree/main/components/event-publisher-proxy).

**Comment by dekiel** [comment]
Github connector is now using event publisher proxy.
