### ISSUE TITLE
common functions and lib scripts in integration tests.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#3624]
**Description**

All scripts for integration test prowjobs should use common functions and scripts.
Scripts for different hypervisors should use aligned structured functions names.
High level functions should provide logic for loading functions for desired hypervisor.

**Reasons**

It's hard to maintain multiple versions of the same code.
Having rules and standards in place it's easier to maintain and develop code.
Cleanup and align our bash scripts is a good starting point for migration to golang.

**Acceptance Criteria**

Integration scripts use functions according to below rules.
Integration scripts use common lib scripts.

**Comment by dekiel** [comment]
KymaCLI support creating clusters on gcp and azure. We could use common lib with tests using gardener managed clusters.

**Comment by dekiel** [comment]
Functions should work with variables passed as arguments only. This allow to support different global variable names in different scripts.
All variables within a function should be initialised as a local.
All local variables names should be camel case and start with lower case.
All functions should have comment documenting function, accepted arguments, returning values and exported variables.

**Comment by Halamix2** [comment]
`prow/scripts/lib/kyma.sh`:

* `kyma::alpha_deploy_kyma` could be simplified to one `if [ "$EXECUTION_PROFILE" ]` or even removed in favour of adding `kyma alpha install` to each of 4 scripts that are currently using this function.

**Comment by dekiel** [comment]
See #4818
