### ISSUE TITLE
Avoid overriding released images

### ISSUE THREAD

**Issue by strekm** [kyma-project/test-infra#364]
Add information about updating RELEASE_VERSION file after the release is complete. 
Adjust order of creating kyma release branch and github release with reasoning (Creating branch will create push event which might trigger release job if defined)

**Comment by aszecowka** [comment]
> Add information about updating RELEASE_VERSION file after the release is complete.
If not, anyone who creates PR to release branch, override already released images which is definitely not good situation.

**Comment by aszecowka** [comment]
How istio release: https://github.com/istio-releases/pipeline

**Comment by aszecowka** [comment]
Idea how to prevent building docker images on **Presubmit** job:
- It seems that there is no option to mark that some images on gcr cannot be overwritten
- at the beginning of presubmit job, we can check if images can be built. If Github release already exist we know that probably we are going to override images - so we should fail fast and exit scrips with error codes. 

How to prevent running **postsubmit** job on branch creation or rebasing:
- maybe we can differentiate merging commits from branch creation or rebasing by the commiter, in case of merge commit I think it will be kyma-bot.
