### ISSUE TITLE
Prow related monitoring should be in kyma-prow project.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#3662]
**Description**

All monitoring and alerting set in gcp for prow should be placed in kyma-prow project not kyma-prow-workloads.

**Reasons**

Kyma-prow-workloads is a project intended to host resources created by prow prowjobs running on workload clusters in kyma-prow project.
This is intuitive and logic separation.
Project level permissions will secure prow related monitoring. This should be changed only by prow admins.

**Acceptance Criteria**

Uptime check for prow console and Grafana are running in kyma-prow project.
![image](https://user-images.githubusercontent.com/12400578/118627016-a63a1300-b7cb-11eb-98d5-f4915926c265.png)

**Comment by Halamix2** [comment]
Uptime check for prow console and Grafana were moved to kyma-prow project.
