### ISSUE TITLE
build psp privileged for debug commando for aws and az.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#3745]
**Description**

We need cluster role binding to enable psp privileged for debug commando pod on aws and azure providers.

**Reasons**

Debug commando need special privileges to access conatinerisation daemon socket. It needs to run as privileged conatiner.

**Acceptance Criteria**

AWS and AZ pipelines can use debug commando.

**Comment by ammarlakis** [comment]
Solved with #4509
