### ISSUE TITLE
All integration script use utils::post_hook for cleanup

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#3859]
**Description**

All integration scripts are using utils::post_hook function in trap on error or exit. Function is doing cleanup and logs collection. At present scripts are using multiple local versions of post_hook or cleanup functions.

**Reasons**

We should have consistent way of cleanup and collecting logs from execution.

**Acceptance Criteria**

All scripts use utils::post_hook function.
Script local cleanup functions are solving custom script local problems.

Parent: #3624

**Comment by Halamix2** [comment]
#3869 will replace post hooks in 3 scripts that were using `gcloud::cleanup`
