### ISSUE TITLE
Scripts: create common function for initialization

### ISSUE THREAD

**Issue by Halamix2** [kyma-project/test-infra#3895]
**Description**

All cluster scripts have their own way of creating network, cluster etc., often copying the same code.

**Reasons**

Making one common function would simplify scripts, making them shorter easier to maintain

**Acceptance Criteria**

All scripts use common initialization function.
Script local initialization functions are solving custom script local problems.

Parent: #3624

**Comment by dekiel** [comment]
See #4818

**Comment by dekiel** [comment]
Parent issue is not valid anymore.
