### ISSUE TITLE
Scripts: unify long-lasting scripts

### ISSUE THREAD

**Issue by Halamix2** [kyma-project/test-infra#3902]
**Description**

GKE & AKS long lasting scripts are using the same scripts, but they have different names of similar variables.

**Reasons**

Unifying variable names would simplify the scripts

**Acceptance Criteria**

**Comment by dekiel** [comment]
Long running clusters are not used anymore or they are used for 1.24 release only. We will evalute that in other issue and cleanup all resources which are not needed.
