### ISSUE TITLE
Clean disks in GCP

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#3915]
**Description**

Disk which are not needed are removed periodically. 

**Reasons**

We have plenty of disk, which i believe are not used and needed anymore.

**Acceptance Criteria**

Not needed disks are cleaned at least once a month.

**Attachments**

https://console.cloud.google.com/monitoring/dashboards/resourceList/gce_disk?project=sap-kyma-prow-workloads&supportedpurview=project&timeDomain=1h

**Comment by Halamix2** [comment]
The `gke-commit` and `gke-pr` disks are now cleaned periodically, reducing number of disks significantly
