### ISSUE TITLE
Provision production Prow cluster

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#40]
The goal of this issue is to prepare official Prow cluster, that is configured for github.com/kyma-project/kyma.
Provision such cluster should be fully automatic. 
Make sure that:
- ingress is using https
Depends on #25

**Comment by aszecowka** [comment]
Consider making all our jobs optional (status is not required for merging) - thanks to that we will not block kyma-developers by immature prow.

**Comment by michal-hudy** [comment]
As discussed, cluster is provisioned manually.
