### ISSUE TITLE
ok-to-test comment is taken into account although it is disabled

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#403]
We disabled ok-to-test functionality in the following task: https://github.com/kyma-project/test-infra/issues/50

But still, when someone from Kyma organization adds such comment it allows triggering build by external contributors. 
Purpose of this task is to check if it is already fixed in Prow repository itself, see discussion here:
https://kubernetes.slack.com/archives/CDECRSC5U/p1545401935001900

To Do:
* check with the community if fixed.
* Verify by deploying the prow cluster with the fix
* Do Prow upgrade in Kyma.

**AC**
- [x] `ok-to-test` flag is disabled.

**Comment by suleymanakbas91** [comment]
This problem will be solved by this PR: https://github.com/kubernetes/test-infra/pull/10991
We need to wait for it to get merged, and then upgrade our Prow cluster to have the fix.

**Comment by crabtree** [comment]
The PR kubernetes/test-infra#10991 was merged.

**Comment by suleymanakbas91** [comment]
I've done some testing. The PR is merged but the images in [starter.yaml](https://github.com/kubernetes/test-infra/blob/master/prow/cluster/starter.yaml) haven't been bumped yet. I tried randomly couple of recent images, but plank component crashes with an error. If I try with a bit older images, then the config updater does not work. Going even older means not including `/ok-to-test` fix. Maybe we should wait until these images are bumped in kubernetes/test-infra so it might get more stable.

**Comment by suleymanakbas91** [comment]
Images have been bumped today. We can test it again. I'm moving this to `To Do`.

**Comment by suleymanakbas91** [comment]
I tested and can confirm that it is fixed. Here is the PR to bump the images in our installation files: https://github.com/kyma-project/test-infra/pull/590

**Comment by suleymanakbas91** [comment]
I realized that usage of these images have been reverted in kubernetes/test-infra: [kubernetes/test-infra#11205](https://github.com/kubernetes/test-infra/pull/11205)
We should wait until they bump the images to a stable version.

**Comment by suleymanakbas91** [comment]
Here is a related ticket about this issue: https://github.com/kyma-project/test-infra/issues/533

**Comment by suleymanakbas91** [comment]
This one is solved as we upgraded the Prow cluster: #590
