### ISSUE TITLE
Kyma CLI release pipeline is broken

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#4033]
**Description**
When I tried to release Kyma CLI 1.24.1 it failed on `pre-kyma-cli-integration-k3s` with the following error: 
```
Starting Node 'k3d-kyma-agent-0'             
': signal: killed
2021/07/28 12:59:32 UTC [INFO] Removing instance cli-integration-test-11cf23cb
Wed Jul 28 12:59:32 UTC 2021
```
https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_cli/947/pre-kyma-cli-integration-k3s/1420366703082082304/build-log.txt

After few days when I tried to solve it, I faced another issue:
```
2021/08/11 13:24:52 UTC [INFO] Installing Kyma
Wed Aug 11 13:24:52 UTC 2021
Pseudo-terminal will not be allocated because stdin is not a terminal.
Failed to add the host to the list of known hosts (/root/.ssh/google_compute_known_hosts).
Error: unknown command "deploy" for "kyma"
Run 'kyma --help' for usage.
```
https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_cli/947/pre-kyma-cli-integration-k3s/1425447419184680960/build-log.txt

This is caused by incompatible changes in the test-infra scripts.

**Proposed solution**
First, release pipelines need to be defined in the same way as component pipelines - they have to use sources from the corresponding release branch in `test-infra` .
Second, let's see if the first issue is still present

**Comment by Halamix2** [comment]
```bash
docker ps --no-trunc
CONTAINER ID                                                       IMAGE                      COMMAND                                                 CREATED         STATUS                          PORTS     NAMES
65e1696517fd19108afb08b4c69b630d2d5d27e782275c7d21b6badd9996367d   rancher/k3s:v1.20.6-k3s1   "/bin/k3s agent"                                        2 minutes ago   Up 2 minutes                              k3d-kyma-agent-0
29dd11cb1cfbf571161dddf8d74675b462a5e2fe25083d0cf878999e93078996   rancher/k3s:v1.20.6-k3s1   "/bin/k3s server --disable traefik --tls-san 0.0.0.0"   2 minutes ago   Restarting (1) 50 seconds ago             k3d-kyma-server-0
```
Second container always fails on
```bash
I0817 07:44:55.561934       7 conntrack.go:103] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
F0817 07:44:55.562121       7 server.go:495] open /proc/sys/net/netfilter/nf_conntrack_max: permission denied
```
Possible solution: set `nf_conntrack_max` manually ( https://github.com/rancher/rancher/issues/33300 )

**Comment by Halamix2** [comment]
The problem was on release-1.24 branch, which now have `nf_conntrack_max` set up, which fixed the problem with k3s start.
Jobs for main and release branches were split up, so previous releases will now use their own test-infra branches, which fixes the problem with command names
