### ISSUE TITLE
Update existing prowjobs to use 1.24 branch

### ISSUE THREAD

**Issue by k15r** [kyma-project/test-infra#4087]
**Description**

All currently existing prow jobs execute based on the main branch. With recent changes on main some of them will not work anymore. In order to run existing tests in a valid setup we need to migrate those tests to execute based on the latest 1.x branch (1.24) 

**Acceptance Criteria**
- [x] Move all jobs that can only be built using the 1.24 branch to relase-124.yaml (#4123)
- [ ] All currently existing prow jobs that are still required in the future are migrated
- [ ] introduce new tests for kyma 2.0 in case a required scenario has been migrated to 1.24

**Missing Tests**
- [x] #4126
- [ ] #4127
- [x] #4168

**Attachments**

**Comment by k15r** [comment]
switching jobs to 1.24 branch should be done by moving the job definition here: 
https://github.com/kyma-project/test-infra/blob/main/prow/jobs/kyma/releases/kyma-release-124.yaml

**Comment by kwiatekus** [comment]
We are also working on adapting the ( removed ) docker registry test https://github.com/kyma-project/test-infra/issues/4168
