### ISSUE TITLE
[CI] ProwJobs created by pjtester are being handled by crier

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#4154]
**Description**

Some of the jobs generated by pjtester are incorrectly reported to GitHub. This makes the jobs to be incorrectly handled by tide and results in blocked, unmergeable PRs.

**Expected result**
Jobs are not reported to the GitHub.

**Actual result**
Some jobs are reported to GitHub.

**Troubleshooting**
Affected PRs:
https://github.com/kyma-project/kyma/pull/12085
https://github.com/kyma-project/kyma/pull/11887

**Comment by dekiel** [comment]
See this PR https://github.com/kyma-project/test-infra/pull/3448.
It introduced problem with reporting statuses to Github. Probably the best solution will be to disable all reporting by default and add ability to enable crier reporting through pjtester.yaml file. Having Crier reporting enabled is needed to get podinfo lens data as described in mentioned PR as well for testing integration with pubsub.

**Comment by dekiel** [comment]
Building and maintaining second prow instance with slightly different configuration sounds too heavy for me. I would give a try enabling crier on demand.

**Comment by Ressetkk** [comment]
Why? Separating production and testing environment is something that will harden the security. I would give it a shot. Having everything on production cluster without any Role-based authorization is a violation and makes the secrets exposed to unattended leakage.

**Comment by dekiel** [comment]
At present a pjtester is reporting tests prowjobs under dedicated context with prefix like `dekiel_test_of_`. This let developers to identify this was created and reported by pjtester. These prowjobs are not known to Tide so we can't set them explicit as optional. I need to check if such failed context, which are unknown to Tide are blocking merges. @Ressetkk @halamix2 maybe you guys can answer. It such contexts do not block merging by tide we should be good to close this issue.

**Comment by Ressetkk** [comment]
It seems that these jobs have annotation `prow.k8s.io/is-optional: "true"`, so in theory should not block merges, but AFAIK there was a problem where such job in fact blocked the tide context.

IMO no test executions are supposed to be reported to GitHub **at all** to not increase confusion.

**Comment by Ressetkk** [comment]
With other people on Slack progressively adjusting ProwJob reporter configs to their own channels this issue is being more visible. Right now postsubmit job has been reported to private channel where it shouldn't be. 
![image](https://user-images.githubusercontent.com/23667947/234876611-deecaad2-84c2-4870-8150-d20421cd5e78.png)

**Comment by Ressetkk** [comment]
I also feel this needs proper retitle.
/retitle [CI] ProwJobs created by pjtester are being handled by crier

**Comment by Ressetkk** [comment]
Another problem. PJTester pins test executions to GitHub commits, falsely marking statuses as failed
<img width="579" alt="image" src="https://user-images.githubusercontent.com/23667947/235088766-d8140ab3-3aa4-4fcb-ace8-ffc5b8db659f.png">
