### ISSUE TITLE
Define strategy for organising jobs in config.yaml

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#42]
Putting the whole configuration to single config.yaml can generate an enormous file and become difficult to maintain. 

For example, Istio define their strategy here: https://github.com/istio/test-infra/tree/master/prow/cluster/jobs

>Presubmit and Postsubmit configs are separated per org/repo/branch to ease config management.
>All periodic jobs are defined in the all-periodics.yaml.

AC: 
- strategy defined
- strategy implemented

UPDATED:
Because we will have many yaml files, it does not make sense to keep autogeneration of config files - it will be too time-cosnuming. Please remove code responsible for config generation. Additionally, update README file which describes how to configure Prow on your fork.
To cleanup structure of project, please rename "prow-configurations" to development directory.

**Comment by crabtree** [comment]
The test-infra repository will have defined configurations for prow cluster in `prow` subdirectory. This directory will have following structure:
- directory `cluster` - contains all yaml files for prow cluster provisioning
- directory jobs/<repository_name> (eg. kyma, console) - contains all files with jobs definitions
- config.yaml - yaml file containing prow configuration (without job definitions)
- plugins.yaml - yaml file containing prow plugins configuration

Directories <repository_name> will have subdirectories which will represent each component and contain jobs definitions. Jobs definitions not connected to a particular component should be defined directly under <repository_name> directory.

Example:
```
...
prow
|-cluster
| |-starter.yaml
|-jobs
| |-kyma
| | |-components
| | | |-environments
| | | | |-postsubmit.yaml
| | | | |-presubmit.yaml
| | |-periodics.yaml
| | |-integration.yaml
|-config.yaml
|-plugins.yaml
...
```

To make prow respect this configuration we need to modify plank start parameters specifying `--job-config-path=...` and involve automatic configmap update for this files with config-updater
