### ISSUE TITLE
K8s cluster 1.18 need to be updated to at least 1.19 on GKE

### ISSUE THREAD

**Issue by dzahariev** [kyma-project/test-infra#4260]
**Description**

Prow jobs start to fail with an error:
```
WARNING: Starting with version 1.18, clusters will have shielded GKE nodes by default.
WARNING: Your Pod address range (`--cluster-ipv4-cidr`) can accommodate at most 1008 node(s). 
WARNING: Starting with version 1.19, newly created clusters and node-pools will have COS_CONTAINERD as the default node image when no image type is specified.
ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=400, message=No valid versions with the prefix "1.18" found.
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
The version that is configured for all prow jobs seem to be 1.18, and need to be updated:
https://github.com/kyma-project/test-infra/blob/main/prow/config.yaml#L277

**Expected result**

Tests to pass

**Actual result**

Test are failing during cluster initialisation

**Steps to reproduce**

See GKE tests in prow.

**Comment by desislavaa** [comment]
Fixed with https://github.com/kyma-project/test-infra/pull/4272
