### ISSUE TITLE
Replace the "Make Kyma release" step in the GA release pipeline

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#4313]
**Description**

Because of changes introduced in the Kyma 2.0 we need to adapt our release pipeline.
It fails on copying configuration fails - they are no longer created in the artifacts pipeline, so source files are not present. 
It looks like the best course of action is to replace the [githubrelease](https://github.com/kyma-project/test-infra/tree/main/development/tools/cmd/githubrelease) tool with some GA plugin (some ready to use github action extension)

**Expected result**

- pipeline is green
- `kyma-components.yaml` is copied to [this bucket](https://console.cloud.google.com/storage/browser/kyma-prow-artifacts)

**Actual result**

- pipeline is broken
- files are not copied

**Comment by Ressetkk** [comment]
The action is now green. Let's close this issue as any other changes would fall into release improvements.
