### ISSUE TITLE
Azure-cli is missing some of the required packages

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#4345]
**Description**
`Azure-cli` started failing after changes made in the kyma-integration file. Supposedly the `--no-install-recommends` made that some of the suggested packages that were in fact required for the tool to work were not installed https://github.com/kyma-project/test-infra/blob/25b7dd15962b10986af77f81af8c8054ad575cf7/prow/images/kyma-integration/Dockerfile#L134

Old `az version` output:
```
Azure CLI Version:
This command is in preview. It may be changed/removed in a future release.
{
  "azure-cli": "2.2.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.2.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}
}
```

New `az version` output:
```
Azure CLI Version:
{
  "azure-cli": "2.18.0",
  "azure-cli-core": "2.18.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

Needs more investigation.

**Comment by Halamix2** [comment]
`--no-install-recommends` doesn't change anything as this package doesn't have any recommended/suggested packages
The `kyma-aks-nightly-rel124` job was failing on `az aks delete -g "${RS_GROUP}" -n "${CLUSTER_NAME}" -y` command

Looks like this was an upstream issue, az 2.18 was broken in Debian: https://github.com/Azure/azure-cli/issues/17928
