### ISSUE TITLE
Prow release pipeline for kyma/event-bus, test/event-bus, event-service, k8s-dashboard-proxy and gateway tests

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/test-infra#444]
See #144 for details.

>Note: Please update #144 when working on a component.

**AC**
* There is prow release pipeline defined and checked in for all the components
* There is image for each component created with the release tag.

**Comment by marcobebway** [comment]
I added prow release jobs and tests:
- components/event-bus
- components/event-service
- components/k8s-dashboard-proxy
- tests/event-bus
- tests/gateway-tests

The PR https://github.com/kyma-project/test-infra/pull/453 is merged and approved by the prow-wg.

Currently, if there is no way to test if the release images are pushed and tagged correctly or not before starting the release process.
