### ISSUE TITLE
[Documentation] Markdown files review and approval proposal.

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#4520]
As a part of the improvements for development and workflow around Kyma I have a small proposal for the documentation approval and review flow. Right now we are using Prow without the full potential of approve and review flow because by definition all Markdown files are **required** to be approved by the technical writers group. This assumption let alone is really good, however it blocks the ability to introduce the approve plugin for Prow and blocks us from revoking the organisation members write access to the repository. By default approve plugin **does not allow** assigning technical writers group to review only specific files determined by a wildcard and there is still ongoing issue https://github.com/kubernetes/test-infra/issues/7690. The new implementation would require complete rewrite to make it work, and there is no KEP defined for that functionality yet. Instead of waiting for upstream we should take some action to un-block the ability to introduce the approve plugin and comment flow that Prow utilises.

Here are 2 of my proposals:
1) Technical writers are not required for the markdown files to be reviewed inside the various repos and be a responsibility for the code owners of the given directory. Of course the author can always ask the technical rites group for a review, but it won't be necessary for the PR to be merged.
2) Introduce Prow plugin that checks wether the Markdown files are changed and adds a label `needs-tws-review` to the PR. The label would work as a blocking label. Given that the members will have no write access to the repo they won't be able to remove the label at all. Once the PR is approved by the member of the technical writers group the PR will be un-blocked and Tide will continue with a merge of the PR. Once the changes to the markdown files are made again it will re-add the label and comment that changes to the markdown have been made.

All options try to tackle problem which blocks us from introducing approve plugin forProw on the `kyma-project` and `kyma-incubator` organisations.

**Comment by dekiel** [comment]
Let's try second option.

**Comment by Ressetkk** [comment]
There is opened Pull Request regarding gradual approvals so the plug-in probably won't be needed at all. https://github.com/kubernetes/test-infra/pull/21398

**Comment by Ressetkk** [comment]
Plugin is working, codebase is merged.
