### ISSUE TITLE
Create prow job for testing kyma on cluster with stability checker installed

### ISSUE THREAD

**Issue by strekm** [kyma-project/test-infra#454]
Goal of this issue is to migrate Jenkins pipeline installing kyma on azure long living cluster with installed stability checker.

AC:
- long living gke cluster installed
- kyma installed
- stability checker installed
- after given period time test env is cleaned

**Comment by Demonsthere** [comment]
After some discussion with @strekm and @Tomasz-Smelcerz-SAP we concluded the following:
In the first step we want to create a MVP version which will:
- Remove the cluster from previous night (each cluster has different IP, DNS and name)
- Create a new cluster (different name, IP, DNS)
- Install kyma & stability-checker

As we only remove the previous cluster, all other resources that may be orphaned should be deleted by our working garbage collectors (this may need regex expansion in the collectors) 

Slack notification will be done as a followup task

**Comment by Demonsthere** [comment]
Additional request from @aszecowka: we should have a `notifySlackNow` function, which would use curl to send a notification to our slack channel, when the nighty task itself fails (could not provision/delete/create, could not install/test kyma)

**Comment by michal-hudy** [comment]
Please consider creating such cluster in `kyma-project`, not `kyma-prow`. "Core" Kyma developers sometimes need to have access to such cluster.

**Comment by strekm** [comment]
https://status.build.kyma-project.io/log?job=kyma-gke-nightly&id=1087974904789209090
