### ISSUE TITLE
Changes to test-infra/go.mod should be tested.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#4573]
**Description**

Changes to test-infra/go.mod should be covered by some tests. Tests should be run on PR. On commit to main we should rebuild all OCI images with binaries compiled with new versions from go.mod.

**Reasons**

After changes in go.mod we don't have any feedback if any binaries builds are broken. We haven't identified if any integration tests need to be tested with new versions. New versions in go.mod are not propagated to OCI images in use, because we doesn't rebuild them on go.mod changes.

**Acceptance Criteria**

- on PR and commit check if all binaries and OCI images can be build
- on commit rebuild and publish all OCI images using modules new versions
- on PR and commit run integrations tests if any

**Comment by Halamix2** [comment]
On changes to the `go.mod`/`go.sum` files,:
* we're now checking if `prow-tools` image can be built
    * the image is published after merge
* we're running the tests of tools in the `development` directory on presubmit

**Comment by Halamix2** [comment]
Example of the tests: https://github.com/kyma-project/test-infra/pull/4713
