### ISSUE TITLE
Automatically bump excluded files in `kyma/releases` directory.

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#4587]
We need to add a template to rendertemplates that will update the names for `kyma/releases` directory. Since we don't want to change the jobs of already released versions.

**Acceptance criteria**
* Only 3 last released versions should be protected
* The yaml file is generated based on a template

**Comment by dekiel** [comment]
Please provide more details what you would like to do, how the template and rendertemplate should behave. What names you want to change? File names or prowjob names? How this works now?

**Comment by Ressetkk** [comment]
Right now we have to figure out a way to automatically bump the excluded files in the https://github.com/kyma-project/test-infra/blob/main/prow/autobump-config/test-infra-autobump-config.yaml because we don't want the kyma release jobs to change in case there is a new version of integration image. Ideally it's needed to template this file and have it regenerated once a release is bumped.
