### ISSUE TITLE
Possible deadlock for Kyma-gke-integration postsubmit job

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#459]
![screenshot 2019-01-04 at 11 57 00](https://user-images.githubusercontent.com/476407/50685159-6918c000-1018-11e9-90b4-806094332fea.png)

Following situation was observed:
- no postsubmit job `kyma-gke-integration` is currently executed
- 3 jobs are triggered, but none is running for a long time

**Comment by aszecowka** [comment]
Let's examine method `canExecuteConcurrently` defined in prow/plank/controller.go
```
func (c *Controller) canExecuteConcurrently(pj *kube.ProwJob) bool {
         ...

	numPending := c.pendingJobs[pj.Spec.Job]
	if numPending >= pj.Spec.MaxConcurrency {
		c.log.WithFields(pjutil.ProwJobFields(pj)).Debugf("Not starting another instance of %s, already %d running.", pj.Spec.Job, numPending)
		return false
	}
	c.pendingJobs[pj.Spec.Job]++
	return true
}
```

and our configuration:
- we have presubmit job `kyma-gke-integration` where `max_concurrency` is set to 10
- we have postsubmit job `kyma-gke-integration` where `max_concurrency` is set to 1

Notice, that presubmit job and postsubmit job have the same name.
At the same time, `pendingJobs` is a map, where key is only a job name.
In our case we have situation that at the same time we have running some presubmit jobs `kyma-gke-integration` and they prevent from running postsubmit jobs.

We need to consider if having the same name for presubmit and postsubmit jobs is OK.
As a quick fix, we can set the same value for max_concurrency for `kyma-integration` and `kyma-gke-integration` = 10.

**Comment by Demonsthere** [comment]
I'd vote for changing the job name to have them unique. I remember we had the discussion previously and we decided to have unique names but only in the scope post/pre-sumit jobs. I think we should change jobs names to have `pre/post/period` as a prefix in the job name
