### ISSUE TITLE
Installation on forks not possible by following the documented steps

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/test-infra#464]
**Description**

[required-secrets.yaml](https://github.com/kyma-project/test-infra/blob/master/prow/cluster/required-secrets.yaml) leads to problems while installing on forks. It requires creating secrets (e.g. **kyma-bot-github-token** and **kyma-bot-github-ssh**) which shouldn't be needed for forks.  Currently, following the documented steps end up with the error `while reading object [kyma-bot-github-token.encrypted] from bucket: storage: object doesn't exist`.

**Comment by derberg** [comment]
@suleymanakbas91 could you please elaborate why it is critical, and if really critical could you do a direct pull request?
