### ISSUE TITLE
Improve slack notifications

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#466]
In this PR https://github.com/kyma-project/test-infra/pull/456/files
slack notifications were introduced. 
Unfortunately, current configuration is quite difficult to maintain and extend in the future:
```
      expr: topk (1, kube_pod_completion_time{namespace="default"} and on(pod) kube_pod_labels{namespace="default", label_prow_k8s_io_job="kyma-integration", label_prow_k8s_io_type="postsubmit"}) and on(pod) kube_pod_status_phase{phase="Failed"} == 1

```
AC:
- Check Crier  https://github.com/kubernetes/test-infra/tree/master/prow/cmd/crier
- Apply to one job and send notification
See also #505

**Comment by mszostok** [comment]
- [Add Kustomize to kubebuilder buildpack](https://github.com/kyma-project/test-infra/pull/598)
- [Add prow-addons-ctrl job and slack token secret information and checks](/kyma-project/test-infra/pull/595)
- [Add slack notifier controller](https://github.com/kyma-project/test-infra/pull/592)
- [Add slack notifier to starter.yaml, add grafana json, add main documentation]() -TBD
