### ISSUE TITLE
Kyma-integration VM - create custom image with preinstalled tools

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#47]
This is follow up task for PR #44
Currently, when we create VM for running integration tests, we install on it all needed tools: docker, kubectl, helm, minikube. This takes time and also can fail (for example URL for minikube is not accessible for short time).
This issue is about implementing custom images (https://cloud.google.com/compute/docs/images)

**Comment by Demonsthere** [comment]
Do we need any specific versions/config for either of those tools?
