### ISSUE TITLE
Testgrid pipeline is broken by spelling error

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#4733]
**Description**

All executions of `pre-test-infra-validate-testgrid-config` fail with the following errror:
```
validating spelling...
./hack/Makefile:19:14: "overriden" is a misspelling of "overridden"
./experiment/Makefile:19:14: "overriden" is a misspelling of "overridden"
ERROR: bad spelling, fix with hack/update-spelling.sh
```
https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_test-infra/4726/pre-test-infra-validate-testgrid-config/1481931904109252608/build-log.txt

The offending file was introduced ~20h, we have a fix for that in this PR: https://github.com/kubernetes/test-infra/pull/24881

This issue blocks our PRs to test infra, temporarily we should make the testgrid job optional.

**Comment by Halamix2** [comment]
Upstream fix has been merged, the job is passing now

**Comment by Ressetkk** [comment]
The issue has been resolved as for now.
/close
