### ISSUE TITLE
[CI] Improve go tools and binaries building flow.

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#4755]
**Description**
As for now adding a new go tooling is a tedious process that require the developer to do the following steps:
1. Add tooling code to the repository
2. Create separate multi-stage Dockerfile that builds the binary, packs it to the minimal container
3. Create Makefile with the steps that invoke the build and push to the repository
4. Add separate ProwJob that runs above building and pushing step

In my opinion this process has several drawbacks:
- It's time-consuming. Developer needs some time to create working flow
- Most of the pipelines are copy-pasted. Too much redundancy
- Dockerfiles are not standarized. Every tool has different Dockerfile based on what dev wrote ATM
- Adding new ProwJobs generate unwanted GitHub status checks. **This is by far the most problematic, because it interferes with Stale-bot.** Stale-bot cannot flag the PRs as stale because of fake "activity" in the stale PRs.

The only pros I see are:
- ProwJobs work independently. Less time, to wait for finish build, more resources required.

I've come up with some ideas that we should evaluate to improve building Go binaries.

1. Building go binaries inside the working ProwJob, then pack prebuilt binary into OCI image:
    * No need to use multi-stage builds. No need to pull another big image only for build.
    * Only one place to bump Golang image - ProwJob image, instead of respective tools' Dockerfiles. One dependency to track.
2. Pack binaries using daemon-less builders:
    * We had some discussion before about it when the evaluation of building tools didn't work out very well. But we tried to work on Dockerfiles using go code. For example with buildah we can define Docker image structure directly in the Go code. With that additional Dockerfile is not needed at all.
    * If the option above doesn't work out it still can be achieved using Docker's go client ([BuildKit](https://github.com/moby/buildkit)).
3. Define how image should be build using declarative `manifest.yaml`:
    * Some tools might have specific run settings or overrides, like used image, additional binaries, remote name etc.
    * Only tools with the manifest will be built

With the above points my suggestion is to create build image with binary that will run `go build` and pack the built binary from scratch, or other OCI image with options defined in the manifest.yaml. The tool will iterate over contents of the repository and build all directories that contain `manifest.yaml` file. Then it will push the images into defined container registry. This approach will reduce the requirements in the process of adding another tooling. Developer will have to add go code and `manifest.yaml` file that will automatically enable building of the new go tool. Building tools will require only 2 ProwJobs - Presubmit that runs initial builds and Postsubmit that builds and pushes file to the directory.

The requirements this approach tackles:
* Provide easy way of automated builds for go binaries and pack them as Docker images (*Required)
* Have an easy Prow-based solution to build kyma components and tooling (*Required)
* Provide multi-arch builds
* Remove usage of docker daemon in Prow when building go binaries
* Have one go build toolkit provided by us in ProwJob, so the Go binary is the same when building all components
* Have one base image with common configuration across components (updates can be automated)
* Reduce the number of configurations for adding a new binary/component to only add code and entry to the manifest file

It's still an idea, so further discussion is much appreciated.

**Comment by Ressetkk** [comment]
@dekiel 
>How we build go binaries now? Are we building outside working Prowjob? What does it mean?
Are we not using all pod resources? You mean cpu and memory? Do we have some metrics about that?
Mutli stage build requires additional Docker daemon?

We build them in 1st stage of Dockerfile. Basically use Docker-in-docker to build image. Note that in kyma-integration image we already have Go installed in yet another `v1.17.5` version.
Some of the tools do not even run from binary (see image-syncer).

Several examples.
https://github.com/kyma-project/test-infra/blob/fe1cc8a96ff9372bb8b5a9bb4d9386725e52cc6f/prow/images/prow-tools/Dockerfile
https://github.com/kyma-project/test-infra/blob/5d70b2740e88d8ed4885cf8652b3248ffacd6de6/prow/images/test-untrusted-plugin/Dockerfile
https://github.com/kyma-project/test-infra/blob/34b6c1c1b2da12c94997f86863f9b6daf276873e/prow/images/debug-commando/Dockerfile
3 Go tools, 3 different Golang images used to build. Clearly there is a room for improvements.

>Why I have no control over golang version used to build binary. I can define it by using FROM directive

Because it may generate errors and additional steps if there is a need to update Go version. One place to change (eg. buildpack-golang image), populates everywhere once we build new image. No need to bump Dockerfiles if there are no Dockerfiles.

>If we run a build image to iterate over all manifest.yaml we will lose ability to build only images which code did change. Possible smal change in one image will trigger rebuild all images, changes in all yaml files using updated images and finally update of all workloads using them. That seems not optimal.

Yes, it's an intended behaviour - Every go tool we use would reflect the same state of changes, since they would be built from the same commit. Similar to `prow-tools`, but each binary has it's own image. You would have one job that builds tools and pushes images, then one autobump job that bumps images, which ultimately will be automatically merged. 
Pros:
* One tag for all versions - time concerns are not a problem since it would take like around 5 +- 2 mins to build, pack and push all images - execution similar time.
* You just have to add go code and a manifest file. Nothing else. No Dockerfiles, no additional ProwJobs. Code and go :)
* Images will be smaller. I already realise it's not a concern, however any security scans will be quicker and more precise since the images would generally contain only single entrypoint binary.

>Did you consider using `rendertemplates` to standardise Dockerfiles?

I did and I think for this scenario Dockerfiles are really not that needed. Also that would suggest adding separate ProwJob for each of the tools. That does not resolve problem where new job added makes the GitHub statuses go wild and generates activity on PRs.

Bullet points:
* No Dockerfile, Only small manifest and Go code. More coding, less configuring.
* Multiple, smaller images but built with the same tag, and synchronise all images across the repo.
* One ProwJob that builds image, one job that bumps images (we already have that one), no need to add another jobs that break statuses across opened PRs.
* Go build outside of Dockerfile. Only one place to change Go version = all images are built using the same version of Go.

**Comment by Ressetkk** [comment]
What I was looking for is some tooling similar to https://github.com/google/ko. It can build multi arch golang containers without Docker daemon and push them directly to the Registry.

**Comment by Ressetkk** [comment]
I have checked how ko works on paper. It basically checks out all the options in that issue. One of the cons against using ko is that we would have to operate on one .ko.yaml file that contains all configurations for our golang tooling, instead of having it split in separate files. This is something we may consider as external contribution to the project. Othwerwise it looks really promising.

**Comment by dekiel** [comment]
@Ressetkk If we make current setup build all dockerfiles with one prowjob and use some shared makefile we will solve problems you mention, without introducing new tools for only golang images. I'm not convinced we need another separate tool and process for that. With using ko I will have to install it on my workstation to locally build images.

**Comment by Ressetkk** [comment]
@dekiel lets at least evaluate that and make small demo. Using ko seems to be actually a big improvement especially for go-oriented programs, even kyma components, and lets you not care about any of the Dockerfiles, Makefiles and shell scripts - just one simple .ko.yaml that contains all components to be built in parallel without Docker daemon, context and other stuff.

**Comment by tobiscr** [comment]
Will be revisited when defining the new image building service
