### ISSUE TITLE
Update dependencies to fix dependabot security alerts

### ISSUE THREAD

**Issue by ammarlakis** [kyma-project/test-infra#4787]

**Comment by Ressetkk** [comment]
Note that https://github.com/kyma-project/test-infra/pull/4770 is invalid and should not be bumped since it's an indirect nested dependency. This one needs to be omitted.

**Comment by dekiel** [comment]
How we can exclude some libraries/versions from bumping by dependabot?
Can we acknowledge security alerts which are not affecting us or we simple can't solve them?

**Comment by Ressetkk** [comment]
Dependabot has a functionality called [ignore](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#ignore).
