### ISSUE TITLE
[Daily Business] Use usernames required for the communication channel.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#4802]
**Description**

When sending message from any automated process I would like to use a username which is valid for the communication channel I use. This will allow me to use @mentions and send messages to desired user if that's needed. I would like to have one service where I could query about username information.

**Reasons**

At present we use tools which have separate user databases thus use different usernames. Bots are not able to match usernames between different systems.

**Comment by tobiscr** [comment]
Closing caused by data privacy issues and technical limitations caused by discontinued backend services.
