### ISSUE TITLE
Provision own TestGrid instance.

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#4805]
Using transfigure.sh is as for now ill advised and instead of using testgrid.k8s.io we should provision our own TestGrid. The sources are available in https://github.com/GoogleCloudPlatform/testgrid. 

**Reasons**
[Transfigure.sh is deprecated](https://github.com/kubernetes/test-infra/blob/ba99165d9d869b93f15480baff7ef1efb786a1b1/testgrid/cmd/transfigure/README.md). It should not be used anymore for updating the TestGrid in upstream one.

/area prow

**Comment by Sawthis** [comment]
@Ressetkk I don't use it at the moment. I will ask @jose-cortina if it is used for any reports.

**Comment by dekiel** [comment]
We will go back to this topic once we redefine and automate our release process and cleanup not used prowjobs. In our opinion having our own testgrid instance will not require much maintenance and should be possible to keep it running and updated in fully automatic way.
/lifecycle frozen

**Comment by kasiakepka** [comment]
Testgrid instance could be helpful for Jellyfish team as they go through Prow dashboard and try to determine `flaky tests` manually every day. It will be also beneficial for whole Kyma to see unstable tests and pipelines statistics.
