### ISSUE TITLE
Allow release testers attach busola to release cluster.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#4851]
**Description**
Testers of release must have admin rights on a release test cluster. Testers must be able to attach busola to the release cluster.

**Reasons**

There are some differences in users permissions on Kyma cluster which is created directly on gcp. This makes impossible, for users who test new release, to connect busola console to the cluster. It was required to manualny change permissions on a gcp project level. This issues are not present when Kyma cluster is created with Gardener.

**Acceptance Criteria**

Users doesn't need to have Kubernetes Engine Admin and Kubernetes Admin rights granted on gcp project.
Permissions granted on gcp kyma-prow-workloads project for testing purposes of 2.0 release are removed from kyma-prow-workloads gcp project.
Testers can attach busola to the release cluster without other teams intervention.
If required, credentials are delivered to testers by release automation.
Users have admin rights on release cluster to not limit it's abilities.

**Comment by dekiel** [comment]
On release test cluster, testers need permissions granted by `cluster-admin` role. On cluster created by gardener this role is bind to testers by gardener. In turn on gke cluster this is managed with gcp IAM permissions.
Last time the solution was to grant a google group a `Kubernetes Engine Admin`, `Kubernetes Engine Role Binding Manager`, `Kubernetes Engine Cluster Admin` IAM roles. Then `kubectl create clusterrolebinding kyma_developers  --clusterrole cluster-admin     --group kyma_developers@domain.com` was executed on a cluster.
Instead of moving from gke to gardener cluster, we could add step of binding `cluster-admin` role to `kyma_developers` as part of release test cluster creation.

**Comment by dekiel** [comment]
Confirmed with other POs there is no explicit need to go for gardener cluster if we can grant access to the release test cluster to testers in easy way. Access should not require any additional steps from testers in comparison to gardener cluster. We will try to grant access to `gke` cluster as it seems simpler solution.

**Comment by Ressetkk** [comment]
I'll take a look
/assign

**Comment by dekiel** [comment]
@Ressetkk do we have a follow up issue for automated delivery of kubeconfig to testers?

**Comment by Ressetkk** [comment]
@dekiel https://github.com/kyma-project/test-infra/issues/4906
