### ISSUE TITLE
Unique jobs - Follow up

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#487]
This is folow-up for task: https://github.com/kyma-project/test-infra/issues/465
TODO:
- update documentation and all examples
- write tests for `pre-test-infra-buildpack-node-chromium`, `post-test-infra-buildpack-node-chromium`
- update tests for release jobs, now we have hardcoded prefix there:
```
t.Run(currentRelease, func(t *testing.T) {
			jobConfig, err := tester.ReadJobConfig("./../../../../prow/jobs/kyma/components/api-controller/api-controller.yaml")
			// THEN
			require.NoError(t, err)
			actualPresubmit := tester.FindPresubmitJobByName(jobConfig.Presubmits["kyma-project/kyma"], "pre-rel06-kyma-components-api-controller", currentRelease)
```
- we can add new validation step that check if job names are unique:
```

import (
	"fmt"
	"k8s.io/test-infra/prow/config"
)

	c, err := config.Load("...")
	if err != nil {
		panic(err)

	}

	names := map[string]int{}

	for _, v := range c.Presubmits {
		for _, pre := range v {
			n := pre.Name
			curr := names[n]
			names[n] = curr + 1
		}
	}

	for _, v := range c.Postsubmits {
		for _, pre := range v {
			n := pre.Name
			curr := names[n]
			names[n] = curr + 1
		}
	}

	for k, v := range names {
		if v > 1 {
			fmt.Println(k)
		}
	}
```

**Comment by jasiu001** [comment]
| Subtask | PRs |
| -------- | ---- |
| Update documentation | |
|  tests for `pre-test-infra-buildpack-node-chromium` and `post-test-infra-buildpack-node-chromium` | |
| Update tests for release jobs | @jasiu001  |
| Add tests for validation unique jobs name | |
