### ISSUE TITLE
Some release jobs are stored outside of `prow/jobs/kyma/releases/` directory

### ISSUE THREAD

**Issue by halamix2** [kyma-project/test-infra#4876]
**Description**

Prowjobs generated from `generic_component` data templates are generating prowjobs for `main` and previous releases in one output file, making it hard to disable image bumping for previous releases jobs.

**Expected result**

We don't want to bump images used in older release jobs

**Actual result**

All images outside `prow/jobs/kyma/releases/` directory are bumped automatically, and generic component prowjobs for multiple releases are stored in one file. Image bump excludes are file-based.

**Steps to reproduce**

**Troubleshooting**

**Comment by dekiel** [comment]
We are going to enable inrepo config and migrate all prowjobs which run against release branches to inrepo config files. This prowjobs consist of component. With inrepo config enabled this issue will be outdated.

**Comment by dekiel** [comment]
Migration to in repo config will be enabled in #5177.

**Comment by kasiakepka** [comment]
This issue will be addressed when inrepo config is enabled https://github.com/kyma-project/test-infra/issues/5177

**Comment by tobiscr** [comment]
also caused by the arch-change coming with modularisation, this change becomes obsolete.
