### ISSUE TITLE
[Security] Tracking changes in permissions

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#4887]
**Description**

Every time we change a permissions schema, in any system such change should be reflected in an issue. Any change of permissions schema/policy must be reviewed and discussed with the team to confirm changes. If permissions change was introduced as a part of failure or bug fixing it must be reviewed after the issue is fixed. The issue must contain detailed description of changes in policy/schema to make possible reverting introduced changes. Any post change issues for permissions changes must be added to the backlog with highest priority so it's evaluated on next planning. Issues should not be public visible to not reveal possible security holes. They should be put in our team project as a draft issues to keep all tasks in one place.

Can we implement some tool which can detect changes in permissions?
Should we run permissions audit periodically?

**Reasons**

This requirements are meant to secure us from granting excessive permissions and to stick to the best practises about permission levels.

**Comment by tobiscr** [comment]
Will be solved when IAC is implemented to create SAs
