### ISSUE TITLE
Require code reviews and status checks for other branches than master

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#494]
I created PR for the release branch and I was able to merge without approvals and no status checks were required.  Also, I am able to push changes directly to the branch, without creation of PR. 

Affected repos:
- kyma
- test-infra

**Comment by tehcyx** [comment]
Not sure this is still valid, as I tried for kyma repo right now:
https://github.com/kyma-project/kyma/pull/3811

For test-infra indeed, the release branches were not protected like they are on kyma repo. With https://github.com/kyma-project/test-infra/pull/922 I've adjusted this, to be in sync.
