### ISSUE TITLE
Add kyma deprovisioning plan

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/test-infra#495]
We need to learn about and test the kyma uninstallation process. Currently, it is not well tested especially with a longer running cluster and also in regards to alerting. We see that clusters under deprovisioning are sending monitoring alerts.

Idea:
Extend the nightly cluster plan to always uninstall kyma before wiping out the cluster in order to install it from scratch. Here, the uninstallation should be timeboxed to assure that the plan continuous with the more important installation process. After uninstallation the pods left should be compared to the pods before installation assuring that nothing is left. As the nightly cluster is alerting configured we will see if alerting will be not giving false positives in that phase.

**Comment by kasiakepka** [comment]
This issue is still valid.
