### ISSUE TITLE
Remove using `VERSION` file in release pipelines

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#4967]
`VERSION` file is used for pushing installer.yaml to specific bucker using pre-rel*-kyma-artifacts jobs. Additionally 1.x installer was picked by contents of this file. Since 2.0 Kyma can be installed using local charts and Installer is not being built anymore. That means we don't need the file anymore and can possibly run some jobs once the tag is created and pushed to the repo. In CI `BASE_REF` will automatically be set to pushed tag. We can use that.

*Acceptance criteria*
* VERSION file is removed from Kyma repo
* All scripts are rewriteen
* Promotion pipeline works only when tag is pushed/release is made.
* Release jobs install kyma using local sources.

#4799

**Comment by Halamix2** [comment]
Scripts/tools using `VERSION` file:
* ~~`development/github-release.sh`~~
    * unused script
* `prow/scripts/build-kyma-artifacts.sh`
* `prow/scripts/cluster-integration/kyma-gke-release-candidate.sh`
* `prow/scripts/cluster-integration/kyma-integration-gardener-eventing.sh`
    * not used by the script, can be safely removed
* `prow/scripts/cluster-integration/kyma-integration-gardener.sh`
    * not used by the script, can be safely removed
* `prow/scripts/lib/utils.sh`, function`utils::generate_vars_for_build`, used by:
    * `prow/scripts/cluster-integration/kyma-gke-external-registry.sh`
    * `prow/scripts/cluster-integration/kyma-gke-integration.sh`
* `development/tools/cmd/githubrelease/main.go`
    * used by the Github release action

**Comment by Ressetkk** [comment]
We cannot remove the VERSION file usage without completely changing the pipelines. Release integration jobs rely on the artifacts that are generated by kyma-artifacts and after the cut-off we update the release artifacts, also integration scripts name the test clusters based on the contents of the VERSION when running from release branch, so we have to have the information about the upcoming version in somewhere. As we don't push test tags we're not able to retrieve the required information about version.

When we will be working on automations for release process then we should have this issue in mind.

**Comment by dekiel** [comment]
@Ressetkk Could you please describe what does it mean in practice "Release integration jobs rely on the artifacts that are generated by kyma-artifacts and after the cut-off we update the release artifacts"? How this relate to the VERSION file?
What you mean byt test tags "As we don't push test tags we're not able to retrieve the required information about version."? Are those tags which test something?
Maybe the easiest way would be to automate updating of this file. Keep an updated of this file a part of release process.

@Halamix2 For the release purpose we could use an input provided in release issue. One of the input data is a Kyma version to release. If we will not remove a Version file and possibly secure it's changes with tight CODEOWNERS entry, we could validate an input from issue with a VERSION file.

**Comment by Ressetkk** [comment]
@dekiel Current approach works that way: artifacts release job runs on all release branches and updates the Kyma-components.yaml file in the GCP bucket for the *next* release. It allows to install this specific version through kyma cli, on which our current pipelines rely on. It's a legacy approach which was relevant for Kyma 1.x, because you had to have installer image, which was built using this job and stored in GCR. Since we moved to Kyma 2.0 and it's become possible to install kyma from local sources we could drop this requirement and treat all integration jobs on release branches as usual postsubmits jobs and install Kyma using cloned sources from local branch without relying on files pushed to the bucket.

However we need a place of truth. We could use tags and add prowjobs that run when the tag is pushed to the repo. However, you need to assume that pushing the tag would start the releasing. Right now we have a workflow that creates a tag and release. We need to rewrite that one so it accepts input string with version. Doable, but requires to rewrite the workflow and the binary that is working underneath it.

This requires rewriting *all* scripts @Halamix2 listed in the comment above (and possibly a bit more on kyma repo itself). From what I understand there is already an action taken to redesign and improve the pipelines (@kasiakepka please correct me if I'm wrong). Maybe this topic should be also raised there so they know what's going on?

Additionally we plan on working around the automation level for the release process and I assume that will also force us to add or remove some of the jobs that use this script. Hence I believe this one should be taken into account when we start implementing release automations, but after giving it a second thought it should be possible to rewrite before doing heavy redesign.

I can work on that right now, but those will be improvements for current release process and may be removed in the future.

/assign

**Comment by dekiel** [comment]
@Ressetkk for what we need a source of truth? For creating a release tag and release itself only or its needed for something else? If we need this for release only, we can make a jobs independent from VERSION file. The dependency on VERSION file in process of creation release we can remove when we will have agreement of changes in a process.
We know that jobs must be rewritten because they relay on VERSION file. This was an initial assumption for this issue.

Which script you mean?
> Additionally we plan on working around the automation level for the release process and I assume that will also force us to add or remove some of the jobs that use this script.

You didn't answer question about test tags.

**Comment by Ressetkk** [comment]
@dekiel we need VERSION to be stored somewhere, else we will not be able to promote the `kyma-components.yaml` file for use in the installation during the release testing. It can be omitted when we rewrite pipelines to use `kyma install --local` and use local charts inside the job, but IIRC reconciler requires this file to be present on a bucket, so we need to promote it. We could publish artifacts only when the tag is pushed. That's it.

If we need this file on our pipelines then we need to find other state of truth for promoting it, like for example pushing tags between RCs during release testing. Test tags are exactly those.

Additionally GitHub-release job needs some improvements - input field where person is able to write which release is created.

**Comment by dekiel** [comment]
@Ressetkk If I understand correctly, we can remove VERSION file but we need rewrite pipelines. However we need a source of truth so instead a VERSION file we will maintain a tags to know a version to install. Maybe it's better to automate maintaining a VERSION file?

**Comment by Ressetkk** [comment]
@dekiel Exactly. I think removing VERSION file would benefit in the long-term since we remove the need to watch another file and we attach to the release process we will have to use anyway.

**Comment by Ressetkk** [comment]
Since recent discussions about modularity of Kyma which would change the release and effort to close that Issue we've decided to postpone it for the future when more discussion will be made.

/lifecycle frozen
/unassign

**Comment by kasiakepka** [comment]
This issue is not valid due to upcoming changes with Kyma modularisation. The cost of implementing this issue is too big when you compare it to the value it brings.
