### ISSUE TITLE
[CI] Service proposal: Bot to automatically add review guidelines to PRs

### ISSUE THREAD

**Issue by k15r** [kyma-project/test-infra#4979]
**Description**

For all eventing related PRs (either area/eventing, or based on the files modified in the PR) we would like to have a bot add our review guidelines either:
- as a comment to the PR
- as additional description to the description field

**Reasons**

This additional information will guide the review process and make it easier for PR author and PR reviewer to verify completeness of the PR

**Acceptance Criteria**

- [ ] ability to specify and update the additional information in the repository (eg. file in `.github/...`)
- [ ] ability to specify the filter (eg. label, or changed file pattern)
- [ ] reacts to all new and currently open PR as soon as the filter criteria is matched

**Attachments**

**Comment by Ressetkk** [comment]
It's still relevant until we decide on final approach.

/reopen
/remove-lifecycle rotten
/lifecycle frozen

**Comment by kasiakepka** [comment]
I think that Goats would benefit from that feature.

**Comment by Sawthis** [comment]
@k15r Have you checked possibilities of https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository ?
CC: @tobiscr

**Comment by tobiscr** [comment]
Descoping as no further need was requested by other teams. Please implement this feature in your team if needed.
