### ISSUE TITLE
Documentation on kyma-project.io is not generated for releases

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#498]
**Description**

Documentation on kyma-project.io is not generated automatically for releases. Job that triggers generation is triggered before release is created. Such generation should be executed in a job that creates releases or after that job.

**Expected result**

Documentation from releases is visible on kyma-project.io immediately after release creation.

**Actual result**

Documentation is not generated and it needs to be triggered manually.

**Steps to reproduce**

Create a release by Prow.

**Troubleshooting**

**Comment by pkosiec** [comment]
In this task I will split the jobs for updating website and pushing Docker images.

**Comment by pkosiec** [comment]
This task will be resolved in https://github.com/kyma-project/website/issues/282.
