### ISSUE TITLE
Create document with complete inventory of current ProwJobs

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#5017]
We have something similar with https://github.com/kyma-project/test-infra/blob/main/test-inventory-integration.md, but this approach depends heavily on the annotations that are added to the ProwJob. I don't think this should be done that way. Either way, we should have a way that allows to generate the document that contains ENTIRE inventory of ProwJobs grouped by the `org/repo` and `trigger` types. The example file should look as follows:
```md
# kyma-project/kyma
## presubmit
* job1
## postsubmit
* job2
* etc.

# kyma-project/busola
(...)

# periodics
* periodic1
* periodic2
```
Ideally each ProwJob listed here should have a link to the yaml file where it's designed. This inventory should be automatically updated once the ProwJobs get updated. Either using Prow plugin, or with periodic/postsubmit job that generates PR with inventory update, or directly commits changes to main.

With that list it should be possible to maintain updated list of the jobs.

**Comment by dekiel** [comment]
@Ressetkk some quick ideas about avoiding rate limit.

1. Store complete list of prowjobs and update it only when it changes.
   - Updates can be done on postsubmit prowjob when prowjob definition is changed.
   - Storage can be a firebase, a configmap, a file on a bucket, a service local storage on k8s.
2. Use some caching for github queries. ghproxy which we use in prow sound like good candidate.

**Comment by Ressetkk** [comment]
I want to keep the tool compliant with Prow API as much as possible. I can't seem to find the specific function that allows you to fetch all static and dynamic jobs. You can only fetch them per repo. Additionally if you want to have the versioned ProwJobs you need to provide the Base SHA you want to test. 
```go
// RefGetter is used to retrieve a Git Reference. Its purpose is
// to be able to defer calling out to GitHub in the context of
// inrepoconfig to make sure its only done when we actually need
// to have that info.
type RefGetter = func() (string, error)
```
Otherwise you'd be obliged to poll every branch from the repository and load the InRepo ProwJobs. I believe that approach was not designed by Prow.

That's why I was thinking about doing the "search engine" where people would look for ProwJobs on-demand. I mean static jobs (those that are defined in Prow config) would be listed regardless. For ex. an actor wants to list all ProwJobs that would run on `kyma-project/kyma` with annotation `foo: bar` will use query `repo:kyma-project/kyma annotation:foo=bar`. That would show all ProwJobs versioned on default branch and all static ProwJobs running on the default branch.

Static ProwJobs are a no-brainer. There is a ConfigMap on which the tool can manipulate.

**Comment by Ressetkk** [comment]
Leaving this topic open for now, since there are other work to do for now. Feel free to pick it up.
/unassign
/lifecycle frozen
