### ISSUE TITLE
`needs-tws` plugin does not respect some usernames in OWNERS_ALIASES

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#5037]
It happened once when @NHingerl approved PR #5031 and the needs-tws plugin didn't remove `missing-docs-review` label.

```
time="2022-03-01T13:46:53Z" level=info msg="Running git config." args="[gc.auto 0]" client=git
2022-03-01T13:46:53.210Z	debug	Load OWNERS_ALIASES	{"event-type": "pull_request_review", "event-GUID": ""}
2022-03-01T13:46:53.211Z	info	'NHingerl' is not in the group of required reviewers.	{"event-type": "pull_request_review", "event-GUID": ""}
```

Plugin should remove the label once person from *technical-writers* group `OWNERS_ALIASES` file approves a PR.

/kind bug
/area tooling

**Comment by Ressetkk** [comment]
Another occurrence of https://github.com/kyma-project/kyma/pull/13896

**Comment by NHingerl** [comment]
Another occurrence in https://github.com/kyma-project/kyma/pull/13729

**Comment by NHingerl** [comment]
and another one in https://github.com/kyma-project/cli/pull/1243

**Comment by NHingerl** [comment]
...and one in https://github.com/kyma-project/kyma/pull/13987. @kwiatekus manually had to remove the label.

**Comment by NHingerl** [comment]
...and here https://github.com/kyma-project/cli/pull/1249

**Comment by NHingerl** [comment]
...and here https://github.com/kyma-project/test-infra/pull/5303#pullrequestreview-948179195

**Comment by Ressetkk** [comment]
@Halamix2 please also update the tests so they reflect your change

**Comment by NHingerl** [comment]
Thank you @Halamix2 and @Ressetkk for getting this to work :) 

So far, my approval doesn't remove the label, at least not in https://github.com/kyma-project/kyma/pull/13878

**Comment by NHingerl** [comment]
one remnant here: https://github.com/kyma-project/kyma/pull/13329
