### ISSUE TITLE
Enable notifications for the governance-nightly job

### ISSUE THREAD

**Issue by kazydek** [kyma-project/test-infra#505]
**Description**

Could you configure/activate notifications which send information on every failed `governance-nightly` job on Kyma repositories to a proper Slack channel? 

**Reasons**

Failed links need to be monitored and corrected on a regular basis.

**Attachments**

Example: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-governance-nightly/1084616304679194624

**Comment by crabtree** [comment]
Should be done in #466
