### ISSUE TITLE
Error retriggering Jobs via Prow Dashboard

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/test-infra#5118]
**Description**

When try to rerun a Job using the `Rerun`-Button on the Prow Dashboard, we get the following error.
```
Error checking if user can trigger job: GitHub failed to fetch members of team 3108790, verify that you have the correct team number and access token: return code not 2XX: 404 Not Found
```

It happened at least for the following pipelines:
- `pre-main-reconciler-publish-pr-cli`
- `nightly-main-reconciler-publish-unstable-cli`

**Expected result**
Rerunning jobs should work using Prow Dashbaord

**Actual result**
![Screenshot 2022-03-16 at 15 26 54](https://user-images.githubusercontent.com/48282931/158613315-2d44b422-78ea-4190-8518-0a3ef15a2209.png)

**Steps to reproduce**
1. Visit https://status.build.kyma-project.io/?job=pre-main-reconciler-publish-pr-cli
2. Click on Rerun button

**Troubleshooting**

**Comment by Ressetkk** [comment]
I've checked the Prow configuration and everything seems to be correct. Recently there was some problem with GitHub services availability. As for now I haven't noticed any problems regarding the issue you created, and I could rerun the jobs without any problems. @jeremyharisch can you please confirm if it's still current? If not then I'll close this issue.

**Comment by jeremyharisch** [comment]
Re-triggering jobs works again 👍🏻
