### ISSUE TITLE
Create a cron job that will update images used by jobs

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#515]
**Description**

Create a cron job that will be responsible for updating images used by jobs. That job can simply use image used by jobs with `imagePullPolicy ` set to `always`.

**Reasons**

During updating `buildpack-golang` to `go 1.11.4` and `dep 0.5.0` I introduced new tag `go1.11` for that buildpack. If we will use this tag in jobs then it will point to latest buildpack with `go 1.11.*`, but it needs to be updated in Prow.

**Attachments**

**Comment by mszostok** [comment]
One problem - all ProwJobs must have image pull policy set to Always cause tag will be always the same e.g. go1.11 but content under this tag can be different than this already cached on the cluster.
To resolve that issue, in general, you can use the [AlwaysPullImages](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#alwayspullimages) addmision webhook.
> It modifies every new Pod to force the image pull policy to Always.

What's more, this also adds new security protection to ensure that other container will not be able to reuse images already cached on the same Node.

> **NOTE:** We need to check if `imagePullPolicy: Always` is checking the SHA and pulling images only if necessary or if it's pulling images always even if SHA wasn't changed. If it's pulling images always then this approach can slow down our infrastructure.

**Comment by michal-hudy** [comment]
@adamwalach I'm not sure if we still need this, as we are using the fixed version of images, not tags like `go1.14` etc.

**Comment by michal-hudy** [comment]
Ok, I'm closing it
