### ISSUE TITLE
Implement Pipelines: Scenario Kyma 2.2.x to 2.3.x

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/test-infra#5167]
# Description
In the current Test-Pipeline setup we have following _upgrade_ scenarios considered in multiple surroundings:

### Reconciler running as Micro-Service:

- Install Kyma main
- Latest Kyma1 release upgraded to latest Kyma2 release

#### Gardener

- Latest Kyma1 release upgraded to latest Kyma2 release
- Latest Kyma2 release upgraded to main branch of Kyma

#### k3d
- Latest Kyma2 release upgraded to main branch of Kyma

### In SKR Landscape
- Latest Kyma1 release upgraded to latest Kyma2 release on **AWS**

## Pre-/Post-Submit Jobs regarding ControlPlane Repository
- Latest Kyma2 release upgraded to main branch of Kyma

## Pre-/Post-Submit Jobs regarding Reconciler Repository
- 2nd-last release Kyma2 upgraded to latest released Kyma2

------
Due to the changes planed for 2.1.x, I suggest to challenge this setup as described in the following:
- Differentiate between Kyma1.x, Kyma2.0.x, and Kyma2.1.x
- Have specific pipelines in place for upgrade scenarios forom Kyma2.0.x to 2.1.x
- Drop Upgrade Kyma1 to Kyma2 pipelines, or maybe switch to Kyma1 to 2.0.x

**Reasons**
- Kyma2.1.x has major architectural changes, i.e. regarding Istio component
- How long do we support Kyma1
- We should Test upgrades between different Kyma2 versions

**Acceptance Criteria**
- Challenge current setup
- Have new pipelines in place, drop not needed ones
- Document everything in internal Wiki (if you need the link you can as me @jeremyharisch )

**Comment by adityabhatia** [comment]
For **Kyma CLI** **gardener pipelines** `kyma-upgrade-gardener-kyma-to-kyma2` will be renamed to `kyma-upgrade-gardener-kyma2-minor-versions`. This will check previous minor versions, going back from the latest release. The no. of previous minor minor versions to be tested for upgrade can be specified via env variable `PREVIOUS_MINOR_VERSION_COUNT`.
To add, **k3d pipeline** (WIP) to test minor upgrades is optional since there's no pipeline testing kyma1 to kyma2 upgrades at the moment. 

For **SKR Landscape** pipeline `skr-kyma-to-kyma2-upgrade-aws-dev` will be renamed to `skr-aws-upgrade-integration-dev` and is worked on by @hanngos

**Comment by jakobmoellersap** [comment]
As we've implemented the kyma-upgrade-gardener-kyma-to-kyma2 release job I think we can consider this a non-release-blocker anymore @Sawthis ?

**Comment by Sawthis** [comment]
@jakobmoellersap so it tests upgrade from 2.0.4 to 2.1.3 on Gardener now? And it will be able to test upgrade from 2.1.3 to 2.2.0 when it will be released?

**Comment by jakobmoellersap** [comment]
> Changes proposed in this pull request:
> 
> * Previous gardener kyma to kyma2 upgrade pipeline is removed
> * New pipeline introduced to test minor version upgrades on kyma2
> * Previous no. of minor versions to be tested can be specified using env variable PREVIOUS_MINOR_VERSION_COUNT

This means it tests 2.0.4 to 2.1.3 and then 2.1.3 to 2.2.0

**Comment by jakobmoellersap** [comment]
Also relates to https://github.com/kyma-project/kyma/pull/14220 and https://github.com/kyma-project/test-infra/pull/5394

**Comment by jakobmoellersap** [comment]
@hanngos is this solved by now or are there still efforts ongoing?
