### ISSUE TITLE
Clusters for nightly stability checker job should be created in Google project which is accessible by all "Core" Kyma devs

### ISSUE THREAD

**Issue by strekm** [kyma-project/test-infra#519]
Nightly cluster shouldn't be created in kyma-prow project. "Core" Kyma developers sometimes need to have access to such cluster.

AC:
- dev has access to the nightly cluster and can check failing test

**Comment by strekm** [comment]
Follow up after #454

**Comment by aszecowka** [comment]
Solved by PR: https://github.com/kyma-project/test-infra/pull/555/
