### ISSUE TITLE
Possibility to define k8s version for provisioning scripts

### ISSUE THREAD

**Issue by crabtree** [kyma-project/test-infra#520]
**Description**

Provide the possibility to easily specify the k8s version for cluster provisioning purpose.

**Reasons**

Currently, we have k8s version hardcode in scripts responsible for cluster provisioning in multiple repositories (`minikube.sh` in `kyma` repository, `provision-gke-cluster.sh` in `test-infra` repository). It is required to have the possibility to define this in one place. Also after a release, it is hard to find on which k8s version the release was tested. 

A possible solution would be to introduce a file with environment variables in `kyma` repository that can store such parameters.

**Attachments**

**Comment by piotrmsc** [comment]
CC @abbi-gaurav

**Comment by kasiakepka** [comment]
Krystian confirmed that it is not valid
