### ISSUE TITLE
Support permissions for creating VMs & pushing images in one job

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/test-infra#5207]
**Our use case**

We have 2 separate jobs:
* 1st builds the Docker image and pushes **both** commit hash & `:latest` versions to Docker repository
* 2nd one grabs the commit hash one and runs tests on it.

We want to merge it to 1 job, that would
1) build image & push commit hash version
2) test it
3) if tests are OK, push `:latest`

I've tried doing that on https://github.com/kyma-project/test-infra/pull/5184, but failed miserably, because of naming/permission clash - as far as I understood correctly, they both use presets with `GOOGLE_APPLICATION_CREDENTIALS` env name and the job fails when there's a conflict ([example here](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_test-infra/5184/pre-main-test-infra-pjtester/1509091476494094336/build-log.txt)). As seen on [latest build](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_busola/1170/wawrzyn321_test_of_prowjob_pre-busola-build-and-test-docker/1509139994067865600), those permissions are required.

**Possible solution**

After talking to @Halamix2 & @Ressetkk, we though of just renaming that env from `GOOGLE_APPLICATION_CREDENTIALS` to `GCR_PUSH_GOOGLE_APPLICATION_CREDENTIALS`, but it would require **a lot of** changes, which we (as @kyma-project/hasselhoff) shouldn't be responsible for, that's why I'created this feature request.

**Possible workaround for now on**

Make 3 jobs - build & push to tag, test, push to `:latest`, link them with job guards. I guess you won't be happy with that, as you despise jobGuards and want to reduce the total number of jobs.

**Comment by Ressetkk** [comment]
If you need a separate service account for building and pushing it should be OK to do so. Additionally, if you still want to use the current secrets you can manually mount a secret without a preset and set different environment name. `gcp::authenticate` accepts the variable name as the application credentials, it just defaults to the `GOOGLE_APPLICATION_CREDENTIALS` in every script. You can simply override it.

**Comment by dekiel** [comment]
Neighbours doesn't have capacity to work on that. No progress since March from author.
