### ISSUE TITLE
Update the "Prow Installation on Forks" document

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/test-infra#5215]
**Description**

Since [Kubernetes changed the way of configuring Prow](https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#create-the-github-secrets), some sections in the [Prow Installation on Forks](https://github.com/kyma-project/test-infra/blob/main/docs/prow/prow-installation-on-forks.md#configure-the-webhook) document are outdated. [Here](https://github.com/kubernetes/test-infra/commit/7a576f39adefa488b64c9524e43bddece5e3f146) you can see the commit with the recent major change in `kubernetes/test-infra`.  Please update the document in our `test-infra` repository so that it reflects the current Prow configuration.

**Area**

area/documentation

**Reasons**

Kubernetes changed the way of configuring Prow and the current documentation is outdated.

**Assignees**

@kyma-project/technical-writers

**Comment by Ressetkk** [comment]
We'll take a look at that in the team.
/area documentation
/area prow

**Comment by kasiakepka** [comment]
Let's think if wee need to keep such documentation.

**Comment by dekiel** [comment]
We are not going to maintain documentation about installation of Prow on forks.
