### ISSUE TITLE
Clean the EventMesh queues/webhooks after the prowjob execution

### ISSUE THREAD

**Issue by vpaskar** [kyma-project/test-infra#5220]
**Description**

Currently we use our `kyma-tunas-prow `EventMesh` instance for BEB subscriptions in the prowjobs fast-integration tests. There some time might be the cases, when the prowjob fails during the execution and the BEB Subscriptions are not cleaned and hence some queues/webhooks remain orphan.  

We currently have the following quota in our EventMesh prow instance:

```
Resource units allocated to subaccount: 200
Resource units allocated to all message clients: 50
```
If these limits are reached, the eventing prowjob will fail with the following error: `"create subscription failed: 422; 422 Unprocessable Entity;{\"error\":{\"code\":\"UNPROCESSABLE_ENTITY\",\"message\":\"Resource Units allocated are not sufficient\"}}"}}` 

To avoid that we need to clean the orphaned EventMesh resources. Some ideas would be:
- Implement a trap script which will be executed anyhow by the end of the prowjob script. This script will be implemented on the fast-integration part and will require a javascript implementation of the EventMesh client.
- Build a cronjobs, which will clean these resources every specific period of time
- Change the eventing-controller, so it would react on these resource qouta exceeded errors and react in a different way

**Comment by k15r** [comment]
> Implement a trap script which will be executed anyhow by the end of the prowjob script. This script will be implemented on the fast-integration part and will require a javascript implementation of the EventMesh client.

in case the job gets killed, the trap will not work. Imho we need to build a cleanup job

**Comment by k15r** [comment]
> Change the eventing-controller, so it would react on these resource quota exceeded errors and react in a different way. 
I like the idea, unfortunately i do not know how it should behave differently

**Comment by VladislavPaskar** [comment]
> > Change the eventing-controller, so it would react on these resource quota exceeded errors and react in a different way.
> 
> I like the idea, unfortunately i do not know how it should behave differently

The idea was to handle this type of issue on the eventing controller side. So if we face error like this (EventMesh is full), we could instead of implementing a cronjob or a periodical job implement the cleanup scenario in the controller.

**Comment by nachtmaar** [comment]
I wrote a small app to remove old EMS Subscriptions, code is not polished but works: https://github.tools.sap/skydivingtunas/ems_janitor

Only thing I saw is that even if Subscriptions are deleted (using the CE API), there are still a lot of Queues left. We might need to implement queue deletion as well.

**Comment by mfaizanse** [comment]
We can start with cronjobs, to have atleast some automatic cleanup. Later we can make it react to events or after every job run.
