### ISSUE TITLE
Investigate usage of GitHub App for Prow integration

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#5228]
Recently Prow creators changed the recommendation on how the Prow should be created. They suggested that instead of using webhook token directly added to the repo, they suggested to create a GitHub App and connect Prow into it. 

The commit with changes: https://github.com/kubernetes/test-infra/commit/7a576f39adefa488b64c9524e43bddece5e3f146

This approach should be investigated since it improves the scaleability of Prow across the organisation, remove the requirement of setting up every repo, and mark the Prow as full-fledged bot user, removing the need of Kyma-bot.

* [ ] Check if the previous automations would work
* [ ] Check if the app can create PRs (auto bumper)
* [ ] Test Tide and other Prow integrations with the GitHub App
* [ ] Write the investigation results and decide about the actual migration
/area prow
/kind feature

**Comment by dekiel** [comment]
What does it mean "remove the requirement of setting up every repo" for us? When we create new repo it will be automatically configured and added to Prow? Based on what settings this will be done? How this will be different from webhook set on org level?
How we can use this improvement? "improves the scaleability of Prow across the organisation"
How we can leverage that Prow will be connected to bot user instead a regular user?

**Comment by Ressetkk** [comment]
@dekiel you'd have a single application that could be configured only once and then you could "Install" it without any additional requirements, like setting up Webhook on organisation level and maintaining the HMAC token across multiple orgs/repos If it needs to be regenerated. Additionally you don't need to operate on personal access tokens for the bot, so you don't really care about keeping track on a password for that account if you want to introduce some automations, like automatic bumps.

I've created this issue since the default approach of configuring Prow has changed. We can leave it as-is, but I think we should keep track on changes that occur upstream and adapt to them.

**Comment by dekiel** [comment]
@Ressetkk 
> so you don't really care about keeping track on a password for that account if you want to introduce some automations, like automatic bumps.

But you still have to authenticate your automation to github. How this will be different from current setup?

**Comment by Ressetkk** [comment]
@dekiel Good question. I'm not quite sure how it works with dependabot, but I assume it would work in a similar way. This is something worth checking out. 

Regardless the internal ProwJobs and their workings, this would change how Prow is defined in GitHub - instead of regular user used with PAT and owner rights to the org/repo plus Webhook client that validates events based on token in header, you have an application instance with precisely defined set of permissions and keys rolled out by GitHub itself. This looks more secure.
