### ISSUE TITLE
Add  retry operation to gardener shoot cluster provisioning for reconciler tests 

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/test-infra#5229]
**Description**

We see flakiness of integration tests related to gardener shoot provisioning, i.e [here](https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main/1511614790609408000/build-log.txt)

There are differences in how provisioning is realised in different tests.
It makes totally sense to use single pattern and fix problems in one place.

**Reasons**

We should harmonise the way how we provision gardener clusters in integration tests
We should decrease flakiness of tests related to gardener shoot provisioning failures

**Proposed solution**

Use gardener provisioning script that includes a retry logic
https://github.com/kyma-project/test-infra/blob/a44cadce5b7a41e776edea08fb646cb543780e1b/prow/scripts/lib/gardener/gcp.sh#L91

**Comment by kwiatekus** [comment]
`gardener::provision_cluster` provisions shoot cluster for kyma runtime via kyma CLI
`reconciler::provision_cluster` provisions shoot cluster for reconciler using a dedicated template spec.

Those are indeed different cases

**Comment by dekiel** [comment]
Example failure from description already use a retry logic.
I don't know what exactly is executed after installation of unstable CLI. It might be that unstable cli doesn't support retry logic and fail whole pipeline execution. It is executing some actions in parallel with Gardener cluster provisioning. 

Just after starting docker unstable Kyma CLI is installed.
```
2022/04/06 08:00:40 UTC [INFO] ### Install latest unstable Kyma CLI
/tmp/bin /home/prow/go/src/github.com/kyma-project/kyma
--> Install kyma CLI (unstable version) linux locally to /tmp/bin
{"level":"INFO","time":"2022-04-06T08:00:42.786Z","message":"Initializing component reconciler 'busola-migrator'"}
--> Kyma CLI (unstable) version: Kyma CLI version: main-90a8a66
OK
/home/prow/go/src/github.com/kyma-project/kyma
```

Next Gardener cluster provisioning is triggered. This attempt fail.

```
2022/04/06 08:00:42 UTC [INFO] ### Provisioning Gardener cluster
2022/04/06 08:00:42 UTC [INFO] Provision cluster: "grdzkyi49"
{"level":"INFO","time":"2022-04-06T08:00:42.827Z","message":"Initializing component reconciler 'busola-migrator'"}
- Validating flags
X Provisioning Gardener(Azure) cluster
Error: unable to provision gardener cluster: shoots.core.gardener.cloud "grdzkyi49" already exists
```
A retry logic jumps in and try to provision new cluster.
```
2022/04/06 08:30:43 UTC [INFO] cluster provisioning failed, trying provision new cluster
2022/04/06 08:30:43 UTC [INFO] cleaning damaged cluster first
2022/04/06 08:30:43 UTC [INFO] Deprovision cluster: grdzkyi49
shoot.core.gardener.cloud/grdzkyi49 annotated
shoot.core.gardener.cloud "grdzkyi49" deleted
2022/04/06 08:30:43 UTC [INFO] building new cluster name
```
But this is interrupted by some failure and pipeline cleanup trap is executed.
```
2022/04/06 08:30:43 UTC [ERROR] AN ERROR OCCURED! Take a look at preceding log entries.
2022/04/06 08:30:43 UTC [INFO] Cleanup
```

What this messages about initializing busola-migrator means? Why they are executed before cluster is ready? Where they are initialized?

```
--> Install kyma CLI (unstable version) linux locally to /tmp/bin
{"level":"INFO","time":"2022-04-06T08:00:42.786Z","message":"Initializing component reconciler 'busola-migrator'"}
--> Kyma CLI (unstable) version: Kyma CLI version: main-90a8a66
```
and
```
2022/04/06 08:00:42 UTC [INFO] Provision cluster: "grdzkyi49"
{"level":"INFO","time":"2022-04-06T08:00:42.827Z","message":"Initializing component reconciler 'busola-migrator'"}
- Validating flags
```

I did check another run of this pipeline which pass cluster provisioning phase and messages about initilizing componenets possibly from CLI looks different.

```
--> Install kyma CLI (unstable version) linux locally to /tmp/bin
{"level":"INFO","time":"2022-04-06T16:00:41.574Z","message":"Initializing component reconciler 'busola-migrator'"}
{"level":"INFO","time":"2022-04-06T16:00:41.574Z","message":"Initializing component reconciler 'cluster-essentials'"}
--> Kyma CLI (unstable) version: Kyma CLI version: main-164ca62
```

**Comment by kwiatekus** [comment]
This was done. 
Provisioning shoot clusters for kyma already had a built in retry operation - see [here](https://github.com/kyma-project/test-infra/blob/a44cadce5b7a41e776edea08fb646cb543780e1b/prow/scripts/lib/gardener/gcp.sh#L91)
Retry for shoot creation for reconciler itself was added by https://github.com/kyma-project/test-infra/pull/5230

**Comment by dekiel** [comment]
Retry logic for cluster provisioning was failing, because script using this logic had `set -o pipefail`. With this bash option enabled retry logic was failing [here](https://github.com/kyma-project/test-infra/blob/bbc80f6c3833c179913899e3d3f0847e0f051083/prow/scripts/lib/utils.sh#L639). Fix was implemented in https://github.com/kyma-project/test-infra/pull/5287/files. It simply disable `pipefail` bash option in `gardener::reprovision_cluster` function and enable it before return from function, if it was enabled when entering in to the function.

Confirmation this fix works in [lines 256-372](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main/1518953279596269568).
