### ISSUE TITLE
[Security] Remove access to kyma-bot token.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#5239]
**Description**

Kyma-bot is one of few accounts with write access to repository. It's used in automation and some decisions are made based on user identity. We have to make sure, kyma-bot tokens are secured and not accessible for other users.

**Reasons**
It's possible that kyma-bot token is used in pipelines. Acces to Kyma-bot token should be controlled.

**Acceptance Criteria**

- [x] Kyma-bot token is not used in pipelines not related to automation.
- [x] Access to token over k8s api is secured. This can be done by applying k8s RBACs.
- [x] Mounting token in pods is secured. This can be done by applying opa gatekeeper constraints.

**Comment by tobiscr** [comment]
Relates to #7285

**Comment by tobiscr** [comment]
Should be covered as part of the OPA-Gatekeeper configuration.

**Comment by dekiel** [comment]
We will define constraints for following tokens.
prow-trusted-workloads
- [ ] kyma-bot-github-token @halamix2 
- [ ] kyma-autobump-bot-github-token
- [ ] kyma-bot-github-sap-token
- [ ] kyma-bot-triage-token
- [ ] kyma-guard-bot-github-token

**Comment by dekiel** [comment]
We need to secure access to these secrets over k8s API by applying respective RBACs.
- [ ] kyma-bot-github-token
- [ ] kyma-autobump-bot-github-token
- [ ] kyma-bot-github-sap-token
- [ ] kyma-bot-triage-token
- [ ] kyma-guard-bot-github-token

**Comment by dekiel** [comment]
Kyma-guard-bot-github-token is used in many different prowjobs. It's not feasible to list and maintain all allowed usages. Bot has only read access to the organisation and token itself has tailored scopes assigned.
