### ISSUE TITLE
Provide buildpack images for ARM64 architecture

### ISSUE THREAD

**Issue by 0xE282B0** [kyma-project/test-infra#5246]
**Description**
The buildpack images are only available for `linux/amd64` architecture. It would be great to have them for `linux/arm64` as well.

**Reasons**
Developers who want to use the buildpacks on arm64 architecture wouldn't need to build them locally.

**Acceptance Criteria**

- [ ] Images Published on GCR.io
- [ ] No waring when building for example [`kyma-environment-broker`](https://github.com/kyma-project/control-plane/tree/main/components/kyma-environment-broker): `WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

**Attachments**

**Comment by Ressetkk** [comment]
I wanted to look at that topic and had some ideas on how to resolve the problem globally. One of ideas was to leverage https://github.com/google/ko to build all OCI images. Since most of Kyma's tooling made with Go this seems to be like good idea to use this. More information you can find in https://github.com/kyma-project/test-infra/issues/4755.

If you are interested in the topic you can evaluate ko with some of the information in the Issue I linked.

**Comment by 0xE282B0** [comment]
Sure, sounds interesting.
I tried to build the KEB (Kyma Environment Broker) with `ko`. Building images works fine and cross platform builds are working too. The only problem is tagging images. In `ko` you can only specify the registry and the tags, but not the image name. The image name is either the name of the go file with a MD5 (e.g. `main.go-08e7b36e175c0ee59eb69137d7e03717`) as postfix or the basepath of the go file (e.g. `/cmd/broker/main.go`). 

Another thing is that `ko` is only for building images and not for running `go test`. That means in contrast to running `go test` and `go build` in the buildpack container we would use the locally installed go version, right?

**Comment by Ressetkk** [comment]
@0xE282B0 thank you very much for evaluating that!
As for the naming - you can try to use `.ko.yaml` configuration file. I'm sure it allows you building the image and renaming them using the actual name. I can point you to the practical example and the documentation on the ko website.

As for the building images... Ideally you want to have your images build as a separate job. `go test` can work as a separate job which will block if the code is broken. I see no problem with that. you don't need to push images when you work on a PR unless you want to have an image for manual tests.

The convenience of ko is that it allows you to use locally installed version of Go for concurrent building multiple images without relying on Docker, Dockerfiles, Makefiles or any other tooling, effectively replacing the buildpack pipelines.

**Comment by dekiel** [comment]
@Ressetkk does kaniko or gcb based building soultion solve this issue?

**Comment by Ressetkk** [comment]
Not quite. Though kaniko should support building images for different architectures, I haven't  research on that topic yet.
We can work on that in the follow-ups

**Comment by dekiel** [comment]
@Ressetkk Please take care of stale label otherwise, close the issue.

**Comment by tobiscr** [comment]
hi @0xE282B0, we added the support for ARM1 images in our copy-sync mechanism. In theory, Kyma should now work as expect on ARM architecture. Can you please confirm, that this issue is solved on your side as well? Thank you very much

**Comment by tobiscr** [comment]
Please reopen the issue if the problem still exists. Many thanks!
