### ISSUE TITLE
pre-master-kyma-gke-integration fails on DNS entry creations

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/test-infra#525]
**Description**

GKE integration jobs on pull requests to Kyma/master fail on DNS entry creation step.
Sometimes it's for Ingress DNS entry, sometimes for Remote Environments DNS entry.

Jobs affected: pre-master-kyma-gke-integration, pre-master-kyma-gke-upgrade.

Behavior is not deterministic, sometimes /rerun on PR helps.

Example PRs: https://github.com/kyma-project/kyma/pull/2357, https://github.com/kyma-project/kyma/pull/2327

**Expected result**

It works

**Actual result**

Log entry:
```
78 | #################################################################################################
-- | --
79 | # Create DNS Record for Remote Environments IP
80 | #################################################################################################
81 |  
82 | Mon Jan 21 13:03:57 UTC 2019
83 | Transaction started [transaction.yaml].
84 | Record addition appended to transaction at [transaction.yaml].
85 | ERROR: (gcloud.dns.record-sets.transaction.execute) HTTPError 412: Precondition not met for 'entity.change.deletions[0]'
86 | Aborted transaction [transaction.yaml].
```

PR logs: 

https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/2327/pre-master-kyma-gke-upgrade/1087333519492911106
```
78 | #################################################################################################
-- | --
79 | # Create DNS Record for Remote Environments IP
80 | #################################################################################################
81 |  
82 | Mon Jan 21 13:03:57 UTC 2019
83 | Transaction started [transaction.yaml].
84 | Record addition appended to transaction at [transaction.yaml].
85 | ERROR: (gcloud.dns.record-sets.transaction.execute) HTTPError 412: Precondition not met for 'entity.change.deletions[0]'
86 | Aborted transaction [transaction.yaml].
87 |  
88 | #################################################################################################
89 | # AN ERROR OCCURED! Take a look at preceding log entries.
90 | #################################################################################################
91 |  
```

https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/2357/pre-master-kyma-gke-integration/1087333140646596612
```
93 | #################################################################################################
-- | --
94 | # Create DNS Record for Ingressgateway IP
95 | #################################################################################################
96 |  
97 | Mon Jan 21 12:57:09 UTC 2019
98 | Transaction started [transaction.yaml].
99 | Record addition appended to transaction at [transaction.yaml].
100 | ERROR: (gcloud.dns.record-sets.transaction.execute) HTTPError 412: Precondition not met for 'entity.change.deletions[0]'
101 | Aborted transaction [transaction.yaml].
```

**Comment by mszostok** [comment]
Found problem: We are using a transaction for adding a new DNS record for given **ZONE**. In both GKE plans we are using the same **ZONE** and _gcloud_ does not support concurrent transaction in the same time in the same zone. Underthehood the Changes API is used, more info [here](https://stackoverflow.com/a/41916215).

This problem may have occurred even before the *pre-master-kyma-gke-upgrade* job introduction. Just run two PR at the same time. 

[This PR](https://github.com/kyma-project/test-infra/pull/526) fixes this problem by adding retries.
