### ISSUE TITLE
[Daily Business] Cleanup servless-fct-repo when discontinuing tools-Kyma instance

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#5283]
**Description**

We moved all serverless functions code running on production tooling kyma to separate git repository.

After discontinuing the Kyma tools instance, we have to cleanup this repository: https://github.com/kyma-test-infra-dev/tooling-serverless-functions 

**Reasons**

Cleanup obosolete repos after discontinuing Kyma tools instance.

**Comment by Halamix2** [comment]
The functions were copied to https://github.com/kyma-test-infra-dev/tooling-serverless-functions, and value files adjusted.

**Comment by dekiel** [comment]
Once new git controller for serverless implementation will be available we should move kyma functions back to kyma-project/test-infra repository.

New git controller for serverless implementation: https://github.com/kyma-project/kyma/issues/13545

**Comment by dekiel** [comment]
@kwiatekus can we move functions code back to test-infra repo?

**Comment by dekiel** [comment]
@Halamix2 I've got confirmation we can move functions back.

**Comment by Halamix2** [comment]
That will require
* update in the test-infra to point to the test-infra again
* reprovisioning controller and all functions on two Kyma tooling (prod/dev) clusters
* removal of the separate functions repository

**Comment by dekiel** [comment]
@tobiscr at present tooling kyma runs functions for sending messages to slack. This can be easily implemented as cloud run service on gcp. If there is no more need to run internal kyma instance we could move to gcp and clean tooling kyma instance and this separate repo with functions code.

**Comment by tobiscr** [comment]
@dekiel : Is this refactoring still required? As we agreed to discontinze the tooling Kyma instance (at least for our CI/CD purposes), I assume we will move this to GCP Cloud Run functions.

**Comment by dekiel** [comment]
Not needed. We need to clean this additional repo once we migrate out of tooling kyma.

**Comment by tobiscr** [comment]
Ok, thx for the update. I adjusted the headline and description to cleanup the repo after we discontinued the Tools  Kyma instance

**Comment by halamix2** [comment]
The repository is no longer needed and was removed
Test-infra counterpart will be removed in https://github.com/kyma-project/test-infra/pull/8695
