### ISSUE TITLE
Improvements to GitHub Projects (beta)

### ISSUE THREAD

**Issue by Disper** [kyma-project/test-infra#5294]
**Description**
After write access to `kyma-project/kyma` was revoked due to implementation of https://github.com/kyma-project/community/issues/613, `GitHub projects (beta)` boards became much less useful. 

**Reasons**
- GitHub Projects (beta) UI is a convenient tool to be used to navigate and edit issues that's no longer usable in a same way since write access has been revoked. 
- Fields edited via GitHub projects are autocompleted and you don't need to spend time in searching e.g. for the right label name.

**Acceptance Criteria**
- [ ] User is able to change **assignees** from project's list-view
- [ ] User is able to change **labels** from project's list-view
- [ ] User is able to change **milestones** from project's list-view
- [x] User should still be able to change any **custom field** that was added for the board from project's list-view
- [ ] All above should work for both **Issues** and **Drafts**

**Comment by kasiakepka** [comment]
Closing due to https://github.com/kyma-project/test-infra/issues/5492
