### ISSUE TITLE
Improvements to the kyma-bot

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/test-infra#5295]
Once the issue is created, kyma-bot should immediately write a message with link to help page (like it does now when I enter wrong label). 

Acceptance criteria:

- [ ] Kyma-bot writes a comment with help right after issue is created.

**Comment by Ressetkk** [comment]
@arturskorupa can you describe more about which help page you are talking about? Every comment from @kyma-bot has a "Details" section which should contain basic information about how to interact with the automation. This template should be easily editable.

**Comment by arturskorupa** [comment]
I mean when one creates an issue, kyma bot should immediately add a comment by itself with details link. As a new user I may not know how to manage the ticket I just created, given I was revoked write access rights.

Note this is only relevant to the situation when we revoke write rights.
