### ISSUE TITLE
Adjust the Links on Prow Responses

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/test-infra#53]
**Description**

Currently, Prow responds with the comments pointing to kubernetes/test-infra repository. We should investigate how we can change this.

<img width="713" alt="screenshot 2018-10-24 at 08 30 04" src="https://user-images.githubusercontent.com/476407/47410777-25c3ea80-d767-11e8-87ab-d7e36617736b.png">

**Comment by suleymanakbas91** [comment]
This message is hard-coded in Prow, so we can't configure it. I'll create an issue in kubernetes/test-infra to address this.

**Comment by kasiakepka** [comment]
Updated https://github.com/kubernetes/test-infra/issues/10138
