### ISSUE TITLE
Clenaup after rollback of prow approval flow plugin

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#5315]
**Description**

Disable unused plugins. #5316 
Remove unused labels.
Revert changes in documentation.
Remove unused external plugin need-tws.
~~Remove Triage GitHub team.~~
Remove OWNERS and OWNERS_ALIASES files.

Parent: #5312

**Comment by dekiel** [comment]
Triage group removed from cli and third-party-images repositories. No Triage group in test-infra and compass repository.

Triage group left to remove on kyma repository.

**Comment by dekiel** [comment]
Triage group removed.
OWNERS files removed in repos cli, kyma, test-infra, third-party-images

**Comment by dekiel** [comment]
@Ressetkk is there anything not cleaned yet? Can we close this issue?

**Comment by Ressetkk** [comment]
We need to move compass to old flow. It's tracked in other issue. Let's close this one as kyma-project is already cleaned up.

/close
