### ISSUE TITLE
Restore write access and revert Prow approval flow for compass repository

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#5322]
**Description**

Rollback plan.
1. Migrate content of OWNERS files to CODEOWNERS. https://github.com/kyma-incubator/compass/pull/2325
2. Restore write access for all teams and organisation members.
3. Remove approve and blunderbuss plugins for repository from test-infra/prow/plugins.yaml file. #5321 
5. Enable required reviews from codeowners in test-infra/prow/config.yaml. #5321 
6. Move repository to Tide query requiring GitHub approval in test-infra/prow/config.yaml. #5321 

Parent: #5312

**Comment by dekiel** [comment]
@Ressetkk  Compass team already established some process around automated labeling and multi team approvals provided by Prow approval flow. We need to check if we can provide some solution which will prevent workaround of PR review and keep current team process.

**Comment by dekiel** [comment]
Revert on compass repository is put on hold till we will agree with the team on suitable solution to meet their new process requirements.

**Comment by Ressetkk** [comment]
We came with an agreement. Clean up is done.

/clone
