### ISSUE TITLE
Investigate tooling for code scanning

### ISSUE THREAD

**Issue by crabtree** [kyma-project/test-infra#538]
**Description**

Perform investigation on possible tooling for code scan, code checks, and security scanning to integrate with our pipelines.

**Reasons**

Our release process requires performing code scan and code checks.

**Attachments**

**Comment by crabtree** [comment]
Consider using https://github.com/securego/gosec

**Comment by derberg** [comment]
How about https://app.fossa.io

**Comment by derberg** [comment]
and Docker or Kubernetes rely on Fossa. Kubernetes example https://github.com/kubernetes/org/issues/164

**Comment by derberg** [comment]
My summary recommendation:

1. Licence check -> we use https://app.fossa.io and do not require check on PR but do a kind of review periodically and resolve issues if needed. A group of people will need to have access to it to be able to resolve issues that do not have to be fixed on our side, so they no longer pop-up
2. Security -> I suggest https://bolt.whitesourcesoftware.com/github/  that looks super cool, we can integrate it and check what issues it creates. Then, once we are free from security issues we should enable it as a PR check

**Comment by piotrmsc** [comment]
All the checks can be triggered once per week. Does not need to be part of release job. Recommended by @meeque
