### ISSUE TITLE
[Istio] test pipeline for istio prod profile

### ISSUE THREAD

**Issue by strekm** [kyma-project/test-infra#5412]
**Description**

Create pipeline triggered by changes in istio or istio-resources kyma components. Pipeline should provision k3d cluster, install partially kyma (kyma pre-reqs + istio-res) from branch and execute Istio component tests. Production profile should be used to kyma installation. Script should be implemented in a way that can be reused for [Istio on eval pipeline](https://github.com/kyma-project/test-infra/issues/5411).

**Acceptance Criteria**

- [x] pipeline implemented and execution is green
- [x] pipeline is triggered on istio or istio-res kyma component changes 
- [x] Istio installed on production profile
- [x] Istio component tests executed

**Attachments**

part of: https://github.com/kyma-project/kyma/issues/13517

**Comment by barchw** [comment]
https://github.com/kyma-project/test-infra/pull/5482
