### ISSUE TITLE
Release issue templates requirements.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#5427]
**Description**

Release issue will be used as an interface to release process. It will carry release status, updates about progress, aggregate related activities and provide commands to interact with release automation. Creation of release issue will start release process. We will use issue form to create issue. Using issue form allow us to define which input is required and its values.
Issue forms are available in github.com only.

An issue form/template can contain special markers which will be replaced with provided values by automation just after issue creation. For example a type and version of release in title can be set based on values from version dropdown and hotfix checkbox fields.

Release issue initial content requirements.
- We distinguish three types of releases, major/minor, patch and hotfix. Type of release must be present in title and body.
- Kyma version to release. Version must be present in title and body.

Example issue form definition: https://github.com/kyma-test-infra-dev/kyma/blob/master/.github/ISSUE_TEMPLATE/release_issue_example.yaml
Example release issue created from a form: https://github.com/kyma-test-infra-dev/kyma/issues/3057

Epic: #5407

**Comment by Sawthis** [comment]
@dekiel I think it should be closed as we will have different requirements for micro deliveries approach.

**Comment by dekiel** [comment]
We decide to not invest in improvements of current Kyma release process.
