### ISSUE TITLE
[Cost Saving] Educate team in QA SIG call: How to remove SSH Connection from Provisioning Scripts and rely on native API-Server Forward

### ISSUE THREAD

**Issue by jakobmoellerdev** [kyma-project/test-infra#5442]
**Description**

The following scripts are using SSH based on gcloud to connect and execute code via copied-over scripts:

- provision-vm-and-start-busola-docker.sh
- provision-vm-and-start-busola-k3s.sh
- provision-vm-and-start-busola-lighthouse.sh
- provision-vm-and-start-kyma-k3d.sh
- provision-vm-and-start-kyma-minikube.sh
- provision-vm-and-start-kyma-upgrade-k3d.sh
- provision-vm-and-start-reconciler-component-integration-k3d.sh
- provision-vm-and-start-reconciler-k3d.sh
- provision-vm-and-start-serverless-k3s.sh
- provision-vm-and-test-reconciler-with-cli-k3d.sh
- provision-vm-cli.sh
- provision-vm-compass.sh
- provision-vm-control-plane.sh

These scripts could be optimized for further use by rewriting the provisioning to expose api-server ports and delivering the kubeconfig.

**Reasons**

That way we could connect remotely via kubectl / kyma-cli and rely on the native HTTP retries for operations instead of regularly receiving the [ssh broken pipe issue](https://github.com/kyma-project/kyma/issues/13968) which did not get fully fixed and is still a major cause for flakiness. Together with the efforts listed in https://github.com/kyma-project/kyma/issues/13855 this should get rid of most of the remaining flakiness

**Acceptance Criteria**

- [ ] Clarify with @TorstenD-SAP whether some security concerns exist
- [ ] All provisioning scripts do not connect via ssh and copy over scripts but instead only retrieve credentials and open necessary ports to bootstrap the deployment via kubectl / kyma-cli.

**Attachments**

**Comment by medmes** [comment]
Hi @jakobmoellersap Does `rsync` will not be useful for this case?

**Comment by jakobmoellersap** [comment]
Removed failing test as it is not hard blocking any tests and it is only about improving testability not actually unblocking anything

**Comment by jakobmoellersap** [comment]
if you get it to work without scp through rsync that will be accepted however maybe not worth replacing due to the effort required.

**Comment by Ressetkk** [comment]
I would rather go with finding a way to expose K8s ports on k3d VMs. It's more of infra task than code.

**Comment by Halamix2** [comment]
These scripts doesn't create k8s cluster inside the VM:
* provision-vm-and-start-busola-docker.sh

**Comment by Halamix2** [comment]
Analysis of all mentioned scripts:
- scripts that doesn't create clusters
    - provision-vm-and-start-busola-docker.sh
        - connects to existing Gardener Kyma cluster and runs Cypress tests
- uses scripts from archived `local-kyma` repository
    - provision-vm-and-start-busola-lighthouse.sh
    - provision-vm-and-start-busola-k3s.sh
- uses `kyma provision k3d`
    - provision-vm-and-start-kyma-k3d.sh
    - provision-vm-and-start-kyma-upgrade-k3d.sh
    - provision-vm-and-start-reconciler-component-integration-k3d.sh
    - provision-vm-and-start-reconciler-k3d.sh
    - provision-vm-and-start-serverless-k3s.sh
- uses `kyma::provision_k3d` function (`kyma provision k3d` but requires to copy over test-infra scripts)
    - provision-vm-and-test-reconciler-with-cli-k3d.sh
- uses `kyma provision minikube`
    - provision-vm-and-start-kyma-minikube.sh
    - provision-vm-cli.sh
- scripts with complex flow
    - provision-vm-compass.sh
        - uses ` kyma provision minikube` through `compass/installation/scripts/prow/deploy-and-test.sh` script from `compass` erpository
    - provision-vm-control-plane.sh
        - uses ` kyma provision minikube` through `control-plane/installation/scripts/prow/deploy-and-test.sh` script from `control-plane` erpository

It should be able to copy `~/.kube/config` file from the VM to the host and setting up ports to allow kubectl to access the cluster.

**Comment by Ressetkk** [comment]
In the long run, we want to run step of creating VM with k3s/k3d cluster using Terraform/Pulumi. That should ultimately resolve and deprecate all unnecessary scripts.

**Comment by Ressetkk** [comment]
After some investigation and trial-and-error we managed to provision K3d cluster with exposed its apiserver ports. The cluster is provisioned on virtual machine with using command
```
k3d cluster create test --api-port 6443 --port 80:80@loadbalancer --port 443:443@loadbalancer --port 32000-32767:32000-32767@loadbalancer --k3s-arg "--tls-san=[IP_ADDRESS]@servers:*"
```
This command creates k3d cluster with exposed apiserver port 6443, exposed ports 80, 443 and range 32000-32767 for NodePort workloads. Additionally command `--k3s-arg "--tls-san=[IP_ADDRESS]@servers:*"` adds Subject Alternative Name for K3s to recognise. When kubeconfig is extracted field `.clusters[0].cluster.server` defaults to `server: https://0.0.0.0:6443` - when we change this to `http://[IP_ADDRESS]:6443` and use that kubeconfig in external workload we are possible to use that cluster without any problems.

Things to make sure:
* We have to make sure Prow clusters have access to those IP addresses.
* We need to have save extraction of kubeconfig, possibly with only one SSH connection.

**Comment by Halamix2** [comment]
I have opened a PR (#5599), which is currently blocked by https://github.com/kyma-project/cli/issues/1291
The script:

* creates a VM, provisions k3d cluster on the VM (using `kyma provision k3d` command through SSH), and exports kubeconfig file to the prowjob
* In the prowjob we're trying to provision Kyma (using `kyma deploy` command), but it fails, as it expects the k3d cluster to be on the same machine as the executed command

cc: @clebs

**Comment by Ressetkk** [comment]
@clebs any news on this issue? I see that issue on the CLI repo has no updates...
/remove-lifecycle stale

**Comment by clebs** [comment]
Hi @Ressetkk,

unfortunately I haven't had time to look into this. There is no straightforward fix for this issue and it requires investigation around the coreDNS patching currently implemented.

We are aware that it causes flakiness on the pipelines and we will try to move it up as soon as possible.

**Comment by tobiscr** [comment]
As we are going to move the pipeline responsibility to our development teams, I would see this investment on the teams side in the feature.

We will educate them in one of the coming SIG quality calls to avoid SSH calls to remote VMs and use instead the worker node itself (either the used agent VM or the executing pod) for spinning up a K8s cluster.

**Comment by medmes** [comment]
I think it make sense to spread the awareness across all teams to not use or implement ssh connection to VMs.

**Comment by Ressetkk** [comment]
Since the scope had changed, and we decided to provide devs a way to provide small k3d cluster inside Prow workload, I'll prepare small documentation for that.

/remove-kind flake
/kind feature
/area ci
/area documentation

**Comment by Ressetkk** [comment]
Docu is merged. https://github.com/kyma-project/test-infra/blob/main/docs/prow/k3d-no-ssh.md

**Comment by Ressetkk** [comment]
Docu is merged, sessions have been made so I believe it's safe to close

/close
