### ISSUE TITLE
Automatic reporting for failing tests

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5475]
### Why?
Currently there is no easy way to determine which pipelines are failing frequently. Jellyfish team goes through Prow dashboard and tries to determine flaky tests/pipelines manually every day. It will be also beneficial for whole Kyma to see unstable tests and pipelines statistics.
Example list of manually created tickets: https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3Akyma-project+label%3Akind%2Ffailing-test

### To do:
1. Create Github issue for pipelines that fail frequently.
AC:
  - [ ] Determine the best criteria for raising issues (reason of a failure, failure rate)
  - [ ] Create issue in the respective repository (kyma-project/kyma , kyma-project/busola)
  - [ ] Do not duplicate issues
  - [ ] Apply necessary labels `kind/failing-test`

### To be considered
2. Create common dashboard to display test results and test statistics.
Example Testgrid instance: https://testgrid.k8s.io/
 See https://github.com/kyma-project/test-infra/issues/4805
  

We already have [Job success rate dashboard](https://monitoring.build.kyma-project.io/d/de6t5dfsw34/quality-dashboard?orgId=1&from=now-24h&to=now)

**Comment by dekiel** [comment]
@kasiakepka in the past I've build system which watch a prowjob statuses and create issues for each failed postsubmit and periodic. The system is smart enough to create only on issue per periodic prowjob, so subsequent failures of the same periodic job create only one github issue. This system can be easily updated with features like detecting flaky tests, closing issues when success rate is high enough etc. This was never enabled because PB want to clean up a prowjobs and later we were busy with other tasks. I did discuss this approach with PB as well and we he accept it. We should go back and work on that in a future.

**Comment by dekiel** [comment]
https://github.com/kubernetes/test-infra/tree/master/metrics
https://github.com/kubernetes/test-infra/tree/master/kettle

**Comment by kasiakepka** [comment]
related issue https://github.com/kyma-project/test-infra/issues/3806

**Comment by dekiel** [comment]
@kasiakepka do you have some examples of criteria which should be evaluated before creating an issue? In my opinion we can create system smart enough to create a valuable issues. Of course at the beginning set of feature will be limited but in my opinion such system can be widely extended with more features and integrated with other processes.

Usually, at the end a solution will require a human attention but this is the same as now. The system can make this interaction easier and faster. It doesn't have to be always a developer intend to fix failing prowjob. This could be a PO to decide if the prowjob should be disabled or removed. This can be a release majster to drive a release bug fix. This can be a whole team to be notified about prowjob issues. The issues and notifications payload could be more detailed and bring more context apart from link to next failure. The issues and notification can be created for a problem with a prowjob not blindly for every execution failure.

Some examples.

1. We can create only one instance of failed periodic.
2. We can detect if periodic is failing constantly or it's a flaky test. We can create issue only if failure rate will drop below some threshold.
3. We can detect if periodic started failing after merge.
4. We can close created issue if failure rate reach threshold. This will cover scenario when external system was down for some longer time.
5. For postsubmits we can assign issues to the commiter.
6. We can assign issues based on prowjob ownership if defined.
7. We can add errors from logs to the issue description. Same as Prow Deck highlight them.
8. We can label issues based on above criteria to allow POs triage or add it to the Developers dashboard.
9. We can add issue command to ignore a failure till an issue with fix is closed.
10. We can add issue command to raise PR removing failing prowjob.
11. We can integrate system with ML to find similar failures and decide about action.
12. We can integrate system with notifications from KCP about provisioning failures.
