### ISSUE TITLE
post-main-k3d-k8s-preview failing

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5487]
**post-main-k3d-k8s-preview job is failing constantly from Feb 14**

Log:
`Deploying Kyma
X Component 'CRDs' failed. Retrying...
no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
 `
`ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
2022-05-24 16:19:50 UTC [INFO] PID:13 --- [/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/lib/utils.sh] utils::receive_from_vm:33 Retrying in 15 seconds..
scp: /home/sa_117798148653314453801/kyma/tests/fast-integration/junit_kyma-fast-integration.xml: No such file or directory`

**Expected result**

 Job is running successfully.

**Actual result**
Job is failing .
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/post-main-k3d-k8s-preview?buildId=

**Comment by kasiakepka** [comment]
@kyma-project/jellyfish can you please check missing `junit_kyma-fast-integration.xml` file?

**Comment by Halamix2** [comment]
junit is not a problem here (it shouldn't fail job even if the file is missing), Kyma is unable to install:
```
Deploying Kyma
X Component 'CRDs' failed. Retrying...
no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
 
X Component 'CRDs' failed 
All attempts fail:
#1: no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
#2: no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
#3: no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
#4: no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
#5: no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

X Deploying Kyma

Deployed Components: 0/1
Could not deploy the following components:
- CRDs
```

**Comment by kasiakepka** [comment]
@kyma-project/jellyfish can you please look at it?

**Comment by varbanv** [comment]
We should move the logic from this test to another type of test.

**Comment by chrkl** [comment]
Job has already been removed by https://github.com/kyma-project/test-infra/pull/5562
