### ISSUE TITLE
Prow Approval Flow [post-mortem]

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5492]
## Background
With this issue we would like to track next steps after revering "Prow Approwal Flow" and revise results of that change.
See [here](https://sap-btp.slack.com/archives/DGC4849U6/p1651667660547579) a little bit of history why it was reverted.

The change was aimed at improving developer experience and accelerating review process (see [here](https://github.com/kyma-project/community/issues/613)) but it also appeared to be a big security topic.

## What we did as a post-mortem
We decided to review changes implemented with this change and tried to evaluate whether we want or need to implement them once again. As an end result we created list of below requirements.

**Must have: Secure release process.**
Options to implement:
- Use [protected tags](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules). Only dedicated people will be able to create GH tags and create release.
- Setup small automation that will notice accidental release and clean it up. There will be no user impact.
- Resurrect Prow Approval flow and revoke write permissions.

**Nice to have: Make review requests more accurate. Make notifications less noisy.**
Options to implement:
- Github based solution with one lengthy CODEOWNERS file.
- Prow based solution where write permissions are revoked.
- Do not implement and wait for modularisation.

### **See below graph with all pros and cons as well as cost of implementation. See also [Mural](https://app.mural.co/invitation/mural/sappm1454/1652685564699?sender=katarzynakepka9315&key=bf61e650-ea56-4d2a-8930-daa39b842a6c)**

![Image](https://user-images.githubusercontent.com/48180632/170508592-50d5d7c5-0bdc-4bc4-bc62-a6eee05105d7.png)

## Other remarks
OSPO guidelines for reference:
> Project Members. You have standard write permissions to the repository and can contribute code and content (e.g. in issues, pull requests, discussions etc.) [source](https://wiki.wdf.sap.corp/wiki/display/ospodocs/Publishing+on+GitHub.com#PublishingonGitHub.com-ProjectMembers)

Note:
We have to take into account upcoming modularisation changes.

**Comment by kasiakepka** [comment]
Close if needed: https://github.com/kyma-project/test-infra/issues/5295

**Comment by m00g3n** [comment]
- All Wookiees are up for **option 2 and option 3** (we may need the tags back if the release process change and we will have own repo but in current process option 3 is justified).
- We also think it is up to Neighbors to decide about turning on/off the automatic assignment of a reviewer in prow repo.

**Comment by dekiel** [comment]
We went for GitHub auto review assignement feature for prow team. Check this comment for details https://github.com/kyma-project/community/issues/613#issuecomment-1152155808

**Comment by jeremyharisch** [comment]
The Jellyfish now decided and we voted for Option 3 to go with the protected Tags.

(The internal results: option1: 0 votes, option2: 2 votes, option3: 8 votes)

**Comment by lilitgh** [comment]
Huskies and Tunas voted for Option 3

**Comment by Disper** [comment]
Framefrog were preferring either options 2+3 or just 3.

**Comment by kasiakepka** [comment]
### So we have the winner: `Use protected tags` (option 3 )
I know that Goats ale also for `option 3`, not sure what about Gophers but still  option 3 wins.
