### ISSUE TITLE
api-gateway component test pipeline

### ISSUE THREAD

**Issue by strekm** [kyma-project/test-infra#5494]
**Description**

Add pre and post main pipelines executing api-gateway component tests. Pipelines should run if api-gateway component resources or tests are changed. List of components should be adjusted. Pipelines should be added to kyma integration gardener pipelines. Script is ready but needs adjustments (istio-resources component added). Check and remove if not needed pipeline [building api-gateway tests](https://github.com/kyma-project/test-infra/blob/main/prow/jobs/kyma/tests/integration/api-gateway/api-gateway-tests-generic.yaml). 

**Reasons**

api-gateway components tests were removed with https://github.com/kyma-project/test-infra/pull/4123

**Acceptance Criteria**

- [x] pre main pipeline created run on changes to api-gateway resources or tests
- [x] post main pipeline created run on changes to api-gateway resources or tests
- [x] makefile of api-gateway component tests adjusted

**Attachments**

https://github.com/kyma-project/test-infra/pull/4028

**Comment by barchw** [comment]
Api-gateway test building pipeline removed in: https://github.com/kyma-project/test-infra/pull/5532
