### ISSUE TITLE
Remove unused jobs

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/test-infra#5507]
**Description**

The jobs:
-  https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/post-rel22-kyma-integration-k3d 
- [post-cli-integration-kyma-1](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/post-cli-integration-kyma-1)

**Comment by kasiakepka** [comment]
@pbochynski Do you want to remove post-rel**XX**-kyma-integration-k3d jobs in general? 
If you want us to disable the specific post-rel**22**-kyma-integration-k3d job - it is done automatically.

**Comment by dekiel** [comment]
Jobs removed.
