### ISSUE TITLE
[CI] Provide functionality to automatically display job description for every prow job

### ISSUE THREAD

**Issue by k15r** [kyma-project/test-infra#5508]
**Description**

Every prow job should print within the first few lines of the 'build log' a description of what the purpose of the job is.

**Reasons**

Figuring out what a job does is a really tedious endeavour atm as one has to 
- read scripts
- check all logs from a job run

**Acceptance Criteria**
- [ ] every prow job can contain a description used for printing
- [ ] every prow job automatically prints that message as the first thing it can actively print

**Comment by dekiel** [comment]
@k15r we could store description in an prowjob annotation. It should be easy to crate function which read pod annotations at the very beginning.
Exposing annotations to containers can be done in two ways. By extending a generic prowjob template we can automaticaly add required env vars or files with annotations.

https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/
https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/

PR level tests can check annotations presence. Some bash testing framework can check if printing function is called.
https://opensource.com/article/19/2/testing-bash-bats

**Comment by dekiel** [comment]
@kasiakepka FYI

**Comment by tobiscr** [comment]
Relates to #5585
