### ISSUE TITLE
Periodic: skr-aws-upgrade-integration-dev

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5524]
**Description**
Job is failing for a month: 181 executions, 28% success rate
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/skr-aws-upgrade-integration-dev

**Expected result**

Fix or delete the job if not needed.

**Comment by Sawthis** [comment]
@kasiakepka I think it is duplicate of: https://github.com/kyma-project/test-infra/issues/5523

**Comment by Sawthis** [comment]
Periodic [skr-aws-upgrade-integration-dev](https://status.build.kyma-project.io/?type=periodic&job=skr-aws-upgrade-integration-dev) job failed 4 times in last 24h counting from 14.06.2022 2PM.

**Comment by Sawthis** [comment]
https://github.com/kyma-project/kyma/issues/14386

**Comment by Sawthis** [comment]
https://github.com/kyma-project/kyma/issues/14368

**Comment by Sawthis** [comment]
I think it is duplicate of: https://github.com/kyma-project/test-infra/issues/5523 .
@kasiakepka please reopen if needed.
