### ISSUE TITLE
Presubmit: pre-main-test-infra-vpathguard

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5525]
**Description**
Job is failing for a month: 458 executions, 0% success rate

**Expected result**

Fix or delete the job if not needed.

**Comment by k15r** [comment]
Isn't the idea of this test to fail? It should prevent merging PRs that contain pjtester configuration. @dekiel ?

**Comment by kasiakepka** [comment]
Yes it is!
