### ISSUE TITLE
Presubmit: pre-main-kyma-integration-k3d-istio-production

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5526]
**Description**
Job is failing for a month: 110 executions, 1% success rate

**Expected result**

Fix or delete the job if not needed.

**Comment by kasiakepka** [comment]
@strekm Can your team please look at it?

**Comment by cnvergence** [comment]
Should be fixed now with
- https://github.com/kyma-project/test-infra/pull/5576

Job histories:
- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-kyma-prod-istio-integration-k3d
- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-kyma-eval-istio-integration-k3d
