### ISSUE TITLE
Presubmit: pre-main-reconciler-protecode-guard

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5527]
**Description**
Job is failing for a month: 68 executions, 1,5% success rate

**Expected result**

Fix or delete the job if not needed.

**Comment by kasiakepka** [comment]
@kyma-project/jellyfish Can you please look at it?

**Comment by jakobmoellersap** [comment]
I've talked with @TorstenD-SAP about this and apparently this job is supposed to check for protecode success. I think the job may be configured badly. Will recheck what the status is, maybe we have to rewrite if we dont want to delete it as it apparently has some expectations that are clearly not fullfillable in day2day working.
