### ISSUE TITLE
Presubmit: pre-main-kyma-skr-eventing

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5528]
**Description**
Job is failing for a month: 421 executions, 4,8% success rate

**Expected result**

Fix or delete the job if not needed.

**Comment by kasiakepka** [comment]
@k15r Can your team please look at it?

**Comment by k15r** [comment]
We're checking...

**Comment by raypinto** [comment]
We're tracking this failing test under [this issue](https://github.com/kyma-project/kyma/issues/13976). Currently this issue is blocked by the Director API issue.

**Comment by raypinto** [comment]
The `pre-main-kyma-skr-eventing` pipeline has been fixed with [this PR](https://github.com/kyma-project/kyma/pull/14515/).
