### ISSUE TITLE
[CI] Bug: nightly build is triggered for future release that does not exist

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5530]
Nightly build is triggered for future release that does not exist yet.
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-gke-nightly-rel24
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-gke-nightly-rel23

**Comment by kasiakepka** [comment]
It is "blocked" by in repo config.

**Comment by tobiscr** [comment]
Jobs were dropped in the meantime. Closing this issue.
