### ISSUE TITLE
misbehaving istio component pipeline

### ISSUE THREAD

**Issue by strekm** [kyma-project/test-infra#5574]
**Description**

Goat team added mandatory istio component pipeline that should only be triggered for istio related changes. despite what seems to be correct configuration pipeline was triggered and mandatory at PRs not related to istio.

**Expected result**

Istio pipeline should be triggered and treated as mandatory only for istio related changes

**Actual result**

pipeline triggered and treated as mandatory on not istio related PRs

https://github.com/kyma-project/kyma/pull/14435/
Istio pipelines: `pre-main-kyma-integration-k3d-istio-production` and `pre-main-kyma-integration-k3d-istio-evaluation`
please be aware that pipelines were switched to optional as they were disturbing kyma devs work

**Comment by Ressetkk** [comment]
I have checked the regular expression and the configuration of the infra. The only thing that comes to my mind is that adding any static ProwJob generates a status on existing PRs that should be affected by the regex. We know that this issue happens, but we lack information about what changed according those 4 days and on how many PRs the status showed up. I assume that regex was too permissive and incorrectly matched against some directories it shouldn't have. And it looks like only evaluation pipeline is affected.

From my tests it seems that regex is correct, but with @cnvergence we changed the regex to match against the files inside those directories more explicitly - `(^resources/istio/.*)|(^resources/istio-resources/.*)|(^tests/components/istio/.*)`. This will match only against the files inside those directories.

If anything else pops up regarding this topic please update the issue.

**Comment by strekm** [comment]
lets close it as i didn't hear anything about it. thanks for investigating
