### ISSUE TITLE
Failing skr-azure-nightly

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5581]
Job is constantly failing from May 26th
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/skr-azure-nightly

Test fails:
```
       CommerceMock Test
         function should be reachable through secured API Rule:
     AssertionError: expected { Object (event, podName) } to have nested property 'order.totalPriceWithTax.value'
      at checkFunctionResponse (test/fixtures/commerce-mock/index.js:136:35)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (skr-test/commerce-mock/index.js:66:5)
```

Provisioning fails:https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/
**Expected result**

Fix or delete the job if not needed.

**Comment by Sawthis** [comment]
Periodic [skr-azure-nightly](https://status.build.kyma-project.io/?type=periodic&job=skr-azure-nightly) job failed 3 times(100%) in last 24h counting from 14.06.2022 2PM.

**Comment by Sawthis** [comment]
Periodic [skr-azure-nightly](https://status.build.kyma-project.io/?type=periodic&job=skr-azure-nightly) job failed 3 times(100%) in last 24h counting from 15.06.2022 11AM.

**Comment by PK85** [comment]
@janmedrek question to you, do you support that commerceMock? cause it's failing and all other skr pipelines do not test commerce mock. What do we do with that skr-azure-nightly plan?

**Comment by varbanv** [comment]
Nobody is using this job so it should be deleted.

**Comment by tobiscr** [comment]
Closing as it's no longer relevant.
