### ISSUE TITLE
Failing post-main-kcp-cli

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5583]
Job is failing from June 3rd.
```
go: updates to go.mod needed; to update it:
	go mod tidy
make: *** [Makefile:28: resolve] Error 1
```
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/post-main-kcp-cli?buildId=

**Expected result**

Fix or delete the job if not needed.

**Comment by varbanv** [comment]
@ebensom could you check the test and remove if not necessary?

**Comment by pbochynski** [comment]
Job is green now.
