### ISSUE TITLE
[CI] Set owners / introduce metadata for Prow Jobs and Pipelines

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5585]
### What?
We should have easy way to determine who is an owner of the pipeline. It would also be helpful to have an option to add further metadata (e.g. purpose of the pipeline) to the pipeline.

We can implement mandatory Prowjob annotation that will tell:
- Who is responsible for the pipeline. In most ceses it will be a team but it also can be release manager, security or one person.
- What is the pipeline testing, what it is doing and why.

### Why?
It is hard to determine who is responsible for given pipeline. Shared responsibility does not work. 

### AC:
- [x] Add annotations like `row.k8s.io/owner` and `row.k8s.io/description`
- [ ] Make annotations mandatory. Test if newly implemented jobs have it: enable the job on 2nd July and reject any Prow-Jobs which doens't include metadata.
- [ ] Update documentation with that information
- [ ] Add it to the templating

**Comment by Ressetkk** [comment]
I've created a PR to k8s/test-infra that adds a warning if some of the annotations are not present. https://github.com/kubernetes/test-infra/pull/26656 Once this gets merged we'll be able to modify the `checkconfig` flags to include the annotations we want. This should work with in-repo configurations.
/kind feature
/area prow

**Comment by Ressetkk** [comment]
With help of other teams we have to determine ownerships of all ProwJobs using annotation `prow.kyma-project.io/owner`, which describes the team responsible for specified ProwJob. We also can use annotation `description` which is used by the TestGrid to fulfill both requirements.

Checkconfig has the ability to make some annotations mandatory. We have to add it to the configuration and keep the job optional until all ProwJobs are annotated. Then we have to make the job required.

**Comment by Ressetkk** [comment]
One big task that we also have to address for implementing this https://github.com/kubernetes/test-infra/issues/27029

**Comment by dekiel** [comment]
#7534 adds non failing check if owner and description annotations are present in prowjob. Once existing prowjobs will be updated with annotations, a test must be rewritten to failing one. By using a gomega matchers it will be easy change.

**Comment by dekiel** [comment]
I did not plan to work on that issue now. I was rather helping Kamil with implementing non failing test. If @Ressetkk is not working on it actively now let's keep it in ToDo. As far I understand the status, we wait for the teams to add annotations. Of course I can work on it as a next task. Once annotations will be in place this is rather quick job.

**Comment by Ressetkk** [comment]
We already have test in place. Once all jobs get annotated with appropriate labels I'll make the test failing.

**Comment by dekiel** [comment]
Neighbors owned prowjobs annotations added in https://github.com/kyma-project/test-infra/pull/7842
Enforcing prowjob annotations test in https://github.com/kyma-project/test-infra/pull/7840

**Comment by Ressetkk** [comment]
/close
as all necessary steps are completed
