### ISSUE TITLE
Prepare documentation how to define pipeline for a component

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#56]
**Description**

 - Prepare documentation that describes how to migrate from Jenkins to Prow (Makefile)
 - How to migrate non standard jobs to Prow - customization
 - How to tests Prow configuration for your component: link to prow documentation, skip_report
 - How to use common features: decorator, where sources are cloned, etc.

**Comment by aszecowka** [comment]
Please add information about structure jobs (described here: https://app.zenhub.com/workspaces/kyma---all-repositories-5b6d5985084045741e744dea/issues/kyma-project/test-infra/42)
