### ISSUE TITLE
nightly-main-reconciler-e2e is failing due to rafter-controller-manager being checked for Metrics endpoint

### ISSUE THREAD

**Issue by jakobmoellersap** [kyma-project/test-infra#5616]
**Description**

Since 21. Jun, we have failing tests in 

` 1) Executing Standard Testsuite:        Prometheus Tests:          Prometheus targets should be healthy:      AssertionError: Following targets are unhealthy: rafter-controller-manager: Get "http://100.96.1.30:8080/metrics": dial tcp 100.96.1.30:8080: connect: connection refused: expected [ 'rafter-controller-manager: Get "http://100.96.1.30:8080/metrics": dial tcp 100.96.1.30:8080: connect: connection refused' ] to be empty       at Object.assertAllTargetsAreHealthy (monitoring/prometheus.js:36:10)       at async Context.<anonymous> (monitoring/index.js:36:7)`
**Expected result**

I think since rafter-controller-manager was affected we probably need to remove the metrics check in the prometheus tests

**Actual result**

Tests should succeed

**Steps to reproduce**

Regular Runs of Pipelines reproduce the issue

**Troubleshooting**

Check https://status.build.kyma-project.io/?job=nightly-main-reconciler-e2e

**Comment by tobiscr** [comment]
Related to https://github.com/kyma-project/kyma/issues/13155
