### ISSUE TITLE
Enable html Lens

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5674]
Prow enhancement that allows to visualise test reports and other information via HTML.
AC:
- [x] enable Lens HTML https://github.com/kyma-project/test-infra/pull/5646/files
- [x] document how to use it (from developer perspective)

**Comment by Halamix2** [comment]
The documentation is ready: https://github.com/kyma-project/test-infra/blob/main/docs/prow/prow-html-lens.md
