### ISSUE TITLE
Unstale issues or PRs when activity happen on issue or PR. 

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#5707]
**Description**
Stale bot should unstale issue or PR when any activity happen on it. At present all stale issues require manual removal of stale label.

Example comment on issue which didn't unstale it. https://github.com/kyma-project/kyma/issues/14147#issuecomment-1174482327

Stale bot documentation: https://github.com/kyma-project/community/pull/689/files#commit-suggestions

Example unstale by any comment: https://github.com/fluent/fluent-bit/issues/2752#issuecomment-1177044544

**Comment by Ressetkk** [comment]
Suggestion: migrate to GitHub actions stale https://github.com/actions/stale
Reason: Current implementation is not maintained anymore. https://github.com/probot/stale Last meaningful commits are from March 2021
* Removes the need to maintain and host our own app instance
* Uses actively maintained stale bot implementation
* Has much more configuration capabilities

**Comment by Ressetkk** [comment]
Our current stale bot is not maintained by the authors and we have to migrate from that ASAP and doesn't provide requested functionality.

Closing, as I don't think we can provide this function with current tooling.

/close
