### ISSUE TITLE
Golangci-lint linter only files changeed in PR.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#5745]
**Description**

Golangcli-lint must allow to check files which were changed in PR.

**Reasons**

Developer doesn't want to fix other component code on it's PR when there was no changes in other component files.

**Acceptance Criteria**

- [ ] Tool is able to operate on files changed in PR only.
- [ ] Tool has flag to run against entire repository.

Parent: #4943

**Comment by Ressetkk** [comment]
When Prow runs the tests on PRs it performs a rebase of the changes against latest revision of main branch AFAIK. Additionally Prow provides variable `PULL_BASE_SHA` which points the SHA of a latest revision from a branch PR is opened.
You can get all changed files between latest PR changes and branch you merge into by using command
```
git diff --name-only --diff-filter=d $PULL_BASE_SHA..HEAD
```
With `golangci-lint` this should work with the following command:
```
golangci-lint run --new-from-rev=$PULL_BASE_SHA
```
or something like that. Worth checking!

**Comment by Ressetkk** [comment]
`golangci-lint` that we use can work only on changed files in a PR. There is no need to reimplement this feature.
