### ISSUE TITLE
Find usage of all GCP service accounts.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#5747]
**Description**

All GCP service accounts will be rotated by automated tool. After SA key rotation, it must be updated in locations where it's used.
A list of usage will be used to plan required tools implementations.

**Acceptance Criteria**

A full list of location where SA keys are used.

PArent: Automate secrets rotation for Gardener, KMS and GCP service accounts. #5691

**Comment by Halamix2** [comment]
Usages of GCP service accounts:

* Prow + Grafana
* Gardener
* Jenkins
* Kyma tooling instance

**Comment by dekiel** [comment]
@Halamix2 do we have issue to cover SA keys rotation in all tools/places where we use them?

**Comment by Halamix2** [comment]
They should be linked in https://github.com/kyma-project/test-infra/issues/5691
