### ISSUE TITLE
Update GCP service account key used in Gardener.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#5749]
**Description**
GCP service account used by Gardener is added by Gardener GUI. This SA is added as secret in Gardener cluster and is used to create Gardener shoot clusters. We don't know if it's possible to update this secret using Gardener API.

**Acceptance Criteria**

- [ ] GCP service account used by Gardener is updated on each key rotation without human intervention.

Automate secrets rotation for Gardener, KMS and GCP service accounts. #5691

**Comment by Halamix2** [comment]
- [x] Create the tool
- [ ] deploy it as a cloud run image triggered by Secret Manager pubsub rotation message
- [ ] add documentation
