### ISSUE TITLE
[CI] Rendertemplate support inrepo prowjobs definition syntax.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#5764]
**Description**

Presubmit and postsubmit definition files for inrepo config doesn't contain information for which repo a prowjob is defined. Rendertemplates must support this syntax for generating prowjobs.

**Reasons**

Rendertemplate must support generating  prowjob definitions for inrepo config. This is our standard approach for working with prowjobs.

**Acceptance Criteria**

- [ ] rendertemplate support syntax for inrepo config

**Parent**
Enable in repo config. #5177

**Comment by dekiel** [comment]
@tobiscr this issue is related to inrepo config. Maybe we could take one issue from inrepo config epic for each sprint to release inrepo to the teams soon.
/remove-lifecycle stale

**Comment by tobiscr** [comment]
Descoped as we are not investing further into Prow. Closing it.
