### ISSUE TITLE
[CI] Validation inrepo prowjob definitions against data files

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#5765]
**Description**

When any prowjob definition change in test-infra we are running test to check if generating definitions from data files provide the same results. This check prevents placing changes directly in prowjob definitions, requiring placing changes in data files first. This same mechanism must be implemented for prowjob definition changes in inrepo config.

**Reasons**

Inrepo prowjob defintions must be always synchronised with data files.

**Acceptance Criteria**

- [ ] Check is running on every change of files in .prow directory or .prow.yaml file.
- [ ] Check fail when there are differences between data files and generated prowjob definitions.

**Parent**
Enable in repo config. #5177

**Comment by dekiel** [comment]
@tobiscr please consider taking this issue to next sprint. This will bring us closer to releasing inrepo config feature for teams.
/remove-lifecycle stale

**Comment by tobiscr** [comment]
Descoped as we are not investing further into Prow. Closing it.
