### ISSUE TITLE
Failing post-main-kyma-integration-k3d-app-conn-validator and runtime-agent

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5783]
**Description**
Job is failing from its first execution: 
- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/post-main-kyma-integration-k3d-app-conn-validator?buildId=
- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/post-main-kyma-integration-k3d-runtime-agent?buildId=1549018364934885376

**Expected result**
Fix or delete the job if not needed.

**Comment by kasiakepka** [comment]
@koala7659 @kyma-project/framefrog Can you please look at it?

**Comment by koala7659** [comment]
This job is currently in the development. Should be ready and start passing soon.

**Comment by franpog859** [comment]
The Application Connectivity Validator job is up and running. The Compass Runtime Agent one is still under development. It should be passing soon. You can track the progress [here](https://github.com/kyma-project/kyma/issues/15037)

**Comment by franpog859** [comment]
I believe we can close this issue as both jobs are now quite successful. Check out their history [here](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/post-main-kyma-integration-k3d-app-conn-validator?buildId=) and [here](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/post-main-kyma-integration-k3d-runtime-agent?buildId=). Please, reopen this issue if needed
