### ISSUE TITLE
[CI] Prowjob code review

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5784]
**Description**
Currently we are reviewing each prowjob configuration change that is submitted to the repository. 

**Proposal**
Let's reduce the necessity to review such PRs as developers are responsible for their prowjob. We should review only prowjob changes that are owned by us. All settings required by automation or security should be enforced by automated tests running on PRs.
Questions:
- Can we find ownership for template data file
- Find out if data file can be splited into subfolders
AC:
- reduce necessity to review prowjob but keep an eye on the code quality
- automated tests on PRs changing prowjobs definitions, should enforce required settings

**Comment by dekiel** [comment]
Data files can exist in subfolders. I already moved some test-infra related data files to respective directory.

>Find out if data file can be splited into subfolders

This should be possible from CODEOWNERS in test-infra. For inrepo we can assume it's a repo owner responsibility if not defined in CODEOWNERS in module repo.

>Can we find ownership for template data file

**Comment by tobiscr** [comment]
We hope the outcomes of OPA Gateway will address the current challenges and we have no longe a need to use processes for Prow-Job reviews
