### ISSUE TITLE
Migrate stale issues triaging to a new tooling

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#5786]
/kind deprecation
/area ci
/area prow

Follow-up for #5707 

Current stale-bot is not maintained for over a year by its authors. We should migrate that to something else that will give us the same functionality of current tooling.

**Acceptance criteria**:

- [ ] Configuration is centralized for all repos across all prow-enabled orgs
- [ ] Bot gives comprehensive comment about it's workings
- [ ] Automatically un-stales issue when there is activity, or gives instruction on how to un-stale the issue/PR
- [ ] Works on both PRs and issues
- [ ] Must run on Prow

**Comment by dekiel** [comment]
@Ressetkk could you please explain in details what you mean with criteria : Doesn't require to host separate workload ?

**Comment by Ressetkk** [comment]
> @Ressetkk could you please explain in details what you mean with criteria : Doesn't require to host separate workload ?

 I meant the requirement that doesn't require to maintain and host a new environment where the application is working. Like, hosting a new deployment on K8s, or maintaining our own GitHub application.

**Comment by dekiel** [comment]
Right, why you didn't write directly that it must be the solution provided by Prow? As there is no other option.

**Comment by Ressetkk** [comment]
Updated.

**Comment by Ressetkk** [comment]
Please let's work on that issue ASAP
/remove-lifecycle stale
