### ISSUE TITLE
Set owners rights on code repositories

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5791]
**Description**
Neighbors team is in a process of taking over ownership over security tooling. As a code owner we need owner rights on all code repositories.

**Task**
Please grant neighbors team owner rights on all security tooling repositories:
- https://github.tools.sap/kyma/security-scans
- https://github.wdf.sap.corp/ce-security-circle/sec_tools_client
- https://github.tools.sap/kyma/security-dashboard
- https://github.tools.sap/kyma/security-scans-pipelines

**Comment by aberezovski** [comment]
The Security Tool Client (implemented in Python) was moved from https://github.wdf.sap.corp/ce-security-circle/sec_tools_client to https://github.tools.sap/kyma/sec-tools-client. 
Neighbours team was granted with Admin rights in new repository.
For all other repositories Neighbours team is also set with Admin permissions
