### ISSUE TITLE
Jenkins Secrets Backup

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#5792]
**Description**
Currently Jenkins secrets backup is not accessible for neighbors team and backed-up in on private laptop.

**Task**
- Determine the storage for all Jenkins Secrets
- Migrate certificates
- Grant owners rights to neighbors
- Verify documentation (secrets have to be rotated during release)

**Comment by dekiel** [comment]
@kasiakepka 
This secrets should be stored along with all other secrets we have.
Which certificates we need to migrate? What is a source and destination for this migration?
Who holds this secrets now and can provide us with it's values?

**Comment by aberezovski** [comment]
All Jenkins pipelines which are used to integrate with recommended security scanners use the config files which are stored on [Jenkins side](https://kymasecurity.jaas-gcp.cloud.sap.corp/job/kyma-opensource/credentials/) as secret files.
All those config files contains credentials/tokens required to access the security tools as well as additional configuration required for each specific workflow.
All config files were shared with @Halamix2.

I also granted access to @Halamix2 and @TorstenD-SAP to Thycotic tools that is used to manage the lifecycle for Technical account used for Checkmarx integration.

All the secrets from mentioned config files have to be rotated once any colleague knowing them is leaving the team, inclusive myself.

**Comment by kasiakepka** [comment]
@Halamix2 Let's keep all secrets in one place and add them to the secret manager.

**Comment by Halamix2** [comment]
All Jenkins secret now have backup in Secret Manager, with label `jenkins:true`

**Comment by Halamix2** [comment]
Documentation about secret updates on each new Kyma release is stored here: https://wiki.one.int.sap/wiki/display/kyma/Switch+supported+Kyma+releases
