### ISSUE TITLE
Backlog review request

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#5820]
Please review which issues are still valid from below repositories and transfer them to https://github.tools.sap/kyma/test-infra

- https://github.tools.sap/kyma/security-dashboard/issues
- https://github.tools.sap/kyma/security-scans-pipelines/issues 
- https://github.wdf.sap.corp/ce-security-circle/sec_tools_client/issues

**Comment by dekiel** [comment]
We need to decide if we have time to move repository with code to tools.github instance. If we decide on that all issues should be transferred to the same repository where code will live.
We will make a decision under https://github.tools.sap/kyma/backlog/issues/2802

**Comment by aberezovski** [comment]
The Python script was. migrated to github.tools.sap server under Kyma organization https://github.tools.sap/kyma/sec-tools-client.
All relevant issues were transferred to new repo.

Only two issues from https://github.tools.sap/kyma/security-scans-pipelines/issues, have to be clarified

**Comment by kasiakepka** [comment]
Both issues are from @Halamix2, I believe they are still valid.
