### ISSUE TITLE
Improve GCP cloud functions code organization

### ISSUE THREAD

**Issue by halamix2** [kyma-project/test-infra#5829]
**Description**

**Reasons**

Currently to deploy cloud functions we need to either call `go mod vendor` to be able to deploy a function, or split PR into two pars, separate for cloud function module and for the common test-infra module

Explore solutions
- [ ] All cloud functions are stored in one module
- [ ] Cloud functions module doesn't use relative imports in go.mod file
- [ ] store gcp functions in separate module imported by test-infra and cloud functions packages

**Acceptance Criteria**

**Attachments**

https://stackoverflow.com/questions/33351387/how-to-use-internal-packages

**Comment by dekiel** [comment]
Recently we made a decision to prefer using cloud-run instead cloud-functions because of better support for go modules. Maybe instead changing cloud functions code organisation we will replace them with cloud run services.

**Comment by tobiscr** [comment]
We prefer to move to CloudRuns... closing issue as obsolete.
