### ISSUE TITLE
Evaluate Makefile steps regarding build infra

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#5834]
If we want to build our images in remote infrastructure, Google Cloud Build using `gcbuild`, we have to investigate Makefile usage for steps `build-image`, `push-image`, `ci-pr`, `ci-release` `ci-main`. Additionally investigate usage of `build-generic.sh`.
We have to make sure if people use these targets in non-standard way and address all usages.

/area ci
/kind cleanup

Parent: Create tool that run docker builds on Google Cloud Build #5637

**Comment by dekiel** [comment]
Copy of my comment from https://github.com/kyma-project/test-infra/issues/5637.

> There is one thing we missed in the discussion and possibly in a requirements. At present we use a makefiles to define build steps. We have a common makefile which can be taken as is or included in another makefile. Even when taken as is, only part of steps can be executed. With a new tool we can provide a common cloudbuild.yaml file however all steps will be executed. There is no way to decide which steps to execute or include some steps from common cloudbild.yaml file. We need think how much this flexibility we need and how we can eventually provide it.
>
> For now I see two ways of dealing with that.
>
> 1. We could create a common steps and use rendertemplate tool and templates to inject them in to cloudbuild.yaml file. This way developers could use only common steps to construct their cloudbuild.yaml or inject some common steps in their cloudbuild.yaml file.
> 2. We could use a Cloud Build golang client library to construct a Build resource to include only steps defined by developer. I think this way will require to define syntax for input file which will define which steps to use and what is their definition. This approach will require much more effort to develop it and probably to use it.

If we learn that we don't need so much flexibility in defining build steps, we can provide an example cloudbuild.yaml file so developers can simply copy paste it and adjust to their use case.
At present we assume only image building steps in our cloudbuild.yaml. Maybe there are some common tasks we should provide within example cloudbuild.yaml.

About build-generic.sh. This file authenticate in gcp, start docker, build pr or short sha image tag and execute makefile passing it's own args. With new tool and cloudbuild.yaml file we can simply drop this file.
https://github.com/kyma-project/test-infra/blob/11e8983750ef06ce14c3a3f5ca5ee44676ad859b/prow/scripts/build-generic.sh

For now I would ask:
- [ ] Can we provide an example cloudbuild.yaml for usage in a copy, paste, edit way or users need some way constructing cloudbuild.yaml from common steps and their custom steps?
- [ ] Should we add some steps to example cloudbuild.yaml?

**Comment by dekiel** [comment]
@Ressetkk do you have a proposal of example cloudbuild.yaml file so users can use it as reference?

**Comment by jakobmoellersap** [comment]
For all operators, we make use of build-generic at the moment to connect it with the kubebuilder style of building images. For standalone builds, this is still something we want to support. Is it possible to still retain the build-generic.sh script even though we use cloudbuild?

**Comment by Ressetkk** [comment]
@dekiel it will be provided in the set-up docs. 

@jakobmoellersap build-generic.sh only runs make target `ci-release` or `ci-pr` plus assumes build tag value. I'm certain you can easily run the same pipeline in the Google Cloud Build with our tool.
Changing build infrastructure will not affect the build itself. If the build tool can return reproducible images then pipeline will also do it. Logs will be available in Prow.

**Comment by jakobmoellersap** [comment]
My point is that in open-source people cannot simply checkout the repo and build it generically without using the cloud build right? 

If we want reproducible images then we will have to put the pipeline into the repo and then call that with google cloud build no?

Anyhow if you can ensure reproducible images and easy to reproduce pipelines that you can run without relying on any pipeline of the Kyma Team (e.g. a provisioned Cloud Build) then I think we are fine :)

**Comment by Ressetkk** [comment]
Fair point. I expect that we'd be using cloudbuild as an extension to get rid of privileged containers from Prow. We'd be running only `docker build` configured in a cloudbuild. If you stick to that, and you do not add any other crucial steps, image build will be the same as usual docker build.

At first I wanted to introduce different approach for building go images with `ko` and use cloudbuild only for Docker builds, but we ended up with migrating that idea to cloud build only. You can set up basically anything with cloudbuild, and you can provide documentation on how to build the application locally.

**Comment by dekiel** [comment]
@Ressetkk should this issue be closed or moved back to different status? Did you finish evaluating requirements and non standard usages?

**Comment by Ressetkk** [comment]
for build pipelines there are no non-standard usage. All build pipelines use the same make step, which is covered by `build-generic.sh`
Evaluation is done.

/close
