### ISSUE TITLE
Migrate Prow clusters to GKE Workload Identity

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#5853]
/area prow

We have to migrate Prow GKE cluster to GKE workload identity. This will remove the need to provide GCP SAs as secrets in cluster.

**Comment by Halamix2** [comment]
trusted and untrusted clusters now have GKE workload identity enabled

**Comment by Halamix2** [comment]
Prow cluster now have GKE workload identity enabled

**Comment by Halamix2** [comment]
Summary:
* on all clusters Workload Identity is enabled
* prow itself uses workload identity instead of secrets
* Secret syncer uses workload identity instead of secrets on all three clusters
