### ISSUE TITLE
Sync secret syncer credentials

### ISSUE THREAD

**Issue by Halamix2** [kyma-project/test-infra#5860]
**Description**

Currently we don't update credentials used for external secret syncer through the external secret syncer

**Reasons**

We want to automatically rotate GCP service account keys, and we need to automatically sync the rotated versions on Prow clusters

**Acceptance Criteria**

- add `external-secrets` namespacce on (un)trusted clusters to monitored namespaces by the `kubernetes-external-secrets` syncer
- sync `sa-secret-manager-*` secrets on prow, (un)trusted clusters with GCP Secret Manager

**Attachments**

- #5691

**Comment by tobiscr** [comment]
Using workload-identify instead
