### ISSUE TITLE
Evaluate using Cloud Run for functions

### ISSUE THREAD

**Issue by Halamix2** [kyma-project/test-infra#5867]
**Description**

All (1st and 2nd gen) Cloud Functions require their code to be at the same level as go.mod file, meaning we have to create separate go.mod file for each function.

 2nd gen Cloud Functions:
    * require eventarc for Pub/Sub triggers
    * builds the image and deploys function as Cloud Run 

We could use raw Cloud Run + eventarc events to be able to simply deploy Docker images ready to be run on the Cloud Run, while keeping one `go.mod` file for the whole test-infra repository

**Reasons**

Maintaining multiple `go.mod` files in the same repository, where modules in subdirectories reference parent modules is problematic, dependencies either have to be vendored with relative dependency path (which will break when main go.mod is updated), or the parent module has to be updated in separate repository before the child go.mod can be updated

**Acceptance Criteria**

**Attachments**

- #5691

**Comment by tobiscr** [comment]
It's great..let's close it
