### ISSUE TITLE
Decision and implementation for code scanning tools

### ISSUE THREAD

**Issue by crabtree** [kyma-project/test-infra#589]
**Description**

In issue #538 we have an investigation for code security tooling done. We need to make a decision which way to go and implement the desired solution.

Considerations:
- Fosa should be run on every PR
- Whitesource scan can be run periodically on master (once a day)

**Reasons**

Our release process requires performing code scan and code checks.

**Attachments**

**Comment by Demonsthere** [comment]
Fossa check badges have been added to both kyma and test-infra README files: 
- https://github.com/kyma-project/kyma/blob/master/README.md
- https://github.com/kyma-project/test-infra/blob/master/README.md
