### ISSUE TITLE
[CI] Enable Easy Caching of Go Cache and Lint Caches

### ISSUE THREAD

**Issue by jakobmoellerdev** [kyma-project/test-infra#5944]
**Description**

We have some build and lint jobs that we would like to cache build data for similar to how Github Actions work. See https://github.com/actions/cache

**Reasons**

his would decrease some of our job times by more than 80% for regular go builds and lint runs, significantly reducing minimum PR Time-To-Merge and increasing reactivity and Developer Response Time to Build Failures. 

See https://golangci-lint.run/usage/configuration/#cache for an example

**Acceptance Criteria**

- [ ] Have easy to integrate Job Configurations that allow us to configure environment variables for golangci-lint and go build commands as well as dockerized builds that allow sharing the build cache across builds, e.g. with a shared volume or similar

**Attachments**

**Comment by dekiel** [comment]
We work on changes in how we build container images. At present we experiment with GCB and Kaniko based solutions. Both allow us to use caching by storing cached layers in separate dedicated OCI repository. See #5637 and #5943 .

Example of caching for go modules shared by @pbochynski https://github.com/pbochynski/kymactl/blob/82b3e0f817c07392b754ceea3aa819a359009110/.github/workflows/k3s-test.yml#L40

**Comment by Ressetkk** [comment]
For caching go modules I was researching on managing it using attached persistent storage, or adapting go proxy which could reduce the time for dependencies to fetch. From what I remember when we evaluated go proxy we didn't see much gain from it. We need more time to experiment on that topic.

**Comment by Ressetkk** [comment]
Quick fix: use https://github.com/sethvargo/gcs-cacher. Downloading and unzipping cache would be much faster

**Comment by tobiscr** [comment]
closing as its's a Prow specific enhancement
