### ISSUE TITLE
Automate old releases cleanup

### ISSUE THREAD

**Issue by halamix2** [kyma-project/test-infra#5968]
**Description**

After the list of images in `templates/config.yaml` is changed, we need to manually remove unuspported versions from `prow/jobs/kyma/releases/`

- Create cleaner that automatically removes unsupported versions from the directory.
- check if this can be implemented as git commit hook or poststubmit that creates new PRs
- add job checking if the files are removed

**Acceptance Criteria**

**Attachments**

**Comment by tobiscr** [comment]
Becomes probably obsolete when moving to modularisation and getting rid of centralized KYma releases.

**Comment by tobiscr** [comment]
Closing this issue as it'S becoming obsolete in coming months when rolling out modularised Kyma
