### ISSUE TITLE
[CI] image-builder: building variants.yaml doesn't work

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#5975]
During my experiments with image-builder I have experienced a medium problem that affects the functionality of the application.
When I try to build the image that uses `variants.yaml` to build multiple versions of the same image, I encounter the problem, where builder thinks that some package configurations are already installed, which breaks `dpkg --configure` command in next runs of the build in the same image. Example with docker-ce in Kyma-integration image that I tried to run with `variants.yaml` file. https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_test-infra/5971/pre-test-infra-kyma-integration/1567465653881802752

/kind bug
/area ci

**Comment by tobiscr** [comment]
Closing issue as we have to rethink the image-building as part of the service offering
