### ISSUE TITLE
Enable quality gates for reconciler E2E tests in control-plane (+ align config-values handling)

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#5993]
**Description**

Currently are three important E2E tests optional quality gate when merging a PR to the control-plane repository.

Reason why there were disabled, is their instability / flakiness: teams which were just updating a value in the values.yaml (even if the modified value has no relation to the reconciler), were blocked in merging their change because these E2E tests never got green.

To make these tests again mandatory for changes related to the reconciler, following actions should be applied:

* **Split values.yaml:**
     Align with SRE team how we deal with the values.yaml changes. Our colleague Xin was already implementing a more granular approach which splits the values.yaml file into several smaller files was rejected by SRE as their pipeline isn't compatible with this new approach. This has to be challenged: we should find an aligned approach with SRE how we can split the monolithically YAML file into smaller chunks so that a change of a non-reconciler related value won't trigger the execution of our long-running E2E tests.

* **Retry flaky E2E tests of reconciler**
    We should verify whether Prow supports an automated retry for flaky / instable test scripts, so that not a human has later to re-trigger these tests when they were getting red with a positive-false finding.

* **Enable E2E test for any change related to reconciler code**
    Finally, we have to make the E2E reconciler tests mandatory again when a PR to the contorl-plane gets opened. The tests should run only if a change related to the reconciler happened (e.g. changing a config-value used by the reconciler etc.)

AC:
- [ ] Define new strategy with SREs to split the monolithically `values.yaml` in smaller chunks, so that a change which is not related to the reconciler, won't trigger the long-running E2E tests.
- [ ] Check if Prow supports automated retries for failing test cases. If yes: configure 3 retries per reconciler E2E tests to mitigate their flakiness.
- [ ] Enable reconciler E2E tests when a PR to the contorl-plane repository is open. But ensure, these E2E tests only run when a code-change related to the reconciler happened (this AC depends on the first item in this AC-list)

**Comment by dekiel** [comment]
`values.yaml` file is used as a source of images to scan by protecode. Support for splited `values.yaml` must be ensured in scaning tools.
There is no flaky test retry feature in Prow. We would have to implement something providing this feature.

**Comment by tobiscr** [comment]
We are going to drop all old reconciler prow jobs soon, closing this ticket as it's becoming obsolete
