### ISSUE TITLE
Move kyma integration tests script to kyma repo

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/test-infra#60]
This is follow up task for #44.

Refactor integration-job folder and move the integrations tests script (`install_deps_and_run_kyma.sh`) to kyma repository.

**Comment by aszecowka** [comment]
Currently, code for integration test in test-infra is placed in `https://github.com/kyma-project/test-infra/tree/master/integration-job`. To have a consistent repository structure, please consider moving it to the same location as other images: bootstrap and buildpacks.

**Comment by michal-hudy** [comment]
Please use `bootstrap` image and if possible `library.sh` script to authenticate to GCP
