### ISSUE TITLE
proposal: image-builder runs build jobs as k8s Job resources

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#6011]
/kind feature

Kaniko is a great solution for building Docker images without the need of running containers in privileged mode.
We've built our in-house solution that wraps kaniko/executor image and adds our own custom settings like automatic tag assumption, build arguments, layer caching and pushing to multiple registries based on the ProwJob information.

The current limitation of image-builder is that it doesn't support concurrent builds of variants of the same image. It is because currently kaniko doesn't support using executor binaries from outside the executor image. More information in #5975 
> Running kaniko in any Docker image other than the official kaniko image is not supported (ie YMMV).
This includes copying the kaniko executables from the official image into another image.

We should go away from using image-builder and executor in the same container. Since we use k8s we could think about using kaniko as a client that creates Jobs on k8s. Fortunately k8s provides builtin resource called `Job` which can be used. image-builder binary would connect to the cluster, create those jobs, watch the execution, fetch the logs and cancel execution if needed. We can re-use our Prow cluster for that. This won't increase the cost.

```mermaid
sequenceDiagram
participant u as User
participant kb as image-builder
participant k8s as K8s cluster

u->>kb: start job
kb->>kb: assume tags and registry
kb->>k8s: create concurrent Jobs with assumed config
kb-->k8s: watch if all jobs are finished
k8s->>kb: all jobs are finished succesfully
kb->>kb: collect logs
kb->>u: notify and pass
```

This approach will be supported by kaniko and will resolve #5975 If the proposal gets accepted, then I will prepare some AC and more technical notes.

**Comment by dekiel** [comment]
Instead of watching k8s Jobs by kaniko-build, this Jobs could register itself as a contexts on a PR or commit. This will make kaniko-build simpler and following build statuses easier. Jobs will be decoupled from each other. On other side a developers would need to know they need to check a build result in different context, however we could communicate this clearly in kaniko-build output. I'm not sure, but probably Jobs which register itself as context will always be required.

**Comment by Ressetkk** [comment]
I wanted to build it independently from Prow. I meant `Job` default resource, rather than ProwJob. kaniko-build tool, which I'll call `scheduler` from now on, was meant to run in a ProwJob. I didn't think about creating more advanced frontend and GitHub integration for that. Simply put, I want to utilize K8s cluster, so we use kaniko as supported, we have concurrent builds, and we have more room to improve on that. For now I want to have scheduler work from ProwJob, then it connects to the cluster using a kubeconfig that has limited access to only one namespace in a cluster.

We could think about implementing GitHub App functionalities and registering build contexts, but I would leave it for the future.

**Comment by dekiel** [comment]
I didn't mean to run it as a GitHub app. You can keep a `scheduler` as ProwJob and use k8s Jobs as `builders` to do the real build. But instead watch `builders` results in `scheduler`, each `builder` can update it's own separate status on GitHub. The same way as regular Prowjobs. The `scheduler` will finish it's job when all `builders` will be scheduled. I think it's possible to create context for each `builder` by scheduler so even when the `builder` will not start it's work the status on PR will reflect this state.

**Comment by Ressetkk** [comment]
Maybe, but there are several problems:
* No access to the logs of each build, as they are not hosted anywhere from builders
* Builders are meant to run with official kaniko/executor image so we use supported approach

Of course it's doable. For example prepare sidecar image that takes care of such reporting, but as I said, I would like to keep it simple for now - we have similar functionality as in gcbuild where scheduler fetches all logs from builder and stores them in artifacts.

**Comment by Ressetkk** [comment]
Scope has been changed. This idea will most likely be invalid in the future. Closing for now.

/close
