### ISSUE TITLE
Use go 1.19 in some pipelines

### ISSUE THREAD

**Issue by werdes72** [kyma-project/test-infra#6028]
**Description**

Istio 1.15 requires go in version 1.19 to work, pipelines are still using go 1.18 so reconciler with latest istio cannot be built.

**Reasons**

We need to bump istio version.

**Acceptance Criteria**

- [ ] Job `pre-latest-istio-reconciler-integration` and `pre-main-istio-reconciler-integration` passes with istioctl in version 1.15.

**Attachments**

See: https://github.com/kyma-incubator/reconciler/pull/1184

**Comment by Halamix2** [comment]
All pipelines should now use Go 1.19
