### ISSUE TITLE
No presubmit/postsubmit job defined for kyma-installer image

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/test-infra#605]
**Description**

In https://github.com/kyma-project/kyma/issues/2090 I had to modify the docker image, and as can be seen in the PR, no prow jobs were run. 

**Expected result**
Some prowjob defined as a presubmit job should be triggered to build/test the image

**Actual result**

Nothing checks changes done to the Dockerfile

**Steps to reproduce**

**Troubleshooting**

**Comment by kasiakepka** [comment]
Investigate why ProwJobs are not running when committing changes:
kyma-project/kyma#4833
kyma-project/kyma#5440
