### ISSUE TITLE
Make protecode scan optional on PR in non release processes.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#6050]
Protecode scan doesn't detect only vulnerabilities introduced by changes in PR, but report all vulnerabilities, new and already known for the image. Because this prevents PRs from merging we decided to make the job optional. If the job is used as security gateway in release process it should stay as required in release process.

**Comment by dekiel** [comment]
Comment from @arturskorupa 

> can you please check if Protecode Guard is used by any other processes (e.g. release). If no, then we may think about removing it completely in a next step.

**Comment by dekiel** [comment]
@kasiakepka moved issue back to In Progress. I believe the status was not changed after reopen. Do we know answer already?

**Comment by kasiakepka** [comment]
The job is used only to perform scans on PRs, it is not involved in release process.
