### ISSUE TITLE
Implementation for code scanning tools - open source vulnerability scanning

### ISSUE THREAD

**Issue by kubadz** [kyma-project/test-infra#607]
@kubadz commented on [Mon Feb 11 2019](https://github.com/kyma-project/kyma/issues/2698)

**Description**

One of two tasks from Epic #589.

AC:
Whitesource scan should be run once a day on master.

**Comment by kubadz** [comment]
@jose-cortina @crabtree I tried integrating Whitesource Bolt (Whitesource integration for GitHub) on my fork of Kyma and on some small js app repo. Here are my observations:

1. due to the documentation, there is no way to configure Bolt to scan the repo periodically (eg. once a day). With the current limitations, the tool will run scan 5 times a day when one of the following events occurs:
>* Every time you commit
>* Whenever a pull request is created
>* When a new vulnerability is disclosed and the vulnerable library is already in your repo
It means that scan will be triggered on the 5 first occurrences of such events a day. So we have no control on when the scan is performed. I contacted the support and they confirmed that we can't configure it differently.

2. most of the created issues will pertain to the code in the PR, not to the code on the master branch. That may create lots of issues, which are not even related to the code on master. The issue also doesn't mention that it is created for changes found in PR.

3. due to the main page of Bolt, the first scan is performed just after the tool is added to the repository. I've added it two days ago at 10 AM and no issues were created since now. 

4. while scanning my small JS application took 2 minutes, I started scanning my fork of Kyma yesterday at 9 AM, and it is still in progress (>23hours). In both cases, it was triggered by a change in one dependency. 

5. while the free plan offers 5 scans a day, the FAQs suggest that users of WhiteSource's "Full Solution" have an unlimited number of scans. There is also a "free for open source projects" plan listed in the Pricing tab. I contacted the Whitesource guys and they said that only paid plans offer unlimited scans.

6. Whitesource offers "Full Solution" which contains, among others, a java app. We probably might create a Docker container with this app and make a prow job for it. However, to use it we need to contact Whitesource sales with (this form)[https://www.whitesourcesoftware.com/contact-us-open-source/]. We should also check if we are able to comply with terms & conditions on that site. 

7. There are alternatives worth checking:
* sonatype Nexus Vulnerability Scanner 
* snyk

**Comment by kubadz** [comment]
@jose-cortina @crabtree 
I did the research for Snyk, and here are some conclusions:
* snyk supports Go projects, but only in their CLI application. [You can read more here](https://snyk.io/docs/snyk-for-golang/). It means that the only way we can use it is to create a prow job. They even encourage users to do that:
>You can also run Snyk as part of your deployment pipeline by scripting the CLI 
* there is a snyk GitHub app for some programming languages (Node.js, Ruby, Python, Scala and Java) and they are continuously adding new languages to the list (10 days ago they added support of .NET projects), so probably they will add Go in the future.
* they state on their website that their database coverage of vulnerabilities is 280% better compared to Whitesource or NPM Audit
* possible slack integration
* snyk offers 200 tests of private repositories per month, and unlimited tests for open source projects

I tried to use snyk CLI to scan Kyma. It searches for the `Gopkg.lock` file and the vendor catalogue in the directory in which is executed. It means that we have to scan every go component separately. 
Snyk offers two ways to scan a project: 
- `snyk test` executes tests, and shows the result in the CLI
- `snyk monitor` executes tests and sends the state of dependencies and any vulnerabilities to the snyk website, where the results can be obtained

As described in [the documentation](https://snyk.io/docs/cli-test/#open-source-projects), after completing all the steps I should be able to test the projects without the limit of 200 tests (which is not sufficient if we want to perfom tests on a daily basis). Unfortunately, only tests performed with `snyk monitor` doesn't count to the test usage and there is no easy way to obtain vulnerability data from the snyk website in a programmed manner because it requires the user to log in. I contacted snyk support regarding counting tests in `snyk test` and I am waiting for their response.

As for now, I can suggest to use the snyk CLI to run tests every two days or more

**Comment by kubadz** [comment]
@jose-cortina
@piotrmsc found out that we can use Whitesource enterprise plan, because of that I will try to use Whitesource Unified Agent - a java app performing scans. I will try to create a Docker container with this app and if it will work as expected I will make a prow job for it.

**Comment by kubadz** [comment]
@jose-cortina
Due to some internal policies we can't use Whitesource Unified Agent to scan projects written in go. Because of that I will create a periodic prow job using snyk CLI to run scans.

**Comment by jose-cortina** [comment]
Thanks @kubadz 
Looking forward to the next steps

**Comment by derberg** [comment]
I'm pretty confused with the comments about whitesource and want to make sure this issue was consulted before someone started working on this issue: https://github.com/kyma-project/test-infra/issues/538

- 5 scans a day was known limitation but not problematic anyway as it can be set to scan commits to master only, 5 a day is super cool and if we have 6 then it is not a big deal, we can wait 1 day. At the end it is security scan that we know from experience takes time and you can't get feedback immediately. Especially that sometimes issues with security in dependencies can be found later
- performance is super cool, if you didn't see any issues created it is simply because there were no issues, I provided in my investigation links to repos where I got hundreds of issues and damn, I was impressed how good it performed

So my comment is simply a concern that we are losing time, and I lost time doing extensive investigation and summary.

**Comment by kubadz** [comment]
@derberg 
* there is no way to set Whitesource Bolt to scan commits to master only. Not only documentation states that scans are triggered on every valid push events, but I also got the same response from Bolt support.
* performance is super cool until you run it on monorepo. I checked it on my fork of Kyma - [here](https://github.com/kubadz/kyma/pull/1/checks) you can check that WhiteSource Security Check status is `In Progress` still. I closed the issue 2 days ago, but as you can see the job started running 7 days ago and didn't finish yet.
* scanning the components with Bolt CLI tool showed a few vulnerable dependencies

**Comment by kubadz** [comment]
We finished the implementation yesterday. The tool will be running once a week at six o clock every Monday. 
The results of scans are available on the Slack. And on the [snyk website](https://app.snyk.io/org/kyma-project). To access the website you have to have a snyk account and be invited to `kyma-project` organization.
