### ISSUE TITLE
Remove `kyma-integration` job for docs

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/test-infra#608]
**Description**

Remove `kyma-gke-integration` job for docs (.md files).

**Reasons**

`kyma-integration` job for docs is not needed. It is time-consuming and it slows down the merging process. This job also tends to fail and it takes additional time (of both dev and TW) to find the source of the failure and fix it. 

**AC**
- leave only docs related jobs and all other must be deactivated

**Comment by tomekpapiernik** [comment]
The `pre-master-kyma-gke-upgrade` job runs for doc-only PRs and takes up to 3,5hrs (!) to complete. Please disable it for doc-only PRs as well. @PK85
