### ISSUE TITLE
Deprecate CNUIDE

### ISSUE THREAD

**Issue by Halamix2** [kyma-project/test-infra#6095]
**Description**

Some of the dependencies that could be updated by dependabot require logr in version 1.2.3, which is incompatible with version 0.4.0

**Reasons**

**Acceptance Criteria**

- update go files to be compatible with logr 1.2.3

**Attachments**

- https://github.com/kyma-project/test-infra/pull/6067
- https://github.com/kyma-project/test-infra/pull/5994

**Comment by KacperMalachowski** [comment]
We decided to remove CNUIDE from our project as it's causing problems with newest logr library
