### ISSUE TITLE
[CI] Add missing tests for pjtester.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#6104]
**Description**

Pjtester recently got new features. Scenarios introduced by new features are not covered by tests.

**Acceptance Criteria**

Following scenarios are tested.
- [ ] "test prowjob definition is in test-infra", "pjtester pull request is in test-infra ", "with provided pull request with test prowjob definition", "with defined test prowjob pull requests"
- [ ] "test prowjob definition is in test-infra", "pjtester pull request is in test-infra ", "with provided pull request with test prowjob definition", "without defined test prowjob pull requests"
- [ ] "test prowjob definition is in test-infra", "pjtester pull request is in test-infra ", "not provided pull request with test prowjob definition", "with defined test prowjob pull requests"
- [ ] "test prowjob definition is in test-infra", "with pjtester pull request not in test-infra", "with provided pull request with test prowjob definition", "with defined test prowjob pull requests"
- [ ] "test prowjob definition is in test-infra", "with pjtester pull request not in test-infra", "with provided pull request with test prowjob definition", "without defined test prowjob pull requests"
- [ ] "test prowjob definition is in test-infra", "with pjtester pull request not in test-infra", "without provided pull request with test prowjob definition", "with defined test prowjob pull requests"
- [ ] "test prowjob definition is in test-infra", "with pjtester pull request not in test-infra", "without provided pull request with test prowjob definition", "without defined test prowjob pull requests"
- [ ] "with test prowjob definition not in test-infra", "with pjtester pull request in test-infra ", "with provided pull request with test prowjob definition", "with defined test prowjob pull requests"
- [ ] "with test prowjob definition not in test-infra", "with pjtester pull request in test-infra ", "with provided pull request with test prowjob definition", "without defined test prowjob pull requests"
- [ ] "with test prowjob definition not in test-infra", "with pjtester pull request in test-infra ", "without provided pull request with test prowjob definition", "with defined test prowjob pull requests"
- [ ] "with test prowjob definition not in test-infra", "with pjtester pull request in test-infra ", "without provided pull request with test prowjob definition", "without defined test prowjob pull requests"
- [ ] "with test prowjob definition not in test-infra", "with pjtester pull request not in test-infra", "with provided pull request with test prowjob definition", "with defined test prowjob pull requests"
- [ ] "with test prowjob definition not in test-infra", "with pjtester pull request not in test-infra", "with provided pull request with test prowjob definition", "without defined test prowjob pull requests"
- [ ] "with test prowjob definition not in test-infra", "with pjtester pull request not in test-infra", "without provided pull request with test prowjob definition", "with defined test prowjob pull requests"
- [ ] "with test prowjob definition not in test-infra", "with pjtester pull request not in test-infra", "without provided pull request with test prowjob definition", "without defined test prowjob pull requests"
- [ ] "Creating new common options"

**Comment by tobiscr** [comment]
Closing it because its Prow specific

/pony rainbowdash
