### ISSUE TITLE
Add status-reconciler Prow component.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#6106]
**Description**

When new required prowjob is added to the Prow configuration, it's context with failed status is added to all current open PRs in the same repo as prowjob. Prow has now a component which clears such false failures. This behaviour cause developers confusion and we are getting requests for help. Installing this component will not require much work and maintenance. It will increase quality of Prow services.

https://github.com/kubernetes/test-infra/tree/master/prow/cmd/status-reconciler

**Comment by Ressetkk** [comment]
This component is already deployed...
