### ISSUE TITLE
Auto updated documentation index page.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#6113]
**Description**

As a user of tools and solutions from test-infra repository I would like to have a convenient access to all docs in test-infra. Because the .md files are located in multiple directories and on different nesting level in a directory tree it's sometimes hard to find needed information. I would like to have a one page with index of all .md files in a repository together with some short summary of its content.

As a test-infra developer I don't want to have another step to do when adding or changing documentation. I want to have this index page updated in automated way. If automation require a metadata in .md files to index it, I want to have an automated check which will ask for adding metadata if it's missing. I want to have a possibility to opt-out from indexing my .md file by automat.

An example library written in go we could use https://github.com/mmiranda/markdown-index

**Acceptance Criteria**

We have one index .md file with links and summary of all .md files in test-infra repository.
Index page is automatically updated after changes in any .md file in repository.
It's possible to opt-out from indexing a .md file.
Verification of requirements for indexing of .md file are automated and run on every commit changing a .md file.

Epic: #5112

**Comment by dekiel** [comment]
A solution we will choose must be able to work with all our repositories and build index page for each repository. As mentioned by @kasiakepka our index pages can be then linked in kyma wide documentation.

Implementation for other repos can be covered by later issues.

**Comment by Sawthis** [comment]
https://github.com/mmiranda/markdown-index go library is not a good solution. It generates list of all heading and index file is almost 660 lines long. In my opinion it is better to implement own solution in Go which will be more flexible and we will have more control about output file content.

**Comment by dekiel** [comment]
The index page must contain list of all .md files located in repository together with links to that .md files.
The page should contain brief summary of each .md file.

**Comment by Sawthis** [comment]
@kyma-project/prow - example of generated list of md files from test-infra repository  [index.md](https://github.com/kyma-project/test-infra/files/9867119/index.md). We need to define structure of this index.md file but it doesn't block this issue. We can change structure in the future easily. 

@dekiel I will add title or description from every md file to the index.md file.

**Comment by dekiel** [comment]
Can we have feature excluding some files? I think following files could be removed from list.

- [.githooks/README.md](/.githooks/README.md)<br/>
- [CODE_OF_CONDUCT.md](/CODE_OF_CONDUCT.md)<br/>
- [CONTRIBUTING.md](/CONTRIBUTING.md)<br/>
- [NOTICE.md](/NOTICE.md)<br/>
- [README.md](/README.md)<br/>

**Comment by Sawthis** [comment]
@dekiel yes we can, I already excluded md files from .github/ folder.

**Comment by Ressetkk** [comment]
@Sawthis it looks great. However, I would see it a little bit differently. Right now this file looks super lengthy and in my opinion doesn't provide required information quickly, as index is supposed to do.

I would rather see it as page with listed directories, eg.:

# Static Heading

Static description of what this file is meant for

## Docs

[Changelog Generator](development/changelog-generator/README.md) - This project is a Docker image that is used to generate a changelog in the kyma repository. It uses GitHub API to get pull requests with specified labels.
[Development](development/README.md) - The purpose of the folder is to store tools developed and used in the test-infra repository.


## How To-s

[Unstaling issue](docs/howtos/unstale_issue.md) - First sentence

And so on. For the names of the docs either path to readme file or heading from that file seems reasonable

**Comment by dekiel** [comment]
@Sawthis Looks good. Make this list more compact is a good idea. You could think about following changes.
- Make an entry title a hyperlink as well and remove link from the last line of entry. This will save us one line for each entry.
- Change title formatting from heading to paragraf with bold. Entries titles will be smaller.
- Exclude directory listing .md files like https://github.com/kyma-project/test-infra/blob/main/development/README.md. Their content doesn't provide much value in terms of documentation. I don't know how excluding works now. Myabe that could be based on some metadata in a file itself.
