### ISSUE TITLE
Use stable version of `KymaCLI` in context of the `kyma-gke-external-registry` pipeline

### ISSUE THREAD

**Issue by pPrecel** [kyma-project/test-infra#6132]
**Description**

Revert changes proposed in [this PR](https://github.com/kyma-project/test-infra/pull/6131) after the new `KymaCLI` release.

**Reasons**

The new `KymaCLI` release would contain changes proposed [here](https://github.com/kyma-project/cli/pull/1398) that fix the issue with the kyma installation on the GKE clusters. We should use a stable version instead of an unstable one.

**Comment by tobiscr** [comment]
@pPrecel : Is this issue still relevant? If not, please close it. Many thanks!

**Comment by tobiscr** [comment]
Too long no reaction - closing it now

/shrug
