### ISSUE TITLE
[CI] Release branch should have the same jobs as main branch

### ISSUE THREAD

**Issue by dbadura** [kyma-project/test-infra#6133]
**Description**
In my opinion release branch is another type of main branch.
That's why all jobs which are executed on main branch, should be executed on release branch

**Reasons**
Sometimes we need to cherry-pick bug fixes and etc, to be sure that backport didn't break anything, the prow should run all needed tests which are run on main.

**Acceptance Criteria**

**Attachments**

**Comment by arturskorupa** [comment]
@zhoujing2022 It would be good to run on release branch all jobs which are a quality gate during the release process, to fail fast. Can you please list them to let @tobiscr plan automation?

**Comment by zhoujing2022** [comment]
I prepared a sheet. We have to figure out at first, which jobs are for what relevant.
https://sap.sharepoint.com/:x:/t/SAPCPFoundationalPlane/Ean9XxOpexxMrUUzNGoEeTUB6euYCUcVt21_q0hNcdGjtQ?email=zhoujing.wang%40sap.com&e=4%3aa9jWdd&at=9

**Comment by grego952** [comment]
I think it'd be good to have the `governance` jobs included to see if there are no broken links on the release branch.
