### ISSUE TITLE
Outdated and missing documentation.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#6144]
**Description**

This issue is a collector of information about outdated or missing documentation in repositories maintained by neighbours team.
- kyma-project/test-infra
- kyma-project/third-party-images
- kyma/sec-tools-client
- kyma/security-dashboard
- kyma/test-infra
- kyma/security-scans-pipelines
- kyma/protescan

Collected list will be used to plan documentation updated.

Add information about documentation as a comment or link another issue or pull request with description, expected action and location.

**Comment by dekiel** [comment]
Outdated documentation to remove #5827

**Comment by dekiel** [comment]
Missing documentation.

It happens a Gardener is not able to delete test kyma cluster. It might happen because some finalizers for resources created by kyma instalator were not removed and Gardener cleaner stuck on deleting them. A possible workaround is to clean them manually.

Gardener error


![Image](https://user-images.githubusercontent.com/48180632/190346771-477570f4-d08f-42a5-b3e4-56edf5cb6707.png)


Possible workaround:
```
kubectl create ns kyma-system || true
kubectl -n kyma-system patch pvc data-helm-broker-etcd-stateful-0 -p '{"metadata":{"finalizers": []}}' --type=merge || true
kubectl -n kyma-system patch pvc data-ory-postgresql-0 -p '{"metadata":{"finalizers": []}}' --type=merge || true
kubectl -n kyma-system patch pvc storage-logging-loki-0 -p '{"metadata":{"finalizers": []}}' --type=merge || true
kubectl -n kyma-system patch pvc prometheus-monitoring-prometheus-db-prometheus-monitoring-prometheus-0 -p '{"metadata":{"finalizers": []}}' --type=merge || true
```

Slack thread: https://sap-btp.slack.com/archives/G01KSPM792P/p1615905859012900

**Comment by Halamix2** [comment]
Secret manager: we don't have any formal documentation how we should name secrets or labels

**Comment by kasiakepka** [comment]
Neighbors info tab 💡 should be also stored in a md files and linked to the rest of our documentation. https://github.com/orgs/kyma-project/projects/22/views/32

**Comment by kasiakepka** [comment]
Add links to the label_sync documentation https://github.com/kubernetes/test-infra/tree/master/label_sync

**Comment by kasiakepka** [comment]
- Label_sync: https://github.com/kyma-project/test-infra/pull/6535/files
- PJtester: https://github.com/kyma-project/test-infra/issues/6502
- secret manager naming convention: https://github.com/kyma-project/test-infra/issues/6536
