### ISSUE TITLE
pjtester: tool picks up incorrect jobs for running if the same named ones are in different repos

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#6156]
Currently some of the jobs that are defined in different repositories, but share the same namer incorrectly picked up by pjtester.

When we have 2 jobs `pull-schema-migrator-build` in Prow config, but under different OrgRepo mapping (this is allowed Prow design) pjtester can pick up incorrect job.
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/23667947/195124069-15ec6a99-5b8f-4933-a128-3df11fcf3f67.png">
This job should have been picked from kyma-incubator/compass repository.  https://github.com/kyma-project/test-infra/blob/7fb7c2e4a98b469dcc048d5199ba03e49819ca6a/vpath/pjtester.yaml

/kind bug
/area tooling

**Comment by dekiel** [comment]
With changes in #5544 a pjtester require a user to provide an organisation and repository names together with prowjob name to test. Pjtester use this to load prowjob definition for provided  repo only.
