### ISSUE TITLE
Upgrade Prow clusters to k8s 1.24 and finally to 1.25

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/test-infra#6176]
**Description**

Upgrade [Prow clusters](https://console.cloud.google.com/kubernetes/list/overview?project=sap-kyma-prow) to k8s 1.24. For upgrade from k8s 1.23 to 1.24 [migration from Docker to containerd is required](https://cloud.google.com/kubernetes-engine/docs/deprecations/docker-containerd).

**Reasons**

[K8s 1.23](https://kubernetes.io/releases/#release-v1-23) has end of life at 2023-02-28.

**Comment by halamix2** [comment]
Prow, trusted, untrusted and tekton clusters are using k8s 1.25
