### ISSUE TITLE
Define evaluation matrix and requirements for pipeline POCs

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#6222]
**Description**

As part of the automated mircodelivery process, the CI/CD system has to be evaluated. To get comparable results, an evaluation guideline has to be defined which is used to challenge each CI/CD system in a structured way.

The guide has to cover:
* definition of a test pipeline which has to be implemented by the CI/CD system  (as diagram + step-wise short explanation what the step is doing)
    * Pipeline triggered by Github.com (Push or Pull Approach - sequence has to be maintained)
    * Build an image (Kaniko/Non-Docker based)
    * Push an image (GCP artefact registry)
    * Create test cluster (K3d/Gardener)
    * Deploy the image
    * Trigger SAP security scanner
* evaluation matrix

The evaluation matrix has to be comparable and each point in the matrix should be tracked in a comparable format (e.g. as figure, Yes/No answer etc.).

The evaluation matrix has to include:
* Was is possible to implement the test pipeline with the evaluated CI/CD system (Y/N)
* List of further the (technical) requirements (see also "[open questions](https://wiki.one.int.sap/wiki/display/kyma/Microdelivery+Strategy)")

Example matrix:

|Requirements|Why is it required?|How to meausre the requirement|Result: JaaS+Piper|Result: Prow+Tekton|Result: AzureDevops+Piper|
|--|--|--|--|--|--|
|..|..|..|..|..|..|

AC:
* Definition of the test-pipeline (as diagram + step-wise explanation)
* Evaluation matrix is created (in the Wiki / Github) in a table format
* The table includes all collected requirements and describes how each requirement has tobe measure/verified.

**Comment by Ressetkk** [comment]
Requirements each pipeline has to meet from my side:


|Requirements|Why is it required|How to measure the requirement|
|---|---|---|
|Safe access to the secrets|SLC-29, prevent secrets from leaking through the logs or other attacks|Every secret used in the pipeline is masked and there is no direct access to it through the logs or other actions|
|No privileged containers|SLC-29, restrict access to host machine, so attacker can't leveraged privileged mode to potentially attack container host|All steps in pipeline do not use privileged containers|
|Ability to integrate secret rotation with external vaulting solutions (eg. GCP Secret Manager)|SLC-29, secret rotation is required to have secure system and automate lifecycle of the secrets|The infrastructure supports secret rotation by default, or with external solutions|
|Support for SAP internal security scans|SLC-29, product security requirements|Pipeline steps can connect to SAP services to trigger security scans|
|Alerting of failed pipelines|To keep track on pipeline executions and reduce time to react on failures|Alerting is available either through e-mails or through chat automations (eg. Slack)|

**Comment by kasiakepka** [comment]
|---|---|---|
|Defining workflows|Defining pipeline as a set of steps allows us to create more sophisticated workflows and cover more complex testing scenarios. It will improve debugging, visibility and reuse of code.| Verify if it is possible to setup pipelines where next step is executed after a condition is met. |

**Comment by Sawthis** [comment]
@kasiakepka @tobiscr do we want to allow also manual steps in the workflows like PO approval etc. ?

**Comment by kasiakepka** [comment]
one more idea
|Requirements|Why is it required|How to measure the requirement|
|---|---|---|
|General UX | How easy and fast it is to setup pipelines. What is overall experience with the tool. | Rate overall UX on a scale from 1 to 5 where 1 is bad and 5 is exccellent. |

**Comment by tobiscr** [comment]
Requirements | Why is it required | How to measure the requirement
-- | -- | --
|easy debugable|For developing new pipeline steps, it's helpful to have debugging options to analyze the implemented code when its executed inside of a pipeline|CI/CD system offers debugging possibilities (e.g. connect the CI/CD system with a debugger, easyreadable log outputs etc.|
|Run CI/CD system locally|To shorten development cycles, having an option to start the CI/CD system locally is helpful to avoid roundtrip efforts (e.g. easy log access, no need to upload code etc.)|CI/CD can be started locally in a productive comparable setup|

**Comment by Ressetkk** [comment]
All information have been collected on internal Wiki for now, as it's mostly internal stuff.

/close
