### ISSUE TITLE
Prow: Refactor jobs to be compliant SLC-29

### ISSUE THREAD

**Issue by tillknuesting** [kyma-project/test-infra#6247]
- [x] make btp-manager pipeline work again and test
- [x] verify kaniko build packs

**Comment by Ressetkk** [comment]
One request - do not use shell script. If you don't have a feature that you'd like to have in image-builder, then please raise a PR with a feature or create an issue. And if you really need to make a script, make it in the target repo.

**Comment by tillknuesting** [comment]
https://github.com/kyma-project/test-infra/pull/6300
