### ISSUE TITLE
[Daily Buiness] Label synchronisation enhancement

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#6287]
**Description**

Currently we use [Label synchronisation tool](https://github.com/kyma-project/test-infra/blob/main/prow/labels.yaml) to synchronise labels across kyma repositories. Standard set of labels (around 100) is copied over to the newly created repos.  Since kyma is migrating to the modular architecture we don't need to synchronise all labels we have, we would like to have more flexibility.

**Reasons**
- Having one hundred labels in the repository where you actually use only 5-10 of them is counterproductive.

**Acceptance Criteria**
- Only minimal set of labels should be synced across repositories.
- When creating repository from the template there is only minimal (standard) set of labels applied.

**Comment by Ressetkk** [comment]
https://github.com/kubernetes/test-infra/tree/master/label_sync

We just need to adjust our workflow. That's it.

**Comment by Sawthis** [comment]
It's not done. @tobiscr @TorstenD-SAP I think we should refine it. Do we still want to do it when Kyma is modular?

**Comment by Ressetkk** [comment]
I don't think so. Depends on if the teams would want some automations or not. At this point I'd just reduce the number of labels to those required by Prow integrations and then if they are not needed anymore, remove the file.

**Comment by tobiscr** [comment]
As teams should maintain their own repository, we should no longer sync labels and let them manage their issues indivually.

**Comment by Sawthis** [comment]
@tobiscr so in this case we should disable synchronisation of labels on Prow. I think we can do it in this issue.
CC: @TorstenD-SAP
