### ISSUE TITLE
[Operation] Unify loggers (if possible) and the log format in Go-code

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#6303]
**Description**
- Currently we are using different loggers. 
- [Many pipelines are failing](https://github.com/kyma-project/test-infra/pull/6274) due to API changes in loggers. 
- Standardise the log format to use a defined pattern everywhere

**Reasons**
Unify loggers and ease the maintenance.

**Acceptance Criteria**

- [ ] Update documentation or create short documentation that defines the standard logger.

**Comment by Sawthis** [comment]
https://github.com/kyma-project/test-infra/pull/6312

**Comment by Sawthis** [comment]
https://github.com/kyma-project/test-infra/pull/6319

**Comment by Sawthis** [comment]
Probably another problematic pull request: https://github.com/kyma-project/test-infra/pull/6358

**Comment by Sawthis** [comment]
Dependabot ignore section: https://github.com/kyma-project/test-infra/blob/main/.github/dependabot.yml#L18-L31

**Comment by tobiscr** [comment]
@kasiakepka : do you know if this issue is still valid?

**Comment by kasiakepka** [comment]
The task is still valid.
