### ISSUE TITLE
Outdated K8s version for shoot creation (Gardener)

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/test-infra#6305]
**Description**

Cluster creation in many prow jobs fail with: 
```
Error from server (Forbidden): error when creating "STDIN": shoots.core.gardener.cloud "grdr56z4a" is forbidden: [spec.kubernetes.version: Unsupported value: "1.23.6": supported values: "1.24.6", "1.24.5", "1.24.3", "1.24.2", "1.23.12", "1.23.11", "1.23.9", "1.23.8", "1.22.15", "1.22.14", "1.22.12", "1.22.11", "1.21.14", "1.20.15"]
Error from server (NotFound): shoots.core.gardener.cloud "[...]" not found
```

**Expected result**

The cluster is created

**Actual result**

Cluster creation fails with an error

**Steps to reproduce**

https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/2211/pre-main-control-plane-reconciler-e2e/1587749184176394240/build-log.txt

**Troubleshooting**

N/A

**Comment by Sawthis** [comment]
@Tomasz-Smelcerz-SAP please reopen if needed.
