### ISSUE TITLE
Support cloning of ARM64/M1 images

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#6388]
**Description**

Currenlty is the image cloner only copying images which have an AMD64 architecture. This is blocking people who run on Mac M1 as the cloned ARM64 images are not working properly for them.

Goal is to extend the current image cloner to support also Mac M1 architectures (please make it configurable which archs it has to support). 

AC:
* image syncer also copies images with Mac M1 architecture

**Reasons**

Support Mac M1 architecture by extending the image syncer to support multiple archtitectures.

**Acceptance Criteria**

**Attachments**

https://github.com/kyma-project/kyma/issues/14797

**Comment by tobiscr** [comment]
Relates to https://github.com/kyma-project/test-infra/issues/5246

**Comment by ptesny** [comment]
Also all the public sapse images https://hub.docker.com/u/sapse are linux/amd64 only; 
The likes of [connectivity proxy](https://hub.docker.com/r/sapse/connectivity-proxy/tags) and soon transparent proxy are part the managed kyma installation...

**Comment by Halamix2** [comment]
- PR #6388 changes image syncer to sync all available architectures. If an image only contains one arch (amd64/linux) it has to be explicitly set in the config file
