### ISSUE TITLE
[Cost Saving] Logging storage retention rule.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#6438]
**Description**

We need establish rule how long we will store logs in GCP logging. This rule should be rolled out to all our projects before 01.03.2023

**Reasons**

</strong></p><h3 style="caret-color: rgb(180, 196, 203); color: rgb(180, 196, 203); font-family: Roboto, arial; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">What do I need to know?</h3><ul style="caret-color: rgb(180, 196, 203); color: rgb(180, 196, 203); font-family: Roboto, arial; font-size: 14px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><li>Logs stored in Cloud Logging for over 30 days, will incur<span class="Apple-converted-space"> </span><strong>a charge of $0.01 per GiB/month.</strong></li><li>Custom retention in Logging Storage was rolled out in June 2020, at which time we also announced pricing, but deferred enforcement.</li><li>We have extended the grace period to March 1, 2023, and are contacting you to provide the advance notice that this previously announced pricing will go into effect on that date.</li></ul><p style="caret-color: rgb(180, 196, 203); color: rgb(180, 196, 203); font-family: Roboto, arial; font-size: 14px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">The table below is a quick reference for our pricing model.</p><div style="caret-color: rgb(180, 196, 203); color: rgb(180, 196, 203); font-family: Roboto, arial; font-size: 14px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">

Pricing | Description | Less than 30 days | More than 30 days
-- | -- | -- | --
Log Retention (SKU: F4AE-5A52-ACE3) | Log data stored in Log Bucket | Included in ingestion price for no charge | $0.01/GiB billed monthly

</div><p style="caret-color: rgb(180, 196, 203); color: rgb(180, 196, 203); font-family: Roboto, arial; font-size: 14px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><strong>Note:<span class="Apple-converted-space"> </span></strong>All charges incur at a Log Bucket level. Please check out the<span class="Apple-converted-space"> </span><a href="https://notifications.google.com/g/p/ACnX6LYn5qOElvXLqKXwjcYi-FM4F4t5keDIkOy2kpApmjCoQ01c_LdGKwWNuhRu-SaCutsAzMOgDcPuwgW80qIdHthsUKLw22Alv3i8j_-KAiTahVm5DdnBIN3qP08dZFTWNgel1Pt8QCQ4"

Google Cloud’s operating suite pricing page</a><span class="Apple-converted-space"> </span>for more information.</p><h3 style="caret-color: rgb(180, 196, 203); color: rgb(180, 196, 203); font-family: Roboto, arial; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">What do I need to do?</h3><p style="caret-color: rgb(180, 196, 203); color: rgb(180, 196, 203); font-family: Roboto, arial; font-size: 14px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><strong>No action is required from you.</strong><span class="Apple-converted-space"> </span>You will be able to see the “Billable Storage” metric on the Log Storage page starting<span class="Apple-converted-space"> </span><strong>January 15, 2023. This is the chargeable approximate log volume for logs retained beyond 30 days.</strong></p>We are writing to let you know we have now extended the grace period for the Logging storage (custom retention). We will begin charging for thepreviously announced pricing for Custom Retention in Cloud Logging on March 1, 2023.

What do I need to know?

Logs stored in Cloud Logging for over 30 days, will incur a charge of $0.01 per GiB/month.
Custom retention in Logging Storage was rolled out in June 2020, at which time we also announced pricing, but deferred enforcement.
We have extended the grace period to March 1, 2023, and are contacting you to provide the advance notice that this previously announced pricing will go into effect on that date.
The table below is a quick reference for our pricing model.

Pricing	Description	Less than 30 days	More than 30 days
Log Retention (SKU: F4AE-5A52-ACE3)	Log data stored in Log Bucket	Included in ingestion price for no charge	$0.01/GiB billed monthly
Note: All charges incur at a Log Bucket level. Please check out the Google Cloud’s operating suite pricing page for more information.

What do I need to do?

No action is required from you. You will be able to see the “Billable Storage” metric on the Log Storage page starting January 15, 2023. This is the chargeable approximate log volume for logs retained beyond 30 days.

**Comment by Sawthis** [comment]
Starting from April 1, 2023 using default logs retention won't cost anything at least for storage.

> Note: Effective April 1, 2023, storage costs will apply to logs data retained longer than 30 days. For pricing details, see [Cloud Logging pricing summary](https://cloud.google.com/stackdriver/pricing#logging-pricing-summary). Prior to April 1, 2023, there are no charges for retaining logs longer than 30 days.
Source: https://cloud.google.com/logging/quotas#logs_retention_periods

**Comment by tobiscr** [comment]
@dekiel : can we close it as it seems to be covered by the chang @Sawthis applied?
