### ISSUE TITLE
Too many certificates already issued for exact set of domains: *.nightly.build.kyma-project.io

### ISSUE THREAD

**Issue by mszostok** [kyma-project/test-infra#646]
**Description**

Nightly cluster cannot be created because of Too many certificates already issued for exact set of domains: *.nightly.build.kyma-project.io

#### Background
On previous nightly cluster (from Jenkins) we had strategy that we generated certificate to use for nightly and then we also stored this cert in valut. Thanks to that when we recreated the cluster we fetch cert from vault checking if it's still valid if not then we renewed them and then one more time used in installation.

Currently on our Prow we do not have such strategy. The certificate is regenerated for each installation and let's encrypt has rate limits for that, see: https://letsencrypt.org/docs/rate-limits/.
We are reaching this one:
> We also have a Duplicate Certificate limit of 5 certificates per week. A certificate is considered a duplicate of an earlier certificate if they contain the exact same set of hostnames, ignoring capitalization and ordering of hostnames

so in logs for our jobs we can see:
```
There were too many requests of a given type :: Error finalizing order :: too many certificates already issued for exact set of domains: *.nightly.build.kyma-project.io: see https://letsencrypt.org/docs/rate-limits/
```

To resolve that we should change the way of generating cert on our Prow.

**Comment by pbochynski** [comment]
Can't we use self-signed certificates for nightly builds?

**Comment by tuxgoose** [comment]
I am assuming we are generating the certificates every build rather than storing them somewhere, and retrieving later?

**Comment by mszostok** [comment]
@pbochynski 
As a first iteration, we used the self-signed certs. But this approach was a little bit problematic. To log into cluster you had to download cert and add to trust store, cause this cluster is recreated every night then u need to delete old, download new, and add to trust. It's not a good developer experience so there was a decision to use the certs from let's encrypt. 

IMO We shouldn't do a step back but improve current solution and implements the same workflow as we had in Jenkins (storing cert in vault and renewing only if needed). In Prow we already using KMS for storing secret so it wont be so hard to do it for cert cause all needed things are already in place.

**Comment by pbochynski** [comment]
Ok. I wasn't aware that you have to log in to nightly cluster often. I did it only a couple of times.

**Comment by tuxgoose** [comment]
I called @mszostok this morning to discuss some possible solutions.
* Modify the kyma-gke-long-lasting.sh to allow for a certificate lifecycle(storing and creating rather per job)
* Create a job for the certificate that we would then manage the certificate
* Investigate a rate increase https://docs.google.com/forms/d/e/1FAIpQLSetFLqcyPrnnrom2Kw802ZjukDVex67dOM2g4O8jEbfWFs3dA/viewform

**Comment by aszecowka** [comment]
We don't know how many keys we will request. Nightly job is executed 5 times in a week so it should be fine, but problem is when we restart that job. We cannot predict how many times we are going to restart it.
Weekly cluster IMO is not affected because we request for a different domain.

About rate increase we don't have any guarantee that they will accept it:
> We will do our best to consider your application in a timely manner but we cannot guarantee acceptance or any form of response.

And IMO if we can solve it on our own, we should do this.

**Comment by tuxgoose** [comment]
@aszecowka I agree that we need need to update the current process, I had hoped that in the interim I could have requested say 3+ additional requests as a temporary bandaid. 
I believe storing the certificates is a solution to the problem, however it will take some time to implement that solution.

**Comment by tuxgoose** [comment]
Currently working on implementing cert-manager - https://docs.cert-manager.io/en/latest/index.html, https://github.com/jetstack/cert-manager

**Comment by tuxgoose** [comment]
golang certuploader
https://github.com/tuxgoose/test-infra/blob/certuploader/development/tools/cmd/certuploader/main.go
