### ISSUE TITLE
Kaniko builds are flaking with high build-times, increasing time to release by up to 30 minutes

### ISSUE THREAD

**Issue by jakobmoellersap** [kyma-project/test-infra#6465]
**Description**

When trying to build with `kaniko`, prow-jobs in the test-infra controlled clusters tend to flake to high build times (we saw over 30 minutes of build time for certain jobs).

We do not really know why this is happening, since the majority of builds run just fine in under < 4 minutes. 

https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pull-lifecycle-mgr-build

After consultation with @Ressetkk I created this issue as we suspect there could be resource starvation problems (maybe CPU on the Node). We did not spot any obvious mistakes in the scaffolded docker file: https://github.com/kyma-project/lifecycle-manager/blob/main/Dockerfile

**Expected result**

- [ ] Build result consistently (>95%) in regular build time (meaning average of under 4 minutes)

**Actual result**

- Build Results flaking out with high build times in unpredictable manner for maintainers.

**Steps to reproduce**

- Run the build jobs multiple times and observe exceptionally long build times

**Troubleshooting**

- Investigated Dockerfile
- Reached out to test-infra maintainers
- Tried to rebuild and find root cause by symptoms

**Comment by Ressetkk** [comment]
I've set the resource requests for build jobs to be 1.5Gi mem and 1 CPU in #6467 Let's see if this will stabilize the build.

/unkind bug

**Comment by jakobmoellersap** [comment]
I think this resolved the issues for us, had no issues since then. LGTM :)
