### ISSUE TITLE
Define Compass credentials as a k8s Secret

### ISSUE THREAD

**Issue by franpog859** [kyma-project/test-infra#6483]
**Description**

Define k8s Secret with the Compass credentials. Once they are defined as a Secret and added to the prowjob, Prow censor is aware of them and will be able to mask them in the build log output

**Reasons**

Having credentials stored in other places than k8s Secret may cause a leak of the confidential data

**Acceptance Criteria**

Compass credentials used in the prowjobs are defined as k8s Secret

**Comment by tobiscr** [comment]
@kyma-project/framefrog : is this issue still relevant?

**Comment by tobiscr** [comment]
Closing, no reaction from framefrogs.

**Comment by akgalwas** [comment]
It seems to be no longer relevant.
