### ISSUE TITLE
[Security] Switch to artifact registry predefined roles.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#6484]
**Description**

To grant access permissions to dev and prod Kyma artifact registries we should use a predefined roles for artifact registry. At present we granted a basic roles on registry resource level. To let developers read, write and delete images and tags we should grant role Artifact Registry Repository Administrator.

**Acceptance Criteria**
- [ ] No basic IAM roles are granted on artifact registry resource level.
- [ ] Kyma developers can write, delete images and tags in dev registry.
- [ ] Prod and dev registries are public available for read access.

**Comment by TorstenD-SAP** [comment]
Already done on the CX Kyma Google Cloud project. Issue no longer needed.
