### ISSUE TITLE
[Daily Business] Can't use GO in VM on Prow

### ISSUE THREAD

**Issue by Cortey** [kyma-project/test-infra#6513]
**Description**
As a frontrunner for the manager topic in Kyma we started working on implementing Prow Tests that run Keda Manager on k3d.
When running a Makefile that deploys and checks manager status we get error `bash: go: command not found`. Value for fixing the issue is that next iterations of manager tests won't propagate it further.

**Expected result**
Prow should run the command without any errors.

**Actual result**
`bash: go: command not found`

**Steps to reproduce**
[Check test-infra PR
](https://github.com/kyma-project/test-infra/pull/6491)

**Troubleshooting**

Current workaround is to add `utils::ssh_to_vm_with_script -z "${ZONE}" -n "keda-manager-test-${RANDOM_ID}" -c 'sudo bash -c "source /etc/profile && make -C ~/keda-manager/hack/local run"'` to the script as the reason for the issue is that go can be used from `/usr/local/go/bin` in the VM but can't be used using `go`.

**Comment by Halamix2** [comment]
PATH was modified in the image's `/etc/profile` file, but it's only loaded by interactive shells

**Comment by tobiscr** [comment]
Is there anything we have to follow-up or was the reply from @halamix2 helpful?

**Comment by tobiscr** [comment]
By our strategical change to move towards a service provider role, we won't work on Prow specific updates anymore.
