### ISSUE TITLE
[Daily Business] Filtering of md files for markdown index based on metadata

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/test-infra#6522]
**Description**

Filtering is now based on [the job configuration](https://github.com/kyma-project/test-infra/blob/main/prow/markdown-index/test-infra-markdown-index-autobump-config.yaml#L11-L21). It would be more convenient to filer it based on metadata included into md file itself.

**Comment by tobiscr** [comment]
Issue in place for 1 year - descoping it as we have to challenge if it's still a required. Please reopen if this requirement still exists.
