### ISSUE TITLE
[Daily Business] Validate documentation index.md on presubmit

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/test-infra#6523]
**Description**

Trigger markdown index generation on presubmit when any .md file is changed.

**Reasons**

Prevent merge of incorrect change in the md files which can broke the markdown index.

**Acceptance Criteria**

- [ ] Display generated markdown index e.g in the logs
- [ ] Verify if the links are correct by running governance job on the generated file

**Comment by Sawthis** [comment]
Maybe better will be to add generation of index.md to Makefile step and run in the presubmit job and compare if index.md was updated like we do for linters.

**Comment by dekiel** [comment]
What we will get by adding makefile instead running tool directly?

**Comment by Sawthis** [comment]
@dekiel My idea was to add execution of the tool to the Makefile that after make run the file will be generated as we do for render-templates. For that tool needs to be updated to not create always PR with updated index.md e.g with the flag. I think render-templates won't be needed soon. We need to re-evaluate if it is not better to migrate it to Github actions too.

**Comment by dekiel** [comment]
Understood, i like idea of generating updated index.md and running on it a tool validating links, however I see one problem with that. If the PR on which we will run a validation, adds resources to which links are added to the `index.md`, then a validation tool will not find these resources by traversing links in validated `index.md`. For that to work, the tool validating links must be aware of changes introduced by the PR itself. If this is already implemented then looks good.

I still think we don't need a Makefile for that. As you mention, we need to add a flag to not create a PR. With such flag we can run a tool directly without additional abstraction layer.

+1 for moving it to the GitHub workflow. It will give as a clean and simple view of steps executed in test which will add another argument to not have a Makefile and bring us closer to not using a Prow for CI/CD.
