### ISSUE TITLE
[Daily Business] Prow governance jobs are not triggered on the of Kyma website

### ISSUE THREAD

**Issue by grego952** [kyma-project/test-infra#6534]
**Description**
Broken links on the Kyma website are missed by the governance job.

**Expected result**
Broken links should trigger the governance jobs.

**Actual result**
Broken links do not trigger the governance jobs.

**Steps to reproduce**

**Related issue**
https://github.com/kyma-project/test-infra/issues/6133

**Comment by tobiscr** [comment]
@grego952 : QQ - what exactly is the issue? Is the job not detecting broken links or is the triggering not happening?

If it's an issue of missing triggers, we will have a look. But if the broken links are not detected, we would not be the right address for this issue.

Please provide a bit more details. Many thanks.

**Comment by grego952** [comment]
@tobiscr 
Sorry for my late response. I somehow missed your reply.
If you go to our [Community section](https://kyma-project.io/community/) on our website, and click e.g. on the **Prow workflow** link you'll see that it throws `404:Page not found`.

**Comment by dekiel** [comment]
@grego952 from which repository and which branch a content of Community section on our website is generated? Once we know where the source of website exist we can check if governance job is running for it. If you are sure a governance job is executed for this source, please provide link to the latest execution.

**Comment by grego952** [comment]
Hi @dekiel 
It's generated from the [community repo](https://github.com/kyma-project/community/tree/main/docs) from the main branch.
[Here](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/community-governance-nightly/1628530290303438848) is the link to the latest execution.

**Comment by dekiel** [comment]
The prowjob is defined and it was called with full validation set to true. You need to open this issue in a repo for the milv tool which is used internally for validation. https://github.com/kyma-incubator/milv
