### ISSUE TITLE
[CI Refurbishment] Provide session to neighbors with technical Tekton deep dive and define our vision for it

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#6586]
**Description**

The usage of Tekton is a new knowledge area and the Neighbors team has to gain the required know-how.

AC:

- [ ] Usage of tasks catalogs
    - [ ] Verify if the tekton task catalog is a suitable way for sharing tasks betweeen Kyma teams
    - [ ] Check how tasks could be applied to the Tekton clusters when they were added to the catalog
- [ ] Rampup session for the Neighbors team was scheduled and the team was enabled to
    - [x] overview of
        - [x] the architecture of Tekton
        - [x] how Tekton is integrated into Prow
        - [x] how the deployment looks on infrastructure level
    - [x] setup a new pipeline from scratch
    - [x] define customer pipeline steps 
    - [x] How to run / debug a pipeline
    - [ ] How to use the catalogs of Tekton (consuming pre-defined tasks form the catalog)
    - [ ] know to add a custom logic/steps to the Tekton catalog
- [ ] Agree on the strategy we are following for Tekton
    - [ ] Using tasks as "interface" to share reusable building pipeline blocks

**Comment by kasiakepka** [comment]
Let's discuss also https://github.com/kubernetes/test-infra/issues/28791
