### ISSUE TITLE
Remove out of date jobs from control-plane repository

### ISSUE THREAD

**Issue by PK85** [kyma-project/test-infra#6612]
**Description**

Since updating minikube version from 1.14 to 1.28 that job started to fail:
- pre-main-control-plane-integration

**AC**
- 1) Remove pre-main-control-plane-integration from test-infra + all scripts used only by that job
- 2) Remove scripts from control-plane that are used by test-infra/pre-main-control-plane-integration job

**Comment by MarekMichali** [comment]
https://github.com/kyma-project/control-plane/pull/2362
