### ISSUE TITLE
Start gathering Prow statistics 

### ISSUE THREAD

**Issue by Disper** [kyma-project/test-infra#662]
**Description**
Citing @a-thaler from a different discussion:
> With that it sounds most meaningful to start gathering statistics about the duration and success rate for the minikube based job and the gke based job. The test execution is logic of our pipeline and no metrics will be available out of the box.

> An open topic is how to access that data. It is accessible via prometheus or grafana dashboard, but both will be secured and only the cluster admins will have access. We can expose the dashboard publicly or we write a job gathering the data and sending it somewhere.

**Reasons**

To be able to monitor the health of Prow continuous integration.

**Attachments**

- Related issue: 
https://github.com/kyma-project/test-infra/issues/147
https://github.com/kyma-project/test-infra/issues/1162

**Comment by kasiakepka** [comment]
We are focusing on https://github.com/kyma-project/test-infra/issues/1162

**Comment by dekiel** [comment]
I've went trough all linked issues. Following is a list of requirements compiled from all of them.

1. Public access to data. - Grafana is public accessible.
2. Metrics
  - average and max duration of prow job - research how to reuse prow addons controller manager for geting data. Check what metrics are provided by this component.
  - prow jobs success rate - exist
  - prow jobs failure rate - not needed as success rate already exist.
  - prow jobs total execution - metric already exist
  - prow jobs total execution per category, peridoic, pre and post - already exist
  - prow components status - already exist
  - memory usage of running jobs
  - github token usage
    - https://developer.github.com/apps/building-github-apps/understanding-rate-limits-for-github-apps/
    - https://developer.github.com/v3/#rate-limiting
    - https://developer.github.com/v3/rate_limit/

All requirements are already implemented except github token usage and average and max duration of prow job.

This issue will be used for implementation of average and max duration of prow job metric.
Github token usage metric will be implemented under #1162 .
