### ISSUE TITLE
K8s cluster required for Tekton in GCP with dedicated network

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#6620]
**Description**

The infrastructure for running Tekton has to be created in GCP (managed K8s instance).

AC:
- [x] Cluster in GCP is created and configuration should be the same as for trusted workload cluster
- [x] Dedicated network is configured and should be the same as for trusted workload cluster
- [x] Security constraints (e.g. Minerva requirements) are considered and properly configured

**Comment by Ressetkk** [comment]
Cluster has been created on prow project.
