### ISSUE TITLE
Setup access from Prow to Tekton (create SA, provide credentials to Prow cluster)

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#6622]
**Description**

Configure Prow and Tekton to be able to interact between each other using a dedicated. A dedicate service account has to be created for it.

AC:

- [x] Follow How-To for integrating Prow with Tekton (https://github.com/kubernetes/test-infra/tree/master/gencred)
    - [x] Setup kubeconfig-file
    - [x] Ensure token within kubeconfig is valid (if it's not possible to configure it endless, the token has to be attached to the automated key rotation mechanism, like we handle it for Gardener)
    - [x] Make token available in Prow

**Comment by Ressetkk** [comment]
Added gencred jobs to Prow that rotate kubeconfigs every 6 hours. External Secrets Operator then Every 10 minutes updates the secret with a new value from GCP Secret manager.

Tekton is connected to Prow and we can use it.

/close
