### ISSUE TITLE
Scheduling of prow job fails on testing a pre-main job using pj-tester

### ISSUE THREAD

**Issue by nesmabadr** [kyma-project/test-infra#6728]
**Description**

On testing a pre-main prow job (that is defined in the test-infra repo) using pj tester, the following error is thrown:
"level=fatal msg="Failed schedule test of prowjob" error="failed generating prowjob specification to test: failed load presubmits or postsubmits, error: failed get presubmits, error: failed to clone repo for \"kyma-project/qa-dashboard\": could not resolve remote for cloning: could not resolve username: fetching bot name from GitHub: status code 401 not one of [200], body: {\"message\":\"Requires authentication\",\"documentation_url\":\"https://docs.github.com/rest/reference/users#get-the-authenticated-user\"}"

PR: https://github.com/kyma-project/test-infra/pull/6654
pull-test-infra-pjtester logs: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_test-infra/6654/pull-test-infra-pjtester/1613847876427845632

**Expected result**
Prow job runs on the target repo PR.

**Actual result**

The above mentioned error is thrown and the prow job does not get triggered on the target PR.

**Comment by jeremyharisch** [comment]
Same bug appears on: https://github.com/kyma-project/test-infra/pull/6726

**Comment by pPrecel** [comment]
Same bug appears on: https://github.com/kyma-project/test-infra/pull/6736

**Comment by Disper** [comment]
@Ressetkk may I ask why is it blocked? In Otters we have some work in our sprint around prow. Is there anything we could do to help unblock it?

**Comment by Ressetkk** [comment]
> @Ressetkk may I ask why is it blocked? In Otters we have some work in our sprint around prow. Is there anything we could do to help unblock it?

Nope. It's most likely authentication issue. Probably access token has expired, and unfortunately I don't have access to the account to regenerate that token.

**Comment by dekiel** [comment]
I will generate new token this evening. @Ressetkk will send it to you.
