### ISSUE TITLE
Firewalls quota exceeded randomly

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/test-infra#677]
**Description**

There's an error on prow jobs that provision GKE clusters:

```
Error creating load balancer (will retry): failed to ensure load balancer for service kyma-system/application-connector-nginx-ingress-controller: googleapi: Error 403: Quota 'FIREWALLS' exceeded. Limit: 500.0 globally., quotaExceeded
```
Probably this also affects any other resource that allocates a Firewall Rule, directly or indirectly (VMs ?)

**Expected result**
Job runs

**Actual result**
Job hangs because LoadBalancer can't be allocated.

**Steps to reproduce**

Happens randomly. Link to a failed job: 
https://status.build.kyma-project.io/log?job=pre-master-kyma-gke-upgrade&id=1101101156869869568

**Comment by kasiakepka** [comment]
I'd like to work on that issue.

**Comment by kasiakepka** [comment]
I'll be able to deliver any solution proposal next Monday at the earliest.

**Comment by suleymanakbas91** [comment]
Closing this one as we defined this task to solve the bug: https://github.com/kyma-project/test-infra/issues/711
