### ISSUE TITLE
Support Otters: Warden CI/CD pipeline

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#6792]
**Description**

Team @kyma-project/otters asked for support in setting up a basic CI/CD pipeline for Warden.

We are going to setup the initial pipeline in Prow CI/CD which is covering the basic CI/CD responsibilities:

* check for clean go.mod (`go mod tidy` should not modify the go.mod file)
* run linters for Golang
* build the code
* run all detected Golang tests (`make run-integration-tests`)

AC:
- [ ] Prow job is created which gets triggered for PRs opened in the warden repository
- [ ] Prow job executes basic build steps:
    - [ ] check for updated go.mod file (`go mod tiny`)
    - [ ] run linters for Golang
    - [ ] build the code
    - [ ] run Golang test cases

**Comment by Ressetkk** [comment]
Will be tracked in https://github.com/kyma-project/warden/issues/28
/close
