### ISSUE TITLE
Use Whitesource Unified Agent to replace Fossa licence check and Snyk vulnerabilities scan

### ISSUE THREAD

**Issue by kubadz** [kyma-project/test-infra#682]
**Description**

Use Whitesource Unified Agent to replace Fossa licence check and Snyk vulnerabilities scan.

**Reasons**

Currently, we use free plans either on Fossa to perform licence check and on Snyk to perform vulnerabilities scan. We can use one tool - Whitesource Unified Agent to perform both.

As we have access to the enterprise version of Whitesource, there are no limits on the number of scans or in access to the API, what is an advantage in relation to Snyk. 

Related issues:
#607 - Implementation of vulnerability scanning with Snyk
#606 - Implementation of licence check with Fossa
#589 - Epic for implementation for code scanning tools

**Attachments**

**Comment by tehcyx** [comment]
Is this still considered?

**Comment by jose-cortina** [comment]
It should be

**Comment by tuxgoose** [comment]
Bot do not close, currently we are able to run scans on individual components in whitesource manually with docker. This workload is not currently automated. I will update with relevant PR later today

**Comment by tuxgoose** [comment]
Service account for whitesource- 
https://jam4.sapjam.com/wiki/show/nTWPp94xFFdZZ1rMjFOq17

**Comment by tehcyx** [comment]
Whitesource changes are live.
