### ISSUE TITLE
Enable nightly AKS cluster notifications

### ISSUE THREAD

**Issue by PK85** [kyma-project/test-infra#684]
**Description**

After bump version of prometheus-operator the value of KYMA_ALERTS_CHANNEL can be restore to its proper value.

**Reasons**

Found by: https://github.com/kyma-project/kyma/issues/2608#issuecomment-468287174
Resolved by: https://github.com/kyma-project/kyma/issues/2873

AC:
- notifications work as expected

**Comment by jasiu001** [comment]
**Description**

Issue was described [here](https://github.com/kyma-project/kyma/issues/2873), to fix the problem, it was necessary to bump the version of the `prometheus-operator` chart what was made [here](https://github.com/kyma-project/kyma/issues/2926)

**Step to fix**
- make sure `prometheus-operator` chart [used in Kyma](https://github.com/kyma-project/kyma/tree/master/resources/prometheus-operator) is equal or higher than version 0.26.0 of this helm [chart](https://github.com/helm/charts/tree/master/stable/prometheus-operator), it is necessary for the chart  to support `kubeApiServer.relabelings` functionality
- enable in Kyma `prometheus-operator` chart relabeling for AKS like is describe in charts [`values.yaml`](https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml#L404) (search for a `relabelings` variable in the file)
- at the end change `KYMA_ALERTS_CHANNEL` in `test-infra` repository
