### ISSUE TITLE
Non-permissive licenses in kubernetes/test-infra dependencies

### ISSUE THREAD

**Issue by jose-cortina** [kyma-project/test-infra#687]
**Description**

In test-infra the kubernetes test-infra is referenced and used. This depends on a number of other open source libraries that have some version of the GPL license which is not permissive and must be avoided. This causes a license failure in FOSSA.

The libraries reported by FOSSA with GPL licenses are:
https://github.com/PyCQA/astroid
https://github.com/spf13/cobra
https://github.com/shurcooL/gofontwoff
https://github.com/grpc
https://github.com/pallets/jinja
https://github.com/PyCQA/pylint
https://github.com/rtfd/sphinx_rtd_theme
https://github.com/docker/docker

**Expected result**

All libraries used have a valid and permissive license.

**Actual result**

Libraries with non-permissive licenses are used.

Please refer to https://app.fossa.io/projects/git%2Bgithub.com%2Fkyma-project%2Ftest-infra/refs/branch/master/6e4852eaf3ac74672dc5522f71cd65fbdb300573/issues/licensing?filter=policy_flag

**Comment by derberg** [comment]
@jose-cortina what is the status of this issue? should it be assigned to someone to fix that

**Comment by jose-cortina** [comment]
Issues have been resolved.
