### ISSUE TITLE
Prepare README.md that follows Kyma guidelines

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#69]
**Description**

Prepare `README.md` for `test-infra` repository that follows Kyma guidelines. It should include:
 - purpose of repository
 - structure of repository
 - link to production prow
 - update `prow/readme.md`
   - links to Prow installation instruction (local and production)
   - directory structure

HINT: check `kubernetes/test-infra` readme

**Comment by kazydek** [comment]
Relates to https://github.com/kyma-project/test-infra/pull/110.
Initial review to be performed by @michal-hudy .
