### ISSUE TITLE
[CI Refurbishment] Setup read-only access to Tekton Dashboard

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#6928]
**Description**

Tekton dashboard offers pure read-only access.

AC:
- [x] Limit permissions of Tekton dashboard to use only read-only permissions (no changes allowed etc.)

**Comment by Ressetkk** [comment]
Tekton has been already installed with read-only access. For now #6976 also restricted access for dashboard to list resources only for default namespace (the one where pipelines are executed).

/close
