### ISSUE TITLE
[Security] Refactor Secrets leaks detector services.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#6942]
**Description**
Some parts of secrets leak detector services code are duplicated for each service. We should review code to identify this duplicated sections and extract them to separate module. Mostly, these will be section related to creating instances of loggers, events or message payloads.

Services are located in paths.
- development/gcp/cloud-run/create-github-issue
- development/gcp/cloud-run/search-github-issue
- development/gcp/cloud-run/scan-logs-for-secrets
- development/gcp/cloud-run/move-gcs-bucket

**Comment by tobiscr** [comment]
As the discussion to discontinue Prow is ongoing, we leave this task closed and will reopen it if we decided to continue the Prow offering for the longterm.

Closing issue for now as obsolete.
