### ISSUE TITLE
[CI] Implement testing strategy pipelines in ADO

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#7039]
**Description**

As part of the Kyma module release pipeline are several testing flows required. Scope of this issue is to implement ADO pipelines which are verifying:

* [No orphan resources after deletion check](https://wiki.one.int.sap/wiki/display/kyma/Microdelivery+and+Testing+Strategy#MicrodeliveryandTestingStrategy-Noorphanresourcesafterdeletioncheck)
* [Kubernetes API compatibility check](https://wiki.one.int.sap/wiki/display/kyma/Microdelivery+and+Testing+Strategy#MicrodeliveryandTestingStrategy-KubernetesAPIcompatibilitycheck)
* [Upgrade test](https://wiki.one.int.sap/wiki/display/kyma/Microdelivery+and+Testing+Strategy#MicrodeliveryandTestingStrategy-Upgradetest)
* [Hyperscaler compatibly check](https://wiki.one.int.sap/wiki/display/kyma/Microdelivery+and+Testing+Strategy#MicrodeliveryandTestingStrategy-Hyperscalercompatiblycheck)

The implementation of the test steps is done by the @kyma-project/pandas team, but the team neighbors is in charge to create the required ADO pipelines which are executing the test steps.

AC:
- [x] Align with @halamix2  and @Sawthis how to integrate the testing flows into the existing ADO pipeline (reuse the existing ADO pipeline which they have prepared for sec-scanners)
- [x] For reusability purposes (e.g. integration beween Prow and Tekton), it would be good to implement each test pipeline as dedicate ADO template (see [docu](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)) to make them "callable" from different pipelines (e.g. as part of the comprehensive release testing pipeline or as dedicated pipeline which can be used by our teams).
- [x] Kyma module release pipelines includes `No orphan resources after deletion check` is implemented and tested together with Pandas team
- [x] Test `Kubernetes API compatibility check` is implemented and tested together with Pandas team
- [x] Test pipeline `Upgrade test` is implemented and tested together with Pandas team
- [x] Test pipeline `Hyperscaler compatibly check` is implemented and tested together with Pandas team
- [x] Run end2end test verifying that the MVP works as expected
- [x] Configure the release channel repository to  require the context-status to be passed

**Comment by the1bit** [comment]
Local cluster dry run. 
1. I had an issue during the module template enablement. We asked some help from @kyma-project/jellyfish. They helped us to investigate the issue. 
Findings:
- Enable command runs longer than time out parameter (`~/kyma/kyma-darwin alpha enable module keda -c alpha -w --non-interactive`) therefore they suggest to use exact time out as parameter like this: `~/kyma/kyma-darwin alpha enable module keda -c alpha -w --non-interactive -t 120s`
- We found a parameter in module template which could cause some problem in the implementation.
https://github.com/kyma-project/kyma/blob/18dfd312bc9456e9323e92d6cd9a9714f9a08d6e/modules/alpha/moduletemplate-keda.yaml#L15
This line is “**remote**” but it should be “**control-plane**” on a local environment. This is an additional task to check during the implementation

2. The "**wait_kyma_module_ready**" routine does not work well.  https://github.tools.sap/pandas/module-smoke-tests/blob/a415890f8e9e0ba058572583caf7ea7e91bb1f03/scripts/bash/lib/kyma.sh#L24

**Comment by the1bit** [comment]
Pipeline SPIKE is in progress: Use Ubuntu 22.04 runner image for all pipeline steps.

- K3d installed
- Kyma (alpha) installed and deployed
- Enable/Disable works

**Comment by the1bit** [comment]
Sequences and commands


![Image](https://user-images.githubusercontent.com/32801432/223484190-4978d275-84fe-4330-9f41-b23fa862a18e.png)

**Comment by the1bit** [comment]
https://github.com/microsoft/terraform-provider-azuredevops

**Comment by the1bit** [comment]
First draft: https://dev.azure.com/hyperspace-pipelines/neighbors-team/_build?definitionId=12189&view=runs

**Comment by the1bit** [comment]
I have created a Hyperspace based repository and pipeline for the further testing. (This configuration is similar to https://github.tools.sap/kyma/kyma-modules)

-ADO: https://dev.azure.com/hyperspace-pipelines/neighbors-team/_build?definitionId=12381&_a=summary
- Git: https://github.tools.sap/neighbors-team/kyma-module-test
-

**Comment by the1bit** [comment]
First drop is done.


![Image](https://user-images.githubusercontent.com/32801432/227303224-9f22beb1-42c6-4844-9d25-225e37a9f30c.png)

Let's fine tune and integrate

**Comment by the1bit** [comment]
- GitHub Enterprise integration solved
- Module template upgrade clarified: https://sap-btp.slack.com/archives/C03BC9UVAR1/p1679915856304579?thread_ts=1679906408.501209&cid=C03BC9UVAR1
- Upgrade steps will be converted to template files.



![Image](https://user-images.githubusercontent.com/32801432/227976578-b1cc7c5d-6de4-4553-bcbf-5ff730882524.png)

**Comment by the1bit** [comment]
Upgrade is done

![Image](https://user-images.githubusercontent.com/32801432/228287145-eebdb58a-c12c-4e13-b39f-a74571aa6c1c.png)


Known issue regarding upgrade test:
- Error: failed to validate module channel: the channel [fast] does not exist for the module template [keda]. choose from one of the available channels: [alpha]
- Error: failed to validate module channel: the channel [regular] does not exist for the module template [keda]. choose from one of the available channels: [alpha]

**Comment by the1bit** [comment]
![Image](https://user-images.githubusercontent.com/32801432/228298014-33336042-7ed7-4160-98c4-d06e3d1b32af.png)



![Image](https://user-images.githubusercontent.com/32801432/228298185-844e21cc-a269-4473-ad40-7ff872441168.png)

**Comment by the1bit** [comment]
Hyperspace based pipeline has been created:
- Azure DevOps: https://dev.azure.com/hyperspace-pipelines/kyma/_build?definitionId=12448&_a=summary
- GitHub (github.tools.sap) PROD: https://github.tools.sap/kyma/kyma-modules
- GitHub (github.tools.sap) DEV: https://github.tools.sap/neighbors-team/kyma-modules

**Comment by the1bit** [comment]
V0.1 is available on https://github.tools.sap/neighbors-team/kyma-modules

**Comment by the1bit** [comment]
Issue list which catched by pipeline:
- Brand new module step:
- Orphan Resources: Nothing
- Kubernetes API Compatibility check: 
`keda-manager-557774c96f-ct4fl pod in kyma-system namespace: '2023-03-30T18:25:06Z	INFO	KubeAPIWarningLogger	autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscale`
- Upgrade check: No files on main branch.

**Comment by the1bit** [comment]
I’ve created a test repo and test pipeline to avoid the PROD related testing
Git: [neighbors-team/kyma-module-release-test (tools.sap) ](https://github.tools.sap/neighbors-team/kyma-module-release-test)
ADO: [kyma-module-release-test](https://dev.azure.com/hyperspace-pipelines/neighbors-team/_build?definitionId=12499)

**Comment by the1bit** [comment]
![Image](https://user-images.githubusercontent.com/32801432/229522163-c234b414-6ae1-4ab5-a0a1-52d6ef8adb87.png)

**Comment by the1bit** [comment]
Fix required:
- Task dependency
- Version check after upgrade

**Comment by the1bit** [comment]
With module template 0.0.3, the primary test have been tested successfully.



![Image](https://user-images.githubusercontent.com/32801432/231160013-2a167db3-de51-403d-ad2a-12fd16da7142.png)

**Comment by the1bit** [comment]
E2E testing idea:
- ask jellyfish to help us to create testing modules and related templates for the related scenarios

**Comment by the1bit** [comment]
![Image](https://user-images.githubusercontent.com/32801432/231814945-1863bfe8-71cc-46b4-a5d8-6ded84a707fa.png)
