### ISSUE TITLE
[Security] Alert on secrets-leak-detector workflow error.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#7068]
**Description**

When a secrets-leak detector workflow return error an alert is raised and neighbours team receive slack notification. All workflow errors are logged in google logging service.

**Reasons**

While we monitor and alert on errors of services called by workflow, an errors of workflow itself pass silent. We need to know when a leaks detection application was not able to process logs because of errors.

**Acceptance Criteria**

- [ ] Alerting policy create alert on workflow execution errors.
- [ ] Alerting policy send slack notification to neighbors team.
- [ ] Alerting policy is setup through terraform config.
- [ ] Alert contains links to application documentation.

**Comment by tobiscr** [comment]
As the discussion to discontinue Prow is ongoing, we leave this task closed and will reopen it if we decided to continue the Prow offering for the longterm.

Closing issue for now as obsolete.
