### ISSUE TITLE
[Kyma module release pipeline] Trigger release pipeline for each module template in PR

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#7075]
**Description**

A PR to a release channel repository can include multiple Kyma module templates. Each module template in the PR has to be verified by a dedicated release pipeline run.

Multiple release pipeline runs have to be triggered if the PR includes multiple Kyma module templates (see [ADO docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/get-started-multiplatform?view=azure-devops))

AC:
- [x] Analyze the PR and extract the Kyma module templates
- [x] For each module template is a dedicate release pipeline triggered
- [x] The PR is only passing the release pipeline quality-gate if ALL Kyma module templates in the PR were passing the release pipeline successfully

**Comment by tobiscr** [comment]
Like https://developercommunity.visualstudio.com/t/matrix-variable-that-is-passed-to-a-template-as-a/1184356

**Comment by Sawthis** [comment]
I think we can use matrix approach explained here: https://stackoverflow.com/a/68506935
