### ISSUE TITLE
Periodic job for cleaning abandoned VPC networks

### ISSUE THREAD

**Issue by crabtree** [kyma-project/test-infra#722]
**Description**

We are creating a new VPC network for each cluster provisioned by Prow (see issue #549). It may happen that there will be some leftovers caused by Prow behavior - Prow is triggered by each commit to a PR. If you push commit after Prow jobs are triggered, recently created jobs are terminated and the new ones are created. That causes the abandoned resources in the GCP.

**Reasons**

There is a resource quota for VPC networks (50). Sooner or later we will hit that limit.

**Comment by michal-hudy** [comment]
In fact, it happened: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1105120897808732160

Maybe we should create network per cluster type, then we will have something like that:
 - night
 - weekly
 - gkeint
 - gke-upgrade
 - etc.

Then we will not exceed quota so quickly. @crabtree, what do you think?

**Comment by michal-hudy** [comment]
As I see we have 12 types of integration tests:
 - presubmit: 4
 - postsubmit: 4
 - periodic: 4

Then we will have 12 networks. In networks we can have many subnetworks, depending on the network mask. But, the number of available subnetworks will be still much bigger than the quota for networks.

**Comment by crabtree** [comment]
@michal-hudy The main implementation switched to network per job type. Now each cluster type (pr, rel, commit, long-running, e2e, loadtest) have its own network. All clusters of each type are provisioned within the network of its type. Thanks to that we do not have to clean up resources like VPC network.
