### ISSUE TITLE
[Daily Business] Set Slack notification for release critical jobs

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#7242]
**Description**

Send Slack notifications to #kyma-skr-release channel when below jobs are failing.
- [kyma-gke-nightly](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-gke-nightly)
- [post-rel212-kyma-release-candidate](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-rel212-kyma-release-candidate/1635652429674450944)
- [post-rel212-kyma-artifacts](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-rel212-kyma-artifacts/1635651584148901888)
- [post-rel212-kyma-integration-k3d](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-rel212-kyma-integration-k3d/1635955720396476416)

**Expected result**

Slack message is send when on of above jobs fails.

**Comment by tobiscr** [comment]
Moving towards modularisation we won't need this feature anymore.
