### ISSUE TITLE
Monitoring of GCP resources

### ISSUE THREAD

**Issue by hudymi** [kyma-project/test-infra#731]
**Description**

Create a Grafana dashboard that will display GCP resources usage. Also, implement alert rules when the quota is close to the limit.

**Reasons**

Many times we were exceeding GCP quotas for resources. Recently it was firewall rules, networks and previously backend modules. Unfortunately, we are not monitoring it and we don't have alerts for that. 

**Attachments**

**Comment by kasiakepka** [comment]
This task will be converted to Epic.
