### ISSUE TITLE
Do not allocate IPs in integration jobs

### ISSUE THREAD

**Issue by sjanota** [kyma-project/test-infra#738]
**Description**
Jobs running on GKE allocate IPs before cluster is created. This is not necessary, as LoadBalancers will dynamically allocate IP if it is not provided.

**Reasons**
This will make GKE jobs behave according to official Kyma docs. Also all domains will be reserved at the same time (apiserver-proxy domain is reserved after Kyma installation) which will save couple of minutes.

**Comment by Demonsthere** [comment]
Implemented by #362

**Comment by Demonsthere** [comment]
In progress via #889

**Comment by kasiakepka** [comment]
this issue is tracked here https://github.com/kyma-project/test-infra/issues/362
