### ISSUE TITLE
[CI] Refactor `test-infra` repository and establish clear structuring

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#7386]
**Description**

The current structure of the [`test-infra` repository](https://github.com/kyma-project/test-infra) has to be reviewed in regards to:

* review folder structure and think about IaC oriented sturucturings
* separation of Go libs / applications within the [development directory](https://github.com/kyma-project/test-infra/tree/main/development)
* review CI/CD jobs for `test-infra` repository (simplifications possible?)
* think how Prow related code should be organised to establish modularised / simplified usage of existing libraries/scripts

![image](https://github.com/kyma-project/test-infra/assets/73824711/57df73da-4cd2-4107-a772-666a680a001c)

AC:
- [x] Create a written proposal how the `test-infra` repository could be restructured to address:
    - [x] clear separation of applications / libraries (see [development directory](https://github.com/kyma-project/test-infra/tree/main/development))
    - [x] how to get closer to an IaC focused structure (when / how to use Terraform modules for structuring features / applications)
    - [x] Options to simplify CI/CD jobs
- [x] Present the proposal to the team (as ADR) and drive the consensus finding process
- [ ] Apply the restructuring of the `test-infra` repository in coordinated steps (sub-tickets have to be created based on the proposal and ADR)

**Comment by Ressetkk** [comment]
@tobiscr I actually found one of my old issues. Feel free if it's something you can see as valuable https://github.com/kyma-project/test-infra/issues/2281

**Comment by Ressetkk** [comment]
99% of things has been moved. The last 1% we will move on the go.
/close
