### ISSUE TITLE
Enable access to test clusters to debug PR issues

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/test-infra#741]
**Description**
Currently, developer has no access to *test clusters* that verify pull requests like `gke-int-pr-1234` clusters.

I suggest developers must have limited access to test clusters to quickly find and resolve installation/upgrade issues.
In addition, the lifetime of these test clusters must be extended beyond test job's time, to allow for such analysis. An hour seems to be reasonable.

**Reasons**
Developer faces the following scenario: PR fails on Kyma Installation and prow job's log contains only information about "core" component failure and several retries. That's all.
All a developer can do now is to *guess* what happened knowing the scope of changes introduced in the PR.
Kyma Installer logs usually don't help much, because the Installer doesn't know precise reasons for Helm release failure. Helm doesn't even bother to provide such information. Helm reports only some obvious errors like template parsing problems.
Examples:
If the reason was Helm template parsing problem, the root cause is hidden in the contents of a ConfigMap used as source of Helm's overrides.
If the reason was a crashing Pod, the root cause is hidden in the Pod's logs.
If the reason was an unmounted PVC, the root cause is hidden in the status of this resource.
If the reason was a misconfigured security access level, the root cause might require inspection of several places, like Pod's logs, deployment status and so on.

All such cases are very common in daily work and there's not a generic "logging" mechanism to gather such information for the purpose of analysis.
Limited access to the cluster is the best way to resolve such cases effectively.

**Comment by tehcyx** [comment]
#850 will solve this
