### ISSUE TITLE
[Submission Pipeline] Implement smoke-test to detect incompatibiltly with next Garden Linux image version

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#7437]
**Description**

During the last releases, we detected that upgrades of the Garden Linux version can have massive impact on particular modules and the Kyma module release pipelines has to verify that a Kyma module is compatible with the NEXT coming Garden Linux version.

This is required to ensure that Kyma modules, after they were released, are not running into trouble when SRE is upgrading a K8s cluster to use the next available Garden Linux version.

![testing_strategy_k8sapi](https://user-images.githubusercontent.com/73824711/230086629-9e1fb573-4c63-4640-8530-0a4c99fdf012.png)

AC:
- [ ] The Kyma module release pipeline is testing the compatibly of a Kyma module with the next Garden Linux version (we can add integrate this step into the K8s compatibility smoke-test)

**Comment by tobiscr** [comment]
Depends on https://github.com/kyma-project/cli/issues/1621

**Comment by TorstenD-SAP** [comment]
Smoke tests are done by the development teams. No need to implement this on our side.
