### ISSUE TITLE
Automatic prow image update on cluster failed.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#7440]
**Description**

Our automation for updating prow images on a cluster is not working.

**Expected result**

Deployments on k8s cluster are updated with changes in yaml files stored in test-infra repository.

**Actual result**

Deployments are not updates. Postsubmit post-test-infra-deploy-prow is failing with error:
```shell
ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=403, message=Required "container.clusters.get" permission(s) for "projects/sap-kyma-prow/zones/europe-west3-a/clusters/prow".
```

**Steps to reproduce**

Run postsubmit post-test-infra-deploy-prow.

**Comment by kasiakepka** [comment]
It is GCP misconfiguration issue.
