### ISSUE TITLE
[Daily Business] Create PR which removes all jobs which are failing for more than 1 week

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#7462]
**Description**

We are facing many jobs which are failing since more than one week. We decided to get rid of these jobs, in collaboration with the team.

AC:

- [x] Create a PR which removes all Prow-Jobs which are failing for more than 7 days in a row
- [ ] Wait 1 week after the PR was opened to give teams an option to remove relevant jobs from this PR
- [ ] After waiting for 1 week, merge the PR and ensure jobs were all successfully erased

**Comment by tobiscr** [comment]
This is a one time activity and doesn't have to run regulalry.

**Comment by halamix2** [comment]
Current list of jobs that are failing for one week:
cli-2.14-whitesource-scan
kyma-cli-compatibility-1
kyma-gke-nightly-rel215
orphaned-assetstore-gcp-bucket-cleaner
post-busola-smoke-test-docker
post-main-k3d-k8s-preview
pre-main-control-plane-reconciler-e2e-latest-release
pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener
serverless-function-metrics-generator
