### ISSUE TITLE
Testing pipeline for custom domain test

### ISSUE THREAD

**Issue by strekm** [kyma-project/test-infra#7478]
**Description**

Implement mandatory pipeline triggered on release branch in api-gateway repo executing custom domain test

**Acceptance Criteria**

- [x] triggered on tag creation on  api-gateway release branch
- [ ] the pipeline should run as first and block other pipelines
- [x] mandatory pipeline
- [x] api-gateway branch image used
- [x] executing custom domain test
- [x] no leftover resources left
- [x] pipeline docu provided

**PR**
- [x] https://github.com/kyma-project/api-gateway/pull/323
- [x] https://github.com/kyma-project/test-infra/pull/7574
- [ ] https://github.com/kyma-project/test-infra/pull/7687

**Prow run**
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/rel-api-gateway-custom-domain-integration/1655461014927314944

**Attachments**

https://github.com/kyma-project/kyma/blob/main/tests/components/api-gateway/features/e2e/custom_domain.feature

**Comment by strekm** [comment]
consider moving the test to api-gateway repository

**Comment by Ressetkk** [comment]
Tekton seems to be the most suitable there. The flow would look like:
Build + push it to dev > Run integrations in parallel starting from grdnr > Promote to prod > do a release.

I could do the same in a script which does the same but runs in a single pod. 

Something like (pseudocode):
```sh
docker build -t europe-docker.pkg.dev/kyma-project/dev/api-gateway:test --push
kyma provision gardener gcp [flags]
make install --image=europe-docker.pkg.dev/kyma-project/dev/api-gateway:test
make custom-domain-test
failed=$?
delete gardener cluster
if not $failed:
    docker tag europe-docker.pkg.dev/kyma-project/dev/api-gateway:test europe-docker.pkg.dev/kyma-project/dev/api-gateway:prod --push
    make GitHub release
exit $failed
```

I will clearly have to look at the possible solutions, but though script would be ultimately dead-easy to implement, still full-fledged CI/CD pipeline is the most promising.
