### ISSUE TITLE
Fix post-main-k3d-k8s-preview and update dependencies

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/test-infra#7499]
**Description**

We updated [post-main-k3d-k8s-preview](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/post-main-k3d-k8s-preview) job to use k8s in 1.27 version and now it is failing.

AC:

- [ ] Job finishes successfully 
- [ ] Update [dependencies](https://github.com/kyma-project/test-infra/blob/main/development/custom-image/install-deps-debian.sh#L17-L25) of the job. nodejs should be updated to 16 and k3d is quite old.
- [ ] As discussed with @zhoujing2022 job should be changed to periodic and run once a day.

**Comment by tobiscr** [comment]
Can be closed... job is gone.

**Comment by Sawthis** [comment]
The job is not gone. Let's do/check it after [upgrade to k8s 1.26](https://github.com/kyma-project/test-infra/issues/7190).

**Comment by Sawthis** [comment]
The best approach would be to rewrite this job to new approach which is not using VM.

**Comment by Sawthis** [comment]
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/post-main-kyma-k3d-k8s-preview is failing again after bump k8s 1.27.

**Comment by Ressetkk** [comment]
/close
Completed by #7951
