### ISSUE TITLE
 Enable end2end tests for Provisioner PRs

### ISSUE THREAD

**Issue by koala7659** [kyma-project/test-infra#7662]
**Current state:**

At the moment any change to Provisioner helm templates does not trigger any test jobs on prow. 
It is a result of recent cleanup activities on prow. 
Some jobs used to verify if updated provisioner image is still functional (like `pre-control-plane-tests-e2e-provisioning`) have been removed.

As a result any change in this area can be merged to main without checking and may possibly break working software on Kyma Control Plane.

**Expected result:**

Any change in Provisioner template is verified by the execution of a test job

**Comment by Disper** [comment]
Should we revert the job deletion that was done in https://github.com/kyma-project/test-infra/commit/d19a57c1e224ea60d8444f946b883841e7e714d0#diff-302a5e6fc8f8fc181f9e5ad473aa0aa63737f771a7aec8ef4a7f181d21468d29 ?

**Comment by Disper** [comment]
Probably reverting `pre-main-control-plane-gke-provisioner-integration` delation will not be possible. 
We're considering now a new e2e test with gardener.

**Comment by Disper** [comment]
Related PR - https://github.com/kyma-project/control-plane/pull/2918 
There will be additional one to the management plane repo.
