### ISSUE TITLE
change branch names in jobs to regex

### ISSUE THREAD

**Issue by atakanyenel** [kyma-project/test-infra#767]
Prow matches branches for jobs using regex. Because of that our jobs can be triggered by other branches that contain the target branch name. 

For example a post-submit job defined for `master` branch can be triggered by making a push to `master-test` branch. To fix it , we have to rename our branches to match exactly the target branch. 

To achieve it , e.g. `master` should be `^master$` in prow jobs. 

To follow the related issue, https://github.com/kubernetes/test-infra/issues/11779

**Comment by lszymik** [comment]
@atakanyenel

Can you please apply proper description of the ticket? Apply labels, milestone, ....
Thank you very much in advance.

**Comment by tehcyx** [comment]
We've just merged the PR to resolve this.
