### ISSUE TITLE
Custom domain test job improvements

### ISSUE THREAD

**Issue by strekm** [kyma-project/test-infra#7692]
**Description**

At this moment custom domain test is running on tag creation in api-gateway repository (release job). Test is running on gcp cluster. Verify and update if needed cluster specification with manage kyma offering. Cluster specification should be as close as it can get to manage kyma offering.

Implement job running (in parallel with other jobs) custom domain test on tag creation in api-gateway repository (release job) on aws cluster. Cluster spec should be the same as kyma managed offering cluster.

**Reasons**

**Acceptance Criteria**

 - [x] gcp cluster spec updated if needed
 - [x] job running in parallel with others executing custom domain test on aws cluster
 - [x] owner and description provided for both jobs
 - [x] job names update
 - [x] running it on 3AZ and similar node specs as on production 

**PRs**
- [x] https://github.com/kyma-project/test-infra/pull/7732
- [x] https://github.com/kyma-project/api-gateway/pull/365

**Comment by videlov** [comment]
Running it on GCP and AWS (slower job)
![Image](https://github.com/kyma-project/test-infra/assets/10164673/c71d8a45-78f0-4c4d-8fb7-23c0ce7340d9)
