### ISSUE TITLE
Maximum number of clusters 

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/test-infra#772]
**Description**

Jobs keep failing with the following error:

```
ERROR: (gcloud.container.clusters.create) ResponseError: code=403, message=Your project already has the maximum number of clusters: (50) in location europe-west3-b.
```

Sample jobs: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1107660251848511488
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1107660251856900096

Could be related to #565

**Comment by tehcyx** [comment]
Is this still valid? #565 was merged. Re-open if problem occurs again.
