### ISSUE TITLE
Reduce the number of resources Prow creates

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/test-infra#774]
**Description**

Right now, we have three jobs creating clusters for **each commit**: `kyma-gke-integration`, `kyma-gke-upgrade`, `kyma-gke-central-connector`, and one job creating VMs: `kyma-integration`. Because of the number of resources these jobs create, we cannot scale well with the number of PRs, and we'll hit hard limits no matter what we do. Cleaners can delay the problems, but cannot solve it altogether. Cost of these resources is also another aspect that we need to keep in mind.

We can discuss further under this issue and come up with solution ideas regarding how we can reduce the number of resources we are using in these jobs.

**Comment by suleymanakbas91** [comment]
Moving to xip.io (see #362) for the integration job in the next release will reduce the cluster creation & deletion times significantly and also reduce the number of resources we use. 

We can investigate if running `kyma-gke-central-connector` for each PR is really necessary. If not, we can switch it to a periodic job.

**Comment by tehcyx** [comment]
#362 will help with this, so for now we can close this.
