### ISSUE TITLE
Increase whitesource scans frequency.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#7744]
**Description**

A Tunas team asked for more frequent execution of whitesource scans. At present we run whitesource scans daily, wheres protecode is running hourly. Team requested to run whitesource hourly as well.

AC:
- [ ]  run the Whitesource scanner periodically for all main-branches with an interval of 1 hour

**Comment by tobiscr** [comment]
@dekiel : is this still valid? I assume with the new sec-backend the issue should be addressed already.

**Comment by Sawthis** [comment]
@tobiscr let's close it, they should be already migrated to the new scanning solution or will be migrated soon.
