### ISSUE TITLE
Refactor all cluster creation jobs

### ISSUE THREAD

**Issue by sayanh** [kyma-project/test-infra#780]
**Description**

There is a ton of code repetition for cluster creation scripts.
All these scripts are based on a single pattern and should be DRYed. In load test script `prow/scripts/cluster-integration/kyma-gke-load-test.sh`, the functions are abstracted, hence can be used a reference.
Following scripts need to be fixed:
- prow/scripts/cluster-integration/kyma-gke-long-lasting.sh 
- prow/scripts/cluster-integration/kyma-gke-integration.sh
- prow/scripts/cluster-integration/kyma-gke-upgrade.sh
- prow/scripts/cluster-integration/kyma-gke-end-to-end-test.sh

**Comment by suleymanakbas91** [comment]
Preferably write them in Go..

**Comment by tehcyx** [comment]
#894 will solve this
