### ISSUE TITLE
Migration to the new k3d integration test image

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#7862]
**Description**

In order to improve image maintainability, performance and CVE management we created new [`e2e-dind-k3d`](https://github.com/kyma-project/test-infra/blob/main/images/e2e-dind-k3d/README.md?plain=1) image designed to be used in k3d tests.
Image: `europe-docker.pkg.dev/kyma-project/prod/testimages/e2e-dind-k3d:v20230612-dadc01a7`

**Expected result**

All k3d integration pipelines are compatible with `e2e-dind-k3d` image.

**Actual result**

Most of the pipelines fail because new image is missing `gcloud` command.

**Steps to migrate**

Most of the pipelines use [`provision-vm-and-start-k3d-and....sh`](https://github.com/kyma-project/test-infra/tree/main/prow/scripts) script or something similar to provision VM and manage GCP resources. With new integration image it is unnecessary.
Here is [basic guide about how to create new k3d pipeline](https://github.com/kyma-project/test-infra/blob/main/docs/prow/k3d-no-ssh.md)
Ideal solution would be to create Prowjob similar to [`pull-istio-integration`](https://github.com/kyma-project/test-infra/blob/6c7686c028043c22501eea563b4560eef2c2682e/prow/jobs/istio/istio-integration.yaml#LL22C11-L22C11). 

**Team checklist:**
Please migrate your k3d pipelines so that they are compatible with new integration image.
We suggest to use SIG quality slack chat or SIG quality call to discuss issues you might have.
 
- [x] @kyma-project/goat 
- [x] @kyma-project/gopher 
- [x] @kyma-project/eventing 
- [x] @kyma-project/hasselhoff 
- [x] @kyma-project/jellyfish 
- [x] @kyma-project/observability
- [x] @kyma-project/framefrog 
- [x] @kyma-project/prow 
- [x] @kyma-project/otters 
- [x] @ebensom SRE
- [x] @kyma-project/cmp

**Comment by Ressetkk** [comment]
/unkind chore
/kind deprecation

This is an issue regarding deprecation of old Kyma-integration image in favor of new one.

**Comment by Disper** [comment]
Hi,
unfortunately, because of some internal incidents and one external one, team @kyma-project/framefrog is unlikely to finish the migration before 14.07.

**Comment by Disper** [comment]
Short update from the @kyma-project/framefrog side: 
We're still working on the incidents and on a newly discovered blocker to the k8s release so sadly we were not yet able to pick this up.

**Comment by mrCherry97** [comment]
Hi, update from @kyma-project/hasselhoff 
kyma-dashboard is fully migrated and whole scripts with VMs are removed.
Busola is partially migrated, integration tests for namespace and cluster are migrated, and scripts with VMs are removed, we have only lighthouse performance test in old way.
