### ISSUE TITLE
Run pre-busola-integration-test-k3s-namespace on kyma-integration image bump.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#7880]
**Description**

Team Hasselhof would like to run pre-busola-integration-test-k3s-namespace on pull request updating eu.gcr.io/kyma-project/test-infra/kyma-integration image. The team would like to make sure image update will not break their tests before new image version will be used on main branch.

**Reasons**

Image bumps in test infra often break hasselhof team tests.

**Acceptance Criteria**

Test pre-busola-integration-test-k3s-namespace run on pull request updating eu.gcr.io/kyma-project/test-infra/kyma-integration image.

**Comment by mrCherry97** [comment]
We have removed VMs and moved gcr to ar. Right now we didn't discover any problems, so the issue could be closed and if will have any problems in the future then we will contact you.
