### ISSUE TITLE
Track failing tests

### ISSUE THREAD

**Issue by sayanh** [kyma-project/test-infra#790]
**Description**

Component tests(e.g. test-monitoring or test-core-core-ui-api-acceptance) are failing randomly in Kyma presubmit/postsubmit jobs. We would like to monitor the failure rates here.

AC:
- Build a service(if needed) to make Prometheus scrap the metrics.
- Build a dashboard/alerts for failed tests.

**Comment by kasiakepka** [comment]
Investigate why ProwJobs are not running when committing changes:
https://github.com/kyma-project/kyma/pull/4833
https://github.com/kyma-project/kyma/pull/5440

**Comment by kasiakepka** [comment]
This issue is related to https://github.com/kyma-project/kyma/issues/5473
Neighbors team for sure will be responsible for delivering Prometheus and Grafana Dashboards. 
It is also important to identify how metrics will be exported to Prometheus and how they are exposed in Octopus.

**Comment by kasiakepka** [comment]
Question of gathering data from Octopus will be covered most likely by Framefrogs. 
Task related to pushing data to Prometheus is here: https://github.com/kyma-project/kyma/issues/5473

**Comment by kasiakepka** [comment]
This issue is covered by testgrid
https://github.com/kubernetes/test-infra/pull/14887
