### ISSUE TITLE
Migrate monitoring stack to operator-based workloads

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#7937]
/area ci
/kind deprecation

This issue is a reminder to migrate our monitoring stack based on https://monitoring.build.kyma-project.io https://github.com/kyma-project/test-infra/tree/main/prow/cluster/components/monitoring to:
Prometheus -> [Prometheus-operator](https://github.com/prometheus-operator/prometheus-operator)
Grafana -> [Grafana-operator](https://github.com/grafana-operator/grafana-operator)

Reason:
* To enable neighbors for creating robust, GitOps-based monitoring stack
* Easier updates of Grafana and its dashboards, and plugins using Kuernetes CRs

AC:
* Grafana, plugins, dashboards deployed using K8s CRs
* deployments of dashboards are managed by kustomize

**Comment by tobiscr** [comment]
Can't we use existing monitoring solutions in GCP for it? Just to minimize our own implementation efforts.

**Comment by Ressetkk** [comment]
When I was making this issue, plan was to replace our current monitoring stack to something more manageable from the GitHub. I haven't taken into the consideration the Google-based solutions, however we'd still need some additional things, like Prometheus, installed on a cluster in a managed way, or not.

**Comment by Ressetkk** [comment]
GCP currently gives pretty much fully managed service with prometheus integration out of the box. For now it's not needed to implement such thing
/close
