### ISSUE TITLE
Pipelines are failing due to missing secrets and connection refused

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/test-infra#7938]
**Description**
The following pipelines are failing to to the following errors:
```
Error from server (NotFound): secrets " *** " not found
```
or

 ```
dial tcp 127.0.0.1:8080: connect: connection refused
```

- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-minor-versions
- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/nightly-main-reconciler
- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e
- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-e2e
- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-e2e-latest-release
- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-ma[…]plane-reconciler-upgrade-kyma2-latest-to-main-gardener
- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener

**Expected result**

Pipelines should not fail during setup.

**Comment by halamix2** [comment]
These issues were caused by the change in prowjobs to default to unprivileged mode
- https://github.com/kyma-project/test-infra/pull/7931/ fixes this issue

**Comment by halamix2** [comment]
The PR was merged, jobs should start now: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-minor-versions/1673614826414280704

**Comment by halamix2** [comment]
You'd need to create a new kubeconfig: https://github.com/gardener/gardener/blob/master/docs/usage/shoot_access.md

**Comment by Sawthis** [comment]
> Note: Static token kubeconfig is not available for Shoot clusters using Kubernetes version >= 1.27. The [shoots/adminkubeconfig subresource](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_access.md#shootsadminkubeconfig-subresource) should be used instead.

https://github.com/gardener/gardener/blob/master/docs/usage/shoot_access.md#static-token-kubeconfig

**Comment by halamix2** [comment]
The issue should be fixed now
