### ISSUE TITLE
[Submission Pipeline] Implement secret rotator

### ISSUE THREAD

**Issue by the1bit** [kyma-project/test-infra#8035]
**Description**

"As a developer I want to implement secret rotators which related to Kyma module release pipeline so that we can manage the secret rotation automatically."

We store Gardener kubeconfig in HashiCorp Vault (Hyperspace). Gardener kubeconfig comes from GCP secret vault, where there is a 30-days (automatic) secret rotation.

At the moment we do two manual secret rotation activities to avoid to stop release pipeline:
1. Every 30 days, we update the Gardener kubeconfig in HashiCorp Vault
2. Every 90 days, we update HashiCorp secret for Azure Pipeline in Hyperspace with button-click

Maybe we need to consolidate these activities, or we need to create 2 secret rotator:

1. Gardener kubeconfig
2. HashiCorp secret

AC:

- [ ] Investigate the possible option to create automation for both secret rotation solution
- [ ] Create a secret rotator for Gardener config (to sync default_gardener-kyma-prow-kubeconfig from GCP to HashiCorp Vault 'PIPELINE-GROUP-3742/PIPELINE-22136/gardenerconfig')
- [ ] Create a secret rotator to HashiCorp Vault secret (to make this manual step to automatic: [my-pipeline-run-fails-with-an-error-that-my-vault-credentials-are-wrong](https://[hyperspace.tools.sap](https://hyperspace.tools.sap/docs/faqs_and_troubleshooting/troubleshooting.html#my-pipeline-run-fails-with-an-error-that-my-vault-credentials-are-wrong)/docs/faqs_and_troubleshooting/troubleshooting.html#my-pipeline-run-fails-with-an-error-that-my-vault-credentials-are-wrong) )

**Comment by TorstenD-SAP** [comment]
No Gardener clusters used anymore. All tests are remove. No need for this anymore.
