### ISSUE TITLE
[CI] Setup alerting for Prow K8s nodes to be informed about the basic operational incidents like exhausted disc capacities, long CPU saturation, OPA Gatekeeper outages etc.

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#8065]
**Description**

One of the Prow K8s nodes was running out of disc space but we didn'T recognise this issue before teams were notifying us about failed jobs.

We have to setup an alerting for our K8s nodes to be informed before issues are interrupting our teams. 

AC:
- [x] Alert when OPA Gatekeeper is malfunctioning / not available
- [x] Verify what values make most sense for our infrastructure. Present results to the team.
- [x]  Setup monitoring for GCP and monitor  for those critical values
- [x] After gaining experiences (2 weeks) of the load-profile of our machines, configure suitable alerting rules (fitting to our use-cases)

**Comment by Ressetkk** [comment]
So far I've created one log-based metric for recent problem described in #8473 with alerting in a channel.
Enabled managed prometheus on the clusters

/assign

**Comment by Ressetkk** [comment]
Additionally by default GKE provides default dashboard that gives complete information about all clusters and workloads. I believe it should be enough to manage and gather information about all incidents in clusters. https://console.cloud.google.com/monitoring/dashboards/resourceList/kubernetes?project=sap-kyma-prow

**Comment by Ressetkk** [comment]
Created log-based metric that fires alerting when gatekeeper fails scheduling with reason that it doesn't match the affinity. I believe this will be sufficient enough for our needs for now.

/close
