### ISSUE TITLE
K3d jobs failing

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#8069]
**Description**

Teams are complaining about unstable and low performing Prow jobs when using DIND for executing K3d within a pod.

Following issues were identified:

1. **Docker failure during pod bootstrap**: Inotify-watches limit is exhausted (see https://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached)

   *   **workaround**: increasing the limit on kernel-level solves the problem (see https://www.baeldung.com/linux/inotify-upper-limit-reached#2-inotify-watch-limit)
   *  **long-term solution**:

       1. verify if the amount of Inotify-watches stays stable or increases (could be a bug in docker?)
       2. apply a script for any new created K8s worker-node VM which increases the limit of Inotfiy-watches to 100k
 
2. **Performance is slow of executed e2e jobs**: VMs are starting to SWAP memory, further investigation required

   * **workaround**: current VM size is quite small (16GB) and could execute just 2-3 end-to-end jobs in parallel. We will try new VM types which have more RAM available and monitor the stability.
   * **long-term solution**: find adequate VM machine type for new load situation

**Comment by Ressetkk** [comment]
There are no subsequent complaints from the devs for several days. I can mark this as resolved.

* Upgraded cluster
* Switched to Cgroupsv2

/close
