### ISSUE TITLE
[CI] Replace Grafana container image with Plutono

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#8072]
**Description**

We are currently using Grafana within our Prow CI/CD system for visualisation purposes. We are currently sticking to a particular quite old Grafana version as the newer versions have incompatible licenses.

This can collide with security requirements as we have sometimes to use newer images to get sec-vulnerabilities solved.

We agreed with our security expert to replace Grafana with the license conform Plutono (https://github.com/credativ/plutono). Goal of this issue is to apply this change and remove Grafana from our deployments and use Plutono instead.

AC:
- [ ] Adjust the deployment of Grafana and use [Plutono](https://github.com/credativ/plutono) as replacement (use an IaC approach for the deployment)
- [ ] Verify that existing graphs also exist in Plutono

**Comment by Ressetkk** [comment]
Why do we have to use Apache-based Grafana? We do not break any licensing if we use it for our internal monitoring

**Comment by Sawthis** [comment]
Grafana will be removed in https://github.com/kyma-project/test-infra/pull/9398
