### ISSUE TITLE
Refactor prow production from prow test

### ISSUE THREAD

**Issue by sayanh** [kyma-project/test-infra#808]
**Description**

`starter.yaml` has configurations for workload cluster which can be a bit heavy for Prow development environment.
Either
- A separate setup for prow production and development environment. This can be challenging to maintain.
Or
- Add more patches like `cluster/00-deck-patch.yaml`

**Comment by suleymanakbas91** [comment]
At the moment, we have `starter.yaml` with the workload cluster configuration which can't be used for creating a test cluster. Also, for updating the production cluster, we have some parts in `starter.yaml` which need to be removed before applying. So, the current status of `starter.yaml` is not good for any environment.

We can adapt the same structure as Kubernetes for this. We should separate the prow components into different files and keep `starter.yaml` as light as possible only for the test cluster, like [here](https://github.com/kubernetes/test-infra/tree/4d676492b2e64d876aff9cfd22b8c06e0eeb8bac/prow/cluster)

**Comment by tehcyx** [comment]
Changes merged
