### ISSUE TITLE
Setup monitoring for prow and workload cluster

### ISSUE THREAD

**Issue by sayanh** [kyma-project/test-infra#813]
**Description**

Improve monitoring of Prow and Workloads cluster (in sap-kyma-prow project)

**Comment by tehcyx** [comment]
The k8s/prow team is changing some monitoring themselves right now. An initial config can be found here: 
https://github.com/kubernetes/test-infra/blob/master/prow/monitoring/grafana_configmaps.yaml

For this dashboard: http://monitoring.prow.k8s.io/d/970b051d3adfd62eb592154c5ce80377/prow-dashboard?orgId=1

They're adding more tomorrow: https://kubernetes.slack.com/archives/CDECRSC5U/p1560895409226300

Also there seems to be an issue that they found with how we're currently monitoring success rates and we might have to adjust our dashboard that is currently on grafana.

**Comment by tehcyx** [comment]
https://kubernetes.slack.com/archives/CDECRSC5U/p1560972498247200 new dashboards of k8s that got released today.
https://monitoring.prow.k8s.io/d/UPkOaX7Zk/github-cache?orgId=1

**Comment by dekiel** [comment]
Latest changes in grafana dashboard documentation. We should check if we can reuse configuration.

https://github.com/kubernetes/test-infra/pull/14610
