### ISSUE TITLE
Create proposal for release process

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#82]
- How to release new kyma version using Prow
- How to release patch for kyma?
- Check an approach used by others(Istio, etc)

AC:
- documentation with described concept

**Comment by derberg** [comment]
Please do not do any work in this area without syncing with people that work now on release process.

**Comment by derberg** [comment]
As long as you do not try to move current release pipeline from jenkins to prow 1:1  in this task, that is fine.
