### ISSUE TITLE
Introduce TestGrid

### ISSUE THREAD

**Issue by sjanota** [kyma-project/test-infra#820]
**Description**
TestGrid is a tool in kubernetes test-infra portfolio which helps with visualisation of test history.  
Let the example be view of [istio integration tests](https://testgrid.k8s.io/istio-presubmits#integration-k8s-tests). Most important features:
* Single page to see history of all tests within a job
* You can easily navigate to logs of failed job to see reason of the error
* You can easily see test duration
* Get aggregates about test history as percentage of failing tests
* Get alerts about flaky and failing tests

**Reasons**
Our test suite is not really stable. It is often hard to get PR to mergeable state because of random failures in infrastructure, installation or tests. To fight with this problem we need decent monitoring in place to understand it better and react quicker. It will also make life of people on CI force a lot easier as they will no longer need to search logs to find out failed tests. 

**Attachments**

**Comment by suleymanakbas91** [comment]
Is it even open-source? @sjanota

**Comment by michal-hudy** [comment]
It is not open source yet: https://github.com/kubernetes/test-infra/issues/10409

**Comment by sjanota** [comment]
That's true, we need to wait until they are ready.
