### ISSUE TITLE
plank is using cluster-admin clusterrole

### ISSUE THREAD

**Issue by sayanh** [kyma-project/test-infra#823]
**Description**

While upgrading Prow, I couldn't create a new Role for plank in Prow production cluster due to HTTP 403 issue. I don't understand this as I'm an owner already. In order to get plank working I created a rolebinding for plank using cluster-admin clusterrole, which needs to go away ASAP.
Edit: May be, I should've done
```
kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=$(gcloud config get-value account)
``` 
before creating a new role.

**Expected result**

Plank role should be as in [here](https://github.com/kyma-project/test-infra/blob/master/prow/cluster/starter.yaml#L570)
 
**Actual result**

**Steps to reproduce**

Failure occurs when you try to create a role/clusterrole in Prow production cluster.

**Comment by dekiel** [comment]
Removed cluster-admin clusterrolebinding for plank.
