### ISSUE TITLE
kyma-gke-nightly fails due to resource already created

### ISSUE THREAD

**Issue by tuxgoose** [kyma-project/test-infra#826]
What happened:
kyma-gke-nightly fails due to resource already created
What you expected to happen:
job to continue to run even though resource exists
How to reproduce it (as minimally and precisely as possible):
re-run the job in prow
Please provide links to example occurrences, if any:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-gke-nightly/1112565485645336578

Anything else we need to know?:
ERROR: (gcloud.beta.compute.addresses.create) Could not fetch resource:

The resource 'projects/sap-kyma-prow/regions/europe-west3/addresses/nightly' already exists
{"component":"entrypoint","error":"wrapped process failed: exit status 1","level":"error","msg":"Error executing test process","time":"2019-04-01T04:03:15Z"}

**Comment by tehcyx** [comment]
Manual cleanup of a DNS record and the IP solved this issue for the time being, but there's some deeper issues with the cleaners which we will have to address:
https://github.com/kyma-project/test-infra/issues/828
https://github.com/kyma-project/test-infra/issues/829

**Comment by sayanh** [comment]
@tehcyx Turns out the job is still failing, please check out the logs from today's run https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-gke-nightly/1112927874194608130

Did manual clean up break anything?

**Comment by tehcyx** [comment]
With https://github.com/kyma-project/test-infra/pull/843 I'm rolling back the changes that are breaking the build right now.

The manual removal should not interfere and the errors are expected when a manual clean removes IPs /DNS entries that should get deleted.

**Comment by Demonsthere** [comment]
What is the status here? Is this stil valid, can we close it?

**Comment by tehcyx** [comment]
Hi @Demonsthere, we have two open PRs that allow us, when merged, to close this ticket.

**Comment by kasiakepka** [comment]
https://github.com/kyma-project/test-infra/pull/1407
