### ISSUE TITLE
Disk cleaner is not cleaning disks properly based on the regex for periodic clusters

### ISSUE THREAD

**Issue by tehcyx** [kyma-project/test-infra#828]
**Description**
The disc cleaner is not cleaning up disks properly for periodic clusters. The regex does not catch these clusters' disks.

https://github.com/kyma-project/test-infra/blob/master/prow/jobs/kyma/kyma-integration.yaml#L351

**Expected result**
Disks should be removed.

**Actual result**
Some disks are not deleted after cleaner run.

**Comment by michal-hudy** [comment]
Currently, we have ~1700 disks. Most of them should be removed.
