### ISSUE TITLE
Add TestGrid to Prow

### ISSUE THREAD

**Issue by sjanota** [kyma-project/test-infra#832]
**Description**
TestGrid should ba available as part of our Prow.

**Reasons**
TestGrid provides functions that will make our CI force life a lot easier and will give us more insight in our test stability.

**Attachments**

**Comment by sjanota** [comment]
This needs to wait for TestGrid to be open source.

**Comment by tehcyx** [comment]
Hello, lets discuss to publish results on k8s testgrid.

**Comment by kasiakepka** [comment]
There was an agreement to use k8's testgrid.
The first task is to talk to K8 guys and gather information how to use their tide.

**Comment by kasiakepka** [comment]
Please add:
- documentation how to make changes to testgrid configuration
- add OWNERS file

**Comment by tehcyx** [comment]
OWNERS is merged, documentation PR is open.
