### ISSUE TITLE
kyma-aks-nightly job fails

### ISSUE THREAD

**Issue by sayanh** [kyma-project/test-infra#833]
**Description**

Periodic prow job `kyma-aks-nightly` keeps failing:

> ERROR: (gcloud.kms.encrypt) could not parse resource []

Failed runs are as follows:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-aks-nightly/1112927874194608131

**Expected result**

The job should be green.

**Actual result**

It is red.

**Steps to reproduce**

**Troubleshooting**

**Comment by tehcyx** [comment]
PR open to unblock this with a rollback. https://github.com/kyma-project/test-infra/pull/843

**Comment by aszecowka** [comment]
Currently provisioning cluster is blocked by: https://github.com/kyma-project/test-infra/pull/862

**Comment by tehcyx** [comment]
cert PR got merged, this should be solved.
