### ISSUE TITLE
Failed to create DNS records in Prow jobs

### ISSUE THREAD

**Issue by sayanh** [kyma-project/test-infra#841]
**Description**

Although the DNS record doesn't exist(meaning it was cleaned up well), job could not create DNS.

Failed builds are as follows:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1113048546749190145
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1113056348020412418

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by sayanh** [comment]
As dicussed, a quick fix would be to delete the transaction.yaml after the 1st installation is done and go for the upgrade. may be printing the `transaction.yaml`will help here.

**Comment by tehcyx** [comment]
This should be covered by moving the scripts to golang: https://github.com/kyma-project/test-infra/issues/829

**Comment by tehcyx** [comment]
Most recent case brought to attention: https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-gke-integration/1126111380202590211/build-log.txt
