### ISSUE TITLE
Upgrade plan resiliency

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/test-infra#842]
**Description**

The upgrade plan calls github to retrieve the last release and uses artifacts from it. Today we had a situation in which the call was unresponsive and could not complete (got an 403). Because of that further steps failed. 

**Reasons**

Currently we do not check if the value returned by `curl` is empty, or a valid version, This should be improved, and fail if the version is empty or otherwise invalid

**Attachments**

Error when curl fails:

```
Tue Apr  2 13:17:48 UTC 2019
curl: (22) The requested URL returned error: 403 Forbidden
```

Further steps when release is not retrieved:

```
#################################################################################################
# Install Tiller from 
#################################################################################################
    
Tue Apr  2 13:25:09 UTC 2019
error: unable to read URL "https://raw.githubusercontent.com/kyma-project/kyma//installation/resources/tiller.yaml", server reported 404 Not Found, status code=404
```

**Comment by tehcyx** [comment]
PR has been merged.
