### ISSUE TITLE
It is possible to introduce broken links

### ISSUE THREAD

**Issue by sjanota** [kyma-project/test-infra#847]
**Description**
Governance job is triggered only if documentation files have changed. However, links in docs may get broken, because other files may be moved around. This is a gap in our PR checks and may introduce broken links on master.

**Expected result**
Every change merged to master is safe

**Actual result**
Broken links may get merged to master. It makes governance fail on master and blocks others from merging their PRs.  

**Steps to reproduce**
Merge a PR which moves a file linked in docs to different location

**Troubleshooting**

**Comment by pkosiec** [comment]
Actually, our current solution for this possible issue was introducing periodic checks for every link, and we have that already implemented. Scanning all files during PR takes just too much time, so it’s a no-go.
