### ISSUE TITLE
Set up a new GCP project for GKE integration jobs

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/test-infra#850]
**Description**
Kyma developers should have access to clusters created by integration jobs. Now, these clusters are created in Prow project and only Prow administrators have access there. We can spin up clusters in the separate project where all Kyma developers have read access.
Additionally, they will get access to logs from active and deleted clusters (through stackdriver).

Please set up a new GCP project and update prow jobs accordingly.

**Reasons**
Debugging errors in K8s is hard on it's own. There are many environment-specific factors. Now we have our CI where we integrate changes across many components in parallel and this introduces many points of failure that are hard to predict.

At the same time, we don't have access to the integration clusters, so often we have to guess what went wrong. Logs from components can be improved to a point, but infrastructure issues like networking, security policies, RBAC, certificate failures etc are often hidden behind some generic errors like "i/o timeout".

**Comment by michal-hudy** [comment]
Logs older than 30 days are automatically removed from `Stackdriver`. https://cloud.google.com/logging/quotas

**Comment by pbochynski** [comment]
Then we can skip the cleanup step :)

**Comment by tehcyx** [comment]
Stories of this epic:
- https://github.com/kyma-project/kyma/issues/3725
- https://github.com/kyma-project/kyma/issues/3726
- https://github.com/kyma-project/kyma/issues/3727

Zenhub decided to not create them on test-infra repo...

**Comment by tehcyx** [comment]
Moved the issues into the test-infra repo:
#919
#918
#917
