### ISSUE TITLE
Run terraform-executor always on newest base branch

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#8593]
**Description**

Executing a terraform commands on pull requests should always use a current base branch HEAD commit. This will ensure proposed changes are always tested against current state.
To assemble merge commit with current base branch HEAD we could use [Checkout Merge](https://github.com/marketplace/actions/checkout-merge) GitHub action. If that will not be possible we can replicate steps executed by prow clonerefs decorator container.

**Reasons**

At present github workflow is testing against pull request base branch ref which over time can be behind a base branch HEAD.

**Acceptance Criteria**

- [ ] Terraform commands running in github workflow on pull request, are always tested against base branch HEAD.

/kind feature
/area automation

**Comment by halamix2** [comment]
After some testing I came to this conclusion:
- checking out `refs/pull/${{ github.event.number }}/merge` will return a branch properly rebased to the latest HEAD of the base branch, no need for change
- the job definition used in re-runs won't update, even with changes pushed to base branch, unless the PR branch is updated as well (either rebase or any new commit)
