### ISSUE TITLE
[Daily Business] Add terraform config for GCP Workload Identity Federation for GitHub

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#8594]
**Description**

GCP workflow identity federation for GitHub must be covered by our IAC. Initial attempt failed because of terraform config apply errors which was caused by potential bug in google provider.
IAC for GCP WIF for GH: #8262 
Revert IAC for GCP WIF for GH: #8339 

The revert pull request contains details about terraform apply errors and expected valid values.

**Reasons**

All infrastructure and application components must be managed through IAC.

**Acceptance Criteria**

- [x] GCP Workload Identity Federation for GitHub is managed through Terraform config.
- [x] GitHub workflow variables for GCP auth github action are managed through Terraform config.
- [x] Plan action has read only permission in gcp

/kind feature
/area automation

**Comment by dekiel** [comment]
@KacperMalachowski please remember about mapping plan action execution to the service account with read only permissions. Think about adding it to the AC list.

**Comment by KacperMalachowski** [comment]
Follow up as the update of role is blocked by Prow: https://github.com/kyma-project/test-infra/issues/10075
