### ISSUE TITLE
Build jobs fails sporadically that cannot connect to buildkitd.sock

### ISSUE THREAD

**Issue by dzahariev** [kyma-project/test-infra#8676]
**Description**
Build jobs (pull-* and pre-*) fails sporadically with following error:

```
...
could not connect to unix:///run/user/1000/buildkit/buildkitd.sock after 10 trials
...
```
Example for such jobs are:
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_serverless-manager/209/pre-serverless-operator-build/1689906849505087488
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_serverless-manager/199/pre-serverless-operator-build/1688549421492473856
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-incubator_compass/3204/pull-director-build/1691354000907046912
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-incubator_compass/3213/pull-tests-build/1691093347290058752

Most of the time after retry the job is executed properly, but in some cases the issue appear again several time in a row.  

**Expected result**

The build to be executed.

**Actual result**

The build is not started at all, as the buildkitd seem to not be started inside the container, or the resources are not sufficient and the process is not able to start for the predefined time (I can see there are 10 attempts performed). 

**Steps to reproduce**

Sporadically happens.

**Troubleshooting**

Retry the job

**Comment by tobiscr** [comment]
As we are moving to a different image-build solution, this bug can be descoped.
