### ISSUE TITLE
Firewall cleaner is repeatedly failing

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#868]
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/firewall-cleaner/1115355123967594496

```
Failed to open /logs/process-log.txt: open /logs/process-log.txt: no such file or directory
```

**Comment by Demonsthere** [comment]
Hi,
This was probably connected to a typo in the image path introduced in the latest change. A fix for that has been already merged: https://github.com/kyma-project/test-infra/pull/867
