### ISSUE TITLE
Approve used GitHub Actions

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#8760]
**Description**

In test infra we have one GH workflow that runs terraform plan and returns results as a PR check and a comment on a PR: https://github.com/kyma-project/test-infra/blob/main/.github/workflows/pull-plan-prod-terraform.yaml
It uses three actions, that aren't official Github actions:
- ahmadnassri/action-workflow-queue@v1 -  limits workflow to only one instance, terraform locks state and can't run two jobs simultaneously
- shmokmt/actions-setup-github-comment@v2 & shmokmt/actions-setup-tfcmt@v2 - installs Terraform commenter (can comment on open PRs)
We need to get security team approval for this actions. Following are open points for actions we use.

Regarding shmokmt/actions-setup-github-comment@v2
Can be used under the following circumstances:

Since the action is only a wrapper for a go tool https://github.com/suzuki-shunsuke/github-comment, the exact version of the tool must be used (can be done by give a version tag as parameter: https://github.com/shmokmt/actions-setup-github-comment/blob/main/install.sh)
We need to use a hash of a commit of the action representing the version we use. E.g. the hash of version 2.0.0 of the action is  f415209aa2ee3eb9b3a864c7d5f8f712f1fb3cdf, in the form shmokmt/actions-setup-github-comment@f415209aa2ee3eb9b3a864c7d5f8f712f1fb3cdf to add the action to the allow list.

ahmadnassri/action-workflow-queue@v1.1.5 - 0144da6a252d1986d817826d963ad3a9af1e7fdf
shmokmt/actions-setup-github-comment@v2.0.0 - f415209aa2ee3eb9b3a864c7d5f8f712f1fb3cdf
shmokmt/actions-setup-tfcmt@v2.0.0 - ce273d5d7e0e3d02ad7b197a5631f6b5307936e2

Unfortunately following actions from shmokmt have bad ratings in the Scorecard tool. Are there any alternatives?
- actions-setup-tfcmt: ~~3.4/10~~ 4.4/10
- actions-setup-github-comment: 3.5/10)

actions-setup-tfcmt maybe could be replaced with https://github.com/shirakiya/setup-tfcmt. This action has a much better rating (5.9/10) than the one which is used atm.
Downloading the tools isn't necessary as long as we pin a dedicated version in the action.

We still need to download the github-comment tool, I'll ask tomorrow in the team if we should just download binaries directly/create custom action instead of using external actions

Alternativelly, can this one https://github.com/thollander/actions-comment-pull-request be used as an alternative?

**Reasons**

Our GitHub workflows must be compliant with policies and use required settings.

**Acceptance Criteria**

- [ ] pull-plan-prod-terraform GitHub workflow is approved by security team.

**Comment by halamix2** [comment]
- https://github.com/thollander/actions-comment-pull-request - cannot hide comments
- https://github.com/int128/hide-comment-action - 5.2 - can hide by author, cannot specify PR
- https://github.com/kanga333/comment-hider - 4.2 - can be used on specific PR/issue
- https://github.com/KekeHub/hide-comments - 4.5 - can be used on specific PR/issue

**Comment by halamix2** [comment]
actions-setup-tfcmt score was bumperd from 3.4 to 4.4

**Comment by Sawthis** [comment]
https://github.com/kyma-project/community/pull/844
