### ISSUE TITLE
failing api-gateway integration test on aws prow job

### ISSUE THREAD

**Issue by strekm** [kyma-project/test-infra#8802]
**Description**

Since more than 2 weeks api-gateway integration tests on aws prow job is failing with `Error: failed to initialize the Kubernetes client from given kubeconfig: Get "https://api.seiwhvakky.kyma-prow.shoot.live.k8s-hana.ondemand.com/api?timeout=30s": read tcp 10.109.1.46:38946->16.16.190.162:443: read: connection reset by peer - error from a previous attempt: read tcp 10.109.1.46:38932->16.16.190.162:443: read: connection reset by peer`. Since then region has been change and retry logic was introduced along with additional sleep (!). 

This prow job is essential for api-gateway development and it is a blocker for modularisation.

**Expected result**

green prow job

**Actual result**

red prow job

**Steps to reproduce**

run api-gateway integration aws prow job

**Troubleshooting**

error: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_api-gateway/484/pull-api-gateway-integration-aws/1696409582953304064
overall status: https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pull-api-gateway-integration-aws?buildId=

**Comment by Ressetkk** [comment]
Seems to be fixed with recent quota increase on AWS project. Now limit is 50 IPs for EC2 instances.
/close
