### ISSUE TITLE
Use project files for mockery

### ISSUE THREAD

**Issue by halamix2** [kyma-project/test-infra#8851]
**Description**

Currently we're using Mockery v2 with the `//go:generate` comments, which will be removed in version v3.

* [ ] convert existing `//go:generate` comments into new package config: https://vektra.github.io/mockery/latest/configuration/

/kind deprecation
/area tests

**Comment by tobiscr** [comment]
@halamix2 : is this issue still valid or can it stay as closed?

**Comment by halamix2** [comment]
It would be relevant if we ever bumped mockery from v2 to v3, but that should arise automatically when running tests in the bump PR
It can stay closed for now
