### ISSUE TITLE
Slack notifications from Prow are sometimes duplicated

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#887]
Sending Slack notification is done by `development/prow-addons-ctrl-manager`. Sometimes we can see 2 notifications for the same job:

<img width="506" alt="Screenshot 2019-04-15 at 09 00 54" src="https://user-images.githubusercontent.com/476407/56113068-1034be00-5f5d-11e9-939f-c413edf9aa98.png">

In this case, the job was executed only once.
Also, there is only one Prowjob for this job:
```
 kubectl get prowjob -l prow.k8s.io/job="kyma-load-tests-weekly"
NAME                                   AGE
42e3452c-5f22-11e9-a5e5-0a580a2c4b3c   4h
```

**Comment by kasiakepka** [comment]
Please try to review CI-Force channel if there are any adjustments required (related to alerting).

**Comment by tehcyx** [comment]
Changes merged. The job cache is not updated fast enough, so there's a 500 ms throttle now. We'll monitor if we need to increase that time.
