### ISSUE TITLE
[CI] Cluster Cleaner script is not cleaning outdated clusters properly

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#8885]
**Description**

We detected that the cluster cleanup script is no longer working correctly and outdated clusters are not cleaned up.

It also seems that clusters were created by using custom scripts and they are also not considered by the cleaner script.

We have to anaylze the situation why clusters are not correctly removed and where these "mysterious" other clusters are coming from.

**Expected result**

Cleanup of outdated cluster is working and capacity limits of our cloud-accounts are not exhausted.

**Actual result**

Cloud account limits are reached and new clusters cannot be created.

**Steps to reproduce**

**Troubleshooting**

**Comment by halamix2** [comment]
* Clusters are not set for immediate deletion
* cleaner got broken after switch from Debian to Alpine abse due to changes in `date` behavior
    * fixed in #8886, now the cleaner should properly clean clusters
