### ISSUE TITLE
[CI] Governance job: migration to Github Action Link-Checker

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#8889]
**Description**

We decided to use the Github Link Checker Action for verifying valid hyperlinks in our documentation. We have to update our governance jobs to follow this new approach and convert the `test-infra` governancen job to use this particular Github Action step.

The job should be executed for each PR but also once a day for the `main`-branch to detect broken / no longer working links. As a example you can check kyma or community repository which was already migrated.

**Reasons**

Update the governance job to the Kyma wide agreed link checker approach.

**Acceptance Criteria**
- [x] The governance job for `test-infra` is based on the Github Action link checker.
- [x] Governance job is executed per PR but also at least once per day for the main branch.
- [x] Fix broken links.
- [x] Help Hasselhofs migrate Busola from milv to GH actions.
- [x] Remove governance jobs, archive milv repository and do cleanup of images etc. 

**Attachments**

**Comment by Sawthis** [comment]
https://github.com/kyma-project/busola/pull/2591
