### ISSUE TITLE
GCP Stackdriver for minikube pipelines

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/test-infra#901]
**Description**

The current configuration of stackdriver can retrieve the logs from all pods running on the GKE clusters, which allows the developers some sort of debugging options without the need to access the cluster. Additionally, view permissions are sufficient to access those logs. 

**Problem**

Currently only the GKE clusters are able to log meaningful data, while the minikube vms only log the fact that they are created. We need to investigate why we don't log the minikube state here. 

**Attachments**

![image](https://user-images.githubusercontent.com/13346689/56206744-5bc69500-604d-11e9-9dfb-0b44221c01af.png)

**Comment by suleymanakbas91** [comment]
I think it'll be enough to install the Stackdriver agent to the VM and in the end copy the logs over to Stackdriver path from `/var/log/containers` folder inside Minikube.

**Comment by Demonsthere** [comment]
I have found that there exists a build-in GCP role: `logsViewer` and `privateLogsViewer`. I have tested it, and they are enough for users to view the logs, but not be able to view secrets or any other sensitive data.

**Comment by kasiakepka** [comment]
We managed to install fluentd and setup gcplogs drived for docker containers however logs are incorrectly parsed (json formatting is not enabled). It will require additional configuration on fluentd side.

https://docs.docker.com/v17.09/engine/admin/logging/gcplogs/

**Comment by kasiakepka** [comment]
I updated install-deps-debian.sh so that it installs google-fluentd and sets up docker log driver.
I have issues figuring out how to configre google-fluentd to fix json log parsing issue (each json line is treated as separate log event).

**Comment by kasiakepka** [comment]
Above changes had to be reverted, see more details here: https://github.com/kyma-project/test-infra/pull/1098
