### ISSUE TITLE
[IaC] Check feasibility of migrating to OpenTofu and update or IaC solution to use OpenTofu (if it is feasible)

### ISSUE THREAD

**Issue by halamix2** [kyma-project/test-infra#9069]
**Description**

Terraform 1.6+ has changed license; the Linux foundation has forked terraform and are supporting it still under MPL 2.0 license.

The SAP managment is still clarifying whether SAP is allowed to use Terraform without licensing issues. But for team, who see a chance to migrate to OpenTofu with acceptable efforts, it's recommended to switch.

AC:
 - [x] Evaluate openTofu
     - [x] Check if there are breaking changes
     - [x] Check if tools we use support openTofu
     - [x] Share results with the team and point out the parts which are causing additional effort to get them working again
- [x] If the technical impacts are acceptable (depending on the evaluation outcomes):
    - [x] migrate existing terraform code to run with Open Tofu
    - [x] update the current Github flows to use Open Tofu instead of Terraform

**Comment by kvendingoldo** [comment]
btw. you can also integrate [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management.
