### ISSUE TITLE
Create periodic ProwJob for MinikubeVM load tests

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/test-infra#907]
**Description**
Since the beginning of April we have seen more and more instances in which the minikube (and only minikube) pipelines fail due to network errors like `getsockopt: connection refused`. 
As this happens randomly and is related to either some network problems, or infrastructure problems we need some sort of debugging possibility here. 

**Reasons**
After some talks we came to the conclusion that we need to create a periodic job, that will run the minikube pipeline every 1-2 hours and in the case of an error, leave the cluster for investigation. In the case of a success, it can be removed. 

**Attachments**

Related to https://github.com/kyma-project/kyma/issues/3622

**Comment by pkosiec** [comment]
@Demonsthere 

@aszecowka have been able to reproduce this error on local machine. It means that this is not only CI issue (related for example for Minikube without driver mode).

**Comment by pkosiec** [comment]
This task is related to this issue: https://github.com/kyma-project/kyma/issues/3622

@Demonsthere can we reduce the number of issues and keep just one?
