### ISSUE TITLE
feat: automatic cloning of multiarch images by image-syncer

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#9145]
/kind feature
/area ci

It's starting to be frequently requested feature - image-syncer has to be able to clone images for all architectures for specific image.
When developer adds an image that is multiarch image-syncer should be able to distinguish between single image and image index, walk over all images in the index and clone them accordingly to the repo, and tag it with provided tag.

**Comment by halamix2** [comment]
By default image syncer expects the given name to point to a image index, which is synced (with all architectures)
Users have to explicitly set `amd64Only: true` if they want to sync singular image: https://github.com/kyma-project/test-infra/blob/5a37509c0493d88aaa2425205f5693cf67e5d038/cmd/image-syncer/main.go#L190

**Comment by tobiscr** [comment]
Descoping this feature as image-syncing need a refinement to consider also signing of 3rd party images. We clone only these images which are required to deploy Kyma on the officially supported architectures.
