### ISSUE TITLE
Move existing integration job execution to new GCP project

### ISSUE THREAD

**Issue by tehcyx** [kyma-project/test-infra#918]
@tehcyx commented on [Mon Apr 15 2019](https://github.com/kyma-project/kyma/issues/3726)

Move all integration job execution to the newly created GCP project

**Comment by kasiakepka** [comment]
I suggest to align the changes with https://github.com/kyma-project/test-infra/pull/1100 and test simultaneously.

**Comment by kasiakepka** [comment]
Current status:
- sap-kyma-prow Service Accounts have the same privileges to sap-kyma-workloads project
- New DNS zone is created
- all cleaners rely on CLOUDSDK_CORE_PROJECT variable so there should be no issues
- test pre-master-kyma-integration-new-project job works as expected

ToDo:
- Update github authenticated apps (update nightly.build.kyma-project.io. domain name) after implementation
- agree on implementation plan and update presets/variables (also https://github.com/kyma-project/test-infra/pull/1100)
- update https://github.com/kyma-project/test-infra/blob/48f460794bb9c332cb1e35f5a7ce297bfcddb1ae/development/tools/pkg/firewallcleaner/cleaner_test.go#L171
