### ISSUE TITLE
[Daily Business] Kyma-bot token is expired

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/test-infra#9186]
**Description**

The Kyma-bot token expired. It's assumed that this account is still used (if not, please close this issue). 

If it's used, please renew the token.

**Reasons**

Regular account token renewal.

**Acceptance Criteria**

Either account is no longer used (no further action requried) or token was renwed.

**Attachments**

**Comment by Ressetkk** [comment]
It's not a feature. Already resolved.
/remove-kind feature
/kind bug
/close
