### ISSUE TITLE
Autobump periodic prowjobs failing.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#9216]
Periodic autobump prowjobs are failing starting from 26.10.
Prowjobs are not scheduled and report errors due to gatekeeper admission webhook denied scheduling pods.

https://status.build.kyma-project.io/?type=periodic&state=error

```
description: 'Pod can not be created: create pod default/b1846354-ecc1-4d6a-846d-babdeccdef4f
    in cluster trusted-workload: admission webhook "validation.gatekeeper.sh" denied
    the request: [kyma-autobump-bot-github-token] Container test is not allowed to
    use restricted secret: kyma-autobump-bot-github-token.'
```

**Comment by halamix2** [comment]
- https://github.com/kyma-project/test-infra/pull/9259
