### ISSUE TITLE
Autobump error notification has no link to logs.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#9217]
Slack notification about failed periodic autobump prowjobs doesn't contain link to logs under text <|View logs>.

![Image](https://github.com/kyma-project/test-infra/assets/12400578/a7dec1f5-affb-4db9-b245-c43803a18cd6)

**Comment by Ressetkk** [comment]
Duplicate of https://github.com/kyma-project/test-infra/issues/9216
/close
