### ISSUE TITLE
Pipelines are failing due to cluster cannot be created

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/test-infra#9299]
**Description**
Some pipelines are failing since they want to create a k8s cluster with version 1.27.7, but this is not supported until now.

```
error when creating "STDIN": shoots.core.gardener.cloud "rec-main-fr" is forbidden: [spec.kubernetes.version: Unsupported value: "1.27.7": supported values: "1.27.6 (preview)", "1.27.5", "1.27.4", "1.27.3", "1.26.9 (preview)", "1.26.8", "1.26.7", "1.26.6", "1.26.5", "1.25.14 (preview)", "1.25.13", "1.25.12", "1.25.11", "1.25.10", "1.24.17", "1.24.16", "1.24.15", "1.24.14"]
```

Examples:
- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/nightly-main-reconciler
- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-e2e-latest-release

**Expected result**
Either go back to supported version or support version 1.27.7

**Actual result**
Cluster cannot be created, since it only supports 1.27.6 (preview)", "1.27.5", "1.27.4", "1.27.3", "1.26.9 (preview)", "1.26.8", "1.26.7", "1.26.6", "1.26.5", "1.25.14 (preview)", "1.25.13", "1.25.12", "1.25.11", "1.25.10", "1.24.17", "1.24.16", "1.24.15", "1.24.14".

**Steps to reproduce**

**Troubleshooting**

**Comment by ruanxin** [comment]
@Ressetkk , the pipeline job still fail in the recent run, however, I saw the image already updated https://github.com/kyma-project/test-infra/blob/32628507717a7ee73d165a861798b119ee17479b/prow/jobs/kyma-incubator/reconciler/reconciler.yaml#L537

**Comment by Ressetkk** [comment]
Looks like I omitted the shoot template. On it
