### ISSUE TITLE
Integration test fails because of "Login profile size exceeds 32 KiB"

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#93]
See: http://status.build.kyma-project.io/log?job=prow/kyma/kyma-integration&id=1059491549756264448
Job: prow/kyma/kyma-integration
Logs:
```
ERROR: (gcloud.compute.scp) INVALID_ARGUMENT: Login profile size exceeds 32 KiB. Delete profile values to make additional space.
```

**Comment by ayush201** [comment]
@holdenrehg I saw the same issue and I couldn't find any answer online that fixed the issue for me.
After trying many things I was able to fix the issue by clearing the ssh-keys in the service account by running the command multiple times to remove all the keys:
gcloud compute os-login --account=<service-account> ssh-keys remove --key=<key>

**Comment by petervandenabeele** [comment]
A very crude way to do the above that worked for me was:

```
for i in $(gcloud compute os-login ssh-keys list); do echo $i; gcloud compute os-login ssh-keys remove --key $i; done
```

**Comment by MasonChinkin** [comment]
> A very crude way to do the above that worked for me was:
> 
> ```
> for i in $(gcloud compute os-login ssh-keys list | grep -v FINGERPRINT); do echo $i; gcloud compute os-login ssh-keys remove --key $i; done
> ```

You are my hero

**Comment by jslmariano** [comment]
That is very neat, awesome @petervandenabeele !
