### ISSUE TITLE
Simplify and consolidate image building in neighbors.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#9434]
**Description**

With current setup for our team we have multiple tools to build oci images and multiple locations to store information which images to build and how to do it?

Tools to build.
- We build images with ko https://github.com/kyma-project/test-infra/blob/main/.koapps.yaml
- We build images using buildx https://github.com/kyma-project/test-infra/blob/main/images/build-images.sh
- We build images using image-builder https://github.com/kyma-project/test-infra/tree/main/cmd/image-builder

Locations in kyma-project/test-infra we store information about images to build.
- cmd/image-builder/images
- images
- prow/images
- .koapps.yaml

All neighbors images should be build with the same tool.
Preferred tool should be SLC-29 certified image building solution.
All neighbors images definitions should be stored in location according to one team policy. The policy should define clear guideline where and how to store image definition. This should be a one central location for all images or each image should be stored along with application code it runs or is used by.

**Reasons**

Our build image setup uses multiple different technologies and doesn't follow any clear rules where to store images definitions.
This brings unnecessary complexity, increase maintenance workload and learning curve.

**Acceptance Criteria**

- [x] All images are build with image builder using Github Actions
- [x] A policy about location to store images definitions exists
- [x] All image definitions are stored in a location aligned with policy

**Comment by Ressetkk** [comment]
Ko is used to not use Dockerfiles in go apps, greatly simplifying maintenance of go-based images and keeping central standard in build environment for each application. When you build go application you don't have to care about writing a Dockerfile, maintaining it, bumping or writing yet another configuration in dependabot, when the tool can provide everything based on centralized source with separate processes.

`docker build` in testimages is used to build images that are supposed to be base images and environment images in organization-wide configuration, hence the name "testimages" and to consolidate task of building and pushing image into one job. You just add a dockerfile if needed, and you are done.

Image-builder is used only for legacy stuff, that is hard to move, like `slackmessagesender`, which is written in Go. It requires its own set of improvements, but there was no real progress there.

---

Keeping this structure is logical and beneficial for development work, speeding up maintenance across multiple applications that you have to maintain.

**Comment by akiioto** [comment]
I don't actually see the pros with using redundant dockerfiles. ko simplify a lot building process, consistency and dependency management.

**Comment by TorstenD-SAP** [comment]
Still relevant and necessary to deprecate prow.
