### ISSUE TITLE
Create list of prow jobs related to the Neighbors team

### ISSUE THREAD

**Issue by TorstenD-SAP** [kyma-project/test-infra#9470]
The prow jobs owned by the Neighbors team have to be removed and if necessary substituted with something else.

- [x] Discuss remaining jobs if the task still has to be performed by Neighbours
- [x] Cluster remaining jobs
- [x] Create separate issues for migration or removal of Prow jobs

**Comment by KacperMalachowski** [comment]
To simplify the process here is a list of prow jobs that should be migrated by neighbors team.

  - [ ] pull-third-party-images-checkconfig 
  - [ ] pull-third-party-images-pjconfigtest 
  - [ ] pull-third-party-images-pjtester 
  - [ ] pull-third-party-images-vpathguard 
  - [ ] pre-third-party-images-presubmit-scanner 
  - [ ] pull-community-checkconfig 
  - [ ] pull-community-pjconfigtest 
  - [ ] pull-community-pjtester 
  - [ ] pull-community-vpathguard 
  - [ ] pre-community-presubmit-scanner 
  - [ ] pre-main-reconciler-validate-dockerfiles 
  - [ ] pull-reconciler-checkconfig 
  - [ ] pull-reconciler-pjconfigtest 
  - [ ] pull-reconciler-pjtester 
  - [ ] pull-reconciler-vpathguard 
  - [ ] pre-reconciler-presubmit-scanner 
  - [ ] pull-btp-manager-checkconfig 
  - [ ] pull-btp-manager-pjconfigtest 
  - [ ] pull-btp-manager-pjtester 
  - [ ] pull-btp-manager-vpathguard 
  - [ ] pre-btp-manager-presubmit-scanner 
  - [ ] pull-istio-checkconfig 
  - [ ] pull-istio-pjconfigtest 
  - [ ] pull-istio-pjtester 
  - [ ] pull-istio-vpathguard 
  - [ ] pre-istio-presubmit-scanner 
  - [ ] pull-migrate-checkconfig 
  - [ ] pull-migrate-pjconfigtest 
  - [ ] pull-migrate-pjtester 
  - [ ] pull-migrate-vpathguard 
  - [ ] pre-migrate-presubmit-scanner 
  - [ ] pull-application-connector-manager-checkconfig 
  - [ ] pull-application-connector-manager-pjconfigtest 
  - [ ] pull-application-connector-manager-pjtester 
  - [ ] pull-application-connector-manager-vpathguard 
  - [ ] pre-application-connector-manager-presubmit-scanner 
  - [ ] pull-website-checkconfig 
  - [ ] pull-website-pjconfigtest 
  - [ ] pull-website-pjtester 
  - [ ] pull-website-vpathguard 
  - [ ] pre-website-presubmit-scanner 
  - [ ] pull-compass-console-checkconfig 
  - [ ] pull-compass-console-pjconfigtest 
  - [ ] pull-compass-console-pjtester 
  - [ ] pull-compass-console-vpathguard 
  - [ ] pre-compass-console-presubmit-scanner 
  - [ ] pull-cli-checkconfig 
  - [ ] pull-cli-pjconfigtest 
  - [ ] pull-cli-pjtester 
  - [ ] pull-cli-vpathguard 
  - [ ] pre-cli-presubmit-scanner 
  - [ ] pull-busola-checkconfig 
  - [ ] pull-busola-pjconfigtest 
  - [ ] pull-busola-pjtester 
  - [ ] pull-busola-vpathguard 
  - [ ] pre-busola-presubmit-scanner 
  - [ ] pull-ord-service-checkconfig 
  - [ ] pull-ord-service-pjconfigtest 
  - [ ] pull-ord-service-pjtester 
  - [ ] pull-ord-service-vpathguard 
  - [ ] pre-ord-service-presubmit-scanner 
  - [ ] pull-private-fn-for-e2e-serverless-tests-checkconfig 
  - [ ] pull-private-fn-for-e2e-serverless-tests-pjconfigtest 
  - [ ] pull-private-fn-for-e2e-serverless-tests-pjtester 
  - [ ] pull-private-fn-for-e2e-serverless-tests-vpathguard 
  - [ ] pre-private-fn-for-e2e-serverless-tests-presubmit-scanner 
  - [ ] pull-sap-btp-service-operator-checkconfig 
  - [ ] pull-sap-btp-service-operator-pjconfigtest 
  - [ ] pull-sap-btp-service-operator-pjtester 
  - [ ] pull-sap-btp-service-operator-vpathguard 
  - [ ] pre-sap-btp-service-operator-presubmit-scanner 
  - [ ] pull-lifecycle-manager-checkconfig 
  - [ ] pull-lifecycle-manager-pjconfigtest 
  - [ ] pull-lifecycle-manager-pjtester 
  - [ ] pull-lifecycle-manager-vpathguard 
  - [ ] pre-lifecycle-manager-presubmit-scanner 
  - [ ] pull-director-size-exporter-checkconfig 
  - [ ] pull-director-size-exporter-pjconfigtest 
  - [ ] pull-director-size-exporter-pjtester 
  - [ ] pull-director-size-exporter-vpathguard 
  - [ ] pre-director-size-exporter-presubmit-scanner 
  - [ ] pull-compass-manager-checkconfig 
  - [ ] pull-compass-manager-pjconfigtest 
  - [ ] pull-compass-manager-pjtester 
  - [ ] pull-compass-manager-vpathguard 
  - [ ] pre-compass-manager-presubmit-scanner 
  - [ ] pre-template-repository-presubmit-scanner 
  - [ ] pull-istio-operator-checkconfig 
  - [ ] pull-istio-operator-pjconfigtest 
  - [ ] pull-istio-operator-pjtester 
  - [ ] pull-istio-operator-vpathguard 
  - [ ] pre-istio-operator-presubmit-scanner 
  - [ ] pull-test-infra-checkconfig 
  - [ ] pull-unit-test-go 
  - [ ] pre-main-test-infra-lint 
  - [ ] pre-main-test-infra-image-syncer-dry-run 
  - [ ] pull-test-infra-pjconfigtest 
  - [ ] pull-test-infra-pjtester 
  - [ ] pull-test-infra-vpathguard 
  - [ ] pre-test-infra-presubmit-scanner 
  - [ ] pre-test-infra-validate-scripts 
  - [ ] pre-main-test-infra-validate-generated-files 
  - [ ] pre-test-infra-validate-dockerfiles 
  - [ ] pull-service-catalog-checkconfig 
  - [ ] pull-service-catalog-pjconfigtest 
  - [ ] pull-service-catalog-pjtester 
  - [ ] pull-service-catalog-vpathguard 
  - [ ] pre-service-catalog-presubmit-scanner 
  - [ ] pull-slack-bot-checkconfig 
  - [ ] pull-slack-bot-pjconfigtest 
  - [ ] pull-slack-bot-pjtester 
  - [ ] pull-slack-bot-vpathguard 
  - [ ] pre-slack-bot-presubmit-scanner 
  - [ ] pull-api-gateway-checkconfig 
  - [ ] pull-api-gateway-pjconfigtest 
  - [ ] pull-api-gateway-pjtester 
  - [ ] pull-api-gateway-vpathguard 
  - [ ] pre-api-gateway-presubmit-scanner 
  - [ ] pre-control-plane-validate-dockerfiles 
  - [ ] pull-control-plane-checkconfig 
  - [ ] pull-control-plane-pjconfigtest 
  - [ ] pull-control-plane-pjtester 
  - [ ] pull-control-plane-vpathguard 
  - [ ] pre-control-plane-presubmit-scanner 
  - [ ] pull-kyma-environment-broker-checkconfig 
  - [ ] pull-kyma-environment-broker-pjconfigtest 
  - [ ] pull-kyma-environment-broker-pjtester 
  - [ ] pull-kyma-environment-broker-vpathguard 
  - [ ] pre-kyma-environment-broker-presubmit-scanner 
  - [ ] pull-examples-checkconfig 
  - [ ] pull-examples-pjconfigtest 
  - [ ] pull-examples-pjtester 
  - [ ] pull-examples-vpathguard 
  - [ ] pre-examples-presubmit-scanner 
  - [ ] pull-opensap-checkconfig 
  - [ ] pull-opensap-pjconfigtest 
  - [ ] pull-opensap-pjtester 
  - [ ] pull-opensap-vpathguard 
  - [ ] pre-opensap-presubmit-scanner 
  - [ ] pull-charts-checkconfig 
  - [ ] pull-charts-pjconfigtest 
  - [ ] pull-charts-pjtester 
  - [ ] pull-charts-vpathguard 
  - [ ] pre-charts-presubmit-scanner 
  - [ ] pull-service-catalog-tester-checkconfig 
  - [ ] pull-service-catalog-tester-pjconfigtest 
  - [ ] pull-service-catalog-tester-pjtester 
  - [ ] pull-service-catalog-tester-vpathguard 
  - [ ] pre-service-catalog-tester-presubmit-scanner 
  - [ ] pull-github-dashboard-checkconfig 
  - [ ] pull-github-dashboard-pjconfigtest 
  - [ ] pull-github-dashboard-pjtester 
  - [ ] pull-github-dashboard-vpathguard 
  - [ ] pre-github-dashboard-presubmit-scanner 
  - [ ] pull-hydroform-checkconfig 
  - [ ] pull-hydroform-pjconfigtest 
  - [ ] pull-hydroform-pjtester 
  - [ ] pull-hydroform-vpathguard 
  - [ ] pre-hydroform-presubmit-scanner 
  - [ ] pull-keda-manager-checkconfig 
  - [ ] pull-keda-manager-pjconfigtest 
  - [ ] pull-keda-manager-pjtester 
  - [ ] pull-keda-manager-vpathguard 
  - [ ] pre-keda-manager-presubmit-scanner 
  - [ ] pull-k8s-prow-integration 
  - [ ] pull-k8s-prow-unit-test 
  - [ ] pull-telemetry-manager-checkconfig 
  - [ ] pull-telemetry-manager-pjconfigtest 
  - [ ] pull-telemetry-manager-pjtester 
  - [ ] pull-telemetry-manager-vpathguard 
  - [ ] pre-telemetry-manager-presubmit-scanner 
  - [ ] pull-runtime-watcher-checkconfig 
  - [ ] pull-runtime-watcher-pjconfigtest 
  - [ ] pull-runtime-watcher-pjtester 
  - [ ] pull-runtime-watcher-vpathguard 
  - [ ] pre-runtime-watcher-presubmit-scanner 
  - [ ] pull-kymart-checkconfig 
  - [ ] pull-kymart-pjconfigtest 
  - [ ] pull-kymart-pjtester 
  - [ ] pull-kymart-vpathguard 
  - [ ] pre-kymart-presubmit-scanner 
  - [ ] pull-kyma-dashboard-checkconfig 
  - [ ] pull-kyma-dashboard-pjconfigtest 
  - [ ] pull-kyma-dashboard-pjtester 
  - [ ] pull-kyma-dashboard-vpathguard 
  - [ ] pre-kyma-dashboard-presubmit-scanner 
  - [ ] pull-compass-checkconfig 
  - [ ] pull-compass-pjconfigtest 
  - [ ] pull-compass-pjtester 
  - [ ] pull-compass-vpathguard 
  - [ ] pre-compass-presubmit-scanner 
  - [ ] pre-release-pr-image-guard 
  - [ ] pre-main-kyma-validate-image-definitions 
  - [ ] pre-main-kyma-validate-image-existence 
  - [ ] pre-main-kyma-validate-dockerfiles 
  - [ ] pull-kyma-checkconfig 
  - [ ] pre-main-check-users-map 
  - [ ] pull-kyma-pjconfigtest 
  - [ ] pull-kyma-pjtester 
  - [ ] pull-kyma-vpathguard 
  - [ ] pre-kyma-presubmit-scanner 
  - [ ] post-k8s-prow-build-release 
  - [ ] post-main-test-infra-image-syncer-run 
  - [ ] post-main-build-testimages 
  - [ ] post-test-infra-ko-build 
  - [ ] post-test-infra-markdown-index-autobump 
  - [ ] post-test-infra-image-detector-autobump 
  - [ ] post-test-infra-deploy-prow 
  - [ ] post-gencred-refresh-kubeconfigs 
  - [ ] post-kyma-release-cluster 
  - [ ] ci-k8s-prow-sync-upstream 
  - [ ] ci-k8s-prow-publish-tag 
  - [ ] ci-k8s-prow-autobump-testimages 
  - [ ] kyma-gardener-cleanup 
  - [ ] gcloud-ssh-keys-cleaner 
  - [ ] orphaned-assetstore-gcp-bucket-cleaner 
  - [ ] orphaned-disks-cleaner 
  - [ ] orphaned-ips-cleaner 
  - [ ] orphaned-clusters-cleaner 
  - [ ] orphaned-vms-cleaner 
  - [ ] orphaned-loadbalancer-cleaner 
  - [ ] orphaned-dns-cleaner 
  - [ ] ci-prow-branchprotector 
  - [ ] secrets-rotate-gardener-neighbors 
  - [ ] ci-gcr-cleaner-untagged 
  - [ ] ci-gcr-cleaner-cache 
  - [ ] ci-gcr-cleaner-pr 
  - [ ] ci-prow-label-sync 
  - [ ] ci-prow-autobump 
  - [ ] test-infra-image-detector-autobump 
  - [ ] ci-prow-autobump-jobs 
  - [ ] ci-gencred-refresh-kubeconfigs 
  - [ ] ci-kyma-bot-triage-close 
  - [ ] ci-kyma-bot-triage-stale 
  - [ ] unstale-gardener-project 
  - [ ] control-plane-whitesource-scan 
  - [ ] kyma-whitesource-scan 
  - [ ] hydroform-whitesource-scan 
  - [ ] reconciler-whitesource-scan 
  - [ ] kyma-2.20-whitesource-scan 
  - [ ] kyma-2.19-whitesource-scan

**Comment by Sawthis** [comment]
We should separate the list, because a lot of jobs will be not needed after last release of kyma or migration of teams to out of Prow.

**Comment by Sawthis** [comment]
A lot of jobs are generated for each repository defined in the templates/config.yaml
  - validate-dockerfiles(hadolint) - Should we migrate it to GH actions and each team should use it?
  - checkconfig(Validate inrepo prow configs) - Do we need it? I think noone is using InRepo Prow configs.
  - pjconfigtest(Run ginkgo suite tests for prowjobs definitions) - Do we need it for other repositories than test-infra?
  - pjtester(Schedule prowjobs tests using pjtester) - Won't be needed after migration outside of Prow.
  - vpathguard(Run pjtester vpathguard) - Won't be needed after migration outside of Prow.
  - presubmit-scanner(Run Gitleaks presubmit scanner to detect commited sensitive data) - Should we migrate it to GH actions and each team should use it?
  
  70 Prow jobs owned by us:
  Do we need it? I think noone is using InRepo Prow configs.
  - [ ] pull-test-infra-checkconfig 

 Can be deleted after last Kyma release planned for end of January.
  - [ ] pre-release-pr-image-guard 
  - [ ] pre-main-kyma-validate-image-definitions
  - [ ] pre-main-kyma-validate-image-existence
  - [ ] pre-main-kyma-validate-dockerfiles
  - [ ] pull-kyma-checkconfig
  - [ ] pull-kyma-pjconfigtest
  - [ ] pull-kyma-pjtester
  - [ ] pull-kyma-vpathguard
  - [ ] post-kyma-release-cluster
  - [ ] kyma-whitesource-scan
  - [ ] hydroform-whitesource-scan
  - [ ] reconciler-whitesource-scan
  - [ ] kyma-2.20-whitesource-scan
  - [ ] kyma-2.19-whitesource-scan

 Should be migrated to the GH actions together with image builder.
  - [ ] post-main-build-testimages
  - [ ] post-test-infra-ko-build

 Blocked with migration of KCP to the new security scans solution.
  - [ ] control-plane-whitesource-scan

 Won't be needed after migration outside of Prow.
  - [ ] pull-k8s-prow-integration
  - [ ] ci-prow-autobump
  - [ ] ci-prow-autobump-jobs
  - [ ] post-test-infra-deploy-prow
  - [ ] pull-test-infra-pjconfigtest
  - [ ] pull-test-infra-pjtester
  - [ ] pull-test-infra-vpathguard
  - [ ] pre-main-test-infra-validate-generated-files

  - [ ] pull-k8s-prow-unit-test
  - [ ] ci-k8s-prow-sync-upstream 
  - [ ] ci-k8s-prow-publish-tag 
  - [ ] ci-k8s-prow-autobump-testimages 
  - [ ] post-k8s-prow-build-release 

 Should be migrated to GH action?
  - [ ] pre-test-infra-presubmit-scanner
  - [ ] pre-test-infra-validate-scripts
  - [ ] pre-test-infra-validate-dockerfiles
  - [ ] pull-slack-bot-checkconfig
  - [ ] pre-main-check-users-map
  - [ ] post-test-infra-markdown-index-autobump
  - [ ] pull-unit-test-go
  - [ ] pre-main-test-infra-lint
  - [ ] pre-main-test-infra-image-syncer-dry-run
  - [ ] post-main-test-infra-image-syncer-run
  - [ ] pre-kyma-presubmit-scanner
 
  - [ ] kyma-gardener-cleanup 
  - [ ] secrets-rotate-gardener-neighbors 
  - [ ] unstale-gardener-project
  - [ ] secrets-rotate-gardener-prow 
  - [ ] secrets-rotate-gardener-kyma-dev(?)
 
  - [ ] post-gencred-refresh-kubeconfigs
  - [ ] ci-gencred-refresh-kubeconfigs 

  - [ ] gcloud-ssh-keys-cleaner 
  - [ ] orphaned-assetstore-gcp-bucket-cleaner 
  - [ ] orphaned-disks-cleaner 
  - [ ] orphaned-ips-cleaner 
  - [ ] orphaned-clusters-cleaner 
  - [ ] orphaned-vms-cleaner 
  - [ ] orphaned-loadbalancer-cleaner 
  - [ ] orphaned-dns-cleaner 
  - [ ] ci-gcr-cleaner-untagged 
  - [ ] ci-gcr-cleaner-cache 
  - [ ] ci-gcr-cleaner-pr 

  - [ ] ci-prow-branchprotector
  - [ ] ci-prow-label-sync
 
  - [ ] test-infra-image-detector-autobump
  - [ ] post-test-infra-image-detector-autobump
 
  - [ ] ci-kyma-bot-triage-close
  - [ ] ci-kyma-bot-triage-stale

**Comment by Sawthis** [comment]
Should be migrated to the GitHub actions.
  - [ ] pre-test-infra-presubmit-scanner
  - [ ] pre-test-infra-validate-scripts
  - [ ] pre-test-infra-validate-dockerfiles
  - [ ] pull-slack-bot-checkconfig
  - [ ] pre-main-check-users-map
  - [ ] post-test-infra-markdown-index-autobump
  - [ ] pull-unit-test-go
  - [ ] pre-main-test-infra-lint
  - [ ] pre-main-test-infra-image-syncer-dry-run
  - [ ] post-main-test-infra-image-syncer-run
  - [ ] pre-kyma-presubmit-scanner
  - [ ] kyma-gardener-cleanup 
  - [ ] secrets-rotate-gardener-neighbors 
  - [ ] unstale-gardener-project
  - [ ] secrets-rotate-gardener-prow 
  - [ ] secrets-rotate-gardener-kyma-dev(?)
  - [ ] post-gencred-refresh-kubeconfigs
  - [ ] ci-gencred-refresh-kubeconfigs 
  - [ ] gcloud-ssh-keys-cleaner 
  - [ ] orphaned-assetstore-gcp-bucket-cleaner 
  - [ ] orphaned-disks-cleaner 
  - [ ] orphaned-ips-cleaner 
  - [ ] orphaned-clusters-cleaner 
  - [ ] orphaned-vms-cleaner 
  - [ ] orphaned-loadbalancer-cleaner 
  - [ ] orphaned-dns-cleaner 
  - [ ] ci-gcr-cleaner-untagged 
  - [ ] ci-gcr-cleaner-cache 
  - [ ] ci-gcr-cleaner-pr 
  - [ ] ci-prow-branchprotector
  - [ ] ci-prow-label-sync
  - [ ] test-infra-image-detector-autobump
  - [ ] post-test-infra-image-detector-autobump
  - [ ] ci-kyma-bot-triage-close
  - [ ] ci-kyma-bot-triage-stale

**Comment by Sawthis** [comment]
@TorstenD-SAP @mm-mariani separate issues were created. Let's refine them further on the refinements.
