### ISSUE TITLE
[CI/CD] Migrate prowjobs out of Neighbor's Prow - Framefrogs

### ISSUE THREAD

**Issue by KacperMalachowski** [kyma-project/test-infra#9490]
**Description**
The prow jobs owned by the Framefrog team have to be removed and if necessary substituted with something else.
To simplify the process here is a list of prow jobs that should be migrated by Framefrog team.

  - [x] pull-compass-manager-tests 
  - [x] pre-main-compass-manager-trivy 
  - [x] pre-main-application-connector-manager-verify 
  - [x] ~pre-main-kyma-common~ 
  - [x] pull-central-application-connectivity-validator-lint 
  - [x] pull-central-application-connectivity-validator-unit-test 
  - [x] pull-central-application-gateway-lint 
  - [x] pull-central-application-gateway-unit-test 
  - [x] pull-compass-runtime-agent-lint 
  - [x] pull-compass-runtime-agent-unit-test 
  - [x] pre-main-kyma-integration-k3d-app-conn-validator 
  - [x] pre-main-kyma-integration-k3d-app-gateway 
  - [x] pre-main-kyma-integration-k3d-runtime-agent 
  - [x] pre-control-plane-components-provisioner 
  - [x] pre-main-provisioner-e2e-tests  (we drop it from Prow, we agreed to run the test manually)
  - [x] pre-control-plane-tests-provisioner-tests 
  - [x] post-application-connector-module-build 
  - [x] post-main-application-connector-manager-upgrade-latest-to-main 
  - [x] ~post-main-kyma-common~ => includes only `logger` library - recommend to replace it globally with ZAP or something similar
  - [x] pre-control-plane-components-schema-migrator (consult with Gophers)

**Comment by Sawthis** [comment]
@tobiscr what is the status for @kyma-project/framefrog team migration outside of Prow?

**Comment by Disper** [comment]
We have the following issues that are still open and not resolved:
- https://github.com/kyma-project/application-connector-manager/issues/135
- https://github.com/kyma-project/compass-manager/issues/84
- https://github.com/kyma-project/infrastructure-manager/issues/116
- (internal issue no. 4878)

**Comment by tobiscr** [comment]
Will be managed in:

* CM: https://github.com/kyma-project/compass-manager/issues/84
* ACM: https://github.com/kyma-project/application-connector-manager/issues/135
* Provisioner: # 4878

**Comment by VOID404** [comment]
We're removing `pre-main-provisioner-e2e-tests` instead of migrating, since KIM is replacing Provisioner soon, and the e2e tests can be easily run locally if needed. Migration to GHA for them is not worth the effort.

**Comment by VOID404** [comment]
We won't be maintaining `kyma/common` anymore, so the jobs won't be migrated. I'll just remove them.

**Comment by Sawthis** [comment]
@VOID404 please look on https://github.com/kyma-project/test-infra/pull/11658
