### ISSUE TITLE
[CI/CD] Migrate prowjobs out of Neighbor's Prow - Gopher

### ISSUE THREAD

**Issue by KacperMalachowski** [kyma-project/test-infra#9492]
**Description**
The prow jobs owned by the gopher team have to be removed and if necessary substituted with something else.
To simplify the process here is a list of prow jobs that should be migrated by gopher team.

  - [x] pre-kyma-environment-broker 
  - [x] post-btp-manager-module-build 
  - [x] skr-aws-upgrade-integration-dev 
  - [x] skr-azure-integration-dev 
  - [x] skr-azure-lite-integration-dev 
  - [x] skr-aws-integration-dev 
  - [x] skr-trial-integration-dev 
  - [x] skr-free-aws-integration-dev 
  - [x] skr-preview-dev 
  - [x] skr-aws-networking 
  - [x] keb-endpoints-test 
  - [x] pre-control-plane-components-schema-migrator (consult with Framefrogs)

**Comment by Sawthis** [comment]
@PK85 is it done by @kyma-project/gopher team?
