### ISSUE TITLE
[CI/CD] Migrate prowjobs out of Neighbor's Prow - Huskies

### ISSUE THREAD

**Issue by KacperMalachowski** [kyma-project/test-infra#9494]
**Description**
The prow jobs owned by the huskies team have to be removed and if necessary substituted with something else.
To simplify the process here is a list of prow jobs that should be migrated by huskies team.

  - [ ] pull-directory-size-exporter-lint 
  - [ ] pull-directory-size-exporter-unit-test

**Comment by a-thaler** [comment]
Both jobs are reomved from the prow setup
