### ISSUE TITLE
[CI/CD] Migrate prowjobs out of Neighbor's Prow - SkydivingTunas

### ISSUE THREAD

**Issue by KacperMalachowski** [kyma-project/test-infra#9496]
**Description**
The prow jobs owned by the skydivingtunas team have to be removed and if necessary substituted with something else.
To simplify the process here is a list of prow jobs that should be migrated by skydivingtunas team.

  - [x] remove pull-eventing-auth-manager-integration-test 
         [new job](https://github.com/kyma-project/eventing-auth-manager/pull/131)
  - [x] pull-event-publisher-proxy-lint 
  - [x] pull-event-publisher-proxy-unit-test 
  - [x] pull-eventing-controller-lint 
  - [x] pull-eventing-controller-unit-test 
  - [x] pre-control-plane-components-kyma-metrics-collector 
  - [x] release-eventing-manager-module-build 
  - [x] post-eventing-module-build 
  - [x] release-nats-manager-module-build 
  - [x] post-nats-module-build 
  - [x] eventing-tools-autobump

**Comment by Sawthis** [comment]
@k15r what is the status of migration outside of Prow for @kyma-project/eventing team? Will it be finished until end of February?

**Comment by k15r** [comment]
all mentioned jobs have been replaced by github actions
