### ISSUE TITLE
[CI/CD] Migrate prowjobs out of Neighbor's Prow -  SRE

### ISSUE THREAD

**Issue by KacperMalachowski** [kyma-project/test-infra#9497]
**Description**
The prow jobs owned by the sre team have to be removed and if necessary substituted with something else.
To simplify the process here is a list of prow jobs that should be migrated by sre team.

  - [x] pre-control-plane-components-kubeconfig-service 
  - [x] pre-main-kcp-cli 
  - [x] post-main-kcp-cli

**Comment by Sawthis** [comment]
@ebensom I've received information from @PK85 and @tobiscr that below jobs are from SRE. Is that correct?
  - [ ] pre-control-plane-components-schema-migrator
  - [ ] pre-control-plane-tests-e2e-provisioning
  
  The deadline for migration out of Prow is end of August.

**Comment by Sawthis** [comment]
https://github.com/kyma-project/test-infra/pull/11658
