### ISSUE TITLE
Enable GitHub reporter for postsubmit jobs

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#950]
**Description**

Since February 13, 2019 it is possible to send postsubmit jobs statuses to GitHub - https://github.com/kubernetes/test-infra/blob/master/prow/ANNOUNCEMENTS.md#announcements

**Reasons**

Better visibility of CI jobs in GitHub.

**Attachments**

**Comment by kasiakepka** [comment]
First we should implement https://github.com/kyma-project/test-infra/issues/1162

**Comment by dekiel** [comment]
Postsubmit jobs are reported to github. It's still done by plank and is now default for prow. Along with migration from plank to crier we will move this feature to github reporter.
