### ISSUE TITLE
Remove all pipelines related to the "old" reconciler

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/test-infra#9543]
**Description**
Since all relevant components have been removed from the "old" reconciler, we can go the next steps and remove all pipelines related to it.

**Acceptance Criteria**
- Check which pipelines are related to old reconciler
- Remove the found pipelines
- Updates Jellyfish Team pipelines check page

Pipeline Examples:
- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e
- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/nightly-main-reconciler
- ...

**Comment by janmedrek** [comment]
Duplicate of: https://github.com/kyma-project/test-infra/issues/9873
