### ISSUE TITLE
Unify presets in tests of integration jobs

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/test-infra#958]
**Description**
I noticed that we have a presets in tests of integration jobs as a strings, not as imported values from `tester` package. In other tests we use constants from `tester` package, so we should unify using those values in all tests.

AC:
- unify presets in https://github.com/kyma-project/test-infra/blob/master/development/tools/jobs/kyma/kyma_integration_test.go and update relevant presets in https://github.com/kyma-project/test-infra/blob/master/development/tools/jobs/tester/tester.go

**Comment by derberg** [comment]
@magicmatatjahu please specify what and where should be fixed. If this is a simple fix just do a PR ;)

**Comment by magicmatatjahu** [comment]
@derberg I added AC and assigned ticket to Dev Tooling Team. Are you satisfied?
