### ISSUE TITLE
Creation of Unit Tests

### ISSUE THREAD

**Issue by akiioto** [kyma-project/test-infra#9623]
**Description**

We need to develop comprehensive unit tests for our entire code base. These tests will be crucial to ensure that every aspect of our testing code functions as expected and does not introduce any errors.
Changes should be made against "`pkg/azuredevops/pipelines/pipelines.go`"

**Reasons**

1. To ensure comprehensive coverage and reliability of our testing code.
2. To verify the logical and functional correctness of the code.
3. To facilitate maintainability and scalability of the testing code as the project evolves.

**Acceptance Criteria**

[ ] Complete unit test coverage for our code.
[ ] Tests should be written in a clear and understandable manner.
[ ] Integration of unit tests into our CI/CD process.
[ ] Documentation of the unit tests and guidelines for running and extending them.

**Attachments**

**Comment by Sawthis** [comment]
Not relevant anymore.
