### ISSUE TITLE
Cover all GCP artifact registries with IaC

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/test-infra#9760]
**Description**

Cover all GCP artifact registries with Infrastructure as code (IaC).

**Reasons**

Currently only one registry for internal kyma modules is covered with IaC.

**Acceptance Criteria**

- [x] All our registries on GCP are covered with IaC.

**Attachments**

**Comment by Sawthis** [comment]
All our registries on GCP are covered with IaC.

**Comment by KacperMalachowski** [comment]
Prod and dev are covered in: https://github.com/kyma-project/test-infra/blob/main/configs/terraform/environments/prod/artifact-registry.tf
Cache and dockerhub-mirror are covered in: https://github.com/kyma-project/test-infra/blob/main/configs/terraform/environments/prod/image-builder.tf
dev-modules-internal is covered in: https://github.com/kyma-project/test-infra/blob/main/configs/terraform/environments/prod/modules-submission.tf
