### ISSUE TITLE
Migrate image-detector-autobump to Github actions

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/test-infra#9767]
**Description**

Migrate below Prow jobs to Github actions and delete them.
  - [x] test-infra-image-detector-autobump
      - periodic updates sec-scanners-config.yaml with images to scan
  - [x] post-test-infra-image-detector-autobump
      - updates sec-scanners-config.yaml with images to scan on push

**Reasons**

**Acceptance Criteria**

- [x] All Prow jobs mentioned in this issue are migrated to Github actions.
- [x] All Prow jobs mentioned in this issue are removed.
- [x] Provide the workflow in the template repository.

**Attachments**

https://github.com/kyma-project/test-infra/issues/9470

**Comment by KacperMalachowski** [comment]
It's working
