### ISSUE TITLE
We should not have kyma related info in test-infra

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/test-infra#981]
**Description**
While working on performance story we had a discussion with @strekm and found kyma related information in test-infra. Following scripts need to be fixed
https://github.com/kyma-project/test-infra/blob/master/prow/scripts/cluster-integration/helpers/create-image.sh
https://github.com/kyma-project/test-infra/blob/master/prow/scripts/cluster-integration/helpers/delete-image.sh
https://github.com/kyma-project/test-infra/blob/master/prow/scripts/cluster-integration/helpers/get-helm-certs.sh
https://github.com/kyma-project/test-infra/blob/master/prow/scripts/cluster-integration/helpers/install-kyma.sh

**Comment by suleymanakbas91** [comment]
Can you be more specific? What do you mean by kyma related information?

**Comment by strekm** [comment]
Listed scripts are a copy of scripts from kyma repository. For maintenance resons, they should be removed from test-infra repo.

**Comment by kasiakepka** [comment]
This task will be covered while working on kyma-project/test-infra#1003
It is depending on:
- hydroform
- kyma CLI

**Comment by dekiel** [comment]
Only this one is still present in test-infra https://github.com/kyma-project/test-infra/blob/main/prow/scripts/cluster-integration/helpers/create-image.sh
