### ISSUE TITLE
[Security] Setup a standard of documenting service accounts usage and ownership.

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/test-infra#9916]
We need a common way of managing service accounts on GCP and k8s along with inventory and documentation how and where we are using it and who is an owner.

**AC:**
- [x] Management should be done with Terraform config.
- [x] We need some automated tests to validated if the name is correct.
- [x] Documentation should be placed in SA description.

**Comment by dekiel** [comment]
When describing a service accounts, pay attention to the SAs which might be removed soon due to Prow/Gardener removal. Such SAs might be described as `to-be-removed-with-prow`

**Comment by Sawthis** [comment]
I would not use `sa-` at the beginning for service accounts names.
