### ISSUE TITLE
Get access to the GCP kyma-project to migrate release-template-operator-assets from the Neighbors Prow

### ISSUE THREAD

**Issue by nesmabadr** [kyma-project/test-infra#9925]
**Description**

As a part of the prow jobs migration from the Neighbors's Prow, we wanted to migrate the [release-template-operator-assets](https://github.com/kyma-project/test-infra/blob/7abd78e0f5af48bc6efd25ef6a3428932df7931d/prow/jobs/kyma-project/template-operator/template-operator.yaml) to a Github Action in the Template Operator repo. But for this we need to get access to the kyma-project  since we are using the [Github action](https://github.com/google-github-actions/auth), so we need to have a service account name, a workload identity provider and to give our repo some access to the GCP project.  

specifically: Assign `principalset://iam.googleapis.com/projects/718973091829/locations/global/workloadIdentityPools/github-action/attribute.repository/kyma-project/template-operator` as `Service Account Token Creator` as well as `Workload Identity User`

**Reasons**

To allow the job to work correctly with GitHub Actions

**Acceptance Criteria**

- Give the template operator Github Action access to the kyma-project GCP artifact registry

This is blocking https://github.com/kyma-project/test-infra/issues/9495
**Attachments**

**Comment by TorstenD-SAP** [comment]
Only pipelines/jobs/actions/... controlled by the Neighbors are allowed to upload images to our registry, especially the productive one. We can think about providing some kind of dev registry to cache images for testing purposes (if this makes sense?). The images from this dev registry must not reach the productive registry!

**Comment by Sawthis** [comment]
https://github.com/kyma-project/test-infra/issues/9925#issuecomment-2049282177
