### ISSUE TITLE
GH action get oidc token

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#9976]
## **Description**

As part of the Image Builder Solution, we need a GitHub Action responsible for obtaining an OIDC token from GitHub's OIDC identity provider. This token is critical for securely passing information about the GitHub workflow and the image to build, to be subsequently used in a separate pipeline execution step. The purpose of this task is to create this GitHub Action that will fetch the OIDC token and set it as a variable, ready for use in the next step of the workflow.

OIDC token must provide enough data to properly clone source code and build image from it in oci-image-builder ADO backend. Following is a list of proposed claims needed in OIDC token. All listed claims are present by default.

### Workflow Identification Claims

The OIDC token contains the following claims that can be used to identify the workflow that triggered the build pipeline. These include:

- `iss`: The issuer of the token. This is always `https://token.actions.githubusercontent.com`.
- `iat`: The time at which the token was issued.
- `exp`: The time at which the token expires.
- `jti`: A unique identifier for the token.
- `nbf`: The time before which the token must not be accepted for processing.
- `kid`: The key ID of the key used to sign the token.
- `alg`: The algorithm used to sign the token.
- `run_id`: The ID of the workflow run.
- `run_number`: The number of the workflow run.
- `actor`: The login of the user who initiated the workflow run.
- `event_name`: The name of the event that triggered the workflow run.
- `workflow`: The name of the workflow that triggered the workflow run.
- `workflow_ref`: The git ref associated with the workflow file.
- `repository`: The repository where the workflow run occurred.
- `repository_owner`: The owner of the repository where the workflow run occurred.

### Source Code Cloning Claims

The OIDC token also contains claims that can be used to clone the appropriate version of the source code:

- `repository`: The repository where the workflow run occurred.
- `repository_owner`: The owner of the repository where the workflow run occurred.
- `event_name`: The name of the event that triggered the workflow run.
- `ref`: The git ref associated with the workflow run. This can be used to checkout the correct branch, tag, or commit.
- `ref_type`: The type of git ref associated with the workflow run. This can be used to determine whether the ref is a branch, tag, or
  commit.
- `base_ref`: The base git ref associated with the workflow run. This can be used to determine the base branch for a pull request.
- `head_ref`: The head git ref associated with the workflow run. This can be used to determine the head branch for a pull request.

These claims ensure that the `oci-image-builder` pipeline builds the exact version of the code that was provided in the PR or merged to the
branch, adhering to slc-29 compliance.

For design proposal of GitHub workflow and oci-image-builder backend integration see https://github.com/kyma-project/test-infra/pull/9970

## **Acceptance Criteria**

- [x] Implement a GitHub Action that interacts with GitHub's OIDC identity provider to issue an OIDC token.
- [x] The GitHub Action should get the OIDC token and subsequently set it as an output variable or use GitHub's environment files feature to set it to be available and used in another step of the GitHub Workflow.
- [x] The OIDC token must include claims that will enable proper source code cloning and image build in the oci-image-builder pipeline.
- [x] Ensure the GitHub action is correctly fetching the OIDC token and setting it as a variable. The functionality can be validated with a test GitHub workflow utilising this GitHub Action and examining the token in subsequent steps.
- [x] The GitHub Action should handle and communicate any potential errors effectively and clearly, especially if the token cannot be obtained.
- [x] Document the operation and usage of the created GitHub Action, including its purpose and the way to utilise the set OIDC token in subsequent pipeline steps.
- [x] Update block and activity diagrams from #9970 with detail level data. Create new diagrams if needed.
- [x] Verify the reusable workflow solution described in this PR: https://github.com/kyma-project/test-infra/pull/10309
- [x] Implement e2e tests for final solution. Check [this](https://github.com/KacperMalachowski/test-infra/blob/triggering-image-builder/.github/workflows/pull-trigger-image-builder.yml) for inspiration.

## **Proposal of Implementation**

- Use GitHub's @actions/core and @actions/github libraries for interacting with the workflow context and OIDC provider.
- In the "main" function of the action's code, utilize core.getInput to get any necessary inputs.
- Use the necessary libraries or API calls to interact with GitHub's OIDC provider and fetch the OIDC token. See https://github.com/actions/toolkit/tree/main/packages/core#oidc-token and https://gal.hagever.com/posts/authenticating-github-actions-requests-with-github-openid-connect
- Use core.setOutput or write to a GitHub environment file to set the fetched OIDC token.
- Ensure the JavaScript action code adheres to best practices and is correctly bundled to be used as a GitHub Action.
- Add error handling code sections to communicate informative error messages via core.setFailed.
- The action should be packaged properly with all the dependencies needed and committed to the repository for it to be reusable and consumed by the workflows.

**Comment by Sawthis** [comment]
@dekiel here you have comparison for OIDC tokens for pull request and pull request_target events.
![Screenshot 2024-04-02 at 14 48 22](https://github.com/kyma-project/test-infra/assets/74361703/884e2830-a403-472b-a489-4072e1299c85)

**Comment by dekiel** [comment]
Thanks, are we fine with our approach?

**Comment by Sawthis** [comment]
@dekiel I don't see these fields:
- `kid`: The key ID of the key used to sign the token.
- `alg`: The algorithm used to sign the token.
- ref_type: The type of git ref associated with the workflow run. This can be used to determine whether the ref is a branch, tag, or commit.

OIDC token from pull_request_target event has ref pointing to @refs/heads/main and https://github.com/Sawthis/test-infra/commit/a8571acd668c416ec3bc89599192b9031f3a326e which is not correct change from pull request.

OIDC token from pull_request event has ref pointing to @refs/pull/15/merge and https://github.com/Sawthis/test-infra/commit/21f22f07c961abebfcfe44fe84d511aa85c0bdef which is correct change from pull request.

If we want to checkout correct version of code to build using only OIDC token fields we should use pull_request event but then we need to find/implement solution for passing secrets and variables for Github actions triggered from forks.

**Comment by Sawthis** [comment]
@dekiel I will test if it is possible to use composite action in this case.

**Comment by Sawthis** [comment]
AC: `Ensure the GitHub action is correctly fetching the OIDC token and setting it as a variable. The functionality can be validated with a test GitHub workflow utilising this GitHub Action and examining the token in subsequent steps.` is tested by @akiioto .

**Comment by akiioto** [comment]
https://github.com/kyma-project/test-infra/pull/10369/files
