### ISSUE TITLE
Add resource limit tests

### ISSUE THREAD

**Issue by tehcyx** [kyma-project/test-infra#998]
**Description**
As part of the #896 we've decided that we'd want to have governance tests introduce tests on resource limits. In the beginning we want to print warnings that developers can see but make tests fail after we announce required changes.

**Reasons**
Resource consumption is not optimal and failing container starts are sometime due to not enough resources.

**Comment by pbochynski** [comment]
Will be resolved by better faster integration tests https://github.com/kyma-project/kyma/issues/10050
